#!/usr/bin/env python3
"""
Expand 9 partial texts (1-999 words) to 1,000+ word minimum.
"""

import sqlite3
from pathlib import Path

DB_PATH = Path("c:/Dev/EmeraldTablet/db/emerald_tablet.db")

TEXTS_TO_EXPAND = {
    "Definitions of Hermes to Asclepius (Armenian)": """<p>The <i>Definitions of Hermes to Asclepius</i>, surviving in Armenian translation, is a fragmentary Hermetic text preserving definitions and philosophical principles attributed to Hermes Trismegistus and addressed to his student Asclepius. The Armenian version represents an important witness to the diversity of Hermetic textual traditions: while the <i>Corpus Hermeticum</i> and the <i>Asclepius</i> survive primarily in Greek and Latin versions, the Armenian tradition preserves materials that may represent independent textual lineages or alternative recensions. The Armenian text appears to be a compilation of Hermetic definitions and aphorisms, similar in some respects to the <i>Liber XXIV Philosophorum</i> in its structure of concise philosophical statements. The text addresses fundamental Hermetic doctrines: the nature of God, the structure of the cosmos, the principles of creation, the nature of the human soul, and the possibilities for spiritual knowledge and transformation. The survival of the Armenian version is significant because it demonstrates the breadth of Hermetic transmission through different linguistic and cultural traditions: the Hermetic corpus was not preserved solely in Greek and Latin but circulated through Syriac, Arabic, Armenian, and other linguistic traditions, each preserving distinct versions and interpretations. The Armenian text, though fragmentary and not extensively studied in modern scholarship, remains valuable for understanding the scope and diversity of Hermetic thought.</p>

<h2>Content and Hermetic Doctrine</h2>
<p>The <i>Definitions of Hermes to Asclepius</i> as preserved in Armenian presents a series of definitions addressing fundamental theological and cosmological concepts. The text defines God or the supreme divine reality as utterly transcendent, beyond being and nonbeing, utterly incomprehensible except through the mediation of the divine intellect (Nous). The text presents creation as an emanation from the divine source, the cosmos arising through the activity of the divine intellect and the celestial powers that mediate between the transcendent divine and the material realm. The text addresses the nature of the human soul, its divine origin, its imprisonment in material existence, and its possibilities for return to the divine through knowledge. The definitions employ the characteristic Hermetic vocabulary: Nous (divine intellect), Logos (divine reason), cosmos (the ordered universe), psyche (soul), and sōteria (salvation or deliverance). The text emphasizes the fundamental kinship between the human intellect and the divine intellect: the human capacity for knowledge derives from the divine intellect present within humans, and through activation of this divine capacity, the soul can achieve knowledge of God and of the true structure of reality. The text presents knowledge (gnosis) as salvific: the soul achieves its liberation and perfection through understanding the truth of its own divine nature and its relationship to the divine source.</p>

<h2>Transmission and the Armenian Hermetic Tradition</h2>
<p>The Armenian translation of the <i>Definitions of Hermes to Asclepius</i> survives in Armenian manuscript sources, though the extent and completeness of the surviving text remain uncertain. The Armenian tradition represents one of several non-Greek, non-Latin linguistic traditions through which Hermetic texts were preserved and transmitted. Armenian became a major literary and scholarly language in late antiquity and the medieval period, with Armenian scholars translating Greek and Syriac philosophical and theological texts. The presence of Hermetic materials in Armenian suggests networks of intellectual exchange between Greek, Syriac, and Armenian scholarly communities. The Armenian version may preserve elements not present in the Greek and Latin traditions, making it valuable for reconstructing the full scope of Hermetic literature. The transmission of the text through Armenian was not merely a matter of passive preservation but involved active engagement and interpretation by Armenian scholars seeking to understand Hermetic philosophy within their own intellectual and theological contexts. Modern study of the Armenian Hermetic materials has been limited partly by the relative scarcity of scholarly attention to Armenian manuscript sources and partly by the linguistic and paleographical challenges of working with Armenian texts. Nevertheless, the Armenian materials remain important for comprehensive understanding of the Hermetic tradition.</p>

<h2>Modern Scholarship and Remaining Questions</h2>
<p>Detailed study of the Armenian <i>Definitions of Hermes to Asclepius</i> has been conducted by scholars specializing in Armenian manuscripts, in the history of Hermeticism, and in late antique philosophical transmission. The text has been examined for its relationship to known Greek and Latin Hermetic materials, with scholars attempting to determine whether the Armenian version represents an independent textual tradition or a translation from a Greek or Syriac source. Questions about the dating and provenance of the text remain open: when was the Armenian translation produced, and from what Greek or other language original? How widely did the Armenian version circulate among Armenian Christian scholars? Modern scholarship has emphasized the importance of examining Hermetic transmission through diverse linguistic traditions to gain a fuller understanding of the scope and development of Hermetic thought. Contemporary research continues to examine Armenian manuscripts for additional Hermetic materials and to refine understanding of how Armenian scholars engaged with Hermetic philosophy. The Armenian Hermetic materials exemplify the broader phenomenon of textual transmission and transformation as texts moved through different linguistic and cultural contexts.</p>

<h2>Literature</h2>
<p>Copenhaver, Brian P. <i>Hermetica: The Greek Corpus Hermeticum and the Latin Asclepius</i>. Cambridge: Cambridge University Press, 1992.<br>
Fowden, Garth. <i>The Egyptian Hermes: A Historical Approach to the Late Pagan Mind</i>. Cambridge: Cambridge University Press, 1986.<br>
Hanegraaff, Wouter J. <i>Hermetic Spirituality and the Historical Imagination</i>. Leiden: Brill, 2022.<br>
Litwa, M. David. <i>Hermetica II: The Greco-Egyptian Texts</i>. Cambridge: Cambridge University Press, 2018.<br>
van Bladel, Kevin. <i>The Arabic Hermes: From Pagan Sage to Prophet of Science</i>. Oxford: Oxford University Press, 2009.</p>""",

    "Manetho: Aegyptiaca": """<p>Manetho of Sebennytos (flourished c. 280 BCE) was an Egyptian priest and historian who composed the <i>Aegyptiaca</i> (<i>Egyptian History</i>), a comprehensive history of Egypt written in Greek for the Hellenistic royal court. Manetho's <i>Aegyptiaca</i>, though surviving only in fragmentary form through quotations in later Greek and Roman authors, represents the most important ancient narrative source for Egyptian history and chronology. The significance of Manetho for Hermetic studies is multifaceted. First, Manetho himself was an Egyptian priest with access to Egyptian priestly learning and temple records; his engagement with Egyptian historical and religious materials provides important evidence for how educated Egyptians understood their own traditions. Second, Manetho's account of Egyptian history and religion influenced subsequent Greco-Roman understanding of Egypt: later Greek and Roman authors citing Manetho shaped their own representations of Egyptian wisdom and culture. Third, the intellectual context of Manetho's work—the Hellenistic period when Greek and Egyptian intellectual traditions were actively engaging and synthesizing—is crucial for understanding the development of Hermetic thought. The <i>Aegyptiaca</i> provides historical and cultural context for understanding how Greek intellectuals encountered, reinterpreted, and appropriated Egyptian learning during the Hellenistic and Roman periods, processes that produced the Hermetic tradition.</p>

<h2>Content and Egyptian History</h2>
<p>Manetho's <i>Aegyptiaca</i> presents a comprehensive narrative history of Egypt from the earliest dynasties through the Ptolemaic period. The work is organized as a chronological succession of dynasties, providing dates, names of rulers, and major events and achievements. Manetho's account established the basic chronological framework still used in Egyptology, though modern scholarship has refined and modified many of his dates. The <i>Aegyptiaca</i> addresses not only political and military history but also cultural, religious, and intellectual matters: Manetho discusses Egyptian priests, temples, religious practices, and the transmission of sacred knowledge. The work addresses the origins of Egyptian civilization, the development of writing and arts, and the role of priest-kings and divine wisdom in establishing Egyptian cultural achievements. Manetho's narrative presents Egypt as possessing an ancient, continuous civilization with sophisticated religious, intellectual, and administrative traditions. The work emphasizes the antiquity of Egyptian learning and the preservation of sacred knowledge through priestly lineages, themes that would be taken up and elaborated by subsequent Greco-Roman and Hermetic writers seeking to authorize their claims to access ancient wisdom.</p>

<h2>Manetho and Greek Understanding of Egypt</h2>
<p>Manetho wrote for a Greek audience, specifically for the Ptolemaic royal court. His presentation of Egyptian history and culture was shaped by the expectations and intellectual frameworks of his Greek readers. Manetho endeavored to present Egypt as possessing ancient, rational, organized civilization and as the source of profound wisdom and learning. This presentation served multiple purposes: it legitimized Ptolemaic rule by connecting the Greek dynasty to the ancient authority of Egyptian kingship; it satisfied Greek intellectual interest in Egypt as a source of ancient wisdom; and it contributed to Greek understanding of Egypt as a civilization worthy of respect and study. Later Greek and Roman authors, drawing on Manetho's authority, promoted the idea that Egypt was a repository of ancient wisdom accessible to those who could learn the Egyptian priesthood's secrets. This representation of Egypt and Egyptian wisdom significantly influenced Greek and Roman intellectuals' reception and interpretation of Egyptian materials, including the Hermetic texts. The idea that Hermes Trismegistus represented the accumulated wisdom of the Egyptian priesthood was shaped partly by the authority lent to claims about Egyptian learning by sources like Manetho.</p>

<h2>Textual Transmission and Modern Understanding</h2>
<p>The <i>Aegyptiaca</i> survives fragmentarily, primarily through the quotations of later ancient authors including Josephus, Eusebius, and others who incorporated Manetho's narrative into their own works. Modern scholars have reconstructed Manetho's text by collecting and analyzing these fragments. The textual transmission has complicated interpretation: the fragments may not represent Manetho's original text accurately, and the contexts in which they were quoted influenced how they were selected and modified. Modern Egyptology has both confirmed and revised Manetho's account through archaeological evidence and direct study of Egyptian sources. Nevertheless, Manetho remains an important witness to how educated Egyptians and Hellenistic Greeks understood Egyptian civilization and culture. Modern scholarship on Manetho has examined his historical accuracy, his sources and methodology, and his influence on subsequent Greek and Roman understanding of Egypt. The work has also been studied for its representation of Egyptian religion and priesthood, offering evidence for how these were understood in the Hellenistic period.</p>

<h2>Literature</h2>
<p>Copenhaver, Brian P. <i>Hermetica: The Greek Corpus Hermeticum and the Latin Asclepius</i>. Cambridge: Cambridge University Press, 1992.<br>
Fowden, Garth. <i>The Egyptian Hermes: A Historical Approach to the Late Pagan Mind</i>. Cambridge: Cambridge University Press, 1986.<br>
Manetho. <i>Aegyptiaca</i>. Translated by W.G. Waddell. Cambridge: Harvard University Press, 1940.<br>
Redford, Donald B. <i>Pharaonic King-Lists, Annals and Day-Books: A Contribution to the Study of the Egyptian Sense of History</i>. Toronto: Society for the Study of Egyptian Antiquities, 1986.<br>
Yates, Frances A. <i>Giordano Bruno and the Hermetic Tradition</i>. Chicago: University of Chicago Press, 1964.</p>""",

    "Esotericism and the Academy": """<p><i>Esotericism and the Academy</i> is a scholarly work examining the relationship between esoteric traditions (including Hermeticism, alchemy, astrology, and related disciplines) and mainstream academic philosophy and theology in medieval and Renaissance universities and scholarly institutions. The work addresses fundamental questions about the boundaries between academic and esoteric knowledge, the degree to which esoteric traditions were engaged with in official academic contexts, and how academic philosophers and theologians understood and engaged with esoteric materials. The study demonstrates that rather than a clear division between academic orthodoxy and esoteric heterodoxy, medieval and Renaissance intellectual life involved complex negotiations and exchanges between academic and esoteric traditions. Scholars in medieval universities engaged with astrological, alchemical, and magical texts; university theologians incorporated esoteric philosophical frameworks into their own work; and esoteric thinkers sought to establish their legitimacy through academic philosophical argument. The work contributes to understanding the intellectual integration of esoteric traditions into broader European intellectual culture and demonstrates the importance of recognizing esoteric thought not as marginal or peripheral but as integral to the development of medieval and Renaissance learning.</p>

<h2>Academic Engagement with Esotericism</h2>
<p><i>Esotericism and the Academy</i> examines how medieval and Renaissance universities and scholars engaged with esoteric materials. The work demonstrates that university scholars studied and taught astrology, alchemy, and magical philosophy as part of the official curriculum. University physicians engaged extensively with astrological and magical theory in their practice and teaching. University theologians drew on Neoplatonic and Hermetic philosophy in their theological work. Renaissance humanist scholars recovered and studied esoteric texts, treating them as worthy of serious academic attention. The work shows that academic respectability was not denied to esoteric traditions: practitioners of astrology, alchemy, and magic could achieve positions of authority in academic and court contexts. This integration of esoteric traditions into academic contexts depended partly on the philosophical frameworks available to medieval and Renaissance thinkers: Neoplatonism and Hermetic philosophy were understood not as antithetical to academic philosophy but as compatible with it or even as enriching it. The work also emphasizes that academic and esoteric traditions were not stable categories: what was considered academic or esoteric varied across contexts and periods, and the boundaries between them were fluid and contested.</p>

<h2>Hermetic Philosophy and Academic Legitimacy</h2>
<p>The study pays particular attention to how Hermetic philosophy was engaged with in academic contexts. Renaissance humanist scholars, after recovering the <i>Corpus Hermeticum</i>, sought to establish the philosophical credentials of Hermetic texts and to integrate Hermetic thought into academic philosophy. Ficino, Pico della Mirandola, and their successors presented Hermetic philosophy as an ancient, sophisticated philosophical tradition worthy of academic study. The integration of Hermetic philosophy into Renaissance Neoplatonism provided a framework through which Hermetic texts could be engaged with as serious philosophical documents rather than as superstitious magical texts. Medieval and Renaissance scholars engaged with Hermetic astrological and magical texts, treating them as embodying legitimate philosophical and scientific knowledge. The work demonstrates how academic legitimacy was contested and negotiated: those promoting esoteric traditions sought to establish their philosophical credentials, while skeptics questioned their validity. The process of legitimation depended on demonstrating the philosophical foundations of esoteric practices and on integrating esoteric materials into recognized philosophical frameworks.</p>

<h2>Modern Implications</h2>
<p>The study has implications for modern understanding of the history of science and philosophy. It demonstrates that the development of modern science cannot be understood as a simple triumph of rationality over superstition, with esoteric traditions representing superstitious irrationality that had to be overcome. Rather, esoteric traditions like alchemy and astrology contributed conceptual resources, empirical interests, and philosophical frameworks that influenced the development of modern science. The work also contributes to understanding esotericism as a significant historical phenomenon worthy of serious scholarly study rather than as a marginal aberration from mainstream intellectual development. Contemporary scholarship continues to examine the relationships between academic and esoteric traditions and to recognize the integration of esoteric thought into broader intellectual cultures.</p>

<h2>Literature</h2>
<p>Copenhaver, Brian P. <i>Magic in Western Culture: From Antiquity to the Enlightenment</i>. Cambridge: Cambridge University Press, 2015.<br>
Hanegraaff, Wouter J. (ed.). <i>Dictionary of Gnosis and Western Esotericism</i>. Leiden: Brill, 2006.<br>
Principe, Lawrence M. <i>The Secrets of Alchemy</i>. Chicago: University of Chicago Press, 2013.<br>
Yates, Frances A. <i>Giordano Bruno and the Hermetic Tradition</i>. Chicago: University of Chicago Press, 1964.<br>
Zambelli, Paola. <i>The Speculum Astronomiae and Its Enigma: Astrology, Theology and Science in Albertus Magnus and His Contemporaries</i>. Dordrecht: Kluwer, 1992.</p>""",

    "Iamblichus: De Mysteriis": """<p><i>De Mysteriis</i> (<i>On the Mysteries</i>, also known as the <i>Reply of Abammon to Porphyry</i>), attributed to Iamblichus of Apamea (c. 245–325 CE), is one of the most important late antique philosophical treatments of religion, magic, and mysticism. The work is framed as a response by an Egyptian priest (Abammon) to criticisms of religious practice and magical theology raised by Porphyry, the Neoplatonic philosopher and contemporary of Iamblichus. Iamblichus's <i>De Mysteriis</i> defends the practices of Egyptian priests, particularly their use of statues, images, and ritual procedures, against the accusation that these practices are superstitious and irrational. The work is significant for Hermetic studies because it engages extensively with Egyptian religious practices and philosophy, cites Hermetic materials, and presents a sophisticated philosophical justification for magical and theurgical practice grounded in a Neoplatonic cosmology that parallels Hermetic doctrines. The <i>De Mysteriis</i> represents a crucial moment in late antique intellectual history: the moment when pagan philosophers mounted sophisticated defenses of religious practice and magic against internal philosophical critique, defenses that would influence both pagan and Christian engagement with these traditions.</p>

<h2>Theological and Magical Philosophy</h2>
<p>Iamblichus's <i>De Mysteriis</i> presents a sophisticated philosophical justification for practices that appear magical or supernatural from the perspective of ordinary rationality. The work presents a cosmology in which the universe is structured as a hierarchy of divine powers emanating from the supreme divine source through multiple levels of celestial and terrestrial reality. These divine powers are not merely abstract principles but active agencies present throughout the cosmos. Through understanding the correspondences linking different levels of reality and through proper ritual and spiritual discipline, the sage or priest can establish contact with divine powers and can direct their influence toward specific ends. Iamblichus presents Egyptian priestly practices—including the veneration of statues, the performance of rituals at specific astrological times, and the use of sacred materials and symbols—not as superstitious magic but as sophisticated techniques for establishing contact with and invoking divine powers. The practice is legitimate because it aligns with the actual structure of the cosmos: the divine powers genuinely operate through material means and can genuinely be invoked through proper procedures. Iamblichus's theology emphasizes that the divine powers are beneficent and responsive to human prayer and invocation, and that the goal of such operations is spiritual elevation and the soul's advancement toward divine union.</p>

<h2>Iamblichus and Hermetic Theurgy</h2>
<p>The <i>De Mysteriis</i> is significant for Hermetic studies because it engages with Hermetic materials and because it presents a philosophical framework similar to that underlying Hermetic thought. Both Iamblichus and the Hermetic texts share an emphasis on the cosmological interconnection of all levels of reality, on the possibilities for human spiritual elevation through knowledge and proper practice, and on the legitimacy of invoking divine powers through ritual. The term "theurgy," often used to describe Iamblichus's approach to religious practice, is also sometimes applied to the magical theology of the <i>Asclepius</i> and related Hermetic texts. Iamblichus's sophisticated philosophical defense of religious practice and magic may have influenced or paralleled Hermetic thought, or the two traditions may represent parallel developments from shared Neoplatonic and Egyptian philosophical foundations. The comparison between Iamblichus and Hermetic philosophy illuminates both traditions and demonstrates the sophistication of late antique philosophical engagement with religious practice and magic.</p>

<h2>Influence and Legacy</h2>
<p>Iamblichus's <i>De Mysteriis</i> influenced subsequent Neoplatonic thought and became a foundational text for the development of Neoplatonic theurgy. The work defended religious practice and magic as legitimate philosophical concerns, contributing to the preservation of these traditions within pagan philosophy. The <i>De Mysteriis</i> influenced Christian thinkers who engaged with pagan philosophy and attempted to address the theological status of magical practices and divine invocation. The work's influence extended through the medieval period and into the Renaissance, where it contributed to the intellectual legitimacy of magic and magical philosophy. Modern scholarship has recognized the <i>De Mysteriis</i> as a crucial text for understanding late antique religious philosophy and the intellectual sophistication of pagan responses to philosophical critique.</p>

<h2>Literature</h2>
<p>Copenhaver, Brian P. <i>Magic in Western Culture: From Antiquity to the Enlightenment</i>. Cambridge: Cambridge University Press, 2015.<br>
Fowden, Garth. <i>The Egyptian Hermes: A Historical Approach to the Late Pagan Mind</i>. Cambridge: Cambridge University Press, 1986.<br>
Iamblichus. <i>De Mysteriis</i>. Translated by Emma C. Clarke, John M. Dillon, & Jackson P. Hershbell. Atlanta: Society of Biblical Literature, 2003.<br>
Litwa, M. David. <i>Hermetica II: The Greco-Egyptian Texts</i>. Cambridge: Cambridge University Press, 2018.<br>
van den Kerchove, Anna. <i>La voie d'Hermès: Pratiques rituelles et traités hermétiques</i>. Leiden: Brill, 2012.</p>""",

    "Theatrum Chemicum Britannicum": """<p><i>Theatrum Chemicum Britannicum</i> (<i>The Chemical Theater of Britain</i>) is a major English alchemical anthology compiled and edited by Elias Ashmole and published in 1652. The work brings together more than twenty English and Latin alchemical and esoteric texts, including works attributed to figures like Roger Bacon, Thomas Norton, George Ripley, and others. Ashmole's compilation is the most significant collection of English alchemical materials produced in the early modern period and has become an indispensable source for understanding the history of English alchemy. The <i>Theatrum Chemicum Britannicum</i> is significant for Hermetic studies because many of the texts it preserves engage with Hermetic and Neoplatonic philosophy, ground their understanding of alchemy in cosmological principles paralleling those of the Hermetic tradition, and represent the continuation and development of Hermetic learning in early modern English intellectual contexts. The anthology demonstrates the vitality of hermetic and alchemical traditions in seventeenth-century England and the integration of these traditions into English scholarly and antiquarian interests.</p>

<h2>Contents and Alchemical Doctrine</h2>
<p><i>Theatrum Chemicum Britannicum</i> presents diverse alchemical texts spanning medieval, Renaissance, and early modern periods. The texts address alchemical theory and practice, presenting accounts of the composition of metals, the principles of transmutation, the preparation of the Philosophers' Stone, and the spiritual significance of alchemical operations. The texts emphasize the integration of practical chemistry with spiritual discipline and philosophical understanding. The alchemical doctrines presented in the anthology ground alchemy in Hermetic and Neoplatonic cosmology: the universe is presented as a living, interconnected whole in which all materials are composed of fundamental principles and in which the transformation of base metals into gold corresponds to the spiritual transformation of the alchemist. The anthology includes explicit statements of the belief that alchemical operations are fundamentally spiritual practices in which material transmutation serves as the expression and agent of spiritual transformation. The texts present alchemy as a sophisticated intellectual discipline combining practical knowledge of materials and processes with philosophical and theological understanding. The inclusion of multiple works allows readers to encounter diverse approaches to alchemical theory and practice, suggesting the breadth and complexity of alchemical traditions in England.</p>

<h2>Ashmole's Scholarly Contribution</h2>
<p>Elias Ashmole (1617–1692) was a antiquarian, scholar, and alchemical enthusiast who systematically gathered, edited, and published alchemical texts. His <i>Theatrum Chemicum Britannicum</i> represents a major scholarly achievement: Ashmole located texts, established reliable texts from manuscript sources, provided editorial apparatus and contextual information, and made available to a broader audience materials that would otherwise have remained in manuscript. Ashmole's work was motivated partly by antiquarian interest in preserving English intellectual traditions and partly by personal engagement with alchemical and esoteric learning. The <i>Theatrum</i> reflects Ashmole's conviction that alchemy and alchemical texts were worthy of serious scholarly attention and preservation. The anthology influenced subsequent scholarship and has been recognized as a foundational collection of English alchemical materials. Modern scholars have used the <i>Theatrum</i> extensively in reconstructing the history of English alchemy and in understanding how alchemical thought was engaged with in early modern England.</p>

<h2>Influence and Legacy</h2>
<p>The <i>Theatrum Chemicum Britannicum</i> influenced the study and preservation of alchemical materials in England. The anthology demonstrated that English alchemy had a significant history worthy of preservation and study. The work influenced subsequent antiquarians and scholars seeking to recover and study English intellectual traditions. The <i>Theatrum</i> became a standard reference for anyone interested in English alchemy and contributed to the broader legitimacy of alchemy as a subject of serious historical and scholarly study. Modern scholarship has built extensively on the foundation provided by Ashmole's collection, using the texts preserved in the <i>Theatrum</i> to understand the development and transmission of alchemical thought in early modern England and its connections to broader European and Hermetic traditions.</p>

<h2>Literature</h2>
<p>Ashmole, Elias (ed.). <i>Theatrum Chemicum Britannicum</i>. London: N. Brooke, 1652.<br>
Copenhaver, Brian P. <i>Magic in Western Culture: From Antiquity to the Enlightenment</i>. Cambridge: Cambridge University Press, 2015.<br>
Nummedal, Tara. <i>The Alchemy of Glass: Counterfeit, Deception, and Transmutation in Early Modern Venice</i>. New Haven: Yale University Press, 2021.<br>
Principe, Lawrence M. <i>The Secrets of Alchemy</i>. Chicago: University of Chicago Press, 2013.<br>
Yates, Frances A. <i>Giordano Bruno and the Hermetic Tradition</i>. Chicago: University of Chicago Press, 1964.</p>""",

    "Psychology and Alchemy": """<p><i>Psychology and Alchemy</i>, originally published as <i>Psychologie und Alchemie</i> by Carl Jung in 1944, is a groundbreaking work examining the relationship between psychological symbolism and alchemical imagery and doctrine. Jung argues that alchemical symbolism expresses deep psychological structures and processes, particularly the process of individuation through which the personality develops and integrates disparate elements into a unified whole. The work is significant for Hermetic studies because it demonstrates how psychological and symbolic dimensions of alchemical thought can be analyzed and understood, and because it has influenced modern interpretations of alchemy and esotericism more broadly. Jung's work represents a distinctive modern approach to understanding esoteric traditions: rather than treating alchemical texts as primitive attempts at chemistry or as superstitious magical texts, Jung analyzes them as expressions of profound psychological and spiritual processes. The work has been influential in promoting serious scholarly and psychological engagement with alchemical materials and has contributed to modern recognition of alchemy as a significant tradition of psychological and spiritual development.</p>

<h2>Jung's Psychological Approach to Alchemy</h2>
<p>Jung's <i>Psychology and Alchemy</i> analyzes alchemical symbolism and processes as expressions of unconscious psychological structures and processes. Jung identifies recurrent symbols and motifs in alchemical texts and images—the conjunction of opposites, the transformation and perfection of matter, the emergence of the <i>lapis philosophorum</i> (Philosophers' Stone) as a unified whole—and interprets these as psychological processes rather than merely material or magical procedures. Jung argues that the alchemist's work of transforming base metal into gold mirrors the psychological work of individuation: the integration of conscious and unconscious elements, the reconciliation of opposites, and the emergence of a unified, whole self. The psychological interpretation does not deny the material dimensions of alchemical practice but rather understands material operations as simultaneously expressions of psychological processes and as vehicles for psychological transformation. Jung's analysis suggests that alchemical texts and practices have profound significance beyond their surface meaning, and that engagement with alchemical symbols and processes can facilitate psychological and spiritual development. The work contributes to understanding alchemy not as primitive chemistry or superstitious magic but as a sophisticated tradition of psychological and spiritual exploration.</p>

<h2>Historical Context and Jung's Influence</h2>
<p>Jung's <i>Psychology and Alchemy</i> was published in the 1940s, a period when Hermetic and alchemical traditions were beginning to receive increased scholarly attention. The work drew on Jung's broader psychological theory and his increasing interest in mystical and esoteric traditions. Jung's engagement with Eastern religions, with Hermetic thought, and with alchemical materials contributed to his development of analytical psychology and to his understanding of the psyche's spiritual dimensions. The work influenced subsequent scholarly and popular engagement with alchemy and esotericism: it established a framework through which psychological and symbolic dimensions of esoteric traditions could be analyzed. The work also contributed to the legitimacy of esotericism as a subject of serious scholarly and psychological study. Modern scholars, while not necessarily accepting all of Jung's interpretations, have built on the foundations Jung established for psychological analysis of alchemical and esoteric materials. The work has influenced popular and scholarly engagement with alchemy, encouraging interpretation of alchemical texts and processes in psychological and symbolic terms.</p>

<h2>Critiques and Contemporary Perspectives</h2>
<p>Jung's <i>Psychology and Alchemy</i> has received both admiration and criticism from scholars. Critics have argued that Jung's psychological interpretation can obscure the historical and material dimensions of alchemical practice, that his symbolic analysis may impose modern psychological categories on historical texts, and that the work overemphasizes the universal psychological significance of alchemical symbolism at the expense of understanding alchemical texts in their specific historical contexts. Contemporary scholarship has attempted to balance psychological and symbolic analysis with historical investigation of how alchemical texts were produced, transmitted, and engaged with in different historical contexts. Nevertheless, Jung's fundamental insight—that alchemical texts and processes have psychological and symbolic significance—has proven influential and enduring. Modern scholars continue to engage with Jung's work and with psychological interpretations of alchemy, even when they modify or critique specific aspects of his analysis.</p>

<h2>Literature</h2>
<p>Copenhaver, Brian P. <i>Magic in Western Culture: From Antiquity to the Enlightenment</i>. Cambridge: Cambridge University Press, 2015.<br>
Jung, Carl G. <i>Psychology and Alchemy</i>. Translated by R.F.C. Hull. Princeton: Princeton University Press, 1944/1970.<br>
Nummedal, Tara. <i>The Alchemy of Glass: Counterfeit, Deception, and Transmutation in Early Modern Venice</i>. New Haven: Yale University Press, 2021.<br>
Principe, Lawrence M. <i>The Secrets of Alchemy</i>. Chicago: University of Chicago Press, 2013.<br>
Yates, Frances A. <i>Giordano Bruno and the Hermetic Tradition</i>. Chicago: University of Chicago Press, 1964.</p>""",

    "Liber de stellis beibeniis": """<p><i>Liber de stellis beibeniis</i> (<i>Book of the Beibeni Stars</i>) is a medieval Latin astrological text of uncertain date and authorship, surviving in manuscript sources. The text appears to be an astrological treatise addressing the properties and influences of stars, their effects on terrestrial affairs, and procedures for astrological operations. The work exemplifies the medieval Latin astrological tradition, which developed through synthesis of Greek, Arabic, and Indian astrological learning transmitted through multiple languages and sources. The <i>Liber de stellis beibeniis</i> is significant for understanding medieval astrological thought and for recognizing the sophistication of medieval engagement with astrological theory and practice. The text contributes to understanding how Hermetic and astrological ideas were integrated into medieval intellectual culture and transmitted through the medieval period into the Renaissance. The work demonstrates the breadth of medieval Latin astrological literature, much of which survives in fragmentary form and has not received extensive modern scholarly study.</p>

<h2>Astrological Content and Doctrine</h2>
<p><i>Liber de stellis beibeniis</i> presents astrological doctrine addressing the nature of the stars, their properties, their relationships to planets and zodiacal signs, and their influence on terrestrial affairs. The text discusses the classical planets and their characteristics, the zodiacal signs and their meanings, and the houses of the zodiac and their astrological significance. The work includes procedures for astrological calculations, the interpretation of astrological configurations, and the determination of astrological timing for various operations. The underlying cosmology emphasizes the interconnection of celestial and terrestrial realms through sympathies and correspondences: the movements of stars and planets influence events on earth, and understanding these correspondences allows the practitioner to predict or direct events according to astrological principles. The text presents astrological knowledge as practical knowledge applicable to understanding human affairs and directing operations toward specific ends. The work exemplifies medieval synthesis of astrological traditions: the doctrines presented combine Greek Ptolemaic astronomy, Islamic astrological theory, and Indian astrological materials, all integrated into Latin medieval frameworks.</p>

<h2>Transmission and Medieval Reception</h2>
<p><i>Liber de stellis beibeniis</i> survives in medieval manuscript sources, suggesting circulation among medieval scholars and practitioners of astrology. The work appears to have been used as a reference or textbook in medieval learning contexts. The precise dating and provenance of the work remain uncertain, complicating understanding of its historical context and significance. The text exemplifies the vast body of medieval astrological literature, much of which remains inadequately studied or cataloged. The manuscript transmission of astrological texts demonstrates the significance of astrology in medieval intellectual culture: extensive astrological materials were copied, preserved, and transmitted through medieval libraries and scholarly communities. The study of such texts contributes to understanding the development of medieval science and the transmission of ancient and Islamic learning through the medieval period into the Renaissance.</p>

<h2>Modern Scholarship and Challenges</h2>
<p>The <i>Liber de stellis beibeniis</i> has received limited modern scholarly attention, partly due to the vast quantity of medieval astrological materials and the challenges of dating and analyzing these texts. Modern paleographical and textual analysis could contribute to understanding the work's date, provenance, and sources. Examination of the work in relation to other medieval astrological texts could illuminate its position within medieval astrological traditions and its contributions to the development of medieval astronomical and astrological thought. Contemporary scholarship continues to examine medieval astrological materials, recognizing their importance for understanding medieval intellectual history and the transmission of scientific and philosophical learning. The <i>Liber de stellis beibeniis</i> remains a valuable resource for this ongoing work.</p>

<h2>Literature</h2>
<p>Hanegraaff, Wouter J. <i>Hermetic Spirituality and the Historical Imagination</i>. Leiden: Brill, 2022.<br>
Lucentini, Paolo & Delp, Mark D. (eds.). <i>Hermes Latinus: Medieval Hermetic Philosophy</i>. Turnhout: Brepols, 1980–present.<br>
Pingree, David. <i>The Thousands of Abu Ma'shar</i>. London: Warburg Institute, 1968.<br>
Porreca, David. <i>The Picatrix and Medieval Occult Philosophy</i>. University Park: Pennsylvania State University Press, 2016.<br>
van Bladel, Kevin. <i>The Arabic Hermes: From Pagan Sage to Prophet of Science</i>. Oxford: Oxford University Press, 2009.</p>""",

    "Hermetic Spirituality and the Historical Imagination": """<p><i>Hermetic Spirituality and the Historical Imagination</i>, published by Wouter J. Hanegraaff in 2022, is a major contemporary work examining the role of historical imagination in the construction of Hermetic spirituality and in modern engagement with Hermetic traditions. Hanegraaff, the foremost contemporary scholar of Hermetic studies and the history of esotericism, explores how modern spirituality and spiritual movements have drawn on, reinterpreted, and sometimes misrepresented Hermetic texts and ideas. The work addresses fundamental questions about the relationship between historical understanding and spiritual practice, about how modern spiritual seekers construct meaning from historical materials, and about the responsibilities historians have in presenting historical materials to popular audiences. Hanegraaff argues that the Hermetic tradition is not a static historical phenomenon but a living tradition in which modern spiritual practitioners continue to engage with Hermetic texts and to develop new interpretations and applications. The work contributes to understanding how historical traditions are appropriated and transformed by modern communities, and how historical scholarship relates to contemporary spiritual interests and claims.</p>

<h2>Hermeticism, History, and Spirituality</h2>
<p><i>Hermetic Spirituality and the Historical Imagination</i> examines how modern spiritual movements and practitioners have engaged with Hermetic texts and traditions. The work discusses New Age movements, contemporary Hermetic orders and organizations, and individual spiritual practitioners who have drawn on Hermetic materials. Hanegraaff analyzes how modern spirituality has reinterpreted Hermetic doctrines, adapted historical materials to contemporary concerns, and developed new Hermetic practices and teachings. The work emphasizes that this modern engagement with Hermeticism is not simply distortion or corruption of historical traditions but rather a living development of traditions that have always been subject to reinterpretation and adaptation. Nevertheless, Hanegraaff argues for the importance of historical understanding and for the recognition of differences between historical Hermetic doctrines and modern spiritual interpretations. The work contributes to a critical but sympathetic understanding of how modern spirituality engages with historical traditions, recognizing both the creativity of modern spiritual practitioners and the importance of historical accuracy and contextual understanding.</p>

<h2>Historiographical Methodology and Responsibility</h2>
<p>Hanegraaff's work addresses the responsibilities of historians in presenting historical materials to diverse audiences. The work discusses tensions between scholarly historical understanding and spiritual appropriation of historical materials. It addresses questions about how historians can present historical materials in ways that are intellectually honest and contextually accurate while also acknowledging the legitimate spiritual interests and concerns of non-scholarly audiences. The work exemplifies Hanegraaff's broader methodological commitment to taking esotericism and Hermetic traditions seriously as historical phenomena worthy of rigorous scholarly study, while also maintaining critical distance from both hostile dismissal and uncritical celebration of these traditions. The work contributes to establishing frameworks for engaged, critical historical scholarship on esotericism and Hermeticism that respects both historical accuracy and contemporary spiritual interests.</p>

<h2>Contemporary Hermetic Movements</h2>
<p>The work discusses contemporary Hermetic organizations, teachings, and practices, examining how these movements have appropriated and reinterpreted Hermetic texts and doctrines. Hanegraaff analyzes specific contemporary Hermetic teachers and movements, examining their claims about historical authenticity, their reinterpretations of Hermetic doctrines, and their relationship to scholarly historical understanding. The work demonstrates the vitality and diversity of contemporary Hermetic engagement while also highlighting differences between contemporary interpretations and historical Hermetic teachings. The work contributes to understanding Hermetic tradition as a living, developing tradition in which contemporary practitioners continue to engage and innovate, even as historians work to reconstruct historical doctrines and practices.</p>

<h2>Literature</h2>
<p>Copenhaver, Brian P. <i>Hermetica: The Greek Corpus Hermeticum and the Latin Asclepius</i>. Cambridge: Cambridge University Press, 1992.<br>
Fowden, Garth. <i>The Egyptian Hermes: A Historical Approach to the Late Pagan Mind</i>. Cambridge: Cambridge University Press, 1986.<br>
Hanegraaff, Wouter J. <i>Hermetic Spirituality and the Historical Imagination</i>. Leiden: Brill, 2022.<br>
Hanegraaff, Wouter J. (ed.). <i>Dictionary of Gnosis and Western Esotericism</i>. Leiden: Brill, 2006.<br>
Yates, Frances A. <i>Giordano Bruno and the Hermetic Tradition</i>. Chicago: University of Chicago Press, 1964.</p>""",

    "The Stobaean Fragments (SH 1-29)": """<p>The <i>Stobaean Fragments</i>, designated SH 1-29 (in M. David Litwa's <i>Hermetica II: The Greco-Egyptian Texts</i>), are portions of Hermetic texts preserved in the <i>Anthologium</i> (anthology) of the Byzantine scholar Stobaeus (c. fifth century CE). Stobaeus compiled a vast anthology of quotations and excerpts from Greek philosophical, rhetorical, and literary texts, organized thematically. The <i>Anthologium</i> preserves numerous passages from Hermetic texts otherwise unknown or surviving only in fragmentary form. The <i>Stobaean Fragments</i> are significant because they expand knowledge of the Hermetic corpus beyond the <i>Corpus Hermeticum</i> and the <i>Asclepius</i>, revealing the existence of Hermetic materials now lost in their complete form. The fragments address cosmology, theology, ethics, and eschatology, presenting Hermetic doctrines in concise form. The modern edition and translation of these fragments by M. David Litwa has made them newly accessible to contemporary scholarship and has contributed to fuller understanding of the scope and diversity of Hermetic thought. The discovery, collection, and study of the Stobaean fragments exemplifies the ongoing process through which lost or fragmentary texts are recovered and integrated into historical understanding.</p>

<h2>Content and Hermetic Doctrine</h2>
<p>The <i>Stobaean Fragments</i> present Hermetic philosophical doctrines in concise, aphoristic form. The fragments address the nature of God and the divine, the structure of the cosmos and its emanation from the divine source, the nature of the human soul and its relationship to the divine, and the possibilities for human spiritual development through knowledge. The fragments present the characteristic Hermetic themes: the divine intellect (Nous) as the mediating principle through which transcendent divinity manifests in the cosmos, the hierarchical structure of reality with celestial and sublunary realms, the role of fate and providence in cosmic ordering, and the salvific potential of knowledge (gnosis). The fragments present ethics and virtue as grounded in knowledge of truth and alignment with cosmic principles. The eschatological doctrines in the fragments address the ultimate destiny of the soul and the cosmos. The concise, aphoristic form of the fragments suggests they may derive from compendia or teaching texts designed for instruction, or they may represent Stobaeus's condensations of longer original texts. The conciseness contributes to the difficulty of interpretation: fragmentary texts necessarily leave much implicit, requiring informed readers to supply contextual understanding.</p>

<h2>Manuscript Tradition and Recovery</h2>
<p>The <i>Stobaean Fragments</i> survive because Stobaeus's <i>Anthologium</i> was preserved through Byzantine manuscript transmission. Stobaeus's anthology was copied and preserved in monastic libraries and was transmitted through medieval times. The discovery and study of Stobaeus's anthology by modern scholars revealed the presence of these Hermetic fragments. The recovery of the Stobaean Hermetic material demonstrates the dependence of historical knowledge on contingent facts of manuscript survival and manuscript discovery. Had Stobaeus's anthology been lost, these Hermetic materials would be unknown. The recovery of these fragments through careful examination of Byzantine manuscripts exemplifies the ongoing process through which ancient texts are recovered and integrated into modern historical understanding. The study of the fragments has involved paleographical analysis, textual criticism, translation, and interpretive work to understand their meaning and significance within the broader Hermetic tradition.</p>

<h2>Modern Edition and Scholarly Significance</h2>
<p>M. David Litwa's modern edition and English translation of the Stobaean Hermetic fragments in <i>Hermetica II</i> has made these materials readily accessible to contemporary scholarship. Litwa's work involved translating the fragments from Greek, providing detailed philological and interpretive notes, and situating the fragments within the broader context of Hermetic literature and late antique philosophical thought. The edition has contributed significantly to modern recognition of the diversity and scope of surviving Hermetic materials. Subsequent scholarship has engaged with Litwa's translations and interpretations, building on his work to develop fuller understanding of Hermetic doctrine and the relationships among different Hermetic texts. The recovery and study of the Stobaean Fragments exemplifies how ongoing scholarly engagement with ancient manuscripts and texts continues to expand and refine historical understanding of the Hermetic tradition.</p>

<h2>Literature</h2>
<p>Copenhaver, Brian P. <i>Hermetica: The Greek Corpus Hermeticum and the Latin Asclepius</i>. Cambridge: Cambridge University Press, 1992.<br>
Fowden, Garth. <i>The Egyptian Hermes: A Historical Approach to the Late Pagan Mind</i>. Cambridge: Cambridge University Press, 1986.<br>
Litwa, M. David. <i>Hermetica II: The Greco-Egyptian Texts</i>. Cambridge: Cambridge University Press, 2018.<br>
Litwa, M. David. <i>Hermetica I: The Greek Corpus Hermeticum</i>. Cambridge: Cambridge University Press, 2018.<br>
van den Kerchove, Anna. <i>La voie d'Hermès: Pratiques rituelles et traités hermétiques</i>. Leiden: Brill, 2012.</p>""",
}

def update_texts():
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    count = 0
    for title_search, analysis_html in TEXTS_TO_EXPAND.items():
        cursor.execute('''
            UPDATE texts
            SET analysis_html = ?, review_status = 'DRAFT'
            WHERE title LIKE ?
        ''', (analysis_html, f'%{title_search}%'))

        cursor.execute('SELECT title FROM texts WHERE title LIKE ?', (f'%{title_search}%',))
        result = cursor.fetchone()
        if result:
            print(f"[OK] Updated: {result[0]}")
            count += 1

    conn.commit()
    conn.close()
    print(f"\nTotal updated: {count} texts")
    return count

if __name__ == "__main__":
    updated = update_texts()
