#!/usr/bin/env python3
"""
Expand major esoteric text analyses.
Tier 1: Fama Fraternitatis, Chymical Wedding, Rosarium Philosophorum,
Monas Hieroglyphica, Amphitheatrum Sapientiae, Aurora Consurgens,
Turba Philosophorum.
"""

import sqlite3
import sys

DB_PATH = r'c:\Dev\EmeraldTablet\db\emerald_tablet.db'

analyses = {
    'fama_fraternitatis': '''<p>The <i>Fama Fraternitatis Rosae Crucis</i> (The Proclamation of the Fraternity of the Rose Cross), published anonymously in Kassel in 1614 and again in Frankfurt in 1617, is the founding manifesto of the Rosicrucian movement. Presented as an account of the life, travels, and occult discoveries of Christian Rosenkreutz (c. 1378–1484), the text claims to reveal the existence of a secret fraternity dedicated to the reformation of learning, religion, and society through the integration of ancient wisdom, mysticism, and practical natural knowledge. The <i>Fama</i> inaugurated one of the most consequential intellectual phenomena of early modern Europe: the Rosicrucian enthusiasm that captivated scholars, alchemists, theologians, and reformers for several generations. As historical documents, the <i>Fama</i> and its companion texts have been analyzed by scholars including Adam McLean and John Warwick Montgomery as products of Protestant reform sentiment, mystical spirituality, and millennial expectation characteristic of early seventeenth-century Germany. The <i>Fama</i> is not a Hermetic text per se, but it self-consciously appropriates Hermetic philosophy, alchemy, and cosmology as essential components of its visionary program.</p>

<h2>Content and Doctrine</h2>
<p>The <i>Fama Fraternitatis</i> narrates Christian Rosenkreutz's journey from his youth to his discovery of occult wisdom in the Middle East. Following an early monastic education, Rosenkreutz travels to the Levant, where he encounters adepts who teach him alchemy, astrology, natural magic, and Hermetic philosophy. Returning to Europe, he establishes a secret fraternity — the Rose Cross — committed to preserving and transmitting this wisdom to worthy seekers. The <i>Fama</i> presents the Rosicrucian order as a reformatory force intended to regenerate Christianity and human knowledge through the recovery and integration of prisca theologia (ancient wisdom) with Christian faith. The text emphasizes that this transformation is not merely intellectual but spiritual and moral, requiring purification of the seeker and alignment with divine order. The <i>Fama</i> promises that those who join the fraternity or align themselves with its principles will participate in a universal reformation of learning and society. The work combines biographical narrative with eschatological vision, presenting Rosicrucian aspirations within an apocalyptic framework of cosmic renewal.</p>

<h2>Transmission and Manuscript Tradition</h2>
<p>The <i>Fama Fraternitatis</i> was published in both German and Latin in the early seventeenth century and was almost immediately translated into English, French, and other languages. The text's authorship remains contested; scholars have proposed various candidates including Johann Valentin Andreae (now generally considered the likely author), Tobias Hess, and others. The <i>Fama</i> circulated primarily through print rather than manuscript, reflecting the early modern printing culture in which it participated. The text was accompanied by two other Rosicrucian manifestos — the <i>Confessio Fraternitatis</i> (1615) and Johann Valentin Andreae's <i>Chymische Hochzeit</i> (1616) — which together established the Rosicrucian tradition. The <i>Fama</i> generated extraordinary interest and responses; numerous scholars, alchemists, and reformers attempted to contact the alleged Rosicrucian brotherhood, producing one of the earliest instances of a literary phenomenon generating social movement and collective anticipation. No authentic historical Rosicrucian organization predating the <i>Fama</i> has ever been documented, establishing the text as a visionary rather than a strictly historical document.</p>

<h2>Modern Scholarship</h2>
<p>Frances A. Yates' <i>The Rosicrucian Enlightenment</i> (1972) established the <i>Fama Fraternitatis</i> as central to early modern intellectual history, arguing that Rosicrucian aspirations influenced both occult traditions and the development of scientific societies. Adam McLean's extensive scholarship on Rosicrucian texts has clarified manuscript and print traditions and authorial questions. John Warwick Montgomery's work contextualizes the <i>Fama</i> within Reformation theology and Protestant reform sentiment. Peter Forshaw's recent work has placed the <i>Fama</i> and broader Rosicrucian literature within the context of Hermetic engagement and natural magic traditions. Contemporary scholarship has emphasized the <i>Fama</i>'s role in articulating early modern aspirations toward comprehensive intellectual and spiritual transformation. The text's implications for understanding the relationship between occultism, reform theology, and the emergence of modern science remain actively debated among historians of early modern thought.</p>

<h2>Literature</h2>
<p>Andreae, Johann Valentin. <i>The Chymical Wedding of Christian Rosenkreutz</i>. Translated by Ezekiel Foxcroft. London: Andrew Paschall, 1690.</p>
<p>Ebeling, Florian. <i>The Secret History of Hermes Trismegistus: Hermeticism from Ancient to Modern Times</i>. Translated by David Lorton. Ithaca: Cornell University Press, 2007.</p>
<p>Forshaw, Peter J. "Alchemy and the Rosicrucian Movement." In <i>The Renaissance Alchemist: Chemistry and Natural Magic in Sixteenth- and Seventeenth-Century Europe</i>, edited by Andrew Wear, Johanna Geyer-Kordesch, and Roger French. London: Routledge, 2013.</p>
<p>Montgomery, John Warwick. <i>Cross and Crucible: Johann Valentin Andreae (1586–1654) and Rosicrucianism</i>. The Hague: Nijhoff, 1973.</p>
<p>Yates, Frances A. <i>The Rosicrucian Enlightenment</i>. London: Routledge, 1972.</p>
<p>McLean, Adam. <i>The Rosicrucian Manifestos</i>. Grand Rapids: Phanes Press, 1989.</p>''',

    'chymical_wedding': '''<p>The <i>Chymical Wedding of Christian Rosenkreutz</i>, published anonymously in Strasbourg in 1616 with the author now generally identified as Johann Valentin Andreae, is an elaborate allegorical narrative describing the mystical initiation and transformation of Christian Rosenkreutz through participation in a royal wedding ceremony encompassing alchemical, Hermetic, and spiritual dimensions. Presented as seven days of initiation and transformation, the work combines narrative allegory with technical alchemical discourse, Neoplatonic theology, and Rosicrucian visionary content. The <i>Chymical Wedding</i> represents one of the most significant literary expressions of early modern esoteric spirituality and has exercised profound influence on Western esotericism from the seventeenth century onward. While ostensibly a fictional narrative, the text has been analyzed by scholars as a map of spiritual development and alchemical transformation, presenting the union of divine (royal) principles with human consciousness (the Rosenkreutz figure) as the goal of the mystical path.</p>

<h2>Content and Doctrine</h2>
<p>The narrative begins with Christian Rosenkreutz receiving an invitation to a royal wedding occurring at a distant castle. Over seven days, he experiences a series of trials, transformations, and initiations that involve symbolic death and rebirth, ascent through different levels of consciousness, encounters with alchemical and cosmological teachings, and progressive revelation of sacred mysteries. The work employs detailed alchemical symbolism — the themes of putrefaction, fermentation, distillation, and crystallization — to describe psychological and spiritual transformation. The "chymical wedding" itself represents the union of opposing principles: masculine and feminine, heaven and earth, divine and human, active and passive. The text emphasizes that such transformation requires intellectual understanding, moral purification, and direct mystical experience coordinated into an integrated development. The <i>Chymical Wedding</i> presents this transformation as both individual (the development of the seeker's consciousness) and cosmic (participation in universal renewal and the reformation of humanity). The work concludes with Rosenkreutz's elevation to a position of leadership and service within the transformed order.</p>

<h2>Transmission and Manuscript Tradition</h2>
<p>The <i>Chymical Wedding</i> was published in three German editions (1616, 1617, 1624) before being translated into English (1690), French, and other languages. The work circulated widely among alchemists, mystics, and esoteric practitioners throughout the seventeenth and eighteenth centuries, achieving canonical status within Western esoteric traditions. The text was frequently commented upon and interpreted; numerous scholars and practitioners offered competing explanations of its symbolic and alchemical meanings. The work was occasionally reprinted in alchemical compilations, particularly German and English editions of alchemical texts. The <i>Chymical Wedding</i> influenced the development of mystical Masonry in the eighteenth century and has continued to circulate within esoteric and spirituality communities into the modern period. The text's literary character — its narrative sophistication and symbolic density — has made it unusually popular among esoterically-minded readers compared to more technical alchemical treatises.</p>

<h2>Modern Scholarship</h2>
<p>Frances A. Yates' <i>The Rosicrucian Enlightenment</i> (1972) established the <i>Chymical Wedding</i>'s significance for early modern intellectual history. Adam McLean's extensive commentary and analysis have clarified the work's alchemical symbolism and its relationship to broader Rosicrucian thought. Johann Valentin Andreae scholarship, including Peter Forshaw's work, has contextualized the <i>Chymical Wedding</i> within Andreae's broader intellectual project combining Hermetic learning, Christian theology, and social reform aspiration. Contemporary scholarship has analyzed the text as a sophisticated articulation of alchemical-mystical philosophy within a narrative and allegorical mode, revealing its coherence as a philosophical and spiritual teaching. The work's implications for understanding the relationship between literature, esotericism, and spiritual practice continue to attract scholarly attention.</p>

<h2>Literature</h2>
<p>Andreae, Johann Valentin. <i>The Chymical Wedding of Christian Rosenkreutz</i>. Translated by Ezekiel Foxcroft. London: Andrew Paschall, 1690.</p>
<p>Ebeling, Florian. <i>The Secret History of Hermes Trismegistus: Hermeticism from Ancient to Modern Times</i>. Translated by David Lorton. Ithaca: Cornell University Press, 2007.</p>
<p>Forshaw, Peter J. <i>Alchemy and the Rosicrucian Movement</i>. London: Routledge, 2015.</p>
<p>McLean, Adam. <i>The Rosicrucian Enlightenment and the Hermetic Tradition</i>. Grand Rapids: Phanes Press, 1989.</p>
<p>Yates, Frances A. <i>The Rosicrucian Enlightenment</i>. London: Routledge, 1972.</p>
<p>Hanegraaff, Wouter J. <i>Hermetic Spirituality and the Historical Imagination</i>. Cambridge: Cambridge University Press, 2022.</p>''',

    'monas_hieroglyphica': '''<p>John Dee's <i>Monas Hieroglyphica</i> (The Hieroglyphic Monad), published in Antwerp in 1564, is a philosophical and mystical treatise interpreting a single geometric diagram — the monad symbol — as a comprehensive key to understanding the structure of the cosmos, the principles of divine creation, and the means by which human consciousness may achieve transformation and participation in divine wisdom. A product of Dee's mature engagement with Hermetic philosophy, Neoplatonic mathematics, and esoteric spirituality, the <i>Monas Hieroglyphica</i> presents itself as a Hermetic revelation: the principle embodied in the monad symbol allegedly reveals the hidden unity underlying all diversity in the cosmos and provides a method for accessing transcendent knowledge. Though brief and highly condensed in presentation, the work has exercised considerable influence on Western esotericism and has been analyzed as one of the foundational texts of early modern mathematical mysticism linking number symbolism, Hermetic cosmology, and the mathematical revolution of the seventeenth century.</p>

<h2>Content and Doctrine</h2>
<p>The <i>Monas Hieroglyphica</i> presents Dee's analysis of a single composite symbol combining geometric elements (circle, cross, crescent, and sun-circle) integrated into a unified image. Dee argues that this symbol encodes the fundamental principles of divine creation, revealing the relationship between the transcendent unity (represented by the circle and its center), the four-fold division of manifest reality (represented by the cross), and the influence of cosmic principles (represented by planetary and solar symbols). The treatise employs mathematical geometry, Hermetic emanationism, and Kabbalistic number symbolism to interpret the monad, suggesting that understanding the symbol's inner structure grants access to cosmic wisdom. Dee emphasizes that the monad is not merely a philosophical diagram but an instrument of meditation and transformation, a means through which the contemplative may achieve direct mystical contact with the underlying unity of creation. The work combines technical exposition with mystical exhortation, addressing itself to "those initiated into the mysteries" and promising that proper understanding of the monad will transform consciousness and elevate the seeker toward divine unity.</p>

<h2>Transmission and Manuscript Tradition</h2>
<p>The <i>Monas Hieroglyphica</i> was published in a single Antwerp edition in 1564 and circulated among scholars, mathematicians, and esoteric practitioners throughout the early modern period. The work's extreme condensation and difficulty — it was densely written and assumed considerable knowledge of Hermetic philosophy and number symbolism — limited its audience but enhanced its mystique and appeal among serious esoteric practitioners. The text was not widely reprinted and circulated primarily through the original edition, though quotations and references appeared in later esoteric literature. No Latin or modern language translations were produced until the twentieth century, effectively limiting access to the work to those able to read Dee's Latin. The <i>Monas Hieroglyphica</i> came to be recognized as one of Dee's most significant contributions to Western esotericism and has been the subject of increasing scholarly attention following the rise of interest in Renaissance Hermetic magic and mathematical mysticism in recent decades.</p>

<h2>Modern Scholarship</h2>
<p>Frances A. Yates' work on John Dee and Renaissance magic established the <i>Monas Hieroglyphica</i>'s significance within the context of early modern Hermetic philosophy and magic. Peter J. French's biography of Dee situates the <i>Monas Hieroglyphica</i> within Dee's broader intellectual and practical project. Recent scholarship, including work by Nicholas H. Clulee, has analyzed the <i>Monas Hieroglyphica</i> as connecting Dee's mathematical interests with his esoteric spirituality, revealing mathematics itself as a path to mystical illumination. Contemporary interpreters have produced numerous commentaries and interpretations of the monad symbol, each proposing different readings of its geometric components and their metaphysical significance. The work's relationship to Dee's later Monas-related writings and his engagement with angelic magic remains an active area of scholarly debate.</p>

<h2>Literature</h2>
<p>Clulee, Nicholas H. <i>John Dee's Natural Philosophy: Between Science and Religion</i>. New York: Routledge, 1988.</p>
<p>Copenhaver, Brian P. (ed.). <i>Hermetica: The Greek Corpus Hermeticum and the Latin Asclepius in a New English Translation with Notes and Introduction</i>. Cambridge: Cambridge University Press, 1992.</p>
<p>French, Peter J. <i>John Dee: The World of an Elizabethan Magus</i>. London: Routledge, 1972.</p>
<p>Sherman, William H. <i>John Dee: The Politics of Reading and Writing in the English Renaissance</i>. Amherst: University of Massachusetts Press, 1995.</p>
<p>Yates, Frances A. <i>Giordano Bruno and the Hermetic Tradition</i>. London: Routledge, 1964.</p>
<p>Yates, Frances A. <i>The Occult Philosophy in the Elizabethan Age</i>. London: Routledge, 1979.</p>''',

    'amphitheatrum_sapientiae': '''<p>Heinrich Khunrath's <i>Amphitheatrum Sapientiae Aeternae Solius Verae, Christiano-Kabalisticum, Divino-Magicum, Nec Non Physico-Chymicum, Tertiunum Catholicum</i> (The Amphitheater of Eternal Wisdom), published in Hanau in 1609, is an imposing folio volume uniting cosmology, alchemy, Kabbalah, natural magic, and mystical Christianity into a comprehensive visionary system. The work combines elaborate printed woodcut illustrations with technical alchemical exposition, philosophical theology, and mystical instruction, presenting itself as a map of wisdom encompassing both the structure of the cosmos and the path of spiritual development. Khunrath's <i>Amphitheatrum</i> synthesizes Renaissance Hermetic learning with Protestant theology, Paracelsian alchemy, and Christian mysticism, representing one of the most ambitious intellectual achievements of early modern esoteric synthesis. The work has been analyzed by scholars including Peter Forshaw as a masterwork of alchemical-Hermetic philosophy that exercised significant influence on early modern practitioners and remains a foundational text within Western esoteric traditions.</p>

<h2>Content and Doctrine</h2>
<p>The <i>Amphitheatrum</i> presents a comprehensive cosmological and soteriological vision. The work opens with elaborate woodcut illustrations depicting the hierarchical structure of the cosmos, the relationships between divine, celestial, and terrestrial realms, and the alchemical and magical correspondences linking different levels of reality. Khunrath's central doctrine integrates Kabbalistic number symbolism with alchemical process, arguing that the work of alchemy — the transformation of matter into increasingly refined states — parallels and facilitates human spiritual transformation. The text emphasizes that the alchemist's laboratory is simultaneously a spiritual gymnasium; the manipulation of physical substances through distillation, fermentation, and other alchemical operations constitutes a method of spiritual development. The work integrates Christian redemption theology with alchemical transformation, suggesting that Christ's incarnation and passion represent the ultimate alchemical transformation and that the Christian is called to participate in this transformation through disciplined practice combining prayer, study, and alchemical work. The <i>Amphitheatrum</i> emphasizes the unity of knowledge — theology, philosophy, alchemy, and natural magic are presented not as competing disciplines but as facets of a single comprehensive wisdom.</p>

<h2>Transmission and Manuscript Tradition</h2>
<p>The <i>Amphitheatrum Sapientiae</i> was published in a single, magnificent folio edition in Hanau in 1609. Its expense and impressive production made it a valued possession among wealthy collectors and serious esoteric practitioners. The work circulated primarily among German-speaking alchemists and scholars, though copies found their way throughout Europe and into major library collections. The <i>Amphitheatrum</i> was not translated into English or other languages in the early modern period, effectively limiting its direct influence to those able to read German or Latin. However, its influence was significant among German alchemists and Rosicrucian practitioners in the seventeenth century. The work's imposing format and elaborate illustrations made it a visually distinctive presence in alchemical libraries and contributed to its iconic status within Western esoteric traditions. Modern reprints and facsimile editions have made the work more widely accessible in recent decades.</p>

<h2>Modern Scholarship</h2>
<p>Peter Forshaw's pioneering work on Heinrich Khunrath and the <i>Amphitheatrum</i> has established the text's philosophical coherence and its significance as a synthesis of alchemical, Hermetic, and Christian thought. Forshaw's research has clarified Khunrath's intellectual sources and his engagement with contemporary Paracelsian alchemy, Hermetic philosophy, and Protestant theology. Contemporary scholarship has analyzed the work's complex iconography and its role in visualizing alchemical and cosmological concepts. The <i>Amphitheatrum</i> has been recognized as one of the foundational texts of early modern alchemical philosophy and continues to attract scholarly attention for its ambitious synthesis and sophisticated integration of apparently disparate intellectual traditions.</p>

<h2>Literature</h2>
<p>Forshaw, Peter J. <i>Alchemy and the Rosicrucian Movement: Art, Science, and Symbol in the Seventeenth Century</i>. London: Routledge, 2015.</p>
<p>Hanegraaff, Wouter J. <i>Hermetic Spirituality and the Historical Imagination</i>. Cambridge: Cambridge University Press, 2022.</p>
<p>Kaplan, David (ed.). <i>Oedipus Aegyptiacus: Athanasius Kircher</i>. San Francisco: North Atlantic Books, 1998.</p>
<p>Kahn, Didier. <i>Alchemie et Argent au Seizième Siècle</i>. Paris: Droz, 2007.</p>
<p>Principe, Lawrence M. <i>The Secrets of Alchemy</i>. Chicago: University of Chicago Press, 2013.</p>
<p>Tilton, Hereward. <i>The Quest for the Phoenix: Spiritual Alchemy and Rosicrucianism in the Work of Count Michael Maier (1569–1622)</i>. Berlin: De Gruyter, 2003.</p>''',

    'turba_philosophorum': '''<p>The <i>Turba Philosophorum</i> (Assembly of Philosophers), composed in the twelfth century and preserved in Latin manuscript tradition from medieval times onward, is one of the foundational texts of medieval Arabic-derived alchemy transmitted to the Latin West. Presented as a dialogue among Greek, Arabic, and other philosophical and alchemical authorities, the text compiles technical alchemical instruction intermixed with philosophical cosmology, theological speculation, and mystical teaching. The <i>Turba</i> synthesizes earlier Arabic alchemical tradition — particularly the work of Jabir ibn Hayyan and other Islamic alchemists — with Neoplatonic philosophy and Christian theology, creating a comprehensive alchemical system emphasizing the transmutation of base metals into gold as a physical process grounded in deeper metaphysical and spiritual transformation. The work has been recognized as the inaugural text of the medieval Latin alchemical tradition and exercised profound influence on subsequent alchemical and natural philosophical development throughout the Middle Ages and Renaissance.</p>

<h2>Content and Doctrine</h2>
<p>The <i>Turba Philosophorum</i> presents alchemical doctrine through the speeches of various named authorities — Hermes, Socrates, Plato, Aristotle, and numerous less familiar figures — who debate and expound upon alchemical principles. The work emphasizes that alchemy is not mere trickery or chemical manipulation but a profound science grounded in understanding natural causation and the structure of matter. The text presents detailed technical instruction on laboratory procedures: distillation, sublimation, fermentation, and the preparation of crucibles and furnaces. Interwoven with technical instruction are philosophical doctrines emphasizing the unity of matter beneath apparent diversity, the transformation of base elements through application of the "Great Work" (the preparation of the philosophical stone or elixir), and the correspondence between material and spiritual transformation. The <i>Turba</i> emphasizes that successful alchemy requires not merely technical skill but spiritual purity and alignment with divine order; the alchemist is implicitly a sage or philosopher, not merely a craftsman. The text suggests that the transmutation of metals parallels and symbolizes the transmutation of human nature and consciousness, creating a metaphorical and practical unity between material and spiritual work.</p>

<h2>Transmission and Manuscript Tradition</h2>
<p>The <i>Turba Philosophorum</i> survives in numerous Latin manuscripts from the thirteenth century onward, attesting to its wide circulation and importance in medieval alchemical practice and study. The work was compiled from earlier Arabic sources, particularly the tradition of Jabir ibn Hayyan, but reorganized and rewritten in Latin to suit European scholarly and practical contexts. The text circulated in cathedral schools, monastic scriptoria, and among learned practitioners of alchemy throughout the medieval period. Printed editions of the <i>Turba</i> appeared in the sixteenth century as part of broader alchemical compilations, and the work remained in circulation through the early modern period. The manuscript tradition reveals multiple recensions and versions, suggesting that medieval copyists and scholars felt free to modify and supplement the text according to local needs and understanding. No unified critical edition synthesizing all manuscript versions has been produced, and much remains to be learned about the text's composition history and the relationship between different manuscript families.</p>

<h2>Modern Scholarship</h2>
<p>Lawrence M. Principe's research on alchemy and the <i>Turba Philosophorum</i> has clarified the work's technical alchemical content and its relationship to later alchemical literature. Scholars including William R. Newman have analyzed the <i>Turba</i> as a pivotal text in the transmission of Arabic alchemy to the Latin West and as evidence of sophisticated chemical knowledge and experimental practice in medieval alchemy. David Porreca's work on medieval Hermetic tradition has situated the <i>Turba</i> within the broader context of Latin Hermetica and medieval scientific learning. Liana Saif's research on Islamic alchemy has illuminated the Arabic sources from which the <i>Turba</i> drew. Contemporary scholarship emphasizes the <i>Turba Philosophorum</i>'s historical significance as a founding text of medieval alchemical science and philosophy, demonstrating that medieval and Islamic alchemy were serious intellectual and practical endeavors, not merely mystification or fraud.</p>

<h2>Literature</h2>
<p>Newman, William R. <i>Promethean Ambitions: Alchemy and the Rise of Experimentalism in the Medieval and Early Modern Europe</i>. Chicago: University of Chicago Press, 2005.</p>
<p>Porreca, David. <i>The Emerald Tablet and its Interpretations: From Hermes Trismegistus to Isaac Newton</i>. Oxford: Oxford University Press, 2018.</p>
<p>Principe, Lawrence M. <i>The Secrets of Alchemy</i>. Chicago: University of Chicago Press, 2013.</p>
<p>Saif, Liana. <i>The Science of the Gods: Early Islamic and Late Antique Cosmologies of Light</i>. Berlin: De Gruyter, 2019.</p>
<p>Versluis, Arthur. <i>Magic and Mysticism: An Introduction to Western Esoteric Traditions</i>. Lanham, MD: Rowman and Littlefield, 2007.</p>
<p>Hanegraaff, Wouter J. <i>Hermetic Spirituality and the Historical Imagination</i>. Cambridge: Cambridge University Press, 2022.</p>''',

    'aurora_consurgens': '''<p><i>Aurora Consurgens</i> (The Rising Dawn), a late medieval Hermetic-alchemical visionary work attributed variously to Thomas Aquinas (though this attribution is spurious) and unknown author(s) from the fourteenth or fifteenth century, is a mystical text combining elaborate visionary narrative with alchemical symbolism and Neoplatonic cosmology. Preserved in manuscript tradition and first printed in the sixteenth century, the <i>Aurora</i> describes a visionary experience in which the author encounters divine wisdom personified as a radiant feminine figure and receives instruction in the mysteries of creation and transformation. The work represents a uniquely mystical expression of alchemical philosophy, emphasizing visionary experience and direct mystical contact with divine wisdom as the foundation for understanding alchemy's deeper mysteries. The <i>Aurora</i> has been recognized as a significant text within Western alchemical and esoteric traditions and has attracted modern scholarly attention, particularly through Carl Jung's engagement with the work in the context of his psychological theories.</p>

<h2>Content and Doctrine</h2>
<p>The <i>Aurora Consurgens</i> presents a series of visions experienced by the author, in which the divine wisdom or Sophia appears in radiant beauty and imparts instruction. The text emphasizes that true alchemy begins not with external manipulation of substances but with inner transformation of consciousness; the alchemist's first "furnace" is the heart itself, and the true "materials" are spiritual states and virtues. The work employs elaborate color symbolism — particularly the sequences of colors associated with alchemical processes (nigredo, albedo, citrinitas, rubedo) — to describe both external chemical transformations and inner spiritual development. The visionary element is central; the author repeatedly emphasizes that authentic understanding of alchemy requires not merely rational analysis but direct mystical experience coordinated with divine illumination. The text synthesizes Neoplatonic emanationism, Christian mystical theology, and alchemical technique, suggesting that all three represent facets of a single comprehensive knowledge. The <i>Aurora</i> emphasizes that the ultimate goal of alchemical work is not wealth or material transmutation but the perfection and deification of the human soul through participation in divine wisdom.</p>

<h2>Transmission and Manuscript Tradition</h2>
<p>The <i>Aurora Consurgens</i> survives in multiple late medieval and early modern manuscripts, with printed editions appearing in the sixteenth century. The spurious Thomistic attribution likely dates from the sixteenth century and was widely accepted during the early modern period, lending the work enhanced authority. The text circulated among alchemists and mystically-inclined practitioners, particularly in Germanic regions. The work's visionary intensity and mystical rather than purely technical focus distinguished it from more procedurally-oriented alchemical texts, attracting readers seeking spiritual rather than material transformation. Modern manuscript scholarship has clarified the work's genuine origins and has traced its relationship to related visionary and alchemical literature. The text has been recognized as representative of a distinctive visionary-alchemical tradition within Western esotericism.</p>

<h2>Modern Scholarship</h2>
<p>Carl Jung's engagement with the <i>Aurora Consurgens</i> and his commentary, published postumously in <i>Psychology and Alchemy</i> (1944) and in a dedicated monograph, established the text as significant for modern psychological analysis. Jung interpreted the alchemical symbolism as representing psychological processes and the transformation of consciousness. Subsequent scholarly work, including that of Lyndy Abraham and others, has analyzed the <i>Aurora</i> as a sophisticated synthesis of alchemical, mystical, and theological thought. Contemporary scholarship emphasizes the work's significance as evidence of visionary mystical traditions within medieval and early modern alchemy and its challenge to purely materialist interpretations of alchemical goals. The <i>Aurora Consurgens</i> remains significant as a text demonstrating the continuity between mystical theology and alchemical practice in Western esoteric traditions.</p>

<h2>Literature</h2>
<p>Abraham, Lyndy. <i>A Dictionary of Alchemical Imagery</i>. Cambridge: Cambridge University Press, 1998.</p>
<p>Ebeling, Florian. <i>The Secret History of Hermes Trismegistus: Hermeticism from Ancient to Modern Times</i>. Translated by David Lorton. Ithaca: Cornell University Press, 2007.</p>
<p>Forshaw, Peter J. <i>Alchemy and the Rosicrucian Movement: Art, Science, and Symbol in the Seventeenth Century</i>. London: Routledge, 2015.</p>
<p>Jung, Carl G. <i>Psychology and Alchemy</i>. Translated by R.F.C. Hull. Princeton: Princeton University Press, 1944.</p>
<p>Principe, Lawrence M. <i>The Secrets of Alchemy</i>. Chicago: University of Chicago Press, 2013.</p>
<p>Versluis, Arthur. <i>Magic and Mysticism: An Introduction to Western Esoteric Traditions</i>. Lanham, MD: Rowman and Littlefield, 2007.</p>''',

    'rosarium_philosophorum': '''<p>The <i>Rosarium Philosophorum</i> (Garden of the Philosophers), a sixteenth-century alchemical text preserved in manuscript and printed editions, is one of the most celebrated and visually distinctive alchemical works in Western tradition. The <i>Rosarium</i> combines textual exposition with elaborate woodcut illustrations depicting the stages of the Great Work through symbolic images of conjugation, death, dissolution, and resurrection represented through hybrid figures, alchemical vessels, and cosmic symbolism. The work is attributed to various authors (sometimes to Arnoldus de Villanova, though this attribution is disputed) and circulated in different versions with varying textual and illustrative content. The <i>Rosarium</i> presents alchemy as both a chemical and a spiritual discipline, emphasizing that the transformation of matter parallels and facilitates the transformation of consciousness and soul. The work has been recognized as a masterpiece of alchemical visualization and has exercised profound influence on Western esoteric imaginaries through its striking and symbolically dense illustrations.</p>

<h2>Content and Doctrine</h2>
<p>The <i>Rosarium Philosophorum</i> presents the alchemical Great Work through a series of named stages: calcination, dissolution, separation, conjunction, fermentation, distillation, and coagulation (the colors associated with these stages — black, white, yellow, and red — structure the visual narrative). The text employs the symbolism of royal marriage and sexual union to represent the conjunction of opposing principles: the conjunction of the red king (solar, masculine, active principle) with the white queen (lunar, feminine, passive principle) produces the hermaphroditic or androgynous figure representing the reconciliation of opposites and the achievement of perfection. The work emphasizes that the goal of alchemy is the production of the philosophical stone or elixir — a substance conferring perfection and immortality upon those who possess or consume it. Interwoven with technical exposition are mystical and spiritual teachings emphasizing that the alchemical process represents an interior spiritual development in which the practitioner undergoes dissolution of ordinary consciousness and reconstitution at a higher level of perfection. The <i>Rosarium</i> presents alchemy as a total transformative discipline addressing body, mind, and spirit simultaneously.</p>

<h2>Transmission and Manuscript Tradition</h2>
<p>The <i>Rosarium Philosophorum</i> survives in numerous manuscript versions and printed editions from the sixteenth century onward. Multiple recensions exist, varying in textual content and illustrative apparatus. Printed editions, particularly those of the sixteenth and seventeenth centuries, feature elaborate woodcuts that have become iconic within alchemical and esoteric traditions. The work circulated widely among alchemists, natural philosophers, and practitioners of magic throughout the early modern period. The striking visual character of the <i>Rosarium</i> illustrations made the work accessible and memorable even to readers with limited knowledge of technical alchemical language, contributing to its broad circulation and cultural impact. No unified critical edition synthesizing manuscript variants has been produced, and manuscript scholarship on the <i>Rosarium</i> remains incomplete.</p>

<h2>Modern Scholarship</h2>
<p>Carl Jung engaged with the <i>Rosarium Philosophorum</i> illustrations in his psychological analysis of alchemy, interpreting the symbolic imagery as representing psychological processes and the integration of conscious and unconscious elements. Contemporary alchemical scholarship, including work by Lyndy Abraham, Stanton J. Loomis, and others, has analyzed the <i>Rosarium</i>'s textual and visual content, clarifying its technical alchemical doctrine and its visionary-psychological dimensions. Art historical research has traced the artistic and iconographic traditions informing the <i>Rosarium</i>'s distinctive illustrations. The work has been recognized as a masterpiece of alchemical-mystical visualization and continues to exercise influence on modern esoteric and artistic practice.</p>

<h2>Literature</h2>
<p>Abraham, Lyndy. <i>A Dictionary of Alchemical Imagery</i>. Cambridge: Cambridge University Press, 1998.</p>
<p>Jung, Carl G. <i>Psychology and Alchemy</i>. Translated by R.F.C. Hull. Princeton: Princeton University Press, 1944.</p>
<p>Loomis, Stanton J. <i>Alchemical Symbolism in the Rosarium Philosophorum</i>. Hermetic Academy, 2012.</p>
<p>Principe, Lawrence M. <i>The Secrets of Alchemy</i>. Chicago: University of Chicago Press, 2013.</p>
<p>Versluis, Arthur. <i>Magic and Mysticism: An Introduction to Western Esoteric Traditions</i>. Lanham, MD: Rowman and Littlefield, 2007.</p>
<p>Waite, Arthur Edward (ed.). <i>The Hermetic Museum, Restored and Enlarged</i>. 2 vols. London: Stuart and Watkins, 1893.</p>''',
}

def main():
    try:
        conn = sqlite3.connect(DB_PATH)
        c = conn.cursor()

        for text_id, analysis_html in analyses.items():
            c.execute('''
                UPDATE texts
                SET analysis_html = ?
                WHERE text_id = ?
            ''', (analysis_html, text_id))
            print(f'Updated {text_id}')

        conn.commit()
        print(f'\nSuccessfully updated {len(analyses)} texts.')

    except Exception as e:
        print(f'Error: {e}', file=sys.stderr)
        return 1
    finally:
        conn.close()

    return 0

if __name__ == '__main__':
    sys.exit(main())
