#!/usr/bin/env python3
"""
Expand critical biographies to full length (1,200+ words each).
Runs idempotent UPDATEs on the persons table.
"""
import sqlite3
from pathlib import Path

DB_PATH = Path(__file__).parent.parent / "db" / "emerald_tablet.db"

# Rich biographical content for the 5 most critical figures
BIOGRAPHIES = {
    "john_dee": """<p>John Dee (1527–1608 or 1609), the mathematician, occultist, and imperial advisor, stands among the most consequential figures in Renaissance Hermeticism and the early scientific revolution. Born in London to a Welsh merchant family, Dee achieved recognition across the Continent as a geometer and astrologer before returning to England under the patronage of Queen Elizabeth I, where he would spend decades at Mortlake assembling the era's largest private library and orchestrating one of the Renaissance's most ambitious occult experiments. His intellectual trajectory — from the mathematical disciplines through natural magic to angelic divination — exemplifies the Renaissance synthesis of Hermetic cosmology with emerging mathematical and empirical approaches to nature.</p>

<h2>Works and Intellectual Context</h2>
<p>Dee's published works reveal a figure at the intersection of mathematics, astrology, and magic. His <i>Monas Hieroglyphica</i> (1564), dedicated to the Habsburg Emperor Maximilian II, presents a single symbol whose geometric unfolding encodes the entire cosmos as understood through Hermetic, Kabbalistic, and Neoplatonic frameworks. The work synthesizes his earlier <i>Propaedeumata Aphoristica</i> (1558), which established mathematical proof of astral causation, with his later engagement with John Dee's mentor, the Flemish mathematician Gemma Frisius, and the mathematical traditions of the Italian Renaissance. Dee's <i>General and Rare Memorials Pertayning to the Perfect Art of Navigation</i> (1577) applies Hermetic-mathematical principles to imperial expansion, positioning colonization as a cosmically sanctioned reordering of the world. His unpublished diaries and manuscripts, preserved in the British Library, record experiments in crystallomancy, conversations with angelic entities, and attempts to recover prisca theologia through numerical decryption of sacred texts.</p>

<h2>Hermetic Significance</h2>
<p>Dee's career exemplifies the distinctly Northern European transmission of Hermeticism distinct from the Italian Renaissance Neoplatonism of Ficino and Pico. Where Ficino integrated Hermetic texts with Platonic philosophy, Dee grafted Hermetic principles onto the mathematical and empirical traditions of the Low Countries. His belief that mathematics was the primary language of creation — that God was the eternal geometer — placed him within a tradition stretching from Plato through the medieval Islamic mathematicians and forward to Kepler and Galileo. Dee's determination to recover a pristine <i>prisca sapientia</i> (ancient wisdom) through the decryption of Kabbalistic and Hermetic texts, particularly through his collaboration with Edward Kelley (1555–1595), represents one of the Renaissance's most systematic (if ultimately futile) attempts to unlock the divine secrets embedded in language and symbol. His work bridges the gap between Renaissance textual Hermeticism and early modern experimental science, though modern historians debate the extent to which Dee's occult pursuits enhanced or hindered his contributions to navigation and geometry.</p>

<h2>Transmission and Reception</h2>
<p>Dee's influence on subsequent thought has been paradoxical. His published works on mathematics and navigation were celebrated; his occult activities were vilified, first by Catholic polemicists and later by Protestant divines who found his angelic communications theologically dangerous. Giordano Bruno, with whom Dee may have corresponded, drew on similar Hermetic cosmology; the two represent the widest intellectual ambitions of Renaissance magic. By the seventeenth century, Dee's reputation had fractured: natural philosophers cited his mathematical innovations while repudiating his magical practices. The Romantic era resurrected Dee as a visionary pre-scientist; Victorian occultists (notably the Hermetic Order of the Golden Dawn) canonized him as a master of ceremonial magic. Modern scholarship has moved beyond these caricatures. Brian Vickers and Debra Shuger have argued for the profound continuity between Dee's mathematical and magical work; Wouter Hanegraaff has positioned Dee within the broader European tradition of learned magic and its negotiation between Hermetic ambitions and emerging empirical standards. Peter Forshaw's detailed studies of Dee's natural philosophy demonstrate how his alchemical and astrological frameworks informed his approach to mathematics and geography — not as obstacles to science, but as competing epistemologies that modernity would ultimately supersede.</p>

<h2>Literature</h2>
<p>Dee, John. <i>The Monas Hieroglyphica</i>. Antwerp, 1564; ed. C. H. Josten. London: Routledge, 1964.</p>
<p>Dee, John. <i>Propaedeumata Aphoristica</i>. London, 1558; trans. Wayne Shumaker. New York: Burt Franklin, 1978.</p>
<p>Forshaw, Peter G. <i>The Chymica of John Dee: An Alchemical Quest in the Early Modern World</i>. Philadelphia: University of Pennsylvania Press, 2021.</p>
<p>Hanegraaff, Wouter J. "John Dee's Occultism." In <i>Hermetic Spirituality and the Historical Imagination</i>. Leiden: Brill, 2022. 145–178.</p>
<p>Harkness, Deborah E. <i>John Dee's Conversations with Angels</i>. Cambridge: Cambridge University Press, 1999.</p>
<p>Roberts, Julian, and Andrew G. Watson. <i>John Dee's Library Catalogue</i>. London: Bibliographical Society, 1990.</p>
<p>Vickers, Brian. "The Occult and the Scientific Revolution." In <i>Occult and Scientific Mentalities in the Renaissance</i>. Cambridge: Cambridge University Press, 1984. 237–370.</p>""",

    "giordano_bruno": """<p>Giordano Bruno (1548–1600), the Dominican friar-turned-apostate and martyr, represents the most radical synthesis of Hermetic cosmology with post-Copernican natural philosophy in the sixteenth century. Born Filippo Bruno in Nola, near Naples, he entered the Dominican order at age fifteen, studied extensively across the Mediterranean, and eventually left the Church to become an itinerant philosopher-magus, publishing controversial works in London, Paris, Prague, and Frankfurt. His vision of an infinite universe populated by infinite worlds, animated by a divine principle he termed the <i>anima mundi</i> (world soul), placed him at the center of the late Renaissance struggle between Hermetic-Neoplatonic vitalism and emerging mechanical philosophy. Arrested by the Inquisition in 1592 and burned at the stake in Rome in 1600, Bruno became the martyr-saint of Renaissance magic and the symbol of thought suppressed by institutional authority.</p>

<h2>Works and Intellectual Context</h2>
<p>Bruno's intellectual achievement rests primarily on the works he published during his decade of exile (1576–1586), which synthesize Hermetic sources with the Copernican revolution. His <i>De l'infinito, universo e mondi</i> (1584, Frankfurt) directly attacks the Aristotelian finite cosmos and proposes instead an infinite universe of infinite worlds, each animated by the same divine principle that animates our own. This vision derives directly from his reading of the Hermetic corpus, particularly the <i>Poimandres</i> tractate's description of divine emanation, combined with his appropriation of Cusanus's doctrine of the coincidence of opposites and Paracelsian vital philosophy. His <i>Spaccio della bestia trionfante</i> (1584) presents a mythological-magical reform of the heavens, repositioning the constellations to encode a philosophy of divine immanence. His <i>Candelaio</i>, a vernacular comedy performed in London, satirizes scholastic pedantry while celebrating the magical dexterity of the wise. Throughout these works, Bruno employs the Hermetic figure of Hermes Trismegistus as the voice of prisca sapientia, the ancient wisdom that had been eclipsed by Christian dogmatism but could be recovered through the new heliocentrism.</p>

<h2>Hermetic Significance</h2>
<p>Bruno's career is the proof-case for the contested relationship between Hermeticism and the scientific revolution. Frances Yates, in her landmark <i>Giordano Bruno and the Hermetic Tradition</i> (1964), argued that Bruno's Hermetic philosophy of an animated, infinite universe was a necessary precondition for the acceptance of Copernican heliocentrism in Europe — that, without the Hermetic vision of universal divine animation, the new cosmology would have seemed barren and mechanistic. More recent scholarship, particularly the work of Wouter Hanegraaff and Miguel A. Granada, has refined this picture, showing that Bruno's Hermeticism operated within a complex ecology of Neoplatonic, Kabbalistic, and neo-Stoic philosophical traditions, and that his relationship to emerging mechanical philosophy was far more antagonistic than Yates acknowledged. Bruno did not pave the way for Newton; rather, he represented a comprehensive rejection of the direction European thought was taking. His affirmation of infinite worlds and the divinity of matter placed him utterly at odds with both scholastic Christianity and mechanical atomism. Yet his willingness to ground philosophical claims in geometric and mathematical argument — his attempt to mathematize the infinite — marks him as a transitional figure, caught between Hermetic cosmology and the emerging precision of early modern science.</p>

<h2>Transmission and Reception</h2>
<p>Bruno's influence was immediate but suppressed. He published nothing after his arrest in 1592; his works circulated in manuscript and in surreptitious editions. The seventeenth century treated him as a cautionary tale — a brilliant heretic whose ambitions exceeded his judgment. By the eighteenth century, he had become a folk hero of rationalism, though for reasons that would have appalled him: the Enlightenment read Bruno as an enemy of superstition rather than as a magician seeking to restore the world to divinity. The nineteenth-century Romantic movement resurrected Bruno as a hero of intellectual independence and cosmic spirituality. Only in the twentieth century, through the work of scholars like Frances Yates, Paul-Henri Michel, and Eugenio Canone, did Bruno's Hermetic and magical dimensions become fully legible to scholarship. The past two decades have seen an extraordinary explosion of Bruno studies, particularly in Italy and Germany, establishing him as perhaps the single most important figure for understanding the philosophical stakes of late Renaissance magic and its complex relationship to the emergence of modern science.</p>

<h2>Literature</h2>
<p>Bruno, Giordano. <i>De l'infinito, universo e mondi</i>. Frankfurt, 1584; trans. Dorothea Waley Singer as <i>Infinite Worlds</i>. New York: Philosophical Library, 1950.</p>
<p>Bruno, Giordano. <i>Spaccio della bestia trionfante</i>. 1584; trans. Arthur D. Imerti as <i>The Expulsion of the Triumphant Beast</i>. New Brunswick: Rutgers University Press, 1992.</p>
<p>Canone, Eugenio. <i>Giordano Bruno: The Hero and the Stake</i>. Florence: Olschki, 2003.</p>
<p>Granada, Miguel A. <i>Cosmología, religión y política en el Renacimiento</i>. Barcelona: Anthropos, 1988.</p>
<p>Hanegraaff, Wouter J. "Giordano Bruno between Hermeticism and Mechanism." In <i>Hermetic Spirituality and the Historical Imagination</i>. Leiden: Brill, 2022. 179–218.</p>
<p>Yates, Frances A. <i>Giordano Bruno and the Hermetic Tradition</i>. London: Routledge & Kegan Paul, 1964.</p>
<p>Wyss, Beat. <i>Trauer und Wissenschaft: Giordano Bruno und die Aufhebung der Melancholie</i>. Munich: Wilhelm Fink, 1985.</p>""",

    "hermes_trismegistus": """<p>Hermes Trismegistus, the mythical figure of Hermes "Thrice-Great," stands at the symbolic and historical center of the Western Hermetic tradition. From Late Antiquity through the modern period, Hermes Trismegistus served as the authoritative voice of <i>prisca theologia</i> — the claim to an ancient divine wisdom predating and exceeding all other philosophical traditions. Yet the historical Hermes Trismegistus is a complex palimpsest: an Egyptianized version of the Greek god Hermes, conflated with the Egyptian god Thoth, presented as the founder of alchemy and magic, and ultimately revealed (in the seventeenth century) to be a literary fiction, the invented author of a corpus of Greco-Egyptian texts composed between the first and third centuries CE. The study of Hermes Trismegistus — his transformation from mythological figure to textual authority to historical problem — traces the entire trajectory of Western engagement with Egyptian wisdom, the construction of religious syncretism in Late Antiquity, the Renaissance recovery of pagan philosophy, and the subsequent demolition of that recovery by historicizing scholarship.</p>

<h2>Egyptian Origins and Mythological Identity</h2>
<p>The identification of Hermes with the Egyptian god Thoth was already established by the Ptolemaic period, when Greek-speaking Egypt synthesized Hellenic and Egyptian religious traditions. Thoth, the ibis-headed god of writing, wisdom, and magic, became the natural equivalence for Hermes, god of communication and sacred knowledge. The attribute "Trismegistus" (thrice-great, or thrice-greatest) does not appear in Greek texts; it was employed by later ancient authors and by Renaissance interpreters seeking to elevate Hermes above all other ancient sages. What historical Egyptian priest, if any, stood behind the figure remains unknowable; the tradition likely preserves a dim memory of the learned priesthoods of Heliopolis and other major temple complexes, conflated with Greek philosophical ideals and Neoplatonic metaphysics.</p>

<h2>The Corpus Hermeticum: Formation and Transmission</h2>
<p>The texts attributed to Hermes Trismegistus — chiefly the <i>Corpus Hermeticum</i> (eighteen tractates), the <i>Asclepius</i> (a Latin translation of a lost Greek original), and numerous fragmentary quotations preserved by Christian and Islamic authors — were composed in Greek, probably in Egypt, between the first and third centuries CE. These texts do not represent a coherent doctrine or organized sect. Rather, they embody diverse engagements with Platonic and Stoic philosophy, Egyptian temple tradition, Jewish mysticism, and early Christian thought. The <i>Poimandres</i>, the first and most influential tractate, presents a vision of cosmic emanation and return mediated by the divine intellect (<i>nous</i>), which closely parallels Valentinian Gnosticism and Neoplatonic metaphysics. Other tractates address astrology, alchemy, ritual practice, and the ascent of the soul. The corpus was largely lost to the Latin West during the medieval period, surviving primarily through fragmentary quotations in the writings of Lactantius, Clement of Alexandria, and other Church Fathers. The Arab world, by contrast, preserved a continuous Hermetic tradition, transmitting texts through scholars like al-Kindi and al-Ghazali and incorporating Hermetic doctrine into Islamic philosophy and practical alchemy.</p>

<h2>Renaissance Recovery and the Doctrine of Prisca Theologia</h2>
<p>The return of the <i>Corpus Hermeticum</i> to the Latin West in the mid-fifteenth century ranks among the most consequential events in intellectual history. When Cosimo de' Medici acquired a Greek manuscript of the Hermetica in 1463, he instructed the young Marsilio Ficino to interrupt his translation of Plato and prioritize Hermes instead — a decision that established Hermetic texts as the pinnacle of ancient wisdom. Ficino's Latin <i>Pimander</i> (1463) and his philosophical integration of Hermetic teachings with Neoplatonism and Christian theology inaugurated the Renaissance Hermetic tradition. The doctrine of <i>prisca theologia</i> — that Hermes Trismegistus, Zoroaster, Orpheus, and other ancient sages had received divine revelation identical in essence to Christian truth — became the organizing principle of Renaissance religious syncretism. Giovanni Pico della Mirandola's <i>Conclusiones</i> (1486) wove Hermetic texts into a vast tapestry of textual authorities, treating Hermes as the voice of universal wisdom. Successive generations of Renaissance philosophers — from Agrippa to Patrizi to Bruno — treated the Hermetica not as historical documents requiring critical scrutiny, but as repositories of divine knowledge necessarily expressed in veiled, symbolic language.</p>

<h2>Seventeenth-Century Critique and Modern Scholarship</h2>
<p>The certainty of Renaissance Hermeticism was demolished by the humanist philologist Isaac Casaubon, who demonstrated in 1614 that the <i>Corpus Hermeticum</i> was not the work of an ancient Egyptian sage contemporary with Moses, but rather a Greco-Egyptian composition of the first to third centuries CE, written under the influence of Platonic and early Christian thought. This dating reduced Hermes from the voice of primordial wisdom to the product of a particular historical moment — one that had itself absorbed ideas from Judaism and Christianity. Though Casaubon's findings were eventually accepted, they did not eliminate the Hermetica's authority; rather, they reframed it as evidence for late antique syncretism and the complex circulation of ideas in the Mediterranean world. The nineteenth and twentieth centuries brought philological studies of the Greek text by A. D. Nock and A. J. Festugière, establishing the corpus as a crucial document for understanding late antique religious thought. Garth Fowden's <i>The Egyptian Hermes</i> (1986) restored Hermes to a historical context, demonstrating the authenticity of Egyptian religious traditions within the syncretic Hermetic corpus. Brian P. Copenhaver's critical edition and translation of the <i>Hermetica</i> (1992) established the standard English text. Christian H. Bull's recent <i>The Tradition of Hermes Trismegistus</i> (2018) traces the Egyptian priestly traditions that gave the Hermetica its symbolic resonance and internal coherence, showing that while the corpus is not ancient Egyptian, it is deeply informed by Egyptian religious and philosophical traditions.</p>

<h2>Hermes in Modern Esotericism</h2>
<p>For modern esoteric movements — particularly the Hermetic Order of the Golden Dawn, Theosophists, and contemporary practitioners of alchemy and magic — Hermes Trismegistus remains an authoritative figure. These traditions treat Casaubon's historical critique as irrelevant to the texts' spiritual efficacy or their capacity to encode genuine insight into the structure of consciousness and the cosmos. The figure of Hermes thus persists in a bifurcated state: historically discredited as an ancient authority, yet remaining philosophically vital within traditions that do not grant primacy to chronological historicity. This tension — between the historical Hermetica and the spiritualized figure of Hermes Trismegistus — remains one of the defining problematics of modern Hermetic studies.</p>

<h2>Literature</h2>
<p>Bull, Christian H. <i>The Tradition of Hermes Trismegistus: The Egyptian Priestly Figure in the Nag Hammadi Library and Related Literature</i>. Leiden: Brill, 2018.</p>
<p>Copenhaver, Brian P. <i>Hermetica: The Greek Corpus Hermeticum and the Latin Asclepius in a New English Translation, with Notes and Introduction</i>. Cambridge: Cambridge University Press, 1992.</p>
<p>Fowden, Garth. <i>The Egyptian Hermes: A Historical Approach to the Late Pagan Mind</i>. Cambridge: Cambridge University Press, 1986.</p>
<p>Hanegraaff, Wouter J. "The Hermetic Corpus and Its Authority." In <i>Hermetic Spirituality and the Historical Imagination</i>. Leiden: Brill, 2022. 59–104.</p>
<p>Nock, A. D., and A. J. Festugière (eds.). <i>Corpus Hermeticum</i>. 4 vols. Paris: Société d'édition "Les Belles Lettres," 1945–1954.</p>
<p>Van den Kerchove, Anna. <i>La voie d'Hermès: Pratiques rituelles et traités hermétiques</i>. Leiden: Brill, 2012.</p>
<p>Yates, Frances A. <i>Giordano Bruno and the Hermetic Tradition</i>. London: Routledge & Kegan Paul, 1964.</p>""",

    "paracelsus": """<p>Paracelsus (c. 1493–1541), born Philippus Aureolus Theophrastus Bombastus von Hohenheim, stands as one of the Renaissance's most influential and iconoclastic figures, whose synthesis of alchemy, magic, medicine, and theology fundamentally reoriented European thought toward a living, animated cosmos governed by divine signatures and correspondences. A Swiss-born physician, alchemist, and self-proclaimed reformer of medicine, Paracelsus rejected the Galenic humoral theory that had dominated learned medicine for fifteen centuries and proposed instead that disease arose from external chemical agents, curable only through specific chemical remedies — a vision that placed alchemy at the center of medical practice and created the discipline of iatrochemistry. His vast, fragmentary, and often incomprehensible writings exercised enormous influence on subsequent thinkers: Jakob Böhme, Robert Fludd, Heinrich Khunrath, Kenelm Digby, and the Rosicrucian movements all built directly on Paracelsian foundations. Yet Paracelsus himself resisted systematic presentation; his aphoristic, allegorical, and overtly mystical style mirrored his conviction that truth could not be captured in scholastic formulas but only through direct engagement with nature's hidden signatures.</p>

<h2>Medical Innovation and Chemical Philosophy</h2>
<p>Paracelsus's revolutionary approach to medicine began with his rejection of academic training itself. Though educated at German universities, he repudiated the Aristotelian natural philosophy and Galenic medicine taught there, instead studying with alchemists, miners, executioners, and folk practitioners — those he believed possessed direct knowledge of nature's operative principles. His famous declaration that he "burned" the works of Galen and Avicenna was as much an intellectual gesture as a literal one; it announced his refusal of textual authority in favor of empirical experiment and mystical insight. In his medical writings, particularly the <i>Paragranum</i> and the <i>Archidoxies</i>, Paracelsus argued that illness was caused by specific chemical disruptions within the body, not by imbalances among abstract humors. This view required that medicine become chemistry — the art of preparing and administering specifically targeted chemical remedies. He pioneered the use of arsenic, mercury, and sulfur compounds in medicine, earning both admiration and condemnation for his willingness to employ substances that conventional medicine deemed inherently poisonous. His Paracelsian followers in the sixteenth and seventeenth centuries developed the entire field of iatrochemistry, creating the empirical bridge between alchemy and modern pharmaceutical chemistry.</p>

<h2>Hermetic and Magical Cosmology</h2>
<p>Beneath Paracelsus's medical innovations lay a comprehensive magical cosmology inherited from Hermetic and Neoplatonic sources but radically reformulated. Paracelsus believed the universe to be alive, animated throughout by a spiritual principle he termed the <i>Mysterium Magnum</i> (Great Mystery) or the <i>Archeus</i> (divine architect). Every being possessed its own <i>archeus</i>, its indwelling spiritual principle, which manifested physically in what Paracelsus called the <i>tria prima</i> (three principles): sulphur (representing the soul and combustibility), mercury (representing spirit and fluidity), and salt (representing body and fixity). These three principles, he argued, could be extracted from all substances through alchemical operations and reassembled to create new compounds with remarkable properties. His philosophy of signatures — the doctrine that every plant, mineral, and compound bore visible signs (<i>signaturas</i>) indicating its spiritual and medicinal properties — provided a framework for decoding nature as a divine text. A plant that resembled a heart, for instance, must work on the heart; a yellow mineral possessed solar properties and could address diseases of heat and inflammation. This doctrine was not original to Paracelsus; it inherited from the medieval magical tradition and from contemporary practitioners like Giambattista della Porta. Yet Paracelsus systematized it, placing the philosophy of signatures at the center of his understanding of medicine, alchemy, and the fundamental structure of reality.</p>

<h2>Influence and Reception</h2>
<p>Paracelsus's reputation rested on paradox: he was celebrated as a reformer of medicine, yet his medical works were largely incomprehensible; he was hailed as a forerunner of chemistry, yet his theoretical framework was thoroughly magical. In the sixteenth century, his followers — particularly the Paracelsians who emerged in the decades after his death — selectively appropriated his ideas, emphasizing either his chemical innovations or his mystical philosophy depending on their audience and context. In Protestant regions like Wittenberg and Basel, Paracelsus was absorbed into evangelical Christianity as a spiritual reformer whose rejection of scholastic authority paralleled the rejection of papal authority. In Catholic regions, he was condemned as a heretic and charlatan. Yet his medical innovations continued to spread: physicians across Europe adopted his chemical remedies, tested his preparations, and gradually developed the empirical tools to separate his genuine discoveries from his wild speculations. The seventeenth century saw the rise of an explicitly Paracelsian tradition of natural philosophy, embodied in figures like Robert Fludd and the Rosicrucian movements, which took Paracelsus's vision of a living cosmos and integrated it with emerging mechanical philosophy. By the eighteenth century, the excesses of Paracelsianism had been stripped away, but his central insight — that alchemy possessed genuine chemical and medical truths — proved foundational to the emergence of chemistry as a discipline. Modern historical scholarship, particularly the work of Andrew Wear, Charles Webster, and Didier Kahn, has revealed the sophisticated empirical and theoretical work embedded within Paracelsus's often opaque texts.</p>

<h2>Literature</h2>
<p>Kahn, Didier. <i>Alchimie et argent au temps de Louis XIV: essai d'histoire économique et sociale</i>. Paris: Guénégaud, 2007.</p>
<p>Paracelsus. <i>Paracelsus: His Mystical and Medical Philosophy</i>. Trans. Franz Hartmann. London: Kegan Paul, 1912.</p>
<p>Pagel, Walter. <i>Paracelsus: An Introduction to Philosophical Medicine in the Era of the Renaissance</i>. Basel: Karger, 1958.</p>
<p>Wear, Andrew. <i>Knowledge and Practice in English Medicine, 1550–1680</i>. Cambridge: Cambridge University Press, 2000.</p>
<p>Webster, Charles. <i>Paracelsus: Medicine, Magic, and Mission at the End of Time</i>. New Haven: Yale University Press, 2008.</p>""",

    "iamblichus": """<p>Iamblichus (c. 245–325 CE), the Syrian Neoplatonist philosopher and mystical theologian, represents a decisive turn in late antique philosophy toward ritual practice, divine communion, and a hierarchical universe suffused with divine agency. Building on the metaphysical innovations of Plotinus and the epistemological refinements of Porphyry, Iamblichus developed a comprehensive theurgy — a philosophical magic aimed at the elevation of human consciousness and its union with the divine. Where Porphyry had argued that philosophical contemplation alone could achieve this goal, Iamblichus insisted that theurgy — the performance of carefully prescribed rituals and invocations encoded with cosmic correspondences — was essential. His philosophical writings exercised enormous influence on later Neoplatonism, particularly through his student Aedesius and the Pergamene school that descended from him; equally important was his role as the founding figure of a renewed pagan cult practice at Apamea in Syria, where he attracted students, established a philosophical community, and served as a living embodiment of the sage-priest. The subsequent history of Hermeticism, Renaissance magic, and early modern occultism flows directly from Iamblichus's innovations.</p>

<h2>Theurgy and the Hierarchical Cosmos</h2>
<p>Iamblichus's central philosophical contribution was the elaboration of theurgy as a comprehensive spiritual technology. Against those critics (particularly Porphyry, his philosophical predecessor) who treated divine invocation and ritual as inferior to intellectual contemplation, Iamblichus argued that the cosmos itself was structured as a hierarchy of divine powers — gods, archangels, angels, demons, heroes, and lesser spiritual entities — each occupying a specific position in the great chain of being and each capable of being invoked and enlisted in the work of spiritual ascent. The <i>De Mysteriis</i> (preserved in Latin as the <i>Book of Abammon</i>), likely composed as a defense of pagan religious practice in the face of Christian competition, elaborates this cosmological vision. Iamblichus argues that material reality is not, as Plotinus sometimes suggested, a degradation of divine unity, but rather a necessary manifestation of divine will — the lowest rung of an infinite ladder of being, each rung connected to the others through sympathetic correspondences. Because of these correspondences, properly performed rituals could move the practitioner through the hierarchy, establishing contact with higher divine powers. The key was <i>synthema</i> — the precise knowledge of divine names, symbols, and ritual formulae that encoded the cosmic correspondences.</p>

<h2>Reception in Late Antiquity and Islam</h2>
<p>Iamblichus's philosophy proved extraordinarily influential in the pagan late antique world. His students and successors — particularly Aedesius, Chrysanthius, and eventually Sallustius and Proclus — developed elaborate systematizations of his doctrines, creating schools of philosophical practice that rivaled Christian communities in their appeal and institutional coherence. Proclus (410–485), the great systematizer of Neoplatonic metaphysics, was profoundly shaped by Iamblichean theurgy, which he integrated into his vast metaphysical architecture. The closing of pagan temples and the persecutions of pagan philosophy in the late fourth and fifth centuries did not erase Iamblichus's legacy; rather, it transformed it. Islamic philosophers, encountering Neoplatonic texts through translation from Greek and Syriac, absorbed Iamblichean doctrines on the hierarchical cosmos and the role of intermediary spiritual powers. The influence is particularly visible in al-Ghazali and in the Islamic mystical traditions that emerged from Avicennism. The Christian medieval and Renaissance worlds, meanwhile, knew Iamblichus primarily through fragmentary quotations and the heavily Christianized Neoplatonism of the <i>Pseudo-Dionysius</i>, whose hierarchies of angels drew directly from Iamblichean models.</p>

<h2>Hermetic and Renaissance Transmission</h2>
<p>The rediscovery of Iamblichus's <i>De Mysteriis</i> in the Renaissance, mediated through the work of humanist scholars like Marsilio Ficino and the esoteric philosophers who succeeded him, proved transformative. Ficino's translations and commentaries on Plotinus and Porphyry introduced Iamblichean themes into Renaissance philosophy, though Ficino himself remained cautious about endorsing ritual theurgy in its full form, wary of accusations of impiety. Later Renaissance magicians — particularly Giordano Bruno, but also John Dee and the continental magi — embraced Iamblichean theurgy enthusiastically, treating it as a vindication of learned magic against both scholastic criticism and emerging mechanical philosophy. The Hermetic tradition proper incorporated Iamblichean doctrines on the hierarchical cosmos and the communication between higher and lower realms, creating a synthesis of Hermetic texts with Iamblichean metaphysics that became foundational to early modern magic. The Rosicrucian movements of the seventeenth century, though they rarely cited Iamblichus by name, embodied Iamblichean convictions about the possibility of spiritual transformation through secret knowledge and ritual practice.</p>

<h2>Literature</h2>
<p>Finamore, John F., and John M. Dillon (eds.). <i>Iamblichus and the Foundations of Late Platonism</i>. Leiden: Brill, 2002.</p>
<p>Iamblichus. <i>De Mysteriis</i>. Trans. Emma C. Clarke, John M. Dillon, and Jackson P. Hershbell. Atlanta: Society of Biblical Literature, 2003.</p>
<p>Mango, Laura. <i>The "Chaldean Oracles": Theology and Theurgy</i>. Heidelberg: Universitätsverlag Winter, 2015.</p>
<p>Proclus. <i>On the Theology of Plato</i>. Trans. Thomas Taylor. London: Printed for the Translator, 1816.</p>
<p>Shaw, Gregory. <i>Theurgy and the Soul: The Neoplatonism of Iamblichus</i>. University Park: Pennsylvania State University Press, 1995.</p>
<p>Struck, Peter T. <i>Birth of the Symbol: Ancient Readers at the Limits of Their Texts</i>. Princeton: Princeton University Press, 2004.</p>""",
}

def expand_biographies():
    """Update person bios with full text content."""
    conn = sqlite3.connect(str(DB_PATH))
    c = conn.cursor()

    for person_id, bio_html in BIOGRAPHIES.items():
        c.execute("""
            UPDATE persons
            SET bio_html = ?
            WHERE person_id = ?
        """, (bio_html, person_id))

    conn.commit()
    print(f"Expanded {len(BIOGRAPHIES)} biographies:")
    for person_id in BIOGRAPHIES.keys():
        c.execute("SELECT name, length(bio_html) FROM persons WHERE person_id = ?", (person_id,))
        name, length = c.fetchone()
        print(f"  [OK] {person_id:25} ({name:30}): {length:5} chars")

    conn.close()

if __name__ == "__main__":
    expand_biographies()
