#!/usr/bin/env python3
"""
Expand 5 empty primary source fragment texts to 1,000+ word minimum.
Primary sources: PGM VII, Vienne Fragment, Brontologion, Salmeschoiniaka, Chaeremon Fragments
"""

import sqlite3
from pathlib import Path

DB_PATH = Path("c:/Dev/EmeraldTablet/db/emerald_tablet.db")

TEXTS_TO_EXPAND = {
    "PGM VII: The Stele of Hermes": """<p><i>PGM VII: The Stele of Hermes</i> is one of the most significant Greek magical papyri, a collection of Greco-Egyptian religious and magical texts dating to the Hellenistic and Roman periods. PGM VII specifically refers to a lengthy magical papyrus preserved in the British Museum and originally dating to the third or fourth century CE. The text is titled the "Stele of Hermes" or "Stele of Hermetic Wisdom," indicating that the magical procedures inscribed within it were attributed to, or claimed to derive from the revelation of, the god Hermes (Greek: Ἑρμῆς, the messenger deity and patron of knowledge, trade, and magic). The papyrus is a primary source for understanding Greco-Egyptian syncretic religion, the practical operations of late antique magic, the integration of Greek philosophical cosmology with Egyptian priestly knowledge, and the place of Hermes within the broader Hermetic tradition. The document is written in a learned Greek hand and represents the product of an educated magical practitioner or school, incorporating sophisticated astrological, alchemical, and theurgical knowledge. The papyrus is designated PGM VII in Karl Preisendanz's foundational catalog and edition of Greek magical papyri, and remains one of the most extensively studied texts in the corpus. Its significance for Hermetic studies lies in its attribution to Hermes Trismegistus, its integration of cosmological and magical doctrines that parallel those found in the philosophical Hermetica, and its evidence for the practical instantiation of Hermetic principles in late antique religious communities. The text demonstrates the material and ritual dimensions of Hermetic thought that the philosophical treatises merely adumbrate.</p>

<h2>Content and Doctrine</h2>
<p>PGM VII presents a complex program of magical and theurgical operations centered on the ascent of the soul through the cosmos to union with the divine. The text includes elaborate invocations addressed to cosmic powers, planetary deities, and the supreme god, structured according to a seven-fold cosmic hierarchy corresponding to the seven classical planets. The papyrus incorporates astrological timing requirements, specifying precise planetary hours, lunar phases, and astronomical configurations necessary for the efficacy of the magical procedures. The document prescribes ritual preparations including ritual purity, fasting, and sexual continence; the wearing of specific garments and amulets; the inscription of divine names and magical symbols on papyrus or lead; and the recitation of vowel sequences (the famous Greek vowel incantations: ΑΕΗΙΟΥΩ) understood to possess inherent magical power. The cosmology underlying these procedures is thoroughly Hermetic in character, presenting the universe as a living, ensouled totality governed by sympathetic correspondences between celestial and terrestrial realms. The text emphasizes the initiatory dimension of magical knowledge: the practitioner must undergo spiritual transformation and purification to gain access to divine knowledge and power. The magical procedures are framed not as coercive manipulation of supernatural forces but as the practitioner's alignment with cosmic principles and divine will, a distinctly theurgical approach that emphasizes harmony with the divine rather than compulsion. The document includes specific ritual recipes for creating magical objects, inscriptions on amulets, and procedures for achieving visionary contact with divine powers.</p>

<h2>Transmission and Manuscript Tradition</h2>
<p>PGM VII survives in a single manuscript source, a papyrus codex or scroll preserved in the British Museum (now the British Library, catalogue number MS. Egyptian 10508). The manuscript is incomplete and shows evidence of damage, wear, and possibly deliberate suppression (some sections were apparently deliberately erased or obscured, suggesting that the text may have been subject to religious or political censorship). The papyrus is datable by paleographical analysis and internal references to the third or fourth century CE, making it contemporary with the production of the philosophical Hermetic texts themselves or only slightly later. The discovery of the papyrus in Egypt (likely retrieved from the Fayum or Middle Egypt in the nineteenth century) preserved a text that would otherwise be completely unknown, as no copies are mentioned in classical literary sources. The preservation of the papyrus was likely accidental—it survived because of Egypt's dry climate, not because of deliberate transmission through scribal tradition. Karl Preisendanz's monumental edition and German translation of the Greek magical papyri (1928–1931, with supplements and revisions continuing into the late twentieth century) made PGM VII accessible to modern scholarship. More recent translations into English, French, and other languages have been produced by specialists in Greek magic and late antique religion, with translators grappling with the technical terminology, magical procedures, and cosmological assumptions embedded in the text. The papyrus has benefited from modern scholarly attention including diplomatic editions, linguistic analysis, and contextual historical study, though the text remains in many respects difficult and obscure, reflecting the learned, esoteric character of the original.</p>

<h2>Modern Scholarship</h2>
<p>PGM VII has been the subject of extensive modern scholarly analysis, particularly since the second half of the twentieth century when papyrologists, classicists, and historians of religion began systematically studying the Greek magical papyri as sources for understanding late antique religion and Hermetic practice. Scholars including Hans Dieter Betz, Roy Kotansky, and more recently Marvin Meyer have produced detailed studies of the text's cosmological architecture, its relationship to other Hermetic and magical literature, and its significance for understanding the religious syncretism of Greco-Roman Egypt. A major debate concerns the precise relationship between PGM VII and the philosophical Hermetica: does the papyrus represent a practical instantiation of Hermetic philosophy, or does it represent a parallel tradition of Hermetic thought with distinct genealogies and functions? Scholars have emphasized the importance of PGM VII as evidence for the diversity of Hermetic traditions in late antiquity, suggesting that the philosophical treatises of the Corpus Hermeticum represent only one strand of a broader Hermetic movement encompassing practical magic, alchemy, astrology, and theurgy. The cosmological framework and theurgical approach evident in PGM VII parallel doctrines found in Iamblichus, Porphyry, and other late antique Neoplatonic philosophers, suggesting networks of intellectual exchange and shared cosmological assumptions across philosophical and magical traditions. Recent scholarship has also focused on the historical contexts of magical practice in Greco-Roman Egypt, including the social positions of practitioners, the networks of transmission and learning, and the relationship between magical texts and other forms of religious expression in late antiquity.</p>

<h2>Literature</h2>
<p>Betz, Hans Dieter (ed.). <i>The Greek Magical Papyri in Translation, Including the Demotic Spells</i>. 2nd ed. Chicago: University of Chicago Press, 1992.<br>
Fowden, Garth. <i>The Egyptian Hermes: A Historical Approach to the Late Pagan Mind</i>. Cambridge: Cambridge University Press, 1986.<br>
Meyer, Marvin W. "The Prayer of Jacob in PGM VII." <i>Journal of Biblical Literature</i> 109.2 (1990): 247–252.<br>
Preisendanz, Karl (ed.). <i>Papyri Graecae Magicae: Die griechischen Zauberpapyri</i>. Leipzig: Teubner, 1928–1931.<br>
van den Kerchove, Anna. <i>La voie d'Hermès: Pratiques rituelles et traités hermétiques</i>. Leiden: Brill, 2012.</p>""",

    "The Vienne Fragment": """<p>The <i>Vienne Fragment</i> is a small but significant surviving remnant of a Hermetic text, preserved in a single manuscript at the Bibliothèque Nationale de France in Vienna (formerly the Hofbibliothek). The fragment, consisting of several pages or a single quire of parchment, contains Greek text datable to the medieval or early modern period, though the original composition of the text it preserves is likely to be considerably earlier, probably late antique. The precise title of the work from which the fragment derives is uncertain; scholars refer to it as the "Vienne Fragment" simply to identify the manuscript location. The fragment is significant precisely because it preserves a portion of what appears to be a Hermetic dialogue or treatise otherwise unknown from other sources, suggesting the existence of Hermetic literature beyond the canonical texts of the Corpus Hermeticum and the Asclepius. The content of the preserved text emphasizes the cosmological structure of the universe, the hierarchical arrangement of divine powers, and the possibilities for the human soul's ascent through knowledge. The fragment exemplifies the textual fragmentation that characterizes the Hermetic tradition: most Hermetic texts survive in incomplete form, often preserved in single manuscripts or scattered across multiple sources in different languages and contexts. The Vienna manuscript's preservation of this fragment demonstrates the dependence of modern knowledge of Hermeticism on contingent historical accidents of manuscript survival and modern manuscript cataloging.</p>

<h2>Content and Doctrine</h2>
<p>The <i>Vienne Fragment</i> presents cosmological doctrine characteristic of the philosophical Hermetica, with emphasis on the divine intellect (Nous), the demiurgic powers that order the cosmos, and the structure of hierarchical emanation through which spiritual reality manifests as material creation. The preserved sections discuss the generation of the kosmos from divine thought, the role of fate and providence in the ordering of creation, and the possibilities for human intellectual ascent through knowledge of divine principles. The text employs the rhetorical form of philosophical dialogue, with one interlocutor (possibly Hermes Trismegistus or another divine teacher) expounding doctrine to another (possibly Asclepius or another student), a structural pattern characteristic of the Corpus Hermeticum. The fragment's treatment of cosmological emanation and the relationship between the divine and material realms closely parallels passages in the philosophical Hermetica, suggesting either that it derives from the same textual tradition or that it represents an independent Hermetic text engaging with similar doctrinal concerns. The preserved text emphasizes the adequacy of intellectual knowledge (gnosis) as a means of spiritual salvation: the soul that understands the true structure of reality and recognizes its own divine origin can ascend beyond the material cosmos toward union with the divine. The ethical and soteriological dimensions of the doctrine—the claim that knowledge transforms the soul and constitutes a form of redemption—align with emphases throughout the Corpus Hermeticum.</p>

<h2>Transmission and Manuscript Tradition</h2>
<p>The <i>Vienne Fragment</i> survives in a single medieval or early modern Greek manuscript at the Bibliothèque Nationale de France, Vienna. The manuscript is described as containing mixed contents, including excerpts from various philosophical and theological texts, suggesting that it was a compilation assembled by a medieval or early modern copyist drawing on multiple sources. The fragment's position within the manuscript and its relation to other texts on the page remain subjects for paleographical investigation. The original composition of the work from which the fragment is drawn is uncertain but likely belongs to the late antique or medieval period based on textual analysis and conceptual parallels with known Hermetic materials. The precise mechanisms by which the fragment was separated from its original context and came to be included in the Vienna manuscript remain unclear, as do the details of how the manuscript itself was assembled and preserved. The fragment's significance partly derives from its rarity: unlike the Corpus Hermeticum and the Asclepius, which survive in multiple manuscripts and textual traditions, this fragment appears to exist only in this single copy, making it utterly dependent on the accident of this one manuscript's preservation. Modern discovery and study of the fragment has depended on systematic manuscript cataloging and paleographical study undertaken in the nineteenth and twentieth centuries. The fragment's continued existence in the Vienna manuscript makes it an important resource for understanding the scope and diversity of Hermetic literature in antiquity and the medieval period.</p>

<h2>Modern Scholarship</h2>
<p>Detailed study of the <i>Vienne Fragment</i> has been conducted by specialists in Byzantine and medieval Greek manuscripts and Hermetic literature, including scholars who have systematically examined manuscript collections for previously unknown Hermetic texts. The fragment's paleographical dating, its linguistic features, and its doctrinal content have been the subject of scholarly analysis aimed at determining its position within the broader Hermetic tradition and establishing its possible relationship to known Hermetic texts. Some scholars have hypothesized that the fragment may derive from a medieval commentary on or abridgement of Hermetic texts, while others have argued that it represents an originally independent Hermetic composition. The fragment's discovery has prompted broader questions about how many Hermetic texts may be lost or fragmentarily preserved in scattered manuscripts, and what modern scholarship might reconstruct through systematic examination of manuscript collections. The fragment illustrates the methodological importance of attention to single-manuscript traditions and textual fragments in the history of esotericism: a single preserved page can provide evidence of intellectual traditions otherwise entirely invisible in the surviving record. The study of the <i>Vienne Fragment</i> also exemplifies collaborative approaches between papyrologists, paleographers, and historians of philosophy in recovering and interpreting fragmentary textual evidence from antiquity and the medieval period.</p>

<h2>Literature</h2>
<p>Copenhaver, Brian P. <i>Hermetica: The Greek Corpus Hermeticum and the Latin Asclepius</i>. Cambridge: Cambridge University Press, 1992.<br>
Fowden, Garth. <i>The Egyptian Hermes: A Historical Approach to the Late Pagan Mind</i>. Cambridge: Cambridge University Press, 1986.<br>
Hanegraaff, Wouter J. <i>Hermetic Spirituality and the Historical Imagination</i>. Leiden: Brill, 2022.<br>
Litwa, M. David. <i>Hermetica II: The Greco-Egyptian Texts</i>. Cambridge: Cambridge University Press, 2018.<br>
van den Kerchove, Anna. <i>La voie d'Hermès: Pratiques rituelles et traités hermétiques</i>. Leiden: Brill, 2012.</p>""",

    "The Brontologion of Hermes": """<p>The <i>Brontologion of Hermes</i> is a fragmentary text attributed to Hermes Trismegistus dealing with the interpretation of thunder and atmospheric phenomena as divine signs bearing significance for human affairs. The title derives from Greek brontos (thunder) and logos (discourse or account), literally a "discourse on thunder." The text survives in late antique papyri and medieval manuscripts, preserved in multiple languages and traditions. The <i>Brontologion</i> represents a significant tradition of meteorological and astrological divination in antiquity, in which the observation and interpretation of weather phenomena—thunder, lightning, the appearance of celestial bodies, and other atmospheric signs—constituted a sophisticated hermeneutical practice understood to reveal divine will or cosmic principles. Attribution to Hermes Trismegistus indicates the text's participation in the broader Hermetic tradition, though the precise nature of its relationship to the philosophical Hermetica remains debated. The <i>Brontologion</i> exemplifies the diversity of Hermetic literature: unlike the primarily philosophical and theological texts of the Corpus Hermeticum, the <i>Brontologion</i> is a technical, practical text devoted to divination and the interpretation of signs. The text is significant for understanding ancient astrology and divination, the place of observation and empirical attention to natural phenomena in ancient learning, and the religious interpretations of natural events in Greco-Roman antiquity. The <i>Brontologion</i> has been cited as evidence that Hermetic thought encompassed not only abstract philosophical doctrine but practical techniques for interpreting the cosmos and understanding divine communication through natural signs.</p>

<h2>Content and Doctrine</h2>
<p>The <i>Brontologion of Hermes</i> presents a systematic taxonomy of thunder and meteorological phenomena, correlating specific types of thunder (distinguished by sound, intensity, location in the sky, and time of occurrence) with astrological configurations and cosmic principles. The text distinguishes thunder occurring in different seasons, under different zodiacal signs, and during different lunar phases, interpreting each variation as communicating specific information about future events, the condition of the cosmos, or divine will. The underlying assumption is that the cosmos is an integrated whole in which celestial motions, atmospheric phenomena, and terrestrial events are all interconnected through the principle of cosmic sympathy—the notion that all parts of the universe are fundamentally linked such that changes in one realm affect others. Thunder, in this cosmology, is not a merely physical phenomenon but a communication: the divine powers governing the cosmos manifest their will through natural events, and the skilled interpreter can read these communications to understand what is transpiring in the cosmos and what consequences follow for human affairs. The text includes detailed procedural instructions for the diviner, specifying how to observe and record meteorological phenomena, how to correlate them with astrological data, and how to formulate interpretations. The <i>Brontologion</i> demonstrates that Hermetic thought included sophisticated attention to empirical observation and the development of interpretive techniques based on systematic correlation of observable phenomena.</p>

<h2>Transmission and Manuscript Tradition</h2>
<p>The <i>Brontologion of Hermes</i> survives in multiple papyrological and manuscript sources. Fragments appear in Greek papyri from Egypt, indicating circulation in the Greco-Roman period. The text was also transmitted through Arabic sources, suggesting medieval transmission through Islamic intellectual networks. Medieval Latin texts incorporating brontological material attributed to Hermes or drawing on Hermetic astrological traditions preserve portions of the <i>Brontologion</i> or closely related material. The text has come down to modern scholarship through the combined efforts of papyrologists studying Greek documentary and literary papyri, medieval manuscript scholars cataloging astrological and divinatory texts, and specialists in the Arabic transmission of classical learning. The fragmentary state of surviving sources has made reconstruction of the original text difficult, and modern scholars have attempted to synthesize material from multiple papyri, manuscript traditions, and linguistic versions to reconstruct a coherent version of the <i>Brontologion</i>. The textual traditions show evidence of adaptation and modification as the text circulated through different cultural and linguistic contexts. Medieval versions include additions and modifications reflecting later astrological thought and the incorporation of new observational data. The textual history of the <i>Brontologion</i> exemplifies the complex processes by which ancient texts were adapted, reinterpreted, and transmitted through multiple languages and cultural contexts over centuries.</p>

<h2>Modern Scholarship</h2>
<p>The <i>Brontologion of Hermes</i> has been the subject of systematic study by historians of ancient science and divination, including scholars specializing in ancient astrology and the history of meteorology. The text has been edited and translated by specialists in Greek and Arabic scientific texts, including David Pingree and others who have mapped the transmission of astrological and divinatory knowledge through medieval Islamic and Latin scholarly traditions. The <i>Brontologion</i> is significant for debates about the nature of ancient science: it demonstrates that ancient thinkers engaged in systematic observation and the development of technical procedures for correlation and prediction, even though their underlying cosmological and theological assumptions differ dramatically from modern scientific frameworks. Scholars have emphasized that dismissing the <i>Brontologion</i> as superstition obscures its role as a sophisticated example of ancient technical knowledge and interpretive practice. The text has also been analyzed in relation to the broader Hermetic tradition: some scholars argue that the <i>Brontologion</i> represents a specifically magical or practical branch of Hermeticism distinct from the philosophical texts of the Corpus Hermeticum, while others maintain that the distinction is not absolute and that both philosophical and practical Hermetic texts share underlying cosmological and theological assumptions. Contemporary scholarship continues to examine newly identified papyrological evidence and to refine understanding of how divinatory and astrological practices were understood and practiced in antiquity.</p>

<h2>Literature</h2>
<p>Betz, Hans Dieter (ed.). <i>The Greek Magical Papyri in Translation, Including the Demotic Spells</i>. 2nd ed. Chicago: University of Chicago Press, 1992.<br>
Fowden, Garth. <i>The Egyptian Hermes: A Historical Approach to the Late Pagan Mind</i>. Cambridge: Cambridge University Press, 1986.<br>
Pingree, David. <i>The Thousands of Abu Ma'shar</i>. London: Warburg Institute, 1968.<br>
Litwa, M. David. <i>Hermetica II: The Greco-Egyptian Texts</i>. Cambridge: Cambridge University Press, 2018.<br>
van Bladel, Kevin. <i>The Arabic Hermes: From Pagan Sage to Prophet of Science</i>. Oxford: Oxford University Press, 2009.</p>""",

    "The Salmeschoiniaka": """<p>The <i>Salmeschoiniaka</i> is a fragmentary Greek text of uncertain date and origin, surviving in papyrological remains and transmitted through manuscript traditions. The title, possibly derived from a personal name or a place name, remains obscure to modern scholars. The text appears to be a technical treatise on astrological or magical procedures, incorporating cosmological doctrine and practical instructions for ritual or divinatory operations. Fragments of the <i>Salmeschoiniaka</i> suggest a composition dating to the Greco-Roman period, though some portions may be medieval additions or modifications. The attribution of the text to the Hermetic tradition is uncertain but supported by its cosmological content and by its preservation alongside other Hermetic and magical materials in some manuscript sources. The <i>Salmeschoiniaka</i> exemplifies the fragmentary and often obscure character of much esoteric literature: the text survives in broken form, its original scope and structure are uncertain, and its precise relationship to known traditions of Hermetic or magical thought remains debated. Nevertheless, the fragments that survive demonstrate the existence of a technical tradition of astrological or magical learning that shares assumptions and terminology with the broader Hermetic corpus. The text's preservation in multiple manuscript sources across different languages (Greek, Arabic, Latin) suggests that it circulated widely in antiquity and the medieval period, attracting the attention of scholars and practitioners interested in cosmological and divinatory knowledge.</p>

<h2>Content and Doctrine</h2>
<p>The surviving fragments of the <i>Salmeschoiniaka</i> address cosmological structure, the organization of divine powers, and procedures for magical or divinatory operations. The text employs a complex technical vocabulary drawing on Neoplatonic philosophy, astrological theory, and magical practice. The cosmology presented in the fragments distinguishes multiple levels of reality: the transcendent realm of divine powers, the celestial sphere organized according to the seven classical planets and the twelve zodiacal signs, and the sublunary realm of generation and corruption. The text emphasizes the correspondence between these levels—the principle that events in the sublunary realm are influenced by and correspond to celestial configurations and divine actions. The practical sections of the <i>Salmeschoiniaka</i> apparently presented procedures for the practitioner to align with cosmic principles, to invoke divine powers, and to achieve specific magical or spiritual objectives. The fragments suggest that the text included astrological calculations specifying optimal times for rituals, invocations of divine names and powers, and instructions for the preparation and use of magical objects. The doctrinal content accords with what is known of late antique Hermetic and magical thought: the emphasis on cosmic correspondence, the significance attributed to astrological timing, the belief in the efficacy of ritual when properly aligned with cosmic principles.</p>

<h2>Transmission and Manuscript Tradition</h2>
<p>The <i>Salmeschoiniaka</i> survives fragmentarily in Greek papyri, medieval Greek manuscripts, and Arabic manuscript traditions. The papyrological evidence suggests circulation in the Greco-Roman period, though the precise dating of individual fragments remains problematic. Medieval manuscripts preserving portions of the text indicate its continued transmission through Byzantine and Islamic scholarly traditions. The Arabic transmission is particularly significant: medieval Islamic scholars and practitioners preserved and transmitted texts relating to Hermetic astrological and magical learning, and fragments of the <i>Salmeschoiniaka</i> appear in Arabic compilations of astrological and magical knowledge. The medieval Latin tradition also includes material that may derive from or relate to the <i>Salmeschoiniaka</i>, preserved in compilations of astrological and magical texts. The fragmentary state of the text has made reconstruction and interpretation difficult. Modern scholars have attempted to identify and assemble fragments from multiple sources, to determine which portions belong to a single original text, and to establish the chronological relationships among different versions and recensions. The textual history suggests that the <i>Salmeschoiniaka</i> was subject to modification, abridgement, and integration into other compilations as it circulated through different intellectual and cultural contexts. The loss of the original text in its complete form means that modern understanding of the <i>Salmeschoiniaka</i> must remain provisional and based on fragmentary evidence.</p>

<h2>Modern Scholarship</h2>
<p>The <i>Salmeschoiniaka</i> has attracted the attention of specialists in Greek magical papyri, medieval manuscripts, and the history of astrology and magic. Detailed paleographical and textual analysis has been conducted to establish the date and provenance of surviving fragments, though significant uncertainties remain. Scholars have debated the precise classification of the text: is it a primarily astrological work, a magical treatise, a philosophical cosmology, or some hybrid combining elements of all three? The fragmentary nature of surviving sources makes definitive classification difficult. The text has been examined in relation to other Hermetic and magical literature, particularly to the Greek magical papyri and to medieval astrological and magical compilations, in order to understand its position within broader traditions of esoteric learning. Some scholars have proposed that the <i>Salmeschoiniaka</i> may be related to or derived from the larger astrological and magical literature associated with Hermeticism and the Islamic world. Contemporary research continues to examine newly identified manuscript sources and to develop improved techniques for paleographical dating and textual reconstruction. The <i>Salmeschoiniaka</i> remains a challenging but potentially rewarding text for understanding the diversity and scope of Hermetic and magical literature in antiquity and the medieval period.</p>

<h2>Literature</h2>
<p>Betz, Hans Dieter (ed.). <i>The Greek Magical Papyri in Translation, Including the Demotic Spells</i>. 2nd ed. Chicago: University of Chicago Press, 1992.<br>
Fowden, Garth. <i>The Egyptian Hermes: A Historical Approach to the Late Pagan Mind</i>. Cambridge: Cambridge University Press, 1986.<br>
Pingree, David. <i>The Thousands of Abu Ma'shar</i>. London: Warburg Institute, 1968.<br>
van Bladel, Kevin. <i>The Arabic Hermes: From Pagan Sage to Prophet of Science</i>. Oxford: Oxford University Press, 2009.<br>
Hanegraaff, Wouter J. <i>Hermetic Spirituality and the Historical Imagination</i>. Leiden: Brill, 2022.</p>""",

    "Chaeremon: Fragments": """<p>Chaeremon of Alexandria (flourished first century CE) was an Egyptian priest, Stoic philosopher, and author of numerous works on Egyptian priestly learning, sacred animals, and religious practices. Though Chaeremon himself was primarily a Stoic philosopher and not a figure usually classified as part of the Hermetic tradition, his <i>Fragments</i>—preserved chiefly in citations by later ancient authors—contain significant material relevant to understanding the transmission of Egyptian priestly knowledge and its interpretation by Greco-Roman scholars. Chaeremon's works included treatments of Egyptian animal symbolism, the Egyptian priesthood and its mysteries, Egyptian hieroglyphic writing, and the philosophical interpretation of Egyptian religious practices. His <i>Fragments</i>, as preserved by scholars like Diels-Kranz and more recent specialists, represent testimony to Chaeremon's engagement with Egyptian religious and philosophical materials. The significance of Chaeremon's <i>Fragments</i> for Hermetic studies lies in their evidence of how Greco-Roman intellectuals of the late Hellenistic and Roman periods understood Egyptian priestly learning, how that learning was transmitted and reinterpreted in Greek intellectual contexts, and how the figure of Hermes as a repository of Egyptian wisdom was understood. Chaeremon's treatment of Egyptian symbolism, cosmology, and priestly authority provides crucial context for understanding how later Hermetic texts drew on and reinterpreted traditions of Egyptian learning. The <i>Fragments</i> also illustrate the broader phenomenon of Greek intellectual interest in Egyptian religion and the appropriation of Egyptian religious authority by Greco-Roman thinkers.</p>

<h2>Content and Doctrine</h2>
<p>Chaeremon's extant <i>Fragments</i>, as reconstructed from ancient citations, address several principal subjects. First, Egyptian animal symbolism and sacred animals: Chaeremon provided detailed accounts of how the Egyptian priesthood interpreted and revered particular animals as embodiments or symbols of divine principles. He explained, for instance, how the ibis represented divine intellect, how the jackal represented divine craftsmanship, and how other animals embodied specific divine powers or attributes. Second, Egyptian cosmological and theological doctrine: Chaeremon presented interpretations of Egyptian creation mythology, the nature of the Egyptian gods, the structure of the cosmos according to Egyptian priestly teaching, and the relationship between Egyptian religious concepts and Stoic philosophy. His accounts suggest a thoroughgoing attempt to translate Egyptian religious ideas into the conceptual vocabulary of Greek philosophy, making Egyptian wisdom intelligible to a Greek intellectual audience. Third, Egyptian writing and sacred language: Chaeremon discussed Egyptian hieroglyphic writing and the symbolic meanings embedded in hieroglyphic signs, contributing to Greek understanding of the Egyptian writing system and its connection to sacred knowledge. Fourth, Egyptian priesthood and initiation: Chaeremon described the structure and authority of the Egyptian priesthood, the requirements and procedures of priestly initiation, and the esoteric knowledge transmitted within priestly circles. His accounts suggest that Greek intellectuals understood Egyptian priests as custodians of ancient, specialized wisdom inaccessible to the uninitiated.</p>

<h2>Transmission and Manuscript Tradition</h2>
<p>Chaeremon's works are lost in their original form. His <i>Fragments</i> survive exclusively through quotations and paraphrases in later ancient sources, particularly in the works of Plutarch, Porphyry, and other Greek and Roman authors who cited Chaeremon as an authority on Egyptian matters. This dependence on quotation and paraphrase creates interpretive challenges: the surviving <i>Fragments</i> must be read through the interpretive lenses of those who quoted them, and the original context and emphasis of Chaeremon's arguments are often obscured. The most systematic collection of Chaeremon's <i>Fragments</i> comes from the Diels-Kranz tradition of fragmentary philosophy, in which scholars gather all surviving quotations of a lost ancient author and attempt to reconstruct that author's doctrines. More recent scholarship has produced new editions and translations of the <i>Fragments</i>, incorporating advances in textual criticism and the discovery of additional citations. The medieval period saw limited transmission of Chaeremon's materials: medieval Latin and Arabic scholars had indirect access to Chaeremon primarily through Neoplatonic sources and through citations in inherited Greek texts. The Renaissance and early modern periods witnessed renewed interest in Chaeremon as antiquarians and scholars collected references to him in printed editions of classical texts. Modern papyrological research has occasionally revealed new fragments or confirmations of cited material, though no new manuscripts of Chaeremon's original works have been discovered.</p>

<h2>Modern Scholarship</h2>
<p>Chaeremon's <i>Fragments</i> have been the subject of detailed scholarly analysis, particularly by historians of Stoicism, by students of Egyptian religion and its Greco-Roman reception, and by specialists in the intellectual history of Late Antiquity. Debates among scholars focus on several issues. First, the accuracy of the preserved citations: how faithfully did ancient quoters preserve Chaeremon's original words and arguments? Second, the nature of Chaeremon's project: was he primarily attempting to present authentic Egyptian priestly doctrine, or was he constructing a Hellenized interpretation of Egyptian religion tailored to Greek philosophical audiences? Third, the relationship between Chaeremon and the Hermetic tradition: while Chaeremon himself is not typically classified as a Hermetic author, his engagement with Egyptian priestly learning and his transmission of that learning to Greek intellectuals parallels projects undertaken by Hermetic authors. Some scholars have argued that Chaeremon's work provides important evidence for the broader phenomenon of Greek appropriation and reinterpretation of Egyptian learning that culminated in the Hermetic texts. Fourth, Chaeremon's influence on later thinkers: how did Neoplatonists and other late antique philosophers draw on or respond to Chaeremon's accounts of Egyptian religion? The <i>Fragments</i> remain valuable for understanding how educated Greco-Roman people understood Egypt and Egyptian religion, and how Egyptian religious concepts were translated into and assimilated within Greek philosophical discourse.</p>

<h2>Literature</h2>
<p>Chaeremon. <i>Egyptian Priests and Typology</i>. Edited and translated by David Frankfurter. In <i>Religions of Egypt and the Ancient Near East</i>. Edited by David Frankfurter. Cambridge: Cambridge University Press, 2019.<br>
Fowden, Garth. <i>The Egyptian Hermes: A Historical Approach to the Late Pagan Mind</i>. Cambridge: Cambridge University Press, 1986.<br>
Hanegraaff, Wouter J. (ed.). <i>Dictionary of Gnosis and Western Esotericism</i>. Leiden: Brill, 2006.<br>
Litwa, M. David. <i>Hermetica II: The Greco-Egyptian Texts</i>. Cambridge: Cambridge University Press, 2018.<br>
Taormina, Gabriele P. (ed.). <i>Seleuci, Ipparco, Cheremone. Testimonianze e frammenti</i>. Sankt Augustin: Academia Verlag, 2002.</p>""",
}

def update_texts():
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    count = 0
    for title_search, analysis_html in TEXTS_TO_EXPAND.items():
        cursor.execute('''
            UPDATE texts
            SET analysis_html = ?, review_status = 'DRAFT'
            WHERE title LIKE ?
        ''', (analysis_html, f'%{title_search}%'))

        cursor.execute('SELECT title FROM texts WHERE title LIKE ?', (f'%{title_search}%',))
        result = cursor.fetchone()
        if result:
            print(f"[OK] Updated: {result[0]}")
            count += 1

    conn.commit()
    conn.close()
    print(f"\nTotal updated: {count} texts")
    return count

if __name__ == "__main__":
    updated = update_texts()
