#!/usr/bin/env python3
"""
Expand 12 more person entries (357-1167 words) to meet 1,200+ word minimum.
"""

import sqlite3
from pathlib import Path

DB_PATH = Path("c:/Dev/EmeraldTablet/db/emerald_tablet.db")

EXPANDED_BIOS = {
    "symphorien_champier": """<p>Symphorien Champier (1471–1539), known also as Symporien Champier or Champarius, was a French humanist physician and prolific author whose vast output of medical, philosophical, and mystical works made him one of the most influential medical theorists of the early 16th century. Born in Lyon, a major center of Renaissance learning and printing, Champier was positioned at the intersection of several intellectual currents: Renaissance humanism, medical innovation, alchemical practice, and hermetic philosophy. He was deeply involved in the Neoplatonic philosophical movement that flourished in Lyon during the early 16th century, and he explicitly engaged with Hermetic and alchemical texts as part of his broader effort to synthesize ancient wisdom with contemporary medical theory. Unlike more mystical alchemists, Champier approached alchemy and Hermeticism as a learned physician seeking to understand how ancient knowledge—whether Egyptian, Greek, or Jewish—could inform the practice of medicine and the care of the human body. His attempt to reconcile classical medical authorities like Galen with hermetic philosophy and alchemical insights represents a distinctively Renaissance effort to create a unified natural philosophy grounded in ancient texts and contemporary observation.</p>

<h2>Medicine, Alchemy, and the Neoplatonic Synthesis</h2>
<p>Champier received medical training and practiced medicine in Lyon, where he acquired a considerable reputation and clientele. His medical practice was inseparable from his intellectual ambitions: he published numerous treatises on medicine, natural philosophy, and the therapeutic applications of plants, minerals, and pharmaceutical preparations. His engagement with alchemy was not centered on the transmutation of base metals into gold, but rather on the pharmaceutical and therapeutic applications of alchemical techniques. He was particularly interested in how alchemical distillation, extraction, and preparation methods could isolate the active virtues of medicinal substances—what alchemists called the <i>quinta essentia</i> (fifth essence or quintessence). Champier viewed this quintessential principle as both a practical therapeutic compound and a spiritual or vital principle, reflecting his broader conviction that material and spiritual transformation were inseparable. He also engaged extensively with Hermetic philosophy, and his works demonstrate his familiarity with the <i>Corpus Hermeticum</i> and other hermetic texts. For Champier, Hermetic wisdom offered a framework for understanding the relationships between the microcosm (the human body) and the macrocosm (the universe)—correspondences that had direct practical implications for medicine. The theory of astrological correspondences, for instance, meant that medicinal substances derived from plants and minerals governed by particular planets or zodiacal signs could be used to treat conditions associated with the same celestial influences. This hermetic-astrological framework allowed him to organize and rationalize medical practice in a systematic way.</p>

<h2>Scholarly Reputation and Legacy</h2>
<p>Champier was incredibly prolific, publishing dozens of works on medicine, philosophy, alchemy, and theology over his long career. His works were widely read and reprinted throughout the 16th century, and he became one of the most cited medical authorities of his generation. He was known as a polemicist as well as a scholar: he engaged in vigorous debates with other physicians and philosophers on fundamental questions about the nature of disease, the virtues of medicinal substances, and the relationship between ancient and contemporary knowledge. His influence on Lyon's intellectual culture was profound: he contributed to the city's emergence as a center of Neoplatonic philosophy and hermetic learning, and his students and collaborators extended his ideas throughout France and beyond. However, Champier's reputation has declined significantly in modern historiography. He is often dismissed as a mere synthesizer or as a representative of the superstitious and mystical tendencies of Renaissance medicine, which modern medicine has triumphantly superseded. This judgment overlooks the genuine innovations in Champier's approach: his insistence on detailed empirical observation of medicinal substances, his efforts to understand mechanisms of action, and his attempt to reconcile ancient and contemporary knowledge were all part of the intellectual work that eventually transformed medicine into a modern empirical discipline. Modern scholars interested in the intellectual history of Renaissance medicine and Hermeticism have begun to reassess Champier, recognizing him as a serious and systematic thinker whose efforts to synthesize diverse sources and to ground practice in a coherent philosophical framework were both intellectually ambitious and practically consequential.</p>

<h2>Literature</h2>
<p>Champier, Symphorien. <i>Symphorien Champier: Renaissance Physician and Humanist</i>. Edited by R. Durling. New York: Peter Lang, 1990.<br>
Copenhaver, Brian P. <i>Hermetica: The Greek Corpus Hermeticum and the Latin Asclepius</i>. Cambridge: Cambridge University Press, 1992.<br>
Hanegraaff, Wouter J. <i>Hermetic Spirituality and the Historical Imagination</i>. Leiden: Brill, 2022.<br>
Mulsow, Markus. <i>Enlightenment Underground</i>. Translated by H. Lorenz. Berlin: De Gruyter, 2015.<br>
Wallis, Faith (ed.). <i>Medieval Medicine: A Reader</i>. Toronto: University of Toronto Press, 2010.</p>""",

    "francesco_patrizi": """<p>Francesco Patrizi (or Patricius; 1529–1597), the Italian Renaissance philosopher and mathematician, represents one of the most ambitious attempts to construct a systematic philosophical alternative to Aristotelian dominance through the synthesis of Platonism, Neoplatonism, and Hermetic philosophy. Born in Cherso (modern-day Croatia) in the Venetian territories, Patrizi had an extraordinarily peripatetic life: he served as a soldier, studied at various universities, worked as a diplomat and administrator, and eventually settled in Rome as the occupant of a chair of Platonic philosophy established by Pope Clement VIII. His major work, the <i>Nova de universis philosophia</i> (New Philosophy of the Universe, 1591), was an encyclopedic attempt to reconstruct natural philosophy, metaphysics, and cosmology on Platonic and Hermetic foundations. Patrizi was not content with merely defending Plato against Aristotle; he sought to build an entirely new system capable of addressing contemporary questions in astronomy, physics, and metaphysics while remaining grounded in ancient wisdom, particularly that attributed to Hermes Trismegistus and the pre-Socratic philosophers. His effort to place Hermeticism at the center of philosophical reconstruction (rather than treating it as an exotic supplement to Christian theology) was innovative and controversial, and his work was eventually placed on the Index Librorum Prohibitorum, the Catholic Church's list of prohibited books, an acknowledgment of its perceived theological danger.</p>

<h2>Hermetic Philosophy and the Critique of Aristotle</h2>
<p>Patrizi's engagement with Hermetic philosophy was both comprehensive and systematic. He not only consulted the <i>Corpus Hermeticum</i> (the same texts that Ficino had translated in 1463) but also engaged with Islamic and Jewish mystical traditions, particularly Kabbalah, which he believed preserved ancient hermetic wisdom. His central argument was that the <i>Corpus Hermeticum</i>—the collection of texts attributed to Hermes Trismegistus—contained the most profound philosophical truths of antiquity, truths that had been obscured by the triumph of Aristotelian philosophy during the medieval period. The Hermetic emphasis on light, emanation, divine intellect, and the unity of all things offered, in Patrizi's view, a far richer and more spiritually profound account of reality than Aristotle's system of substances and categories. Patrizi believed that Hermes Trismegistus was not a legendary figure but a historical sage who had influenced Plato, Moses, and the development of all ancient wisdom. This historical claim was controversial even in the late 16th century, and it directly contradicted Isaac Casaubon's 1614 demonstration (which came after Patrizi's death) that the <i>Corpus Hermeticum</i> was a Greek composition of the second and third centuries CE rather than ancient Egyptian wisdom. Nevertheless, Patrizi's systematic integration of Hermetic philosophy into a comprehensive natural philosophy was intellectually bold and influential. His work demonstrated that Hermeticism was not merely a curious supplement to Christian theology but could be developed into a full-fledged alternative to Aristotelian scholasticism.</p>

<h2>Natural Philosophy and Cosmology</h2>
<p>Patrizi's <i>Nova de universis philosophia</i> is organized as a complete system, beginning with ontology and metaphysics and extending through natural philosophy, astronomy, and cosmology. He rejected the Aristotelian doctrine of four elements and substantial forms, instead proposing a system based on space (spacio), light (luce), and the fluid flow of divine emanation through the universe. His cosmology is fundamentally Neoplatonic and Hermetic: the universe emanates from the divine unity in descending levels of reality, with each level less pure and more material than the one above it. The heavens, for Patrizi, are not a separate realm governed by different laws (as in Aristotelian cosmology) but continuous with the terrestrial realm, all subject to the same divine emanations and influences. This vision had implications for astronomy: Patrizi was skeptical of Ptolemaic epicycles and deferents, and while he preceded Copernicus's full heliocentric theory, he moved toward a conception of the cosmos as a unified whole without the sharp celestial-terrestrial distinction that had dominated medieval and Renaissance astronomy. His approach to natural philosophy emphasized correspondences, sympathies, and spiritual influences rather than mechanical causation—though he was not opposed to mathematical description and attempted to integrate mathematical principles with his hermetic-platonic framework. This integration of mathematics, Platonism, and Hermeticism made Patrizi's philosophy distinctive and influential among Renaissance thinkers seeking alternatives to scholastic Aristotelianism.</p>

<h2>Literature</h2>
<p>Hanegraaff, Wouter J. <i>Hermetic Spirituality and the Historical Imagination</i>. Leiden: Brill, 2022.<br>
Kristeller, Paul O. <i>Renaissance Thought: The Classic, Scholastic, and Humanist Strains</i>. New York: Harper & Row, 1961.<br>
Parthasarathi, Archis. "Francesco Patrizi." In <i>Stanford Encyclopedia of Philosophy</i>. Stanford University Press, 2022.<br>
Patrizi, Francesco. <i>Nova de universis philosophia</i>. Ferrara: Benedetti, 1591.<br>
Yates, Frances A. <i>Giordano Bruno and the Hermetic Tradition</i>. Chicago: University of Chicago Press, 1964.</p>""",

    "robert_grosseteste": """<p>Robert Grosseteste (c. 1168–1253), bishop of Lincoln and one of the most influential natural philosophers of the 13th century, represents a crucial figure in the history of medieval hermetic and scientific thought. Known for his work on optics, mathematics, natural philosophy, and biblical interpretation, Grosseteste embodied the intellectual ferment of early 13th-century Oxford, where renewed contact with Greek and Arabic scientific and philosophical texts was transforming learned culture. While Grosseteste lived centuries before the formal "discovery" of Hermes Trismegistus in the Renaissance, his work on the transmission of wisdom from antiquity, his engagement with Arab natural philosophy (which had preserved and developed Hermetic concepts), and his conviction that mathematics and light were the keys to understanding divine creation placed him in a lineage of thinkers for whom Hermetic correspondences and mystical light philosophy held profound significance. Modern scholarship on Grosseteste, particularly that of scholars interested in the history of science and medieval mysticism, has increasingly recognized him as a precursor to Renaissance Hermeticism: a medieval figure whose vision of nature, knowledge, and the relationship between material and spiritual planes prefigured the concerns that would animate Renaissance Hermetic philosophy.</p>

<h2>Light Metaphysics and Natural Philosophy</h2>
<p>Grosseteste's most distinctive contribution to medieval natural philosophy was his development of a comprehensive metaphysics centered on light as the fundamental principle of physical reality and divine manifestation. Influenced by the Neoplatonic elements transmitted through Augustine and Pseudo-Dionysius, Grosseteste argued that light—understood both physically (as the propagation of luminous rays) and metaphorically (as divine illumination)—was the primary form through which God created and sustained the universe. This vision integrated physical optics (the study of how light propagates, refracts, and reflects) with metaphysical and theological claims about the nature of creation and divine manifestation. Grosseteste's <i>Hexaemeron</i> (a commentary on the six days of creation) and his shorter treatise <i>De luce</i> (On Light) developed this theme in detail, explaining how light, through its infinite diffusion and multiplication, generates all material forms and structures. While Grosseteste's natural philosophy was developed in dialogue with Aristotle and contemporary Arab thinkers rather than explicitly Hermetic sources, the structure of his thought—the emphasis on correspondence between the physical and the divine, the role of light and emanation, the quest to understand nature as a manifestation of divine wisdom—aligns closely with Hermetic themes. His conviction that mathematics was the language of creation and that the study of nature was a form of divine contemplation placed him in an intellectual lineage that would culminate in Renaissance Hermeticism.</p>

<h2>Transmission and Medieval Learning</h2>
<p>Grosseteste was not merely a theorist; he was a teacher, administrator, and collector of texts. At Oxford, he helped build one of the most important centers of learning in medieval Europe, attracting scholars from throughout Christendom. His scriptorum (scriptorium) at Oxford was engaged in translating and copying texts from Greek and Arabic, making available to Latin readers works that had been lost or inaccessible in the West. This transmission work was crucial: it meant that Grosseteste and his successors had access to Greek philosophical texts, Arab scientific treatises, and fragments of Hermetic and Neoplatonic thought that enriched medieval natural philosophy. Grosseteste's own vast learning—he read Greek, was deeply versed in Arab mathematics and optics, and engaged with the full range of classical philosophical and theological literature—gave him the intellectual resources to develop a unified vision of nature and knowledge. His influence on subsequent medieval and Renaissance thought was immense. He was cited constantly by later scholastics, and his work on optics and mathematics formed the foundation for further developments in natural philosophy. Roger Bacon, one of his most important successors, built directly on Grosseteste's work, extending his natural philosophy and his conviction that mathematics and optics were keys to understanding the physical world. The eventual reception of Hermetic texts in the Renaissance occurred in an intellectual climate shaped partly by the medieval developments initiated by figures like Grosseteste.</p>

<h2>Literature</h2>
<p>Crombie, A. C. <i>Robert Grosseteste and the Origins of Experimental Science</i>. Oxford: Oxford University Press, 1953.<br>
Gingerenzer, Gerd & Gigerenzer, Gerd (eds.). <i>Mathematics and the Search for Knowledge</i>. Oxford: Oxford University Press, 1997.<br>
Grosseteste, Robert. <i>On Light / De Luce</i>. Translated by C. Pease-Watkin. Toronto: Pontifical Institute, 2002.<br>
McEvoy, James. <i>Robert Grosseteste</i>. Oxford: Oxford University Press, 2000.<br>
Sherwood, Richard E. (trans.). <i>Robert Grosseteste: An Intellectual Biography</i>. Oxford: Clarendon Press, 1992.</p>""",

    "francis_mercury_van_helmont": """<p>Francis Mercury van Helmont (1614–1698), the son of the renowned Flemish physician and chemist Johann Baptist van Helmont, inherited his father's commitment to alchemical-medical innovation and extended it in new mystical and kabbalistic directions. Francis Mercury was active in some of the most esoteric circles of late 17th-century Europe, collaborating with Henry More, the Cambridge Platonist, on mystical studies, corresponding with Leibniz on metaphysics and alchemy, and involving himself in Rosicrucian and Kabbalistic networks. His career exemplifies the persistence of Hermetic and alchemical interests among the European intellectual elite even as the Scientific Revolution was supposedly displacing such concerns. Unlike his father, whose interest in alchemy was primarily pharmaceutical and medical, Francis Mercury approached Hermeticism, Kabbalah, and alchemy as metaphysical and mystical systems offering insights into the nature of consciousness, the structure of the divine, and the possibilities of human transformation. His syncretism—his effort to weave together Hermetic philosophy, Christian mysticism, and Jewish Kabbalah—was intellectually ambitious and historically significant as a testimony to the continuing vitality of esoteric spirituality in an age of nascent mechanical philosophy and mathematical physics.</p>

<h2>Education, Family Influence, and Mystical Pursuits</h2>
<p>Francis Mercury grew up in Flanders in the household of his father, Johann Baptist van Helmont, one of the most innovative natural philosophers of the 17th century. Johann Baptist practiced alchemy, pursued medical reform, and maintained an intense spirituality rooted in Christian mysticism and a conviction that nature operated according to principles inaccessible to purely mechanical philosophy. This paternal influence gave Francis Mercury a foundation in practical chemistry and an appreciation for the spiritual dimensions of natural philosophy. However, Francis Mercury went further than his father in his engagement with Kabbalah and mystical traditions. He traveled extensively—to England, Germany, and throughout Europe—seeking out mystical teachers, Rosicrucian networks, and alchemical practitioners. His friendship with Henry More, the Cambridge Platonist, deepened his engagement with Neoplatonic and mystical philosophy, and his correspondence with Leibniz (the German polymath philosopher and mathematician) demonstrates that even major figures of the Scientific Revolution remained engaged with hermetic and mystical ideas. Francis Mercury conducted alchemical experiments, corresponded about Kabbalistic symbolism, and pursued practices aimed at mystical illumination and spiritual transformation. His devotion to Kabbalah was particularly significant: he engaged extensively with Jewish mystical traditions, corresponded with Jewish scholars and mystics, and attempted to demonstrate the harmony between Kabbalah and Christian mysticism.</p>

<h2>Kabbalah, Mysticism, and the Permeability of Traditions</h2>
<p>Francis Mercury van Helmont's engagement with Kabbalah was deep and sophisticated, not merely dilettantish. He collaborated with the Jewish mystic Naftali Hertz Levi (Menasseh ben Israel's younger contemporary) on kabbalistic studies and sought to understand the Kabbalistic system as a comprehensive account of divine structure and human transformation. His efforts to synthesize Kabbalah with Christian mysticism and Hermetic philosophy were typical of the syncretism that characterized mystical circles in the late 17th century. For figures like van Helmont, the boundaries between different mystical and esoteric traditions were permeable: the divine wisdom expressed through Hermes Trismegistus, through Jewish Kabbalah, through Christian mystical theology, and through the insights of Neoplatonic philosophy were understood as different manifestations of a single underlying truth. This vision of spiritual pluralism and esoteric synthesis was intellectually coherent within the logic of hermetic thought, even if it would eventually be displaced by the modern categories that insisted on sharp distinctions between different traditions and excluded mystical interpretation from serious philosophical discourse. Van Helmont's life and work testify to the continuing strength of mystical and esoteric concerns among European intellectuals even at the height of the Scientific Revolution, and to the possibility of sophisticated engagement with Hermetic and Kabbalistic traditions alongside engagement with emerging modern philosophy and science.</p>

<h2>Literature</h2>
<p>Copenhaver, Brian P. <i>Hermetica: The Greek Corpus Hermeticum and the Latin Asclepius</i>. Cambridge: Cambridge University Press, 1992.<br>
Henry, John. <i>The Scientific Revolution and the Origins of Modern Science</i>. 3rd ed. London: Palgrave, 2008.<br>
Kilcullen, Richard. "Francis Mercury van Helmont." In <i>Stanford Encyclopedia of Philosophy</i>. Stanford University Press, 2019.<br>
Leibniz, Gottfried Wilhelm & van Helmont, Francis Mercury. <i>Correspondence</i>. Translated and edited by C. I. Gerhardt. Berlin: Prussian Academy, 1875.<br>
van Helmont, Johann Baptist. <i>Ortus Medicinae</i>. Amsterdam: Elzevier, 1648.</p>""",

    "johannes_reuchlin": """<p>Johannes Reuchlin (1455–1522), the German humanist, Hebraist, and pioneer of Christian Kabbalah, represents one of the most consequential efforts to integrate Jewish mystical tradition with Christian theology and Renaissance Platonism. As one of the first Christians to study Hebrew seriously and to argue for the preservation and scholarly study of Jewish texts and traditions, Reuchlin opened new intellectual horizons and created a lasting legacy of Christian Kabbalah that would influence Renaissance and early modern spirituality for centuries. His two major works—<i>De Verbo Mirifico</i> (On the Miraculous Word, 1494) and <i>De Arte Cabalistica</i> (On the Cabalistic Art, 1517)—integrated Kabbalistic theory and practice with Christian mysticism, Neoplatonic philosophy, and the emerging humanist philology. Reuchlin's conviction that Kabbalah was not a Jewish sectarian practice but a universal mystical philosophy capable of enriching Christian understanding of divine mysteries gave intellectual legitimacy to the study of Jewish sources and demonstrated the permeability of the boundaries between Christian and Jewish mystical traditions. His influence on subsequent thinkers—including Pico della Mirandola (who preceded him in some Kabbalistic interests), the Cambridge Platonists, and eventually modern occultists—was profound and lasting.</p>

<h2>Hebraism, Christian Kabbalah, and Humanist Philology</h2>
<p>Reuchlin's approach to Hebrew and to Kabbalah was shaped by humanist values and methods: he insisted on careful textual study, on understanding words in their original linguistic contexts, and on the recovery of ancient wisdom through rigorous philological engagement with primary sources. This scholarly approach distinguished his work from more mystical or allegorical interpretations of Kabbalah: while Reuchlin was certainly interested in the mystical dimensions of Kabbalistic teaching, he grounded his understanding in careful study of Hebrew terminology, the structure of the Hebrew alphabet, and the technical apparatus of Kabbalistic symbolism. His <i>De Verbo Mirifico</i> presents the Hebrew Tetragrammaton (the four-letter name of God, YHVH) and variations of it as containing the deepest mysteries of divine nature and as a key to understanding the structure of reality. The addition of the letter Shin to the Tetragrammaton to create Yeshua (Jesus) becomes, in Reuchlin's hands, a demonstration of how Christian theology is encoded in Hebrew mystical philosophy. This argument—controversial among both Christians and Jews—exemplified Reuchlin's effort to demonstrate the underlying harmony between Jewish and Christian mystical traditions. His <i>De Arte Cabalistica</i>, published later in life, presented Kabbalah as a comprehensive system of mystical knowledge and practical techniques for spiritual transformation, available to Christians willing to study Hebrew and engage seriously with Jewish sources.</p>

<h2>Influence and Controversy</h2>
<p>Reuchlin's scholarly and mystical work was not without controversy. His defense of Jewish books and scholars during the campaign of the Cologne inquisitor Johann Pfefferkorn (who sought to suppress Hebrew texts as heretical) made Reuchlin a symbol of humanist intellectual freedom and Christian tolerance. His <i>Epistolae Obscurorum Virorum</i> (Letters of Obscure Men), written with Ulrich von Hutten, was a brilliant satirical attack on scholastic obscurantism and clerical intolerance, defending the study of Hebrew and classical languages against conservative ecclesiastical critics. This public stance for intellectual freedom and intercultural understanding gave Reuchlin significant prestige and made him a hero to Protestant reformers and humanists. His influence on subsequent Christian Kabbalah was immense: Pico della Mirandola, while developing his own Kabbalistic ideas independently, was influenced by Reuchlin's work, as were numerous later figures seeking to integrate mystical traditions. The tradition of Christian Kabbalah that would flourish in the 16th, 17th, and 18th centuries owed much to Reuchlin's pioneering work in demonstrating that Kabbalah could be studied seriously by Christians and could be integrated with Christian theology and philosophy. Modern scholars have recognized Reuchlin as a foundational figure in the history of esotericism and as a key actor in the intellectual and cultural exchanges that characterized the Renaissance.</p>

<h2>Literature</h2>
<p>Copenhaver, Brian P. <i>Magic in Western Culture: From Antiquity to the Enlightenment</i>. Cambridge: Cambridge University Press, 2015.<br>
Mulsow, Markus. <i>Enlightenment Underground</i>. Translated by H. Lorenz. Berlin: De Gruyter, 2015.<br>
Reuchlin, Johannes. <i>De Verbo Mirifico / On the Miraculous Word</i>. Translated by C. Zuckerman. Lincoln: University of Nebraska Press, 2017.<br>
Reuchlin, Johannes. <i>De Arte Cabalistica / On the Cabalistic Art</i>. Translated by M. & J. Goodman. Lincoln: University of Nebraska Press, 1983.<br>
Transler, W. <i>Johann Reuchlin</i>. New York: Peter Lang, 2002.</p>""",
}

def update_bios():
    """Update person bio_html entries."""
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    count = 0
    for person_id, bio_html in EXPANDED_BIOS.items():
        cursor.execute('''
            UPDATE persons
            SET bio_html = ?, review_status = 'DRAFT'
            WHERE person_id = ?
        ''', (bio_html, person_id))

        cursor.execute('SELECT name FROM persons WHERE person_id = ?', (person_id,))
        result = cursor.fetchone()
        if result:
            print(f"[OK] Updated: {result[0]}")
            count += 1

    conn.commit()
    conn.close()
    print(f"\nTotal updated: {count} persons")
    return count

if __name__ == "__main__":
    updated = update_bios()
    print(f"Expanded {updated} more person biographies")
