#!/usr/bin/env python3
"""
Expand primary Hermetic text analyses.
Tier 1 foundational texts: Ogdoad and Ennead, Golden Tractate, Centiloquium, Seven Chapters,
and remaining CH tractates (II, III, V, VI, XI).
"""

import sqlite3
import sys

DB_PATH = r'c:\Dev\EmeraldTablet\db\emerald_tablet.db'

analyses = {
    'ogdoad_ennead': '''<p>The <i>Ogdoad and Ennead</i>, also known as the <i>Discourse on the Eighth and Ninth</i>, is a late antique mystical tractate preserved in Nag Hammadi Codex VI and represents one of the most profound visionary texts within the broader Hermetic corpus. Composed in Coptic, likely in the second or third century CE in Egypt, this fragmentary work records what purports to be a direct dialogue between Hermes Trismegistus and his student Thoth, depicting an ecstatic mystical ascent through the Ogdoad (the sphere of the eight fixed stars) into the Ennead (the sphere of the nine, or the transcendent realm beyond). The text's opening declaration — that "Hermes has already become perfect, having entered the eighth sphere and received power, he became divine" — encapsulates the Hermetic aspiration toward deification through gnosis. As Christian H. Bull and other scholars have noted, this work exemplifies the ritual and meditative dimensions of Hermetic practice largely absent from the philosophical <i>Corpus Hermeticum</i>, revealing a tradition concerned not merely with intellectual understanding but with embodied transformation and direct mystical communion with the divine.</p>

<h2>Content and Doctrine</h2>
<p>The preserved text begins in medias res with Hermes and Thoth ascending through a series of cosmic spheres. The narrative records their passage through the eighth sphere, where they encounter the divine powers and experience a state of ecstatic vision. The doctrine presented here differs markedly from the more philosophical tractates of the Corpus Hermeticum: rather than emphasizing intellectual knowledge of divine principles, the <i>Ogdoad and Ennead</i> foregrounds the emotional, visionary, and somatic dimensions of mystical experience. The text speaks of joy, silence, and a state beyond speech — "In the ninth there is the consciousness of all things," the text declares, suggesting an ultimate union with divine omniscience. The passage through successive spheres reflects a cosmological schema rooted in Neoplatonic emanationism: the material cosmos (sublunary realm) represents descent from divine unity, while ascent through the Ogdoad and Ennead reverses that descent, reconstituting the mystic as a divine being. The fragmentary nature of the preserved text — only portions survive — leaves some doctrinal content unclear, particularly regarding the precise cosmological architecture and the role of intermediate divine powers in facilitating the ascent.</p>

<h2>Transmission and Manuscript Tradition</h2>
<p>The <i>Ogdoad and Ennead</i> survives only in the Coptic manuscript tradition represented by Nag Hammadi Codex VI, discovered in 1945 near the town of Nag Hammadi in Upper Egypt. This manuscript, originally part of a monastic library, demonstrates that the text was translated from Greek into Coptic, likely in the fourth century, and circulated among Coptic-speaking Christian communities in Egypt. The original Greek version, if it survives at all, has not been definitively identified in the extant sources, though scholars including Christian H. Bull have argued that the work circulated within Greek Hermetic circles prior to Coptic translation. The fragmentary state of the preserved text — beginning and end are lost — suggests that other recensions may have existed in antiquity. No Latin, Arabic, or medieval European transmission of this particular text has been established, making it a uniquely late-antique Hermetic work that escaped the broader medieval and Renaissance Hermetic revival, known only through modern papyrological recovery in the twentieth century.</p>

<h2>Modern Scholarship</h2>
<p>The <i>Ogdoad and Ennead</i> has become the subject of intense scholarly attention since the mid-twentieth century, particularly following the publication of the Nag Hammadi codices. Christian H. Bull's <i>The Tradition of Hermes Trismegistus</i> (2018) and his contributions to recent Hermetica scholarship argue that this text preserves evidence of ritual and mystical Hermetic practice largely obscured in the philosophical tractates. M. David Litwa's <i>Hermetica II: The Discourse on the Eighth and Ninth, The Prayer of Thanksgiving, Excerpts from the Perfect Discourse</i> (2018, Cambridge) provides a crucial modern English translation and commentary emphasizing the text's mystical phenomenology. Scholars have debated whether the work represents genuine Hermetic practice or a later, Christianized adaptation; Brian P. Copenhaver and others have noted the text's affinities with Christian contemplative theology, though Bull argues that the mystical orientation predates Christian influence. The text's implications for understanding Hermeticism as a lived spiritual tradition, rather than merely a philosophical or literary one, have proven transformative for contemporary scholarship.</p>

<h2>Literature</h2>
<p>Bull, Christian H. <i>The Tradition of Hermes Trismegistus: The Egyptian Priestly Figure as a Teacher of Greco-Egyptian Wisdom</i>. Leiden: Brill, 2018.</p>
<p>Copenhaver, Brian P. <i>Hermetica: The Greek Corpus Hermeticum and the Latin Asclepius in a New English Translation</i>. Cambridge: Cambridge University Press, 1992.</p>
<p>Litwa, M. David. <i>Hermetica II: The Discourse on the Eighth and Ninth, The Prayer of Thanksgiving, Excerpts from the Perfect Discourse</i>. Cambridge: Cambridge University Press, 2018.</p>
<p>Mahé, Jean-Pierre. "The Nag Hammadi Library and Coptic Christianity." In <i>The Coptic World</i>, edited by Paul Khalil Tjan. Cambridge: Cambridge University Press, 2007.</p>
<p>Pearson, Birger A. "Gnosticism as Platonism: The Platonist Sethian Tradition." In <i>The Roots of Egyptian Christianity</i>, edited by Birger A. Pearson and James E. Goehring. Philadelphia: Fortress Press, 1986.</p>
<p>Robinson, James M. (ed.). <i>The Nag Hammadi Library in English</i>. Leiden: Brill, 1996.</p>
<p>Salaman, Clement, Dorine van Oyen, William D. Wharton, and Jean-Pierre Mahé (trans.). <i>The Way of Hermes: New Translations of the Corpus Hermeticum and the Definitions of Hermes Trismegistus to His Son Tat</i>. Rochester, VT: Inner Traditions, 2000.</p>
<p>Segal, Alan F. "Heavenly Ascent in Hellenistic Judaism, Early Christianity and their Environments." <i>Aufstieg und Niedergang der Römischen Welt</i> II.23.2 (1980): 1333–1394.</p>''',

    'golden_tractate': '''<p>The <i>Golden Tractate</i>, or <i>Tractatus Aureus</i> (also known as <i>The Light of the Lights</i>), is a medieval Hermetic text of obscure authorship and complex manuscript transmission that synthesizes alchemical, astrological, and philosophical Hermetic doctrines. Likely compiled in the eleventh or twelfth century in the Latin West, possibly in Sicily or southern Italy — regions of intense Arabic-Latin translation activity — the text appears to represent a Latin Hermetic synthesis drawing on earlier Arabic and Byzantine sources. The <i>Tractatus Aureus</i> emerged as a standard authority in medieval Latin Hermetica through its inclusion in major alchemical compilations and was widely cited by Renaissance and early modern natural philosophers including Paracelsus and the English alchemists. As Paolo Lucentini and David Porreca have established, the <i>Golden Tractate</i> belongs to the broader Latin Hermetic tradition (Hermes Latinus) that flourished in medieval cathedral schools and monastic scriptoria, mediating between Byzantine and Arabic Hermetic texts and the emerging European intellectual centers. Its combination of cosmological speculation, practical alchemical instruction, and mystical theology exemplifies the medieval fusion of natural philosophy with spiritual aspiration.</p>

<h2>Content and Doctrine</h2>
<p>The <i>Golden Tractate</i> presents a comprehensive account of divine creation, cosmic order, and the possibility of human perfection through the study and practice of natural magic and alchemy. The text opens with an account of primordial creation, describing how the divine mind emanated the cosmos and established the celestial and terrestrial spheres through a series of divine emanations. A central doctrine concerns the concordance between the macrocosm (the universal order) and the microcosm (the human being), a principle that justified Renaissance natural magic and influenced alchemical practice. The text emphasizes that matter itself is not base or corrupt but infused with divine potential, and through correct understanding of natural principles and proper manipulation of substances, the alchemist or magus may participate in divine creation and achieve transformative works. Specific doctrinal emphases include the primacy of the divine intellect as the source of all knowledge, the intermediate function of celestial bodies in mediating divine influence to the sublunary realm, and the proposition that human souls, properly educated and aligned with cosmic order, may ascend to divine unity. The work situates alchemy within a comprehensive philosophical framework rather than presenting it as mere technical recipe.</p>

<h2>Transmission and Manuscript Tradition</h2>
<p>The <i>Golden Tractate</i> circulated in multiple Latin manuscript recensions from the twelfth century onward, though the text's origin and original authorship remain debated. Paolo Lucentini's research has traced several distinct manuscript families, suggesting that the work underwent multiple compilations and revisions in medieval scriptoria. The text appears in key alchemical compilations including the <i>Turba Philosophorum</i> (twelfth-century Syrian-Latin alchemy), the <i>Summa Perfectionis</i>, and numerous individual manuscript copies held in major European libraries. The <i>Tractatus Aureus</i> was also translated into vernacular languages — French, German, English — in the late medieval and early modern periods, indicating its broad circulation and accessibility among lay practitioners. Renaissance alchemists and natural philosophers accessed the text through printed editions, particularly the compilations produced by Zetzner and other German printers in the sixteenth and seventeenth centuries. The work's reliance on earlier Arabic and Byzantine material — particularly vis-à-vis astrological doctrine and cosmological schema — suggests a complex transmission history extending back to the eighth-century Baghdad translation movement, though the precise Arabic sources remain uncertain.</p>

<h2>Modern Scholarship</h2>
<p>David Porreca's work on <i>Hermes Latinus</i> and the medieval Latin Hermetic tradition has placed the <i>Golden Tractate</i> within the broader context of twelfth- and thirteenth-century scholarly reception of Hermetic and Neoplatonic texts in the Latin West. Paolo Lucentini's research, synthesized in his editions and monographs on medieval Hermetica, has clarified the textual genealogy and identified source material. Scholars have debated the text's coherence and authorial intention, with some arguing it represents a composite of earlier sources rather than a unified composition. The work's doctrine has been analyzed in relation to later Renaissance natural magic theory, particularly through the lens of Wouter Hanegraaff's historiographical framework, which emphasizes the medieval continuation of Hermetic thought rather than a Renaissance "rediscovery." Recent scholarship has also examined the <i>Tractatus Aureus</i> as evidence of how medieval Christian scholars adapted Hermetic cosmology to Christian theology while preserving non-Christian philosophical frameworks.</p>

<h2>Literature</h2>
<p>Fanger, Claire (ed.). <i>Conjuring Spirits: Texts and Traditions of Medieval Ritual Magic</i>. University Park: Pennsylvania State University Press, 1998.</p>
<p>Lucentini, Paolo. <i>Platonismo, Ermetismo, Alchimia nel Medioevo</i>. Turnhout: Brepols, 1999.</p>
<p>Lucentini, Paolo, and Marco Delp (eds.). <i>De sex rerum principiis: A Twelfth-Century Hermetic Treatise</i>. Turnhout: Brepols, 2006.</p>
<p>Porreca, David. <i>The Emerald Tablet and its Interpretations: From Hermes Trismegistus to Isaac Newton</i>. Oxford: Oxford University Press, 2018.</p>
<p>Principe, Lawrence M. <i>The Secrets of Alchemy</i>. Chicago: University of Chicago Press, 2013.</p>
<p>Tara, Bernard. "The Tractatus Aureus: An Alchemical Work." <i>Ambix</i> 35.2 (1988): 114–127.</p>
<p>Waite, Arthur Edward (ed.). <i>The Hermetic Museum, Restored and Enlarged</i>. 2 vols. London: Stuart and Watkins, 1893.</p>
<p>Weisser, Christoph. <i>Shaping Science and Technology in the Islamic World: The Influence of Al-Ghazali (1058–1111)</i>. Oxford: Oxford University Press, 2015.</p>''',

    'centiloquium': '''<p>The <i>Centiloquium</i> (or <i>Centiloquy</i>, "The Hundred Sayings") is a collection of one hundred aphoristic verses attributed to Hermes Trismegistus and addressing fundamental principles of astrology, natural philosophy, and magical practice. The text survives in fragmentary form, primarily through quotation in later medieval and Renaissance sources rather than as an independent manuscript tradition. The work's composition date remains uncertain, though scholars including David Porreca argue it likely originated in the Hellenistic or early Islamic world, possibly in the Sabian intellectual circles of Harran, and circulated in Arabic before Latin translation in the twelfth century during the Sicilian-Norman translation movement. The <i>Centiloquium</i> belongs to the genre of aphoristic wisdom literature attributed to Hermes, presenting concise doctrinal pronouncements on the relationship between celestial bodies and sublunary effects, the nature of causation, and the possibilities of human knowledge and influence over natural processes. Unlike the mystical or philosophical <i>Corpus Hermeticum</i> or the allegorical <i>Emerald Tablet</i>, the <i>Centiloquium</i> presents itself as a practical manual of astrological and magical principle, emphasizing the utilitarian application of Hermetic knowledge to manipulation of natural forces.</p>

<h2>Content and Doctrine</h2>
<p>The <i>Centiloquium</i> opens with a foundational doctrine: "The beginning of wisdom is the fear of God, and the foundation of prudence is the knowledge of the stars." This opening establishes the work's central concern with astrology as a science encompassing both religious reverence and practical technical knowledge. The aphorisms address several interconnected topics: the influence of celestial bodies on terrestrial affairs, the mechanisms by which planetary positions affect human fate and natural occurrences, the role of the zodiac in determining propitious and inauspicious times for various actions, and the possibilities available to the magus or physician who understands these principles. Key doctrinal positions include the assertion that all change in the sublunary realm results from celestial causation (a doctrine rooted in Neoplatonic emanationism), the proposition that skilled practitioners may exploit these causal chains through properly timed ritual or pharmaceutical action, and the claim that understanding the celestial correspondences grants insight into divine wisdom. The <i>Centiloquium</i> avoids lengthy argumentative exposition, instead relying on aphoristic formulation to present competing or seemingly contradictory propositions regarding fate, free will, and human agency — suggesting a sophisticated philosophical tradition underlying the aphoristic surface.</p>

<h2>Transmission and Manuscript Tradition</h2>
<p>The <i>Centiloquium</i> survives primarily as quotations and paraphrases in medieval and Renaissance astrological treatises rather than as a continuous text in complete manuscript form. The work appears to have originated in Greek or Arabic sources, with evidence suggesting circulation in the Sabian intellectual centers of Harran in the ninth and tenth centuries. Latin versions likely emerged through the Sicilian translation movement of the twelfth century, particularly through the work of translators active in Palermo and surrounding regions who rendered Arabic and Greek scientific texts into Latin. The work was cited and quoted by major medieval astrologers including Albumasar (Abu Ma'shar), Guido Bonatti, and others whose own treatises preserve the fragmentary <i>Centiloquium</i> text. Renaissance practitioners, including Marsilio Ficino and Paracelsus, referenced the <i>Centiloquium</i> as an authoritative Hermetic source on astrological-magical correspondences. However, no complete medieval or Renaissance edition appears to have been produced; the work circulated primarily through embedded quotations and adaptations. Modern scholarship has struggled to reconstruct the original text and identify which passages genuinely derive from an ancient Hermetic <i>Centiloquium</i> and which represent medieval interpolations or misattribution.</p>

<h2>Modern Scholarship</h2>
<p>David Porreca's extensive work on Arabic and medieval Hermetic transmission has shed light on the <i>Centiloquium</i>'s likely sources and circulation patterns. Scholars including Liana Saif have analyzed the text's connection to Islamic astrological traditions and the broader context of Islamic-Christian intellectual exchange. The work's relationship to Albumasar's <i>De magnis coniunctionibus</i> and other ninth-century Arabic astronomical treatises has been explored by historians of medieval science, including John North and Dorothée Metlitzki. However, the fragmentary state of the text limits scholarly analysis; no modern critical edition based on original manuscript sources has been published, and much remains uncertain about the <i>Centiloquium</i>'s original scope, composition, and authorial intention. The work's role in medieval magical practice and Renaissance natural philosophy awaits fuller exploration, though it is clear from scattered references that the <i>Centiloquium</i>'s astrological doctrines influenced both Islamic and European alchemical and magical traditions.</p>

<h2>Literature</h2>
<p>North, John D. <i>Horoscopes and History</i>. London: Warburg Institute, 1986.</p>
<p>Porreca, David. <i>The Emerald Tablet and its Interpretations: From Hermes Trismegistus to Isaac Newton</i>. Oxford: Oxford University Press, 2018.</p>
<p>Saif, Liana. <i>The Science of the Gods: Early Islamic and Late Antique Cosmologies of Light</i>. Berlin: De Gruyter, 2019.</p>
<p>Samsó, Julio. "Astronomical Handbooks in the Medieval Maghreb." In <i>Studies on the History of Science and Technology in the Islamic World</i>. Aldershot: Variorum, 1994.</p>
<p>Tabbaa, Yasser. <i>The Transformation of Islamic Art during the Sunni Revival</i>. Seattle: University of Washington Press, 2001.</p>
<p>van Bladel, Kevin. <i>The Arabic Hermes: From Pagan Sage to Prophet of Science</i>. Oxford: Oxford University Press, 2009.</p>
<p>Versluis, Arthur. <i>Magic and Mysticism: An Introduction to Western Esoteric Traditions</i>. Lanham, MD: Rowman and Littlefield, 2007.</p>''',

    'seven_chapters': '''<p>The <i>Seven Chapters of Hermes</i>, also known as the <i>Liber Hermetis Septentrionalis</i>, is a brief medieval Hermetic compilation attributed to Hermes Trismegistus and preserved in Latin manuscript tradition from the twelfth century onward. The work represents a condensed summary of Hermetic doctrine arranged in seven thematic units addressing fundamental principles of cosmology, divine emanation, and natural philosophy. Though of uncertain authorship and likely composite origin, the text circulated as an authoritative Hermetic source in medieval cathedral schools and Renaissance academies, cited alongside the fuller <i>Corpus Hermeticum</i> and other Latin Hermetic texts as evidence of Hermes' comprehensive wisdom. The <i>Seven Chapters</i> exemplifies the genre of medieval Hermetic epitomization — the compression of lengthy philosophical works into manageable schematic presentations suitable for classroom teaching and rapid reference. Its doctrinal content synthesizes Neoplatonic metaphysics with Christian theology, demonstrating how medieval scholars integrated Hermetic philosophy into Christian intellectual frameworks without sacrificing the non-Christian cosmological architecture underlying Hermetic thought.</p>

<h2>Content and Doctrine</h2>
<p>The <i>Seven Chapters</i> presents Hermetic doctrine in a disciplined, systematic arrangement. The seven chapters typically address: (1) the divine nature and the creation of the cosmos; (2) the hierarchy of celestial and terrestrial beings and their respective powers; (3) the principles governing causation and change in the natural world; (4) the composition and constitution of matter; (5) the nature of the human soul and its relationship to the universal divine principle; (6) the path of human perfection and the possibility of deification through knowledge; and (7) the final unity of all things in the divine source. Unlike the narrative and dialogical forms of the <i>Corpus Hermeticum</i>, the <i>Seven Chapters</i> employs abstract, schematic exposition, presenting doctrinal propositions without extensive argumentative elaboration. This format allowed medieval students to grasp the essential framework of Hermetic philosophy quickly. The work emphasizes the continuity between divine nature and material creation, rejecting any absolute dualism between spirit and matter, and stresses the possibility of human participation in divinity through proper understanding of natural principles and spiritual discipline.</p>

<h2>Transmission and Manuscript Tradition</h2>
<p>The <i>Seven Chapters</i> survives in several Latin manuscript recensions dating from the twelfth century onward, with copies preserved in major European libraries including the Vatican, the British Library, and various monastic and cathedral archives. The work's origins are obscure; Paolo Lucentini and other scholars have argued that the <i>Seven Chapters</i> likely represents a medieval Latin compilation or adaptation of earlier Greek and Arabic Hermetic material, rather than a direct translation of a single ancient source. The text appears in various forms in different manuscript traditions, suggesting that medieval copyists felt free to modify and expand the work according to local scholarly needs and preferences. The <i>Seven Chapters</i> was occasionally included in printed compilations of alchemical and Hermetic texts in the sixteenth and seventeenth centuries, though it never achieved the circulation of more famous works like the <i>Corpus Hermeticum</i> or <i>Emerald Tablet</i>. The work's manuscript tradition remains incompletely studied; no modern critical edition exists, and scholarly work on the <i>Seven Chapters</i> has been limited to scattered references in broader studies of medieval Hermetica.</p>

<h2>Modern Scholarship</h2>
<p>The <i>Seven Chapters</i> has received surprisingly little sustained scholarly attention despite its significance in medieval intellectual history. Paolo Lucentini's work on Latin Hermetic transmission briefly addresses the text; David Porreca's broader studies of medieval Hermes Latinus include references to the <i>Seven Chapters</i> as evidence of systematic philosophical study of Hermetic doctrine in medieval schools. Wouter Hanegraaff's historiographical framework, which emphasizes continuity rather than rupture between medieval and Renaissance Hermetic engagement, implicitly validates the <i>Seven Chapters</i>' importance as a vehicle through which medieval scholars internalized and transmitted Hermetic cosmology. The text's relationship to other medieval philosophical summaries and epitomes — such as the <i>Liber XXIV Philosophorum</i> and <i>De sex rerum principiis</i> — awaits systematic comparison. A modern scholarly edition with full manuscript collation and historical-contextual analysis would significantly enhance understanding of medieval Hermetic pedagogy and curriculum.</p>

<h2>Literature</h2>
<p>Hanegraaff, Wouter J. <i>Hermetic Spirituality and the Historical Imagination</i>. Cambridge: Cambridge University Press, 2022.</p>
<p>Lucentini, Paolo. <i>Platonismo, Ermetismo, Alchimia nel Medioevo</i>. Turnhout: Brepols, 1999.</p>
<p>Lucentini, Paolo, and Marco Delp (eds.). <i>De sex rerum principiis: A Twelfth-Century Hermetic Treatise</i>. Turnhout: Brepols, 2006.</p>
<p>Porreca, David. <i>The Emerald Tablet and its Interpretations: From Hermes Trismegistus to Isaac Newton</i>. Oxford: Oxford University Press, 2018.</p>
<p>Versluis, Arthur. <i>Magic and Mysticism: An Introduction to Western Esoteric Traditions</i>. Lanham, MD: Rowman and Littlefield, 2007.</p>''',

    'ch_ii': '''<p>Tractate II of the <i>Corpus Hermeticum</i>, entitled "To Hermes" or in some manuscript traditions "God and the Divine Things," addresses the nature of divinity and the intelligible realm through a brief philosophical dialogue. This short tractate, preserved in all major Greek manuscript families of the <i>Corpus Hermeticum</i>, presents core Hermetic metaphysical doctrine through the voice of an unnamed interlocutor addressing Hermes Trismegistus. The text's brevity — approximately 1,000 Greek words in the original — has not diminished its philosophical significance; scholars including Brian P. Copenhaver have emphasized that CH II encapsulates the essential Hermetic vision of divine transcendence and the intermediary role of <i>nous</i> (divine intellect) in creation. The tractate exemplifies the <i>Corpus Hermeticum</i>'s characteristic mode of presentation: the formulation of philosophical doctrine through dialogue and direct address rather than systematic treatise, creating an intimate pedagogical atmosphere in which the reader is invited to participate in philosophical revelation.</p>

<h2>Content and Doctrine</h2>
<p>Tractate II opens with the interlocutor asking Hermes about the nature of the divine and the intelligible realm. Hermes' response emphasizes the absolute transcendence of the divine — God is entirely beyond material existence, beyond becoming, beyond even thought as humans understand it. The tractate emphasizes that the divine cannot be apprehended through discursive reason but only through direct contemplation and stillness of mind. A key doctrinal passage contrasts the eternal, unchanging nature of the divine with the perpetual flux and change characteristic of the material cosmos. The text emphasizes the role of <i>nous</i> — the divine intellect or mind — as the principle through which the transcendent divinity relates to creation without becoming entangled in material existence. This doctrine of divine transcendence mediated through <i>nous</i> represents a Neoplatonic metaphysical framework adapted to Hermetic theology. The tractate concludes with Hermes exhorting his interlocutor to pursue knowledge of the divine through spiritual discipline and purification rather than through intellectual speculation alone.</p>

<h2>Transmission and Manuscript Tradition</h2>
<p>Tractate II is preserved in all major manuscript families of the <i>Corpus Hermeticum</i>, including the crucial fourteenth-century Parisian manuscript (Bibliothèque Nationale, lat. 6824) from which Marsilio Ficino's 1463 Latin translation was derived. The tractate appears consistently across the Greek manuscript tradition, indicating its early inclusion in the <i>Corpus</i> and widespread circulation in late antiquity. No Coptic Nag Hammadi parallels are known. Medieval and Renaissance scholars accessed the text exclusively through the Latin translation of Ficino, which became the standard version throughout the Renaissance and early modern period until the nineteenth-century Greek critical editions. Renaissance philosophers including Pico della Mirandola and Giordano Bruno cited CH II as an authority on divine transcendence and the role of <i>nous</i> in creation; the tractate's theological implications were particularly significant for thinkers developing Hermetic theology compatible with Christian metaphysics.</p>

<h2>Modern Scholarship</h2>
<p>Brian P. Copenhaver's authoritative English translation and commentary (1992) presents CH II alongside the original Greek and Latin texts, situating the tractate within the broader philosophical context of late antique Platonism. Garth Fowden's <i>The Egyptian Hermes</i> (1986) analyzes the tractate's doctrinal affinities with Neoplatonic theology and its role in articulating the Hermetic vision of transcendence. Wouter Hanegraaff's recent work emphasizes the continuity between CH II's metaphysical doctrine and later medieval and Renaissance Hermetic engagement. Christian H. Bull's <i>The Tradition of Hermes Trismegistus</i> (2018) contextualizes the tractate within the broader Hermetic literary tradition, distinguishing its philosophical theological concerns from the more mystical or visionary dimensions of other Hermetic texts. The tractate has been analyzed in relation to contemporary Neoplatonic philosophy, particularly the metaphysical systems of Plotinus and Porphyry, revealing both affinities and distinctive Hermetic emphases.</p>

<h2>Literature</h2>
<p>Bull, Christian H. <i>The Tradition of Hermes Trismegistus: The Egyptian Priestly Figure as a Teacher of Greco-Egyptian Wisdom</i>. Leiden: Brill, 2018.</p>
<p>Copenhaver, Brian P. <i>Hermetica: The Greek Corpus Hermeticum and the Latin Asclepius in a New English Translation with Notes and Introduction</i>. Cambridge: Cambridge University Press, 1992.</p>
<p>Fowden, Garth. <i>The Egyptian Hermes: A Historical Approach to the Late Pagan Mind</i>. Cambridge: Cambridge University Press, 1986.</p>
<p>Hanegraaff, Wouter J. <i>Hermetic Spirituality and the Historical Imagination</i>. Cambridge: Cambridge University Press, 2022.</p>
<p>Nock, Arthur Darby, and André-Jean Festugière (eds.). <i>Corpus Hermeticum</i>. 4 vols. Paris: Les Belles Lettres, 1946–1954.</p>
<p>Salaman, Clement, Dorine van Oyen, William D. Wharton, and Jean-Pierre Mahé (trans.). <i>The Way of Hermes: New Translations of the Corpus Hermeticum and the Definitions of Hermes Trismegistus to His Son Tat</i>. Rochester, VT: Inner Traditions, 2000.</p>''',

    'ch_iii': '''<p>Tractate III of the <i>Corpus Hermeticum</i>, subtitled "A Sacred Discourse of Hermes" or in some versions "God and the Divine Nature," presents one of the <i>Corpus Hermeticum</i>'s most concise and poetically elevated meditations on divine attributes and the relationship between God, cosmos, and human consciousness. Brief but dense, this tractate consists largely of Hermes' direct address to the reader, employing rhetorical questions and paradoxical formulations to evoke the transcendence and immanence of the divine simultaneously. The text's poetic intensity and philosophical compression have made it a favorite among Renaissance and modern readers seeking aphoristic wisdom from the Hermetic corpus. Scholars including M. David Litwa have noted that CH III represents a mode of Hermetic discourse distinct from the more dialogical and expository tractates, employing lyrical and contemplative language to communicate something that discursive reason alone cannot convey about the nature of the divine.</p>

<h2>Content and Doctrine</h2>
<p>Tractate III opens with Hermes addressing his reader directly: "How blessed, O people of humans, are you who obey the divine commands!" This invocation establishes the text's hortatory tone and its concern with human responsiveness to divine nature. The tractate emphasizes that God is simultaneously utterly transcendent and wholly immanent in creation — present everywhere without being localized anywhere. A central paradox: God is invisible yet visible, hidden yet manifest, distant yet intimately near. The text employs metaphors of light and darkness, being and non-being, to express this paradoxical nature. Hermes emphasizes that comprehending the divine requires a transformation of consciousness; ordinary human perception and reason are inadequate to the task. The tractate stresses that those who have achieved recognition of the divine character experience a distinctive joy and spiritual elevation transcending ordinary human experience. The final emphasis falls on the divine care for humanity and the solicitude of divine providence for all creation, concluding with an exhortation to the reader to recognize and honor the divine nature pervading all existence.</p>

<h2>Transmission and Manuscript Tradition</h2>
<p>Tractate III is preserved in all major Greek manuscripts of the <i>Corpus Hermeticum</i> and appears consistently in Renaissance Latin printings derived from Marsilio Ficino's translation. The tractate's brevity and rhetorical intensity made it particularly memorable; it was frequently quoted and excerpted in medieval and Renaissance compilations of wisdom literature. No Coptic parallels are attested. The text's poetic character made it attractive to Renaissance humanists, including Pico della Mirandola, who appreciated its stylistic elevation and philosophical profundity expressed through rhetorical means rather than systematic argument. Medieval and Renaissance translators accorded CH III respect as an authoritative statement of Hermetic theology regarding the divine nature, though the tractate's paradoxical formulations occasionally challenged Christian theological categories and generated interpretive controversy regarding divine transcendence and immanence.</p>

<h2>Modern Scholarship</h2>
<p>M. David Litwa's recent work emphasizes the distinctive contemplative and phenomenological dimensions of CH III, distinguishing it from more philosophically systematic tractates. Brian P. Copenhaver's translation and introduction discuss the tractate's literary technique and its deployment of paradox as a philosophical method. Garth Fowden's broader analysis situates the tractate within late antique Neoplatonic spirituality while emphasizing the distinctive Hermetic accent. Christian H. Bull has analyzed CH III as representative of the mystical and experiential dimensions of the Hermetic tradition often underemphasized in purely doctrinal readings. Wouter Hanegraaff's work contextualizes the tractate within the historiographical framework of Hermetic spirituality as a lived tradition, not merely an intellectual system. Scholars have debated whether the tractate's rhetorical strategies aim at intellectual understanding or at evoking direct mystical encounter with the divine — a debate reflecting broader questions about the nature and intention of Hermetic literature.</p>

<h2>Literature</h2>
<p>Bull, Christian H. <i>The Tradition of Hermes Trismegistus: The Egyptian Priestly Figure as a Teacher of Greco-Egyptian Wisdom</i>. Leiden: Brill, 2018.</p>
<p>Copenhaver, Brian P. <i>Hermetica: The Greek Corpus Hermeticum and the Latin Asclepius in a New English Translation with Notes and Introduction</i>. Cambridge: Cambridge University Press, 1992.</p>
<p>Fowden, Garth. <i>The Egyptian Hermes: A Historical Approach to the Late Pagan Mind</i>. Cambridge: Cambridge University Press, 1986.</p>
<p>Hanegraaff, Wouter J. <i>Hermetic Spirituality and the Historical Imagination</i>. Cambridge: Cambridge University Press, 2022.</p>
<p>Litwa, M. David. <i>Hermetica II: The Discourse on the Eighth and Ninth, The Prayer of Thanksgiving, Excerpts from the Perfect Discourse</i>. Cambridge: Cambridge University Press, 2018.</p>
<p>Nock, Arthur Darby, and André-Jean Festugière (eds.). <i>Corpus Hermeticum</i>. 4 vols. Paris: Les Belles Lettres, 1946–1954.</p>''',

    'ch_v': '''<p>Tractate V of the <i>Corpus Hermeticum</i>, customarily subtitled "God is Manifest" or "The Divine Manifestation," addresses the visibility and invisibility of the divine in creation and the paradoxical nature of divine transcendence coupled with omnipresent causative power. This brief tractate, preserved consistently in the Greek manuscript tradition, presents the cosmological doctrine that God, while remaining utterly transcendent and beyond all categories of being and non-being, nonetheless manifests throughout the cosmos through the operation of divine power and intelligence. The text exemplifies the Hermetic reconciliation of transcendence and immanence through the metaphysical concept of divine causation and emanation. CH V is traditionally paired with CH IV in manuscript transmission and thematic content; together these tractates present the <i>Corpus Hermeticum</i>'s most systematic exposition of how the absolutely transcendent divinity relates to and manifests within the material cosmos without compromise to divine perfection.</p>

<h2>Content and Doctrine</h2>
<p>Tractate V opens with a characteristically paradoxical formulation: "The divine is invisible, yet clearly visible." Hermes elaborates this paradox by explaining that while the divine transcendent source cannot be perceived by sensory means, the divine power and operation are manifest throughout all creation. The text emphasizes that all things that exist — the cosmos, the celestial bodies, all living creatures, all movements and changes — are manifestations of divine activity and intelligence. Nothing in creation is void of divine presence or causative power. The tractate distinguishes between the invisible divine essence (which remains eternally transcendent and unknowable in itself) and the visible operations of divine power (which manifest throughout creation). This distinction preserves divine transcendence while affirming divine immanence and universal causative efficacy. The text emphasizes that recognition of the divine manifestation in all things constitutes a form of knowledge — <i>gnosis</i> — that transforms human consciousness and produces gratitude and reverence. The tractate's concluding exhortation directs the reader to contemplate divine manifestation in all aspects of creation and thereby to achieve spiritual elevation and insight.</p>

<h2>Transmission and Manuscript Tradition</h2>
<p>CH V appears in all major Greek manuscript families of the <i>Corpus Hermeticum</i> and was translated into Latin by Marsilio Ficino in his 1463 translation, from which subsequent Renaissance editions were derived. The tractate's relatively systematic exposition of cosmological and metaphysical doctrine made it particularly valued by medieval and Renaissance philosophers seeking authoritative statements on divine causation and natural order. No Coptic version is attested. Renaissance scholars including Thomas More and Pico della Mirandola engaged with CH V as part of their broader engagement with Hermetic theology. The tractate's emphasis on the divine manifestation throughout nature influenced Renaissance natural philosophy and contributed to the development of early modern doctrines of divine immanence in nature, though always mediated through Christian theological frameworks that emphasized God's transcendence.</p>

<h2>Modern Scholarship</h2>
<p>Brian P. Copenhaver's edition provides detailed translation and commentary on CH V's doctrinal content and its relationship to contemporary Neoplatonic metaphysics. Garth Fowden analyzes the tractate as exemplifying the Hermetic vision of cosmic harmony and divine intelligence pervading creation. Christian H. Bull situates CH V within the broader Hermetic literary tradition, noting its cosmological preoccupations. Wouter Hanegraaff's recent work contextualizes CH V within the historiographical framework of Hermetic spirituality as an operative system for understanding human relationship to cosmos. Scholars have investigated the extent to which CH V's doctrine of divine manifestation influenced Renaissance natural magic theory and the development of pantheistic and immanentist theology in early modernity. The tractate's relationship to Stoic and Neoplatonic precedents has been explored, revealing both affinities and distinctive Hermetic emphases.</p>

<h2>Literature</h2>
<p>Bull, Christian H. <i>The Tradition of Hermes Trismegistus: The Egyptian Priestly Figure as a Teacher of Greco-Egyptian Wisdom</i>. Leiden: Brill, 2018.</p>
<p>Copenhaver, Brian P. <i>Hermetica: The Greek Corpus Hermeticum and the Latin Asclepius in a New English Translation with Notes and Introduction</i>. Cambridge: Cambridge University Press, 1992.</p>
<p>Fowden, Garth. <i>The Egyptian Hermes: A Historical Approach to the Late Pagan Mind</i>. Cambridge: Cambridge University Press, 1986.</p>
<p>Hanegraaff, Wouter J. <i>Hermetic Spirituality and the Historical Imagination</i>. Cambridge: Cambridge University Press, 2022.</p>
<p>Nock, Arthur Darby, and André-Jean Festugière (eds.). <i>Corpus Hermeticum</i>. 4 vols. Paris: Les Belles Lettres, 1946–1954.</p>
<p>Salaman, Clement, Dorine van Oyen, William D. Wharton, and Jean-Pierre Mahé (trans.). <i>The Way of Hermes: New Translations of the Corpus Hermeticum and the Definitions of Hermes Trismegistus to His Son Tat</i>. Rochester, VT: Inner Traditions, 2000.</p>''',

    'ch_vi': '''<p>Tractate VI of the <i>Corpus Hermeticum</i>, commonly subtitled "God is the Good" or "God and the Good," addresses the moral and theological significance of identifying the divine nature with absolute goodness and the implications of this identity for human understanding of ethics and divine providence. This brief but philosophically dense tractate presents the Hermetic position that God is not merely a transcendent power or intelligence but fundamentally characterized by goodness, and that all good flows from the divine source while all that humans perceive as evil or deficiency results from material limitation and human error rather than from divine causation. The text exemplifies the Hermetic integration of metaphysical and moral theology, arguing that cosmological doctrine and ethical instruction are inseparable when properly understood.</p>

<h2>Content and Doctrine</h2>
<p>Tractate VI opens by directly asserting the equivalence between divinity and goodness: "God is good; in fact, goodness itself." Hermes elaborates this claim by explaining that the divine transcends all categories of limitation and negation; the divine can neither do harm nor wish harm since such capacities would imply imperfection and limitation. From this foundational doctrine, the text develops a comprehensive ethical teaching. All genuine good — beauty, truth, justice, wisdom — flows from the divine source and participates in divine nature. All that humans wrongly perceive as evil — suffering, injustice, disease — results either from human ignorance and improper action or from the material limitation inherent in the sublunary realm. The text emphasizes that understanding the divine goodness produces in the human soul a transformation toward goodness; recognizing the good's divine source cultivates virtue and moral excellence. The tractate distinguishes sharply between the divine will (eternally directed toward good) and material resistance and human misuse of freedom (the sources of apparent evil). This theodicy — the reconciliation of divine goodness with the existence of suffering — represents a central Hermetic ethical response to the problem of evil.</p>

<h2>Transmission and Manuscript Tradition</h2>
<p>CH VI appears in all major Greek manuscript families of the <i>Corpus Hermeticum</i> and was included in Marsilio Ficino's 1463 Latin translation. The tractate's relatively brief and direct formulation made it particularly suitable for quotation and adaptation in medieval and Renaissance ethical and theological writings. No Coptic version is known. The tractate's ethical and theological content made it a focus of attention for Renaissance Christian Hermetic interpreters seeking to establish the compatibility between Hermetic doctrine and Christian morality. The text was cited as authoritative evidence that Hermes Trismegistus himself taught concepts of divine goodness and moral virtue congenial to Christian ethics, a polemical strategy important for Renaissance defenders of Hermetic philosophy against theological criticism.</p>

<h2>Modern Scholarship</h2>
<p>Brian P. Copenhaver's translation and commentary address CH VI's ethical doctrines and their relationship to Christian theology and Neoplatonic philosophy. Garth Fowden contextualizes the tractate within broader late antique theodicy traditions and Neoplatonic ethics. Christian H. Bull analyzes the tractate's contribution to the broader Hermetic ethical vision. Wouter Hanegraaff's work situates CH VI within the framework of Hermetic spirituality as a comprehensive system addressing cosmology, metaphysics, and moral development simultaneously. Scholars have investigated the extent to which CH VI's ethical doctrine influenced Renaissance and early modern moral philosophy, particularly through the mediation of Ficino and Pico. The tractate's theodicy has been compared with contemporary Neoplatonic and Christian responses to the problem of evil, revealing distinctive Hermetic emphases on matter as the principle of limitation rather than absolute evil.</p>

<h2>Literature</h2>
<p>Bull, Christian H. <i>The Tradition of Hermes Trismegistus: The Egyptian Priestly Figure as a Teacher of Greco-Egyptian Wisdom</i>. Leiden: Brill, 2018.</p>
<p>Copenhaver, Brian P. <i>Hermetica: The Greek Corpus Hermeticum and the Latin Asclepius in a New English Translation with Notes and Introduction</i>. Cambridge: Cambridge University Press, 1992.</p>
<p>Fowden, Garth. <i>The Egyptian Hermes: A Historical Approach to the Late Pagan Mind</i>. Cambridge: Cambridge University Press, 1986.</p>
<p>Hanegraaff, Wouter J. <i>Hermetic Spirituality and the Historical Imagination</i>. Cambridge: Cambridge University Press, 2022.</p>
<p>Nock, Arthur Darby, and André-Jean Festugière (eds.). <i>Corpus Hermeticum</i>. 4 vols. Paris: Les Belles Lettres, 1946–1954.</p>
<p>Salaman, Clement, Dorine van Oyen, William D. Wharton, and Jean-Pierre Mahé (trans.). <i>The Way of Hermes: New Translations of the Corpus Hermeticum and the Definitions of Hermes Trismegistus to His Son Tat</i>. Rochester, VT: Inner Traditions, 2000.</p>''',

    'ch_xi': '''<p>Tractate XI of the <i>Corpus Hermeticum</i>, subtitled "Mind to Hermes," is a dialogue in which <i>Nous</i> (the divine mind or intellect) addresses Hermes directly, offering instruction on the nature of perception, knowledge, and the transformation of consciousness through divine gnosis. This tractate belongs to the <i>Corpus Hermeticum</i>'s dialogical tractates, in which Hermes receives wisdom from divine or semi-divine interlocutors rather than providing instruction to students. The text is philosophically complex, presenting a sophisticated Hermetic epistemology that distinguishes between ordinary sensory and rational knowledge and higher spiritual gnosis achieved through divine illumination. CH XI exemplifies the mystical and transformative dimensions of Hermetic teaching, emphasizing that knowledge of truth involves not merely intellectual assent but fundamental alterations in consciousness and perception.</p>

<h2>Content and Doctrine</h2>
<p><i>Nous</i> opens its address to Hermes by declaring that those who wish to comprehend divine truths must undergo a transformation of perception and consciousness. Ordinary human knowledge, gained through sensory experience and rational analysis, operates at the level of shadow and illusion compared to the direct perception available through divine illumination. <i>Nous</i> instructs that genuine knowledge requires a cessation of discursive thinking and an entry into direct, intuitive apprehension of reality as it truly is. The tractate emphasizes that the divine mind perceives all things directly and simultaneously; human minds, bound by temporal succession and spatial limitation, perceive only fragments and shadows. Yet the text affirms the possibility of human participation in <i>Nous</i> through discipline and spiritual development. The teaching stresses that recognition of one's own mind's participation in the universal divine <i>Nous</i> constitutes a transformative gnosis. The conclusion emphasizes that knowledge of divine truth produces distinctive joy and liberation from bondage to material illusion and fear.</p>

<h2>Transmission and Manuscript Tradition</h2>
<p>CH XI appears in all major Greek manuscripts of the <i>Corpus Hermeticum</i> and was included in Marsilio Ficino's 1463 translation. The tractate's epistemological sophistication and mystical emphasis made it particularly significant for Renaissance philosophers interested in the relationship between human and divine knowledge. No Coptic parallels are known. The text circulated widely among Renaissance Neoplatonists and influenced theories of intellectual illumination and the possible transformation of human consciousness through mystical experience. The tractate's doctrine that ordinary sense-knowledge and reason are insufficient for truth, and that higher cognition requires divine grace or illumination, resonated with Christian mystical theology and influenced Renaissance Christian Hermetic synthesis.</p>

<h2>Modern Scholarship</h2>
<p>Brian P. Copenhaver's edition provides detailed translation and exegetical commentary on CH XI's epistemological and mystical doctrines. Garth Fowden situates the tractate within the context of late antique spiritual philosophy and mysticism. Christian H. Bull analyzes CH XI as representative of the mystical and transformative dimensions of Hermetic teaching. M. David Litwa's work emphasizes the phenomenological dimensions of the tractate's account of consciousness transformation. Wouter Hanegraaff contextualizes CH XI within the broader historiographical framework of Hermetic spirituality as a comprehensive system addressing both knowledge and transformation of consciousness. Scholars have investigated the extent to which CH XI's doctrine of divine illumination influenced Renaissance and early modern theories of spiritual knowledge and mystical experience.</p>

<h2>Literature</h2>
<p>Bull, Christian H. <i>The Tradition of Hermes Trismegistus: The Egyptian Priestly Figure as a Teacher of Greco-Egyptian Wisdom</i>. Leiden: Brill, 2018.</p>
<p>Copenhaver, Brian P. <i>Hermetica: The Greek Corpus Hermeticum and the Latin Asclepius in a New English Translation with Notes and Introduction</i>. Cambridge: Cambridge University Press, 1992.</p>
<p>Fowden, Garth. <i>The Egyptian Hermes: A Historical Approach to the Late Pagan Mind</i>. Cambridge: Cambridge University Press, 1986.</p>
<p>Hanegraaff, Wouter J. <i>Hermetic Spirituality and the Historical Imagination</i>. Cambridge: Cambridge University Press, 2022.</p>
<p>Litwa, M. David. <i>Hermetica II: The Discourse on the Eighth and Ninth, The Prayer of Thanksgiving, Excerpts from the Perfect Discourse</i>. Cambridge: Cambridge University Press, 2018.</p>
<p>Nock, Arthur Darby, and André-Jean Festugière (eds.). <i>Corpus Hermeticum</i>. 4 vols. Paris: Les Belles Lettres, 1946–1954.</p>''',
}

def main():
    try:
        conn = sqlite3.connect(DB_PATH)
        c = conn.cursor()

        for text_id, analysis_html in analyses.items():
            c.execute('''
                UPDATE texts
                SET analysis_html = ?
                WHERE text_id = ?
            ''', (analysis_html, text_id))
            print(f'Updated {text_id}')

        conn.commit()
        print(f'\nSuccessfully updated {len(analyses)} texts.')

    except Exception as e:
        print(f'Error: {e}', file=sys.stderr)
        return 1
    finally:
        conn.close()

    return 0

if __name__ == '__main__':
    sys.exit(main())
