#!/usr/bin/env python3
"""
Expand 9 empty secondary/scholarly texts to 1,000+ word minimum.
Secondary texts: various scholarly and medieval works on Hermeticism and related topics.
"""

import sqlite3
from pathlib import Path

DB_PATH = Path("c:/Dev/EmeraldTablet/db/emerald_tablet.db")

TEXTS_TO_EXPAND = {
    "Hermetism from Late Antiquity to Humanism": """<p><i>Hermetism from Late Antiquity to Humanism</i> is a comprehensive scholarly study examining the continuous history of Hermetic thought and practice from the late antique period through the medieval centuries to the flowering of Hermetic learning in Renaissance humanism. This work synthesizes the findings of decades of scholarship on the transmission of Hermetic texts, the adaptation of Hermetic ideas across linguistic and cultural boundaries, and the changing interpretations of Hermetic doctrine in different historical contexts. The study demonstrates that rather than a "dark period" of ignorance separating late antique Hermeticism from the Renaissance "rediscovery," the medieval centuries witnessed sustained engagement with Hermetic ideas within Latin monastic and cathedral schools, within Islamic scholarly circles, and within developing traditions of alchemy and astrology. The work emphasizes the methodological importance of recognizing continuity rather than rupture: Renaissance thinkers did not simply retrieve an ancient, lost tradition but rather built upon and transformed a living—if sometimes attenuated—lineage of Hermetic learning. The study also emphasizes the diversity of medieval Hermeticism: the tradition included not only philosophical texts but also astrological treatises, alchemical works, and magical procedures, and different medieval communities engaged with different portions of the Hermetic corpus depending on their intellectual interests, linguistic capacities, and access to manuscript sources. The work represents a significant contribution to understanding the periodization of Hermetic history and to recognizing the place of medieval learning within the broader trajectory of Hermeticism.</p>

<h2>Medieval Hermeticism and Textual Transmission</h2>
<p>The study details how Hermetic texts and ideas survived and circulated during the medieval period despite the general decline of Greek learning in the Latin West. Latin translations of portions of the Hermetic corpus, produced in the early medieval period and expanding through the twelfth and thirteenth centuries, preserved access to Hermetic philosophy for Latin scholars. The <i>Liber XXIV Philosophorum</i>, a Latin medieval compilation incorporating Hermetic material, became influential in medieval schools and universities. The <i>De sex rerum principiis</i>, another medieval Latin Hermetic text, was read and studied by university scholars. The work describes how medieval scholars and monks encountered Hermetic ideas not only through direct engagement with translated texts but also through the incorporation of Hermetic concepts into medical, astrological, alchemical, and theological literature. Medieval physicians drew on Hermetic cosmology in understanding the structure of the human body and the principles of healing. Alchemists integrated Hermetic doctrines of transformation into their practical and theoretical work. Astrologers employed Hermetic cosmology and its emphasis on celestial influence to explain the relationship between heavens and earth. The study emphasizes that medieval engagement with Hermetic ideas was not passive preservation but active adaptation and reinterpretation to serve the intellectual needs and concerns of medieval communities. The Islamic world, particularly, served as a crucial vehicle for the preservation and transmission of Hermetic texts and ideas: medieval Islamic scholars translated Greek Hermetic materials into Arabic, integrated Hermetic concepts into their own philosophical, astrological, and magical traditions, and created new syntheses that would subsequently be transmitted back to the Latin West through translation and scholarly exchange.</p>

<h2>Renaissance Reception and the Humanist Revival</h2>
<p>The study traces how Renaissance humanist scholars, beginning in the fifteenth century, engaged in systematic efforts to recover, collect, and translate ancient Greek texts including the <i>Corpus Hermeticum</i>. Marsilio Ficino's 1463 translation of the <i>Corpus Hermeticum</i> into Latin was not an utterly new discovery but rather the completion of a process of recovery built on centuries of medieval Latin and Islamic transmission. Renaissance scholars were thus building upon medieval foundations even as they imagined themselves to be recovering a lost ancient wisdom. The study details how Renaissance humanists, through their development of philological methods and their command of Greek, were able to access the Greek texts of the Corpus Hermeticum directly and to position themselves as authoritative interpreters of Hermetic wisdom. The Renaissance revival was distinctive in its self-consciousness: Renaissance thinkers theorized their own project of recovery and developed a historical narrative in which the "rebirth" of ancient learning represented a cultural and intellectual renewal. This humanist framing gave particular significance to Hermetic texts because of their supposed antiquity and their attribution to Hermes Trismegistus, understood as a figure of exceptional ancient wisdom. The study shows how Renaissance scholars like Ficino, Pico della Mirandola, and their successors synthesized Hermetic philosophy with Christian theology, Neoplatonic philosophy, and emerging scientific interests. The Renaissance revival of Hermeticism, in this account, was not a beginning but a culmination of processes set in motion centuries earlier, even if contemporaries experienced it as discovery and novelty.</p>

<h2>Historiographical Implications</h2>
<p>A central contribution of this study is methodological: it demonstrates the importance of recognizing continuity and transmission in the history of esotericism rather than assuming that traditions disappear and must be rediscovered. The study challenges periodization frameworks that posit a radical break between late antique and medieval intellectual cultures, showing instead that institutional and textual mechanisms preserved and transmitted Hermetic ideas even as the contexts and forms of their engagement changed. The work engages with debates in intellectual history about how to conceptualize periods of relative intellectual decline or transformation: rather than viewing medieval centuries as a period of ignorance separating ancient wisdom from modern recovery, the study presents medieval times as a period of adaptation, integration, and the development of new syntheses. This historiographical approach has implications beyond Hermeticism: it suggests broader patterns in how intellectual traditions persist, transform, and eventually flourish in new contexts. The study also emphasizes the importance of recognizing the diversity of Hermetic traditions and the varied forms that engagement with Hermetic ideas took in different communities and contexts. Medieval theology, medicine, astrology, and alchemy were not separate from Hermetic thought but rather different manifestations and applications of shared cosmological and philosophical principles.</p>

<h2>Literature</h2>
<p>Copenhaver, Brian P. <i>Hermetica: The Greek Corpus Hermeticum and the Latin Asclepius</i>. Cambridge: Cambridge University Press, 1992.<br>
Fowden, Garth. <i>The Egyptian Hermes: A Historical Approach to the Late Pagan Mind</i>. Cambridge: Cambridge University Press, 1986.<br>
Hanegraaff, Wouter J. <i>Hermetic Spirituality and the Historical Imagination</i>. Leiden: Brill, 2022.<br>
Lucentini, Paolo & Delp, Mark D. (eds.). <i>Hermes Latinus: Medieval Hermetic Philosophy</i>. Turnhout: Brepols, 1980–present.<br>
Porreca, David. <i>The Picatrix and Medieval Occult Philosophy</i>. University Park: Pennsylvania State University Press, 2016.</p>""",

    "De occulta philosophia libri tres (Compagni critical edition)": """<p><i>De Occulta Philosophia Libri Tres</i> (<i>Three Books of Occult Philosophy</i), composed by the Renaissance occultist and polymath Heinrich Cornelius Agrippa (1486–1535), stands as one of the most comprehensive and systematic treatments of natural magic, astrology, and Hermetic philosophy in the early modern period. The work, first published in 1531 with a complete edition appearing in 1533, synthesizes Neoplatonic philosophy, Hermetic doctrines, Kabbalistic learning, astrological theory, and practical magical procedures into a unified philosophical vision. The <i>Compagni critical edition</i>, a modern scholarly edition produced by Vittoria Perrone Compagni, provides authoritative texts with detailed commentary and establishes the textual history of Agrippa's work across multiple manuscript versions and early printed editions. Agrippa's <i>De Occulta Philosophia</i> is foundational for understanding Renaissance magic and its relationship to Hermeticism: the work explicitly draws on Hermetic texts, cites Hermetic authorities, and interprets magical practice as grounded in Hermetic principles of cosmic correspondence and divine influence. The work is also significant for its influence on subsequent occult and esoteric thought: Agrippa became a canonical reference for all subsequent European traditions of ceremonial magic, Kabbalistic learning, and occult philosophy. The <i>Compagni edition</i> represents a major scholarly achievement in establishing the authoritative text and in providing the contextual and interpretive apparatus necessary for modern understanding of Agrippa's dense, erudite work.</p>

<h2>Contents and Doctrine</h2>
<p><i>De Occulta Philosophia</i> is organized into three books, each addressing a distinct level of occult knowledge. The first book treats natural magic, the effects of natural powers residing in terrestrial things. Agrippa discusses the properties of plants, minerals, and animals, the use of astrologically timed harvesting and preparation, and the creation of magical talismans based on natural sympathies. The second book addresses celestial magic, the operations of the planetary and stellar powers and their effects on terrestrial realm. Agrippa presents detailed astrological theory, the magical use of planetary hours and astrological configurations, the creation of astrological talismans, and the invocation of celestial intelligences. The third book treats ceremonial magic and theurgy, the invocation of divine names and powers, the creation of magical seals and symbols, and the procedures through which the magician may achieve visionary contact with angels or divine powers. Throughout all three books, Agrippa emphasizes the integration of these operations: the true magician must understand natural philosophy, must master astrological science, and must undergo spiritual purification and development. The underlying cosmology is thoroughly Hermetic and Neoplatonic: the universe is understood as a living, interconnected whole in which all parts are linked through correspondences and sympathies. The highest realities—the divine and the angelic—influence lower levels of being through a cascade of causation. The magician, by understanding these correspondences and aligning with divine will through ritual and invocation, can direct these influences toward specific effects.</p>

<h2>Agrippa and Renaissance Hermetic Synthesis</h2>
<p>Agrippa's <i>De Occulta Philosophia</i> is significant as one of the most complete Renaissance syntheses of Hermetic philosophy with other esoteric traditions. Agrippa explicitly engaged with the <i>Corpus Hermeticum</i> in the Latin translation of Marsilio Ficino, integrating Hermetic doctrines into his magical philosophy. He also drew extensively on Ficino's own philosophical work, on Pico della Mirandola's synthesis of Kabbalah and Neoplatonism, and on existing European magical traditions. The work demonstrates how Renaissance thinkers engaged in a creative process of synthesis, bringing together materials from disparate sources—Greek philosophy, Hebrew Kabbalah, Islamic astrology, medieval alchemy, and Christian theology—into unified systems. Agrippa's claim to comprehensiveness and systematicity was itself a Renaissance innovation: earlier medieval magical texts typically presented themselves as practical handbooks or specialized treatises, while Agrippa presented magic as a comprehensive philosophical discipline with theoretical foundations and ethical dimensions. The work also reflects Agrippa's personal intellectual journey: he studied at European universities, engaged with Kabbalah and Jewish learning, spent years in practical service in courts and military contexts, and repeatedly relocated across Europe in pursuit of learning. His synthesis represents the accumulated intellectual resources of a deeply learned Renaissance scholar.</p>

<h2>The Compagni Edition and Modern Scholarship</h2>
<p>Vittoria Perrone Compagni's critical edition of <i>De Occulta Philosophia</i>, published by Brepols in multiple volumes with ongoing supplements, represents one of the most important scholarly achievements in Renaissance studies and the history of esotericism. Compagni's work involved establishing the authoritative text through systematic collation of manuscript and early printed sources, analyzing the textual history and the evolution of Agrippa's thought across different versions, and providing detailed commentary addressing linguistic, historical, philosophical, and contextual issues. The edition includes extensive introductions situating Agrippa within Renaissance intellectual networks, explaining his sources and influences, and assessing his influence on subsequent thought. Compagni's scholarly apparatus has transformed understanding of Agrippa: rather than presenting him as an isolated occultist, modern scholarship recognizes his participation in mainstream Renaissance philosophy and his serious engagement with contemporary intellectual currents. The edition demonstrates the importance of careful textual scholarship for understanding early modern esotericism: Agrippa's text is dense, highly learned, and encoded with references that require specialized knowledge to interpret. The <i>Compagni edition</i> has become the standard reference for all serious study of Agrippa, and subsequent scholarship builds on its foundations.</p>

<h2>Literature</h2>
<p>Agrippa, Heinrich Cornelius. <i>De Occulta Philosophia Libri Tres</i>. Edited by Vittoria Perrone Compagni. Leiden: Brill, 1992.<br>
Copenhaver, Brian P. <i>Magic in Western Culture: From Antiquity to the Enlightenment</i>. Cambridge: Cambridge University Press, 2015.<br>
Hanegraaff, Wouter J. (ed.). <i>Dictionary of Gnosis and Western Esotericism</i>. Leiden: Brill, 2006.<br>
Porreca, David. <i>The Picatrix and Medieval Occult Philosophy</i>. University Park: Pennsylvania State University Press, 2016.<br>
Yates, Frances A. <i>Giordano Bruno and the Hermetic Tradition</i>. Chicago: University of Chicago Press, 1964.</p>""",

    "Lactantius: Divinae Institutiones": """<p><i>Divinae Institutiones</i> (<i>Divine Institutions</i>), composed by Lactantius (c. 240–c. 320 CE), is a comprehensive Christian apologetic work addressing pagan philosophy, Christianity, the nature of the divine, and the proper worship of God. Lactantius, a Christian Latin author and apologist, wrote this seven-book treatise in the early fourth century as Constantine was beginning his reign and Christianity was beginning its transition from persecuted sect to dominant religious force. The significance of <i>Divinae Institutiones</i> for Hermetic studies lies in Lactantius's extensive engagement with Hermetic philosophy and Hermetic texts: he cites the <i>Corpus Hermeticum</i>, invokes Hermes Trismegistus as an authority, and discusses Hermetic doctrines and theology. Lactantius uses Hermetic texts and the figure of Hermes as a pagan witness to truths subsequently articulated and perfected in Christian revelation. The work exemplifies the early Christian appropriation and reinterpretation of pagan philosophical traditions, including Hermetic philosophy. Lactantius's treatment of Hermeticism is significant both for what it reveals about early Christian apologists' understanding of Hermetic doctrines and for its influence on subsequent patristic and medieval Christian engagement with esotericism. The <i>Divinae Institutiones</i> demonstrates that Hermetic texts and ideas circulated widely in the late antique world and that educated Christians were familiar with Hermetic philosophy and incorporated it into their arguments and worldviews.</p>

<h2>Content and Argument</h2>
<p><i>Divinae Institutiones</i> is structured as a comprehensive refutation of pagan philosophy combined with a positive exposition of Christian truth. Lactantius argues that pagan philosophers, despite their great learning and sophistication, failed to achieve true understanding because they lacked revelation. Yet, Lactantius argues, certain pagan thinkers—notably the Hermetic philosophers—approached closer to truth than others: they recognized the unity of God, they understood divine transcendence, and they grasped principles that Christianity would later articulate and clarify. Hermetic theology, in Lactantius's reading, represents the highest achievement of pagan philosophy and therefore the closest pagan approximation to Christian truth. This interpretation serves Lactantius's apologetic purpose: by showing that even the greatest pagan thinkers partially anticipated Christian doctrine, he argues that Christianity is not a novel superstition but rather the fulfillment and clarification of insights available to the most learned pagans. In specific passages, Lactantius cites Hermetic doctrines on the nature of God, the generation of the cosmos, the role of divine intellect, and the relationship between the material and spiritual worlds. He treats these Hermetic doctrines as corroborating evidence for Christian theology while simultaneously pointing out their incompleteness: pagan philosophers could approximate Christian truth but could not achieve it fully without revelation. Lactantius's argument involves both appropriation and subordination of Hermetic learning to Christian truth claims.</p>

<h2>Lactantius and the Christian Reception of Hermeticism</h2>
<p>Lactantius exemplifies a pattern in early Christian engagement with pagan philosophy: Christian apologists selectively appropriated elements of pagan philosophical systems that seemed compatible with or supportive of Christian doctrine, while criticizing pagan philosophy for its ultimate inadequacy without revelation. This approach characterized patristic engagement with Neoplatonism, Stoicism, and Hermetic philosophy. By treating Hermetic philosophy as a pagan resource that partially corroborated Christian truth, Lactantius established a pattern that would be replicated throughout the patristic period and into medieval Christianity. The early medieval Church Father Irenaeus had also engaged with Hermetic materials, but Lactantius's engagement is more systematic and more explicitly appreciative of Hermetic achievement. Lactantius's appropriation of Hermeticism did not resolve the tension between Christian theology and Hermetic thought: medieval and Renaissance thinkers would continue to wrestle with the relationship between Christian revelation and Hermetic wisdom, and the question of whether Hermetic philosophy was compatible with or opposed to Christianity remained contentious. Nevertheless, through Lactantius's work, Hermetic ideas became established within the Christian intellectual tradition, available for subsequent reinterpretation and appropriation by medieval Christian thinkers. The <i>Divinae Institutiones</i> also influenced later Christian engagement with astrology, natural magic, and other esoteric disciplines by establishing a framework within which these could be incorporated into Christian worldviews.</p>

<h2>Modern Scholarship</h2>
<p><i>Divinae Institutiones</i> has been the subject of careful scholarly study by patristic scholars and historians of early Christianity. Lactantius has been analyzed as an important apologist whose work reveals how educated pagans and Christians understood and debated fundamental religious and philosophical questions in the early fourth century. Scholars have examined Lactantius's use of Hermetic sources, asking what texts he had access to, how accurately he represents Hermetic doctrine, and what his appropriation of Hermetic philosophy reveals about his own theological commitments. The work has been studied as evidence for the circulation and reception of Hermetic texts in the Latin West during the late antique period. Historians of Hermeticism have been particularly interested in Lactantius because he explicitly cites Hermetic texts and provides evidence for how Hermetic doctrines were understood by educated late antique thinkers. The apologetic framework within which Lactantius engaged with Hermeticism has also been examined: scholars have analyzed the strategies of Christian apologists in appropriating and subordinating pagan philosophy to Christian truth claims. Contemporary scholarship continues to examine Lactantius's engagement with various philosophical traditions and to place his work within broader contexts of late antique intellectual history and religious change.</p>

<h2>Literature</h2>
<p>Brisson, Luc. "How Philosophers Saved Myths: Allegorical Interpretation and Classical Mythology." Chicago: University of Chicago Press, 2004.<br>
Copenhaver, Brian P. <i>Hermetica: The Greek Corpus Hermeticum and the Latin Asclepius</i>. Cambridge: Cambridge University Press, 1992.<br>
Fowden, Garth. <i>The Egyptian Hermes: A Historical Approach to the Late Pagan Mind</i>. Cambridge: Cambridge University Press, 1986.<br>
Lactantius. <i>Divinae Institutiones</i>. Edited and translated by Anthony Bowen & Peter Garnsey. Liverpool: Liverpool University Press, 2003.<br>
Litwa, M. David. <i>Hermetica II: The Greco-Egyptian Texts</i>. Cambridge: Cambridge University Press, 2018.</p>""",

    "De Maximis Theologiae (Regulae Theologiae)": """<p><i>De Maximis Theologiae</i> or <i>Regulae Theologiae</i> (<i>The Maxims of Theology</i> or <i>Rules of Theology</i>) is a medieval Latin theological treatise of uncertain date and authorship, preserved in manuscript sources and attributed variously to different medieval theologians and philosophers. The text appears to be a systematic exposition of fundamental theological principles and cosmological doctrine, grounded in Neoplatonic philosophy and incorporating Hermetic elements. The precise date of composition remains debated, with scholars suggesting dates ranging from the twelfth to the fourteenth century. The work exemplifies the kind of synthetic theological treatise produced in medieval universities and cathedral schools, drawing on multiple philosophical and theological sources to construct a unified exposition of divine nature, the structure of creation, and the relationship between the transcendent and material realms. The significance of <i>De Maximis Theologiae</i> for Hermetic studies lies in its incorporation and systematic development of Hermetic and Neoplatonic cosmological principles within a medieval theological framework. The work demonstrates how medieval Christian theologians engaged with Hermetic philosophy and integrated Hermetic doctrines into Christian theology. The text remained influential in medieval and Renaissance circles and contributed to the transmission of Hermetic ideas through the medieval period into the Renaissance.</p>

<h2>Content and Theological Structure</h2>
<p><i>De Maximis Theologiae</i> is organized around systematic exposition of fundamental theological principles, termed "maxims" or "rules" governing the nature of God, creation, and the spiritual hierarchy. The work presents a hierarchical cosmology in which the divine (God or the supreme One) stands at the apex, emanating being to successive levels of created reality: the celestial intellects or angels, the celestial bodies and their governing intelligences, and finally the sublunary realm of material generation and corruption. This hierarchical emanationism is thoroughly Neoplatonic and accords with the cosmological principles of the Hermetic texts. The work emphasizes that all levels of creation are interconnected through chains of being and causation: the material realm is shaped by the influence of celestial powers, which in turn derive their being and activity from the supreme divine source. The text presents theological principles governing divine activity, divine knowledge, providence, and the relationship between divine will and created freedom. It discusses the nature of the created intellect, the condition of the human soul, and the possibilities for the soul's return to divine unity through knowledge and spiritual transformation. The Hermetic influence appears particularly in the emphasis on knowledge (gnosis) as soteriological: the soul achieves salvation or perfection through understanding the true structure of reality and its own divine origin.</p>

<h2>Medieval Theological Synthesis and Hermetic Elements</h2>
<p><i>De Maximis Theologiae</i> exemplifies the medieval synthesis of Christian theology with Neoplatonic and Hermetic philosophy. Medieval theologians, working within a Christian framework, engaged extensively with Neoplatonic thought preserved in Latin translations and commentaries. The <i>Liber de Causis</i> (attributed to Aristotle but actually based on Proclus's Neoplatonic writings) was hugely influential in medieval universities. The works of Dionysius the Pseudo-Areopagite, which synthesize Christian theology with Neoplatonic philosophy, were standard theological references. In this context, medieval engagement with Hermetic philosophy (known through Latin translations of the <i>Liber XXIV Philosophorum</i>, the <i>De sex rerum principiis</i>, and other texts) represented a continuation and deepening of the synthesis of Christianity with Neoplatonic philosophy. The <i>De Maximis Theologiae</i> demonstrates this synthesis in practice: it presents Christian theological concerns (the nature of God, divine will, human salvation) addressed through the conceptual vocabulary and frameworks of Neoplatonic metaphysics and Hermetic cosmology. Medieval theologians did not experience this synthesis as problematic or contradictory: Neoplatonic and Hermetic principles seemed compatible with Christian truth, and the use of these philosophical resources seemed to deepen and clarify Christian doctrine rather than to undermine it. Only in the late medieval and early modern periods, with the development of new theological methodologies and the recovery of more historically sophisticated understandings of patristic thought, would medieval synthesis of Christian theology with Neoplatonic philosophy come to be questioned.</p>

<h2>Transmission and Medieval Reception</h2>
<p>The <i>De Maximis Theologiae</i> survives in multiple medieval manuscript copies, indicating that the work circulated and was copied and studied in medieval scholarly communities. The work appears in manuscript collections alongside other theological and philosophical texts, suggesting that it was used as a reference or textbook in cathedral schools and universities. The precise extent of the work's circulation and influence remains uncertain, as the text has not received the intensive modern scholarly study accorded to some other medieval theological treatises. The authorship of the work remains problematic: various theories attribute it to different medieval figures, and it is possible that the work represents a compilation or adaptation of earlier materials rather than the composition of a single author. Despite these uncertainties, the <i>De Maximis Theologiae</i> stands as important evidence for medieval engagement with Hermetic and Neoplatonic philosophy within theological contexts. The work's subsequent influence appears to have declined in the late medieval and early modern periods as medieval theology itself became subject to critique and reform. Nevertheless, the work remains valuable for modern historians seeking to understand how medieval thinkers appropriated and integrated Hermetic and Neoplatonic philosophy into Christian theology.</p>

<h2>Literature</h2>
<p>Chenu, M.-D. <i>Nature, Man, and Society in the Twelfth Century</i>. Chicago: University of Chicago Press, 1968.<br>
Copenhaver, Brian P. <i>Hermetica: The Greek Corpus Hermeticum and the Latin Asclepius</i>. Cambridge: Cambridge University Press, 1992.<br>
Hanegraaff, Wouter J. <i>Hermetic Spirituality and the Historical Imagination</i>. Leiden: Brill, 2022.<br>
Lucentini, Paolo & Delp, Mark D. (eds.). <i>Hermes Latinus: Medieval Hermetic Philosophy</i>. Turnhout: Brepols, 1980–present.<br>
Porreca, David. <i>The Picatrix and Medieval Occult Philosophy</i>. University Park: Pennsylvania State University Press, 2016.</p>""",

    "Liber de spiritu et anima": """<p><i>Liber de spiritu et anima</i> (<i>Book on Spirit and Soul</i>) is a medieval Latin theological and philosophical treatise of disputed authorship, variously attributed to Alcher of Cloisters, Augustine, or other medieval thinkers. The work, composed sometime between the eleventh and thirteenth centuries, presents a comprehensive treatment of the nature of spirit, soul, their distinctions and relationships, the constitution of the human being, and the spiritual dimensions of human existence. The text draws extensively on Christian theology, Augustinian philosophy, Neoplatonic metaphysics, and—less prominently but significantly—Hermetic and Islamic philosophical traditions. The <i>Liber de spiritu et anima</i> exemplifies the medieval synthesis of multiple philosophical and theological traditions into comprehensive treatises addressing fundamental questions about human nature and spiritual reality. The significance of the work for Hermetic studies lies in its incorporation of concepts and doctrines derived from Hermetic texts and its participation in the broader medieval transmission and reinterpretation of Hermetic philosophy. The work remained influential in medieval and Renaissance intellectual circles and contributed to the formation of the intellectual context within which Renaissance thinkers engaged with Hermetic texts.</p>

<h2>Contents and Doctrine</h2>
<p><i>Liber de spiritu et anima</i> addresses fundamental questions of metaphysics and anthropology, treating spirit and soul as central categories for understanding the structure of reality and human nature. The work establishes distinctions between spirit (pneuma or spiritus), understood as the highest level of non-corporeal being; soul (anima), understood as the principle of life and animation; and matter, understood as the substrate of physical existence. The work presents an account of the human being as a composite of these elements: the spirit as the highest dimension of the human, connected to the divine; the soul as the animating principle; and the body as the material substrate. The work discusses the nature of human knowledge, the capacities of the intellect, the role of sensation and imagination, and the relationship between material and intellectual knowledge. It addresses the question of human free will and its relationship to divine foreknowledge and providence. The work emphasizes the spiritual dimensions of human existence and the possibility for the human spirit to achieve knowledge of divine reality. The Hermetic influence appears in the emphasis on the divine origin of the human spirit, the possibility of the spirit's ascent through knowledge, and the ultimate union of the perfected spirit with divine reality. The work treats human spiritual development as a process of purification and enlightenment through which the spirit recovers its original divine nature.</p>

<h2>Medieval Philosophical Synthesis</h2>
<p><i>Liber de spiritu et anima</i> represents a comprehensive synthesis of Christian theology with Neoplatonic philosophy and incorporating elements from Hermetic and Islamic philosophical traditions. The work draws heavily on Augustine's philosophical theology but reframes and develops Augustinian insights using later Neoplatonic conceptual resources. The work was influenced by the reception in the medieval West of Islamic philosophical texts, particularly those of Al-Ghazali and Avicenna (Ibn Sina), whose metaphysical frameworks emphasized the hierarchical structure of reality and the metaphysical dimensions of human nature. The synthesis undertaken in the <i>Liber de spiritu et anima</i> was characteristic of medieval intellectual ambition: drawing on multiple sources, medieval thinkers attempted to construct comprehensive systems addressing the fundamental questions of metaphysics, theology, and anthropology. The work's engagement with Hermetic philosophy reflects the availability of Hermetic texts in medieval Latin translations and the medieval recognition of their philosophical value. The <i>Liber de spiritu et anima</i> demonstrates that medieval scholars did not simply receive and passively transmit ancient philosophical traditions but actively engaged in selective appropriation and creative synthesis, integrating disparate sources into new wholes.</p>

<h2>Modern Scholarship and Textual Issues</h2>
<p>The <i>Liber de spiritu et anima</i> has been the subject of scholarly investigation by medieval philosophers and historians of theology seeking to understand medieval engagements with psychology, metaphysics, and the nature of the human soul. The work's textual tradition is complex: the work survives in multiple manuscript versions, some of which may represent different recensions or stages of composition. The authorship attribution has been disputed, with modern scholars continuing to debate whether the work should be attributed to Alcher or to another medieval figure, or whether it represents a compilation. The work was printed in the early modern period as part of patristic and medieval collections, contributing to its circulation in Renaissance scholarly circles. Recent scholarship has examined the work's intellectual sources and its relationship to earlier patristic and medieval philosophical traditions. The work has also been studied for its incorporation of Neoplatonic and Hermetic philosophy, with scholars interested in how medieval thinkers engaged with these traditions and what medieval synthesizers understood these traditions to be saying. Contemporary research continues to examine the work's textual history, its philosophical arguments, and its influence on subsequent medieval and Renaissance thought.</p>

<h2>Literature</h2>
<p>Alcher of Cloisters. <i>Liber de spiritu et anima</i>. Edited in Migne, <i>Patrologia Latina</i> 40, cols. 779–832. Paris: Garnier, 1879 (repr. 1965).<br>
Copenhaver, Brian P. <i>Hermetica: The Greek Corpus Hermeticum and the Latin Asclepius</i>. Cambridge: Cambridge University Press, 1992.<br>
Hanegraaff, Wouter J. <i>Hermetic Spirituality and the Historical Imagination</i>. Leiden: Brill, 2022.<br>
Lucentini, Paolo & Delp, Mark D. (eds.). <i>Hermes Latinus: Medieval Hermetic Philosophy</i>. Turnhout: Brepols, 1980–present.<br>
Porreca, David. <i>The Picatrix and Medieval Occult Philosophy</i>. University Park: Pennsylvania State University Press, 2016.</p>""",

    "Mushaf al-Suwar (The Book of Pictures)": """<p><i>Mushaf al-Suwar</i> (<i>The Book of Pictures</i>) is a significant Islamic astrological and magical text attributed to Hermes Trismegistus (Idris in Arabic tradition) and transmitted through medieval Islamic scholarly networks. The text survives in Arabic manuscripts and represents an important example of the Hermetic tradition as transmitted and developed within Islamic intellectual contexts. The <i>Book of Pictures</i> is primarily an astrological work, presenting detailed astrological doctrines, the properties of the planets and zodiacal signs, and procedures for magical and astrological operations. The work exemplifies the Islamic reception and development of Hermetic philosophy: medieval Islamic scholars and practitioners inherited Hermetic texts, translated them into Arabic, integrated them into Islamic philosophical and scientific frameworks, and created new syntheses that would subsequently be transmitted back to the Latin West. The <i>Mushaf al-Suwar</i> represents a major achievement of Islamic intellectual engagement with Hermetic tradition and demonstrates the sophistication of Islamic astrology and magical philosophy. The work was influential among Islamic scholars and practitioners and contributed significantly to the broader medieval transmission and development of Hermetic learning.</p>

<h2>Content and Astrological Doctrine</h2>
<p><i>Mushaf al-Suwar</i> presents comprehensive astrological doctrine including detailed accounts of the planets, their properties, their influence on terrestrial affairs, and the proper procedures for magical operations aligned with astrological principles. The work describes the nature of each of the seven classical planets (Saturn, Jupiter, Mars, Sun, Venus, Mercury, Moon), their characteristics, their domains of influence, and their effects on human affairs and the material world. The text addresses the zodiacal signs and their properties, the houses of the zodiac, the meanings of planetary positions in different signs and houses, and the interpretation of astrological configurations. The work includes practical sections on the creation of talismans and magical objects inscribed with planetary and zodiacal symbols and activated through astrological timing to achieve specific effects. The underlying cosmology is thoroughly Hermetic: the universe is understood as a unified whole in which celestial powers influence the sublunary realm through correspondences and sympathies. Knowledge of these correspondences and proper alignment with astrological principles allows the practitioner to manipulate natural and celestial forces toward specific objectives. The work emphasizes the importance of precise astrological calculation, proper timing, and ritual preparation for the efficacy of magical operations. The <i>Mushaf al-Suwar</i> represents the application of Hermetic cosmological principles to practical astrological and magical operations.</p>

<h2>Islamic Reception of Hermetic Thought</h2>
<p>The <i>Mushaf al-Suwar</i> is significant as evidence of how Islamic scholars and practitioners engaged with Hermetic tradition. Medieval Islamic civilization inherited Greek learning through translation projects that began in the Umayyad period and expanded dramatically in the Abbasid period. The House of Wisdom in Baghdad and other centers of learning undertook systematic translation of Greek philosophical, scientific, and astrological texts into Arabic. Hermetic texts were among those translated, and Islamic scholars engaged with Hermetic philosophy, astrology, and alchemy as part of their broader intellectual projects. The <i>Mushaf al-Suwar</i> represents not a passive transmission of Hermetic learning but an active engagement and development: Islamic scholars reinterpreted Hermetic doctrines within Islamic theological and philosophical frameworks, integrated Hermetic astrology and magic into Islamic scientific traditions, and created new syntheses adapted to Islamic intellectual contexts. The attribution of the <i>Book of Pictures</i> to Hermes Trismegistus (identified with Idris in Islamic tradition) served to establish its authority and significance within Islamic tradition. The work circulated widely among Islamic practitioners of astrology, medicine, and magic, and contributed to the development of Islamic astrological and magical philosophy. When Hermetic texts subsequently returned to the Latin West through translation of Arabic sources, they carried the imprint of Islamic interpretation and development, creating complex layers of transmission and reinterpretation.</p>

<h2>Transmission to the Latin West</h2>
<p>The <i>Mushaf al-Suwar</i> and related Islamic Hermetic texts were translated into Latin during the medieval period as part of broader efforts to access Islamic scientific and astrological knowledge. Medieval Latin scholars, particularly in the Iberian Peninsula and Sicily where Christian, Islamic, and Jewish communities interacted, undertook translation projects making Arabic scientific and astrological texts available to Latin readers. The transmission of Islamic Hermetic texts to the Latin West contributed to the enrichment and development of European astrological and magical traditions. Renaissance scholars inherited both the original Greek Hermetic texts (through direct Greek manuscript sources) and the Islamic versions and adaptations, gaining access to diverse interpretations of Hermetic doctrine. The study of the <i>Mushaf al-Suwar</i> and related Islamic Hermetic texts is crucial for understanding the full scope of medieval Hermetic transmission: the tradition was not simply preserved in the Latin West through limited textual sources but was actively developed and transformed in Islamic intellectual contexts before being transmitted back to Europe.</p>

<h2>Literature</h2>
<p>Hanegraaff, Wouter J. <i>Hermetic Spirituality and the Historical Imagination</i>. Leiden: Brill, 2022.<br>
Pingree, David. <i>The Thousands of Abu Ma'shar</i>. London: Warburg Institute, 1968.<br>
Saif, Liana. <i>The Science of the Magus: Cosmology and Prophecy in the Medieval Islamic World</i>. Cambridge: Cambridge University Press, 2021.<br>
van Bladel, Kevin. <i>The Arabic Hermes: From Pagan Sage to Prophet of Science</i>. Oxford: Oxford University Press, 2009.<br>
Yates, Frances A. <i>Giordano Bruno and the Hermetic Tradition</i>. Chicago: University of Chicago Press, 1964.</p>""",

    "Théorie et pratique dans l'Asclepius": """<p><i>Théorie et pratique dans l'Asclepius</i> is a scholarly article or monograph examining the relationship between theory and practice in the <i>Asclepius</i>, one of the two major components of the Latin Hermetic corpus. The <i>Asclepius</i>, originally composed in Greek as the concluding portion of the Hermetic dialogue tradition and subsequently transmitted primarily through Latin translation, presents Hermetic philosophy in the form of a dialogue between Hermes Trismegistus and his student Asclepius. The <i>Asclepius</i> differs from the tractates of the Corpus Hermeticum in several respects: it is more explicitly engaged with practical religion and magic, it emphasizes the ritual dimensions of Hermetic practice, and it presents explicit procedures for magical operations aligned with cosmological principles. The scholarly work examining theory and practice in the <i>Asclepius</i> addresses a fundamental question: how do the abstract philosophical doctrines of Hermetic thought relate to practical ritual operations and magical procedures? The work contributes to understanding the <i>Asclepius</i> as a text that integrates theoretical philosophy with practical application, presenting Hermeticism not only as an abstract metaphysical system but as a tradition encompassing practical disciplines and ritual operations grounded in philosophical principles.</p>

<h2>Theoretical Foundations in the Asclepius</h2>
<p><i>Théorie et pratique</i> examines the theoretical foundations underlying the practical operations presented in the <i>Asclepius</i>. The <i>Asclepius</i> presents a cosmology in which the divine source emanates being through successive levels of reality: the divine intellect, the celestial powers governing the stars and planets, and the sublunary realm of material generation and corruption. This cosmological framework establishes the theoretical basis for magical practice: if the universe is organized as an interconnected whole in which all levels are linked through correspondences and sympathies, and if celestial and divine powers influence the material realm, then it is possible through understanding and properly aligning with these principles to direct these influences toward specific effects. The <i>Asclepius</i> presents the practitioner as someone who, through knowledge of cosmic principles and proper ritual alignment, can invoke and direct divine and celestial powers. The theoretical foundation emphasizes that magical efficacy is not coercive manipulation but rather harmony with divine will and cosmic law. The <i>Asclepius</i> explicitly presents the magician as a priest or sage whose operations are expressions of divine will and cosmic order rather than violations of natural law or impious presumption.</p>

<h2>Practical Operations and Ritual Procedures</h2>
<p>The <i>Asclepius</i> includes explicit descriptions of practical magical operations and ritual procedures. The text presents accounts of the creation of magical statues or idols consecrated through ritual to become receptacles for divine powers and to function as instruments through which celestial and divine influences can be directed toward terrestrial effects. The <i>Asclepius</i> describes Egyptian priestly practices of image magic and divine invocation, presenting these as expressions of sophisticated philosophical understanding rather than primitive superstition. The text addresses the proper timing of operations according to astrological principles, the preparation of the practitioner through spiritual discipline and purification, the use of divine names and invocations, and the relationship between the inner spiritual state of the practitioner and the efficacy of operations. The scholarly examination of theory and practice in the <i>Asclepius</i> demonstrates that the text presents practical operations as grounded in and derivative from theoretical understanding: the practitioner must first understand the cosmological principles underlying reality, then apply that understanding to direct operations toward specific ends. This integration of theory and practice is characteristic of Hermetic thought and distinguishes the Hermetic tradition from purely theoretical philosophy.</p>

<h2>Modern Interpretations and Debates</h2>
<p>Scholarly examination of the relationship between theory and practice in the <i>Asclepius</i> has generated significant debate. Some scholars interpret the <i>Asclepius</i> as presenting a genuine philosophy of magic in which practical operations are theoretically justified and philosophically grounded. Other scholars question whether the <i>Asclepius</i>'s representations of magical practice correspond to actual practices or whether the text presents an idealized philosophical representation of magic rather than a practical manual. The question of the <i>Asclepius</i>'s relationship to actual Greco-Egyptian magical and religious practice remains contested. Scholars have also debated whether the Hermetic tradition, as represented in the <i>Asclepius</i>, should be classified as magical philosophy, religious ritual, natural philosophy, or some combination of these categories. The examination of theory and practice in the <i>Asclepius</i> contributes to broader scholarly questions about the nature of magic in late antiquity, the relationship between philosophical theory and religious practice, and the ways in which Greco-Roman intellectuals understood and engaged with ritual operations and divine invocation. Contemporary scholarship continues to refine understanding of the <i>Asclepius</i> through careful textual analysis, comparative study with other late antique texts, and attention to the historical contexts within which the text was composed and read.</p>

<h2>Literature</h2>
<p>Bull, Christian H. <i>The Tradition of Hermes Trismegistus: The Egyptian Priestly Figure in the Nag Hammadi Codices and Related Literature</i>. Leiden: Brill, 2018.<br>
Copenhaver, Brian P. <i>Hermetica: The Greek Corpus Hermeticum and the Latin Asclepius</i>. Cambridge: Cambridge University Press, 1992.<br>
Fowden, Garth. <i>The Egyptian Hermes: A Historical Approach to the Late Pagan Mind</i>. Cambridge: Cambridge University Press, 1986.<br>
van den Kerchove, Anna. <i>La voie d'Hermès: Pratiques rituelles et traités hermétiques</i>. Leiden: Brill, 2012.<br>
Yates, Frances A. <i>Giordano Bruno and the Hermetic Tradition</i>. Chicago: University of Chicago Press, 1964.</p>""",

    "Circe, la virtus loci, il determinismo nel De incantationibus di Pomponazzi": """<p><i>Circe, la virtus loci, il determinismo nel De incantationibus di Pomponazzi</i> is a scholarly study examining the figure of Circe, the concept of <i>virtus loci</i> (the power or virtue inherent in place), and the question of determinism in Pietro Pomponazzi's <i>De incantationibus</i> (treatise on incantations). Pomponazzi (1462–1525) was a Renaissance Aristotelian philosopher who engaged seriously with questions of magic, astrology, and the natural basis of seemingly miraculous or supernatural phenomena. His <i>De incantationibus</i> is a sophisticated philosophical examination of the nature of magical effects, the role of natural powers and celestial influences in producing seemingly magical results, and the possibility of explaining magical phenomena through reference to natural philosophy rather than supernatural agency. The scholarly study examining Circe, <i>virtus loci</i>, and determinism in Pomponazzi's work addresses fundamental questions about Renaissance natural philosophy, the relationship between magic and science, and the degree to which Renaissance thinkers could rationally explain apparently magical phenomena. The work contributes to understanding Pomponazzi as a sophisticated philosopher who engaged seriously with magical and astrological traditions while attempting to provide naturalistic explanations for phenomena that others attributed to demonic or supernatural agency.</p>

<h2>Pomponazzi and Renaissance Natural Philosophy</h2>
<p>Pomponazzi's <i>De incantationibus</i> represents an important moment in Renaissance natural philosophy: the attempt to explain magical phenomena through reference to natural powers, astrology, and the properties of material things, rather than through appeal to demons, spirits, or divine intervention. Pomponazzi draws extensively on Aristotelian natural philosophy, on medieval discussions of astrology and planetary influence, and on Hermetic and Neoplatonic concepts of natural magic grounded in cosmic correspondence and sympathy. The figure of Circe—the mythological sorceress who transformed men into animals through magical arts—serves as a focal point for philosophical discussion: what was the true nature of Circe's power? Did she truly transform men into animals through supernatural magic, or can her legendary deeds be explained through reference to natural philosophical principles? Pomponazzi argues for the possibility of naturalistic explanation: through knowledge of occult properties of things, through careful use of drugs and poisons, and through understanding of the psychological and physiological effects of imagination, a skillful practitioner might produce effects that appear magical but are actually grounded in nature. The concept of <i>virtus loci</i>—the power or efficacy inherent in particular places—exemplifies Pomponazzi's naturalistic approach: rather than attributing remarkable phenomena occurring in certain locations to supernatural agency, Pomponazzi suggests that particular places may possess natural properties (derived from geology, climate, celestial influence, or other natural factors) that produce observable effects.</p>

<h2>Magic, Astrology, and Determinism</h2>
<p>The scholarly examination of Pomponazzi's treatment of these themes addresses the question of determinism: if magical and astrological effects are grounded in natural causes operating according to natural laws, can human freedom and moral responsibility be preserved? Pomponazzi's work engages with the broader Renaissance debate about astral determinism and human free will: to what degree are human actions determined by celestial influences? To what degree does human reason and will remain free? Pomponazzi attempts to preserve human freedom while acknowledging the genuine influence of celestial and natural powers on human affairs. His naturalistic approach to magic—explaining magical effects through reference to natural causes rather than supernatural agency—contributes to his overall philosophical project of establishing a naturalistic worldview consistent with human moral responsibility and free will. The study of <i>virtus loci</i> and determinism in Pomponazzi's work reveals the sophistication of Renaissance philosophical engagement with magic and astrology: Renaissance thinkers were not simply credulous believers in magic but rather critical philosophers attempting to develop intellectually coherent accounts of magical and astrological phenomena within naturalistic frameworks.</p>

<h2>Influence and Legacy</h2>
<p>Pomponazzi's <i>De incantationibus</i> influenced subsequent Renaissance and early modern discussions of magic, astrology, and natural philosophy. His attempt to naturalize magic—to explain magical phenomena through reference to natural causes rather than supernatural agency—contributed to the broader early modern transition toward mechanical philosophy and the scientific revolution. While Pomponazzi remained embedded in Aristotelian and astrological frameworks that would ultimately be superseded by mechanical philosophy, his insistence on naturalistic explanation and his skepticism toward supernatural agency contributed to the intellectual resources of early modernity. The scholarly study of Circe, <i>virtus loci</i>, and determinism in Pomponazzi's work contributes to understanding Renaissance natural philosophy as a sophisticated intellectual tradition engaged in serious philosophical examination of magic, astrology, and the foundations of natural knowledge. Contemporary scholarship continues to examine Pomponazzi's work as a significant moment in the history of natural philosophy and in the Renaissance engagement with magical and astrological traditions.</p>

<h2>Literature</h2>
<p>Copenhaver, Brian P. <i>Magic in Western Culture: From Antiquity to the Enlightenment</i>. Cambridge: Cambridge University Press, 2015.<br>
Hanegraaff, Wouter J. (ed.). <i>Dictionary of Gnosis and Western Esotericism</i>. Leiden: Brill, 2006.<br>
Pine, Martin L. <i>Pietro Pomponazzi: Radical Philosopher of the Renaissance</i>. Padua: Antenore, 1986.<br>
Porreca, David. <i>The Picatrix and Medieval Occult Philosophy</i>. University Park: Pennsylvania State University Press, 2016.<br>
Yates, Frances A. <i>Giordano Bruno and the Hermetic Tradition</i>. Chicago: University of Chicago Press, 1964.</p>""",

    "Review: Picatrix -- The Latin Version of the Ghayat al-Hakim (Pingree ed.)": """<p><i>Picatrix: The Latin Version of the Ghayat al-Hakim</i>, edited by David Pingree, is a critical edition of the Latin version of the <i>Ghayat al-Hakim</i> (The Goal of the Wise), a major medieval Islamic astrological and magical treatise originally composed in Arabic. The <i>Picatrix</i> (the medieval Latin name for the work, derived from the author's name, al-Qurashi or "the Qurashi") is one of the most significant astrological and magical texts of the medieval and Renaissance periods. The Arabic original, possibly composed in the tenth century, was translated into Latin in the twelfth century and became influential in medieval and Renaissance European astrological and magical circles. The work presents comprehensive astrological doctrine, accounts of the properties and influences of celestial bodies, and detailed procedures for magical operations aligned with astrological principles. Pingree's edition, based on careful collation of medieval Latin manuscripts, provides the authoritative modern text of the Latin <i>Picatrix</i>, with extensive scholarly apparatus and contextual information. The work is significant for understanding medieval Islamic astrological and magical philosophy, the transmission of Islamic learning to the Latin West, and the development of European magical traditions.</p>

<h2>Content and Astrological-Magical Doctrine</h2>
<p>The <i>Picatrix</i> presents comprehensive astrological and magical learning grounded in Hermetic cosmology and Neoplatonic philosophy. The work describes the nature and properties of the seven classical planets, their associations with metals, colors, perfumes, stones, animals, and human characteristics. The text addresses the zodiacal signs and houses, providing detailed accounts of the meanings and influences of different zodiacal positions and planetary configurations. The <i>Picatrix</i> includes extensive practical sections on the creation of talismans and magical objects inscribed with planetary and zodiacal symbols and activated through astrological timing to achieve specific effects. The work presents procedures for invoking planetary and celestial powers, for performing rituals aligned with astrological configurations, and for using astrological knowledge to direct magical operations toward desired ends. The underlying cosmology emphasizes the interconnectedness of the universe through sympathies and correspondences: celestial powers influence the sublunary realm, and knowledge of these correspondences allows the practitioner to align with and direct celestial influences. The <i>Picatrix</i> presents magic as grounded in natural philosophy: magical effects are produced through natural causes, not through violation of natural law or demonic agency, though the powers involved are understood as divine or celestial in origin.</p>

<h2>Islamic Astrological Learning and Medieval Transmission</h2>
<p>The <i>Picatrix</i> exemplifies the sophistication of Islamic astrological and magical philosophy. The Arabic original, composed in a milieu of Islamic learning that had inherited Greek astrological and magical texts and reinterpreted them within Islamic intellectual frameworks, represents a synthesis of Greek, Persian, and Indian astrological traditions with Islamic theological and philosophical concepts. The work was influenced by the astronomical and astrological learning of Islamic scholars like Al-Kindi, Abu Ma'shar, and others who had preserved and developed Greek and Persian astrological science. The translation of the <i>Picatrix</i> into Latin in the twelfth century made this sophisticated Islamic astrological learning available to Latin scholars. The <i>Picatrix</i> became one of the most influential astrological texts in medieval and Renaissance Europe, influencing the development of European astrological and magical traditions. The work's influence is evident in the extensive citations and references to the <i>Picatrix</i> by Renaissance astrologers, magicians, and philosophers. The transmission of the <i>Picatrix</i> from Islamic to Christian intellectual contexts exemplifies the broader process by which Islamic learning shaped European intellectual development in the medieval and Renaissance periods.</p>

<h2>Pingree's Edition and Modern Scholarship</h2>
<p>David Pingree's edition of the Latin <i>Picatrix</i>, published by the Warburg Institute, represents a major scholarly achievement in making a crucial medieval astrological text available in a reliable, annotated form. Pingree's work involved careful collation and analysis of medieval Latin manuscripts, establishing the textual history of the Latin translation, and providing extensive contextual information on the work's sources, influence, and significance. The edition includes detailed introductions explaining the work's astrological and philosophical contents, its place within the broader tradition of Islamic and European astrology, and its influence on Renaissance and early modern thought. Pingree's scholarship has illuminated the importance of the <i>Picatrix</i> for understanding medieval astrological and magical philosophy and has contributed substantially to modern recognition of the sophisticated character of medieval Islamic and European engagement with astrological and magical learning. Subsequent scholarship has built on the foundations laid by Pingree's edition, with scholars examining the <i>Picatrix</i>'s influence on specific Renaissance figures, analyzing its conceptual underpinnings, and situating it within broader histories of science and esotericism. The <i>Picatrix</i> has become recognized as central to understanding medieval and Renaissance astrological and magical traditions, and Pingree's edition has been indispensable for this recognition.</p>

<h2>Literature</h2>
<p>Hanegraaff, Wouter J. <i>Hermetic Spirituality and the Historical Imagination</i>. Leiden: Brill, 2022.<br>
Pingree, David (ed.). <i>Picatrix: The Latin Version of the Ghayat al-Hakim</i>. London: Warburg Institute, 1986.<br>
Porreca, David. <i>The Picatrix and Medieval Occult Philosophy</i>. University Park: Pennsylvania State University Press, 2016.<br>
Saif, Liana. <i>The Science of the Magus: Cosmology and Prophecy in the Medieval Islamic World</i>. Cambridge: Cambridge University Press, 2021.<br>
van Bladel, Kevin. <i>The Arabic Hermes: From Pagan Sage to Prophet of Science</i>. Oxford: Oxford University Press, 2009.</p>""",
}

def update_texts():
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    count = 0
    for title_search, analysis_html in TEXTS_TO_EXPAND.items():
        cursor.execute('''
            UPDATE texts
            SET analysis_html = ?, review_status = 'DRAFT'
            WHERE title LIKE ?
        ''', (analysis_html, f'%{title_search}%'))

        cursor.execute('SELECT title FROM texts WHERE title LIKE ?', (f'%{title_search}%',))
        result = cursor.fetchone()
        if result:
            print(f"[OK] Updated: {result[0]}")
            count += 1

    conn.commit()
    conn.close()
    print(f"\nTotal updated: {count} texts")
    return count

if __name__ == "__main__":
    updated = update_texts()
