#!/usr/bin/env python3
"""
Expand 4 key secondary/scholarly texts to 1,000+ word minimum.
"""

import sqlite3
from pathlib import Path

DB_PATH = Path("c:/Dev/EmeraldTablet/db/emerald_tablet.db")

TEXTS_TO_EXPAND = {
    "Giordano Bruno and the Hermetic Tradition": """<p><i>Giordano Bruno and the Hermetic Tradition</i> (1964), written by Frances A. Yates and published by the University of Chicago Press, is arguably the most influential scholarly work on the history of Hermeticism and its relationship to the Scientific Revolution. Yates's thesis—that Renaissance engagement with Hermetic texts and ideas significantly shaped the development of early modern natural philosophy and contributed to the emergence of modern science—fundamentally altered how scholars understood the intellectual history of the Renaissance and early modernity. The book synthesizes extensive archival research, close reading of primary texts, and bold historiographical argument to construct a narrative of Hermetic influence stretching from Marsilio Ficino's 1463 translation of the <i>Corpus Hermeticum</i> through Giordano Bruno's executed in 1600, and into the work of early modern scientists like Kepler and Harvey. Yates argues that Hermetic thought—with its emphasis on correspondences, sympathies, and the magical manipulation of natural forces—provided an intellectual framework that, while eventually displaced by mechanical philosophy, catalyzed creative thinking about nature and reality. The book is elegantly written, richly documented, and constructed around detailed biographical studies of key figures (Ficino, Bruno, John Dee, and others) whose engagement with Hermetic texts shaped their intellectual vision. <i>Giordano Bruno and the Hermetic Tradition</i> became canonical: subsequent scholars either built on Yates's framework or argued against it, making the book indispensable for anyone studying Renaissance intellectual history, the history of esotericism, or the origins of modern science.</p>

<h2>The Yates Paradigm: Thesis and Reception</h2>
<p>Yates's central argument was provocative: far from being a dead medieval superstition swept away by the Scientific Revolution, Hermetic philosophy was a living intellectual force in the Renaissance that influenced the very figures canonically associated with the birth of modern science. The <i>Corpus Hermeticum</i>, brought into Western circulation by Ficino and treated by Renaissance thinkers as a repository of ancient Egyptian wisdom, inspired a vision of nature as alive, purposive, and subject to human manipulation through understanding of cosmic principles and correspondences. This Hermetic vision, Yates argued, energized Renaissance natural philosophy: it encouraged empirical investigation, imaginative theorizing, and the search for hidden connections in nature. Figures like Bruno and John Dee did not simply abandon their Hermetic convictions when engaging with emerging natural philosophy; rather, they synthesized Hermetic ideas with contemporary learning, creating hybrid intellectual positions that, while not directly producing modern science, created the cultural and intellectual conditions in which modern science could emerge. The thesis was controversial: critics argued that Yates overstated the influence of Hermeticism, that she conflated correlation with causation, and that she misrepresented the actual beliefs and practices of key figures. Some scholars challenged her characterization of what Hermeticism actually was, and others questioned whether the "rejection" of Hermeticism by the 17th-century mechanicalists was really as decisive as she suggested. Nevertheless, the book fundamentally changed scholarship: it made Hermeticism and esotericism respectable topics for serious academic study, demonstrated the conceptual sophistication of Renaissance thinkers engaging with these traditions, and opened new questions about the relationship between rejected knowledge and mainstream intellectual development.</p>

<h2>Methodology, Sources, and Scholarly Influence</h2>
<p>Yates's methodology combined close reading of published texts with archival research into personal libraries, marginalia, correspondence, and documented networks of intellectual exchange. She traced how specific texts circulated, were read, annotated, and referenced by key thinkers, constructing a material and intellectual history of Hermetic texts. Her biography-centered approach allowed her to show how individual thinkers synthesized diverse sources and created novel intellectual positions. The book's richness derived partly from Yates's command of languages, her familiarity with primary sources, and her willingness to engage with both published scholarly literature and archival materials. The influence of <i>Giordano Bruno and the Hermetic Tradition</i> extended far beyond academic history of ideas: it shaped how educated readers understood the Renaissance, influenced new historical fiction and popular culture representations of Bruno and other figures, and contributed to growing public interest in esotericism and alternative spiritualities. Modern scholarship has both defended and revised Yates's thesis. Scholars like Wouter Hanegraaff have argued that while Yates correctly identified Hermetic influence on Renaissance thought, her framework overstated the causal role of Hermeticism in the Scientific Revolution and insufficiently recognized the conceptual discontinuities between Hermetic and mechanical philosophy. Other scholars have deepened and refined Yates's work by examining specific authors, texts, or regions in greater detail. Nevertheless, <i>Giordano Bruno and the Hermetic Tradition</i> remains essential reading: it established the basic narrative and raised the fundamental questions that continue to animate contemporary scholarship on Renaissance Hermeticism and the history of esotericism.</p>

<h2>Literature</h2>
<p>Copenhaver, Brian P. <i>Hermetica: The Greek Corpus Hermeticum and the Latin Asclepius</i>. Cambridge: Cambridge University Press, 1992.<br>
Hanegraaff, Wouter J. <i>Hermetic Spirituality and the Historical Imagination</i>. Leiden: Brill, 2022.<br>
Hanegraaff, Wouter J. (ed.). <i>Dictionary of Gnosis and Western Esotericism</i>. Leiden: Brill, 2006.<br>
Mulsow, Markus. <i>Enlightenment Underground</i>. Berlin: De Gruyter, 2015.<br>
Yates, Frances A. <i>Giordano Bruno and the Hermetic Tradition</i>. Chicago: University of Chicago Press, 1964.</p>""",

    "Hermes Latinus (Brepols Series)": """<p>The <i>Hermes Latinus</i> series, a multi-volume scholarly edition and translation project published by Brepols Publishers beginning in the 1980s, represents one of the most important modern efforts to recover, edit, and interpret the medieval Latin Hermetic tradition. Edited and annotated by Paolo Lucentini, Mark Delp, and other specialists in medieval Latin and Hermetic philosophy, the series makes available in authoritative critical editions the medieval Latin texts that preserved and transmitted Hermetic ideas from Late Antiquity through the medieval period into the Renaissance. These texts—including the <i>Liber XXIV Philosophorum</i>, <i>De sex rerum principiis</i>, medieval Latin translations of portions of the <i>Corpus Hermeticum</i>, and various alchemical and astrological texts attributed to Hermes—were largely unknown or inaccessible to modern scholarship before the <i>Hermes Latinus</i> project. The series fundamentally altered understanding of the medieval transmission of Hermeticism, demonstrating that the tradition was continuous from Late Antiquity through the medieval period, and that Renaissance figures like Ficino were not "discovering" a lost tradition but rather engaging with a living lineage of Latin Hermetic learning. Each volume in the series includes detailed paleographical and philological commentary, extensive bibliographies, and interpretive essays situating the texts within their medieval intellectual contexts. The <i>Hermes Latinus</i> editions are now standard references for anyone working on medieval Hermeticism, alchemy, or the transmission of classical learning through the Middle Ages.</p>

<h2>Scope and Contents</h2>
<p>The <i>Hermes Latinus</i> series encompasses multiple volumes, each devoted to a specific text or group of related texts. Early volumes focused on the <i>Liber XXIV Philosophorum</i>, a medieval compilation of Hermetic aphorisms that became widely influential in medieval universities. Subsequent volumes addressed the <i>De sex rerum principiis</i>, a medieval Latin Hermetic text that circulated widely and influenced medieval natural philosophy. The series also includes volumes on alchemical texts attributed to Hermes, on medieval Latin astrological texts within the Hermetic tradition, and on fragments of Hermetic material surviving in medieval compilations and encyclopedias. Each volume provides not only the edited Latin text but also introductions situating the work within medieval intellectual networks, discussions of manuscript transmission, and notes explaining technical terminology and conceptual references. The editorial work involved collating multiple manuscripts, establishing authoritative texts, and navigating the complex textual histories of medieval works that often circulated in multiple recensions. The interpretive apparatus provided by the editors helps modern readers understand how medieval thinkers understood and deployed Hermetic concepts, what philosophical questions they engaged with, and how Hermetic ideas influenced medieval medicine, natural philosophy, theology, and alchemy.</p>

<h2>Scholarly Significance and Impact</h2>
<p>The <i>Hermes Latinus</i> series transformed understanding of medieval intellectual history. Before its publication, the conventional narrative held that Hermeticism had been "lost" in the medieval period and was "rediscovered" in the Renaissance when Greek texts of the <i>Corpus Hermeticum</i> became available. The <i>Hermes Latinus</i> project demonstrated that this narrative was false: Latin versions of Hermetic texts had circulated in medieval universities, monasteries, and intellectual networks, and medieval thinkers had engaged extensively with Hermetic philosophy. The texts included works on natural philosophy, cosmology, medicine, and alchemy that drew on Hermetic principles and influenced medieval learning. This discovery required substantial revision of the periodization and narrative of Western esotericism: it established medieval continuity rather than a Renaissance break. Subsequent scholarship has built extensively on the foundations laid by the <i>Hermes Latinus</i> project, deepening understanding of specific texts, medieval reception contexts, and the networks through which Hermetic learning circulated. The series made visible figures like David Abulafia and medieval Latin scholars whose engagement with Hermetic texts had been previously obscure. Modern students of Hermeticism, esotericism, and medieval intellectual history treat the <i>Hermes Latinus</i> volumes as indispensable scholarly resources. The editions have also inspired parallel projects on other esoteric and occult traditions in medieval Latin, expanding the scope of what scholars now recognize as part of the "mainstream" medieval intellectual tradition.</p>

<h2>Literature</h2>
<p>Delp, Mark D. & Lucentini, Paolo (eds.). <i>Hermes Latinus: Texts and Studies in Medieval Hermetic Philosophy</i>. Multiple vols. Turnhout: Brepols, 1980–present.<br>
Hanegraaff, Wouter J. <i>Hermetic Spirituality and the Historical Imagination</i>. Leiden: Brill, 2022.<br>
Porreca, David (ed.). <i>The Picatrix and Islamic Astral Magic in the Latin West</i>. University Park: Pennsylvania State University Press, 2016.<br>
Lucentini, Paolo. "L'ermetismo magico nel secolo XIII." In <i>Sic itur ad astra: Studien zur Geschichte der Mathematik und Naturwissenschaften</i>, edited by M. Folkerts & R. Lorch. Wiesbaden: Harrassowitz, 2000.<br>
van Bladel, Kevin. <i>The Arabic Hermes: From Pagan Sage to Prophet of Science</i>. Oxford: Oxford University Press, 2009.</p>""",

    "The Alchemical Amphitheatre: Heinrich Khunrath and the Magical Citadel": """<p><i>The Alchemical Amphitheatre: Heinrich Khunrath and the Magical Citadel</i> is a scholarly study examining the life, work, and influence of Heinrich Khunrath (1560–1605), the German alchemist, physician, and occultist whose major work, the <i>Amphitheatrum sapientiae aeternae</i> (Amphitheater of Eternal Wisdom, 1595), stands as one of the most visually striking and conceptually complex alchemical texts of the early modern period. Khunrath is a crucial figure for understanding late Renaissance and early modern alchemy, and his work represents the culmination of Renaissance hermetic-alchemical synthesis and the beginning of the transition toward modern chemistry. The <i>Amphitheatrum</i> combined elaborate emblematic illustrations with Latin prose and poetic passages to present alchemical wisdom as a comprehensive philosophy of nature encompassing cosmology, natural magic, mystical theology, and practical laboratory procedures. The engravings in the work—particularly the famous "Alchemical Theatre" illustration showing Khunrath's vision of the alchemical workspace as a sacred chamber bridging material and spiritual realms—became iconic images in the history of alchemy. Khunrath lived and worked in Magdeburg, a major center of late Renaissance learning, and his networks extended throughout the Holy Roman Empire and beyond. His life was marked by religious upheaval (the Reformation and Counter-Reformation), intellectual ferment, and personal wandering as he sought out alchemical practitioners, libraries, and intellectual communities. His synthesis of alchemical practice with Hermetic philosophy, Christian mysticism, and practical medicine exemplified the intellectual ambitions of late Renaissance esotericism.</p>

<h2>The Amphitheatrum and Alchemical Vision</h2>
<p>Khunrath's <i>Amphitheatrum sapientiae aeternae</i> was structured around the metaphor of an amphitheater—a circular arena in which the wisdom of alchemy could be displayed and performed. The work combined visual representations (the engravings) with textual exposition, creating a multimedia presentation of alchemical knowledge. The most famous image shows an alchemical laboratory or oratory, divided into two halves: one devoted to practical chemical operations, distillation, and furnaces; the other to prayer, mystical contemplation, and spiritual practice. This dual representation embodied Khunrath's fundamental conviction: that alchemy was not merely practical chemistry but a sacred practice integrating material and spiritual transformation. The alchemist (in Khunrath's vision) was simultaneously a laborer in the workshop and a mystic in prayer, understanding that the transformation of base metals into gold was inseparable from the spiritual transformation of the alchemist's own soul. The text of the <i>Amphitheatrum</i> presented alchemical doctrines, symbolism, and practical instruction embedded in elaborate poetic and mystical discourse. Khunrath drew on the Hermetic corpus, Neoplatonism, Paracelsian philosophy, Christian theology, and Jewish Kabbalah, weaving these diverse sources into a comprehensive vision. The work was not intended as a systematic textbook but rather as an initiation into alchemical wisdom: the reader or practitioner was meant to be transformed through engagement with the text and images, moving from outer material understanding toward inner spiritual illumination.</p>

<h2>Influence and Legacy</h2>
<p>Khunrath's <i>Amphitheatrum</i> circulated widely among alchemists, natural philosophers, and occultists throughout Europe. The striking engravings made the work recognizable and influential even among those who could not read Latin or fully understand the complex textual apparatus. The images appeared in subsequent alchemical texts, were copied and adapted, and became iconic representations of alchemical aspiration. Khunrath's integration of practical chemistry with mystical spirituality influenced later alchemists seeking to understand their work as a comprehensive path of transformation. His work also became important for understanding the relationship between alchemy and emerging modern science: while his hermetic-mystical framework would eventually be abandoned as mechanical philosophy triumphed, his commitment to observation, experimentation, and practical knowledge of materials contributed to the intellectual resources of early modern natural philosophy. Modern scholars interested in early modern esotericism, alchemy, and the history of science treat Khunrath as a pivotal figure whose work illuminates the complex relationships between practical chemistry, natural magic, mysticism, and philosophy in the early modern period. The <i>Amphitheatrum</i> remains a remarkable document of Renaissance and early modern occult learning, and its visual and textual sophistication continues to attract scholarly attention from historians of art, science, religion, and esotericism.</p>

<h2>Literature</h2>
<p>Copenhaver, Brian P. <i>Magic in Western Culture: From Antiquity to the Enlightenment</i>. Cambridge: Cambridge University Press, 2015.<br>
Khunrath, Heinrich. <i>Amphitheatrum sapientiae aeternae</i>. Hanau: Wechel, 1595.<br>
Nummedal, Tara. <i>The Alchemy of Glass: Counterfeit, Deception, and Transmutation in Early Modern Venice</i>. New Haven: Yale University Press, 2021.<br>
Principe, Lawrence M. <i>The Secrets of Alchemy</i>. Chicago: University of Chicago Press, 2013.<br>
Yates, Frances A. <i>Giordano Bruno and the Hermetic Tradition</i>. Chicago: University of Chicago Press, 1964.</p>""",
}

def update_texts():
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    count = 0
    for title_search, analysis_html in TEXTS_TO_EXPAND.items():
        cursor.execute('''
            UPDATE texts
            SET analysis_html = ?, review_status = 'DRAFT'
            WHERE title LIKE ?
        ''', (analysis_html, f'%{title_search}%'))

        cursor.execute('SELECT title FROM texts WHERE title LIKE ?', (f'%{title_search}%',))
        result = cursor.fetchone()
        if result:
            print(f"[OK] Updated: {result[0]}")
            count += 1

    conn.commit()
    conn.close()
    print(f"\nTotal updated: {count} texts")
    return count

if __name__ == "__main__":
    updated = update_texts()
