"""
write_concepts_batch1.py — Alchemical Actor Terms
Idempotent: writes full definition_long and definition_short for:
  - the_way_of_hermes
  - chrysopoeia
  - solve_et_coagula
  - lapis_philosophorum
"""
import sqlite3

DB_PATH = r"C:\Dev\EmeraldTablet\db\emerald_tablet.db"

ENTRIES = {}

# ---------------------------------------------------------------------------
# 1. THE WAY OF HERMES
# ---------------------------------------------------------------------------
ENTRIES["the_way_of_hermes"] = {
    "definition_short": (
        "The Way of Hermes (Greek: hodos) is an Actor Term designating the distinctive Hermetic path "
        "of spiritual initiation and contemplative ascent described in the philosophical treatises of the "
        "Corpus Hermeticum. It combines rigorous intellectual training with visionary experience and "
        "ethical transformation, culminating in the soul's return to its divine source. Garth Fowden "
        "introduced the phrase as an analytical framework in The Egyptian Hermes (1986), and Anna van "
        "den Kerchove's La voie d'Hermes (2012) has since provided the most detailed ritual analysis "
        "of its practice."
    ),
    "definition_long": """<p>The Way of Hermes — rendered in Greek as <i>hodos</i> — is an Actor Term designating the spiritual and philosophical path of initiation described across the philosophical Hermetica of Late Antiquity, particularly those collected in the <i>Corpus Hermeticum</i> (hereafter CH). As an Actor Term in the sense developed by Wouter J. Hanegraaff, it refers to a concept genuinely operative among historical practitioners who inhabited the Hermetic textual tradition, not a retrospective scholarly construct. The path involves a progressive transformation of the knower through intellectual discipline, visionary experience, and ethical practice — a process that culminates in the soul's re-ascent through the planetary spheres to union with the supreme divine principle. Garth Fowden gave the phrase its canonical modern scholarly form in <i>The Egyptian Hermes: A Historical Approach to the Late Pagan Mind</i> (1986), where he argued that the philosophical Hermetica collectively describe a coherent religious path rooted in the specific cultural and intellectual milieu of Roman Egypt. Subsequent scholarship by Anna van den Kerchove, Christian H. Bull, and Wouter J. Hanegraaff has substantially deepened and in certain respects revised Fowden's account, but his foundational insight — that the Hermetic texts document a genuine religious practice rather than merely philosophical speculation — has become the consensus framework of the field.</p>

<h2>Historical Usage</h2>
<p>The language of a "way" or "path" pervades the philosophical Hermetica from their earliest attested forms. In <i>Poimandres</i> (CH I), the revelatory dialogue that opens the <i>Corpus Hermeticum</i>, the divine Poimandres appears to the narrator in a vision and promises to teach him "what you wish to learn and what you long to hear." The encounter initiates a process of cosmogonic revelation followed by the instruction: "Let the man endowed with mind mark, recognize, and know himself." The entire tractate maps a path from ignorance through gnosis to the soul's liberation from material bonds. CH IV, <i>The Mixing Bowl</i> (<i>Krater</i>), presents the path in terms of immersion in a divine vessel of mind (<i>nous</i>) sent down by God: those who receive the message of Hermes and "hurry back to gnosis" are "filled with mind." CH XIII, the treatise on regeneration (<i>palingenesia</i>), provides the most detailed account of the initiatory path as a structured transformation of the soul's cognitive and affective constitution, in which the twelve penalties (<i>timoriai</i>) of matter are progressively replaced by the ten divine powers of the decad. The narrator's exclamation — "I have been born again in mind!" — marks the completion of the Way.</p>

<p>The Egyptian documentary context matters enormously. Christian H. Bull's <i>The Tradition of Hermes Trismegistus</i> (2018) argues that the philosophical Hermetica were composed in priestly circles in Roman Egypt, most likely in the second and third centuries CE, as a synthesis of Egyptian priestly wisdom with Greek philosophical vocabulary. On this reading, the Way of Hermes is not simply a Platonic philosophical exercise translated into religious terminology but a specifically Egyptian priestly path — the "way of the god" (<i>medu netjer</i>) reformulated in the Platonic idiom of the soul's ascent. The address formulae, the teacher-student dialogue structure, and the vocabulary of secrecy and initiation all point toward an institutional setting within Egyptian temple culture. Fowden, working with somewhat different emphases, stressed the continuity between the Hermetic "way" and the broader Late Antique quest for personal salvation through philosophical practice, locating it within the same cultural milieu as Platonism, Gnosticism, and the nascent monastic movements of Egypt.</p>

<p>The way has a strongly contemplative and intellectual character, but it also involves ritual and communal dimensions. Anna van den Kerchove's <i>La voie d'Hermès: Pratiques rituelles et traités hermétiques</i> (2012) subjected the Hermetic texts to detailed ritual analysis, demonstrating that the "way" as described in the Hermetica involves not only intellectual contemplation but specific ritual practices — hymnic prayer, contemplation of divine images, ritual washing, and the transmission of wisdom within teacher-student lineages. The hymns preserved in CH III, CH V, and the <i>Prayer of Thanksgiving</i> (<a href="../concepts/corpus_hermeticum.html">Corpus Hermeticum</a>) function as integral liturgical components of the path rather than merely decorative additions.</p>

<h2>Scholarly Significance</h2>
<p>Fowden's identification of a coherent "way of Hermes" within the philosophical Hermetica was, at the time of its formulation in 1986, a deliberately polemical counter-move against two dominant positions in the field. The first was the then-prevailing view, associated with A.-J. Festugière's monumental <i>La Révélation d'Hermès Trismégiste</i> (4 vols., 1944–1954), that the philosophical Hermetica were essentially a popular Platonism with a religious gloss — interesting as cultural documents but lacking philosophical originality and constituting no genuine religious path. Fowden argued, against Festugière, that the Hermetica are best understood as documents of a real religious practice with serious intellectual content. The second target was the tendency — visible in popular treatments and in certain strands of the history of religion — to treat the Hermetic texts as a sourcebook for timeless mystical truths, stripped of their historical context.</p>

<p>Hanegraaff's <i>Hermetic Spirituality and the Historical Imagination</i> (2022) represents the most sophisticated recent engagement with the concept. Hanegraaff argues that the Way of Hermes involves what he calls "altered states of knowledge" — not merely a cognitive reorientation but a radical transformation of the knowing subject, in which the practitioner comes to perceive reality from the perspective of the divine <i>nous</i> rather than from the perspective of the embodied, materially conditioned ego. This is a phenomenologically rich claim that goes beyond earlier characterizations of Hermetic gnosis as simply "intellectual knowledge of God." Hanegraaff reads CH I, XIII, and related texts as documenting experiences of cognitive transformation that are not reducible to either mystical union (in the Christian sense) or to discursive philosophical argument.</p>

<p>The question of the Way's relationship to Egyptian religion has been the most contested issue in recent scholarship. Bull's priestly-school hypothesis has not gone unchallenged — Roelof van den Broek and others have maintained that the Hermetic milieu was more broadly Greco-Egyptian and less specifically tied to institutional temple culture. Kevin van Bladel's <i>The Arabic Hermes</i> (2009) approaches the tradition from a different angle, tracing the subsequent transformation of the Hermetic figure and his "way" in the Islamic world, where Hermes became the prophet Idris and his path a form of prophetic wisdom. The result is a picture of a path that was continuously transformed in transmission without losing its core association with intellectual and spiritual ascent.</p>

<h2>Transmission and Variant Forms</h2>
<p>The Greek <i>hodos</i> (ὁδός) is the standard term for "road" or "way" in classical and Hellenistic Greek, carrying both literal and metaphorical valences. In philosophical usage it follows the well-established tradition of Plato's <i>Republic</i> (the ascent from the cave) and the Pythagorean "way of life" (<i>bios</i>). The Hermetic texts also use related vocabulary: <i>tropos</i> (manner, turn), <i>agoge</i> (leading), and terms for initiation (<i>myesis</i>, <i>teleiosis</i>) drawn from the mystery-religion vocabulary of the period.</p>

<p>The Latin transmission of the Way of Hermes concept is mediated primarily through the <i>Asclepius</i> — the Latin version of the Greek <i>Perfect Discourse</i> preserved in the corpus of Apuleius — and through the citations of Lactantius, Augustine, and other Latin Fathers who quoted Hermetic material extensively, often polemically. The medieval Latin reception, documented by Paolo Lucentini, David Porreca, and others, transformed the Way into a form of philosophical theology focused on the knowledge of God and the structure of the cosmos, largely stripped of the ritual and initiatory dimensions visible in the Greek texts. The rediscovery of the Greek <i>Corpus Hermeticum</i> by Ficino in 1463 and his rapid translation of the first fourteen tractates (the <i>Pimander</i>, completed 1463) restored something of the original contemplative depth, though filtered through Ficino's Neoplatonic Christianity.</p>

<p>In the Arabic tradition, as van Bladel documents, Hermes' "way" became a prophetic wisdom communicated through revelation (<i>wahy</i>) rather than philosophical initiation, harmonizing with Islamic prophetology. The <i>Picatrix</i> (<i>Ghayat al-Hakim</i>) and related texts preserve a more practical and <a href="../concepts/astral_magic.html">astral-magical</a> interpretation of the Hermetic path, focused on the manipulation of celestial correspondences rather than contemplative ascent.</p>

<h2>Related Concepts</h2>
<p>The Way of Hermes is inseparable from the concept of <a href="../concepts/gnosis.html"><i>gnosis</i></a>, which names the specific form of knowledge — transformative, experiential, and intellectually rigorous — that the Way cultivates. The path is mediated through the divine <a href="../concepts/nous.html"><i>nous</i></a>, the intellect or mind that descends from the supreme God and whose restoration to its source constitutes the goal of Hermetic practice. The concept of <a href="../concepts/palingenesia.html"><i>palingenesia</i></a> — regeneration or rebirth — names the central transformation undergone by the practitioner at the culmination of the Way, as described most fully in CH XIII. The initiatory context links it closely to <a href="../concepts/theurgy.html">theurgy</a>, the ritual practice of ascending to the divine through sacred acts, though the Hermetic texts maintain their own distinctive vocabulary and institutional setting separate from the Iamblichan theurgical tradition.</p>

<h2>Literature</h2>
<p>Fowden, Garth. <i>The Egyptian Hermes: A Historical Approach to the Late Pagan Mind</i>. Cambridge: Cambridge University Press, 1986.</p>
<p>Van den Kerchove, Anna. <i>La voie d'Hermès: Pratiques rituelles et traités hermétiques</i>. Turnhout: Brepols, 2012.</p>
<p>Bull, Christian H. <i>The Tradition of Hermes Trismegistus: The Egyptian Priestly Figure as a Teacher of Hellenized Wisdom</i>. Leiden: Brill, 2018.</p>
<p>Hanegraaff, Wouter J. <i>Hermetic Spirituality and the Historical Imagination</i>. Oxford: Oxford University Press, 2022.</p>
<p>Copenhaver, Brian P. (trans.). <i>Hermetica: The Greek Corpus Hermeticum and the Latin Asclepius in a New English Translation</i>. Cambridge: Cambridge University Press, 1992.</p>
<p>Festugière, André-Jean. <i>La Révélation d'Hermès Trismégiste</i>. 4 vols. Paris: Gabalda, 1944–1954.</p>
<p>Van Bladel, Kevin. <i>The Arabic Hermes: From Pagan Sage to Prophet of Science</i>. Oxford: Oxford University Press, 2009.</p>
<p>Mahé, Jean-Pierre. <i>Hermès en Haute-Égypte</i>. 2 vols. Quebec: Presses de l'Université Laval, 1978–1982.</p>
<p>Litwa, M. David (trans.). <i>Hermetica II: The Excerpts of Stobaeus, Papyrus Fragments, and Ancient Testimonies in an English Translation with Notes and Introduction</i>. Cambridge: Cambridge University Press, 2018.</p>
<p>Hanegraaff, Wouter J. (ed.). <i>Dictionary of Gnosis and Western Esotericism</i>. 2 vols. Leiden: Brill, 2006.</p>"""
}

# ---------------------------------------------------------------------------
# 2. CHRYSOPOEIA
# ---------------------------------------------------------------------------
ENTRIES["chrysopoeia"] = {
    "definition_short": (
        "Chrysopoeia (Greek: chrysopoiia, 'gold-making') is an Actor Term designating the alchemical "
        "practice of transmuting base metals into gold through chemical and philosophical operations. "
        "Attested from the earliest Greek alchemical papyri (c. 3rd century CE), it was distinguished "
        "from argyropoeia (silver-making) and from iatrochemistry. Zosimos of Panopolis is its "
        "foundational ancient theorist. Modern scholarship — above all Lawrence Principe's The Secrets "
        "of Alchemy (2013) — has insisted on reading chrysopoeia as a genuine practical discipline "
        "rather than merely a spiritual allegory."
    ),
    "definition_long": """<p>Chrysopoeia (Greek: <i>chrysopoiia</i>, from <i>chrysos</i>, "gold," and <i>poiein</i>, "to make") is an Actor Term designating the alchemical pursuit of gold-making — the transmutation of base metals, typically lead or copper, into gold through a sequence of chemical operations informed by philosophical principles concerning the nature of matter, the unity of substance, and the perfective power of fire. As an Actor Term in the Hanegraaffian sense, it names a concept and practice used by historical alchemical practitioners themselves, not a retrospective scholarly category. Chrysopoeia is attested in the earliest surviving Greek alchemical literature — the corpus of Greek alchemical manuscripts collected and edited by Marcellin Berthelot and Charles-Émile Ruelle in <i>Collection des anciens alchimistes grecs</i> (1887–1888) — and it sustained an unbroken textual and practical tradition from the Alexandrian workshops of the Roman imperial period through the Islamic chemical sciences (<i>kimiya</i>) and into the Latin West of the high medieval and Renaissance periods. Its most significant ancient theorist was Zosimos of Panopolis (fl. c. 300 CE), whose surviving writings — preserved in Byzantine manuscript collections — combine detailed laboratory instruction with visionary allegory and philosophical reflection in a way that makes the spiritual and practical dimensions of chrysopoeia inseparable.</p>

<h2>Historical Usage</h2>
<p>The documentary record of chrysopoeia begins with the Greek alchemical papyri of Egypt, notably the <i>Leiden Papyrus X</i> and the <i>Stockholm Papyrus</i> (both c. 3rd–4th century CE), which contain practical recipes for dyeing metals to resemble gold and silver (<i>diplosis</i>, doubling). These texts are not yet the philosophical chrysopoeia of Zosimos but belong to the artisan tradition of metal-working and dyeing that preceded the fully theorized alchemical practice. The crucial figure in the transition is Zosimos of Panopolis (modern Akhmim, Upper Egypt), whose <i>Cheirokmeta</i> (Things Made by Hand) — a vast alchemical encyclopedia, of which substantial excerpts survive — theorizes chrysopoeia as the practical application of a philosophical understanding of matter's unity. For Zosimos, following the Stoic concept of the <i>pneuma</i> that pervades all things, all metals share a single underlying substance (the <i>divine water</i> or <i>philosophical mercury</i>) that can be worked into its perfect gold form through the action of fire, sulfur, and spirit.</p>

<p>In Zosimos's famous visionary narrative, the "Visions" (preserved in the Syrian ms. tradition and in Byzantine excerpts), the alchemical operations are allegorized as processes of death and resurrection: the base metal, tortured by fire, is killed and reborn as a purified, luminous substance. This visionary register does not replace the practical but accompanies it — chrysopoeia is simultaneously a laboratory practice and a philosophical contemplation of matter's capacity for perfection. The Arabic transmission, documented by Kevin van Bladel and Seyyed Hossein Nasr, preserved the Zosimean corpus and added to it the vast chemical encyclopedias of Jabir ibn Hayyan (8th–9th century CE), whose system of sulfur-mercury theory became the standard theoretical framework for chrysopoeia in both Islamic and Latin alchemy. Jabir's <i>sulfur-mercury theory</i> — the doctrine that all metals are generated from two principles, a burning principle (sulfur) and a mercurial principle — provided chrysopoeia with a coherent natural-philosophical foundation within Aristotelian matter theory.</p>

<p>In the Latin West, the theoretical framework was further developed by pseudo-Geber (probably the Spanish Franciscan Paul of Taranto, fl. c. 1300), whose <i>Summa perfectionis magisterii</i> is the most rigorous Latin alchemical text of the medieval period. The Lullian alchemical corpus (attributed to Ramon Lull but almost entirely post-Lullian, as Michela Pereira's critical work established) extended chrysopoeia into a vast theoretical and practical literature. Paracelsus (Theophrastus Bombastus von Hohenheim, 1493–1541) partially redirected the alchemical tradition away from chrysopoeia and toward <i>iatrochemistry</i> (medicinal chemistry), but he did not abandon gold-making theory altogether — his <i>tria prima</i> system of salt, sulfur, and mercury was applied to chrysopoeia as well as to medicine. The 17th-century debates among Robert Boyle, Georg Starkey (Eirenaeus Philalethes), and Isaac Newton mark the final period of serious engagement with chrysopoeia within a natural-philosophical framework before the Chemical Revolution.</p>

<h2>Scholarly Significance</h2>
<p>The modern historiography of chrysopoeia has been defined above all by the tension between two interpretive traditions. The first, associated with Carl Gustav Jung's <i>Psychology and Alchemy</i> (1944) and <i>Mysterium Coniunctionis</i> (1956), reads chrysopoeia as essentially a spiritual and psychological practice — a projection of unconscious processes of individuation onto chemical operations. Jung's framework had enormous cultural influence and shaped a generation of popular and semi-scholarly treatments of alchemy. The second tradition, associated with Lawrence M. Principe, William R. Newman, and Barbara Obrist, insists on recovering the genuine practical and theoretical content of chrysopoeia as a historical discipline. Principe's <i>The Secrets of Alchemy</i> (2013) is the most accessible statement of this position: Principe argues, with detailed laboratory reconstructions, that alchemists were engaged in real chemical operations with identifiable outcomes, operating within a coherent — if incorrect — theory of matter, and that the Jungian "spiritual alchemy" interpretation is largely a modern projection.</p>

<p>Newman and Principe's <i>Alchemy Tried in the Fire: Starkey, Boyle, and the Fate of Helmontian Chymistry</i> (2002) demonstrates through archival work that figures like George Starkey (writing as Eirenaeus Philalethes) conducted serious experimental chemistry aimed at chrysopoeia and that their work influenced Robert Boyle's development of experimental chemistry. This revisionist scholarship has substantially rehabilitated chrysopoeia as a serious intellectual and practical tradition. Michela Pereira's <i>The Alchemical Corpus Attributed to Raymond Lull</i> (1989) established the textual criticism of the pseudo-Lullian chrysopoietic corpus. More recently, Matteo Martelli's critical edition of Zosimos in the Budé series and Jennifer Rampling's work on English alchemy have extended the historical reconstruction of chrysopoeia into new archival territory.</p>

<h2>Transmission and Variant Forms</h2>
<p>The Arabic transmission of chrysopoeia proceeded through two main channels: the translation of Greek alchemical texts in Baghdad's <i>Bayt al-Hikma</i> (House of Wisdom) under the Abbasid caliphs (8th–9th century CE), and the independent development of Islamic chemistry by Jabir ibn Hayyan and the Jabirian corpus. The Arabic term <i>kimiya</i> — from which the European "alchemy" derives — covers the full range of transformative chemical practice including chrysopoeia. The Latin reception of Arabic alchemy, primarily through the Toledo translation movement of the 12th century (Robert of Chester's 1144 translation of <i>Liber de compositione alchemiae</i> being the first Latin alchemical text), brought chrysopoeia into the European university curriculum as a branch of natural philosophy. The Latin technical vocabulary — <i>lapis philosophorum</i>, <i>elixir</i> (from Arabic <i>al-iksir</i>), <i>tinctura</i>, <i>sublimatio</i> — reflects this Arabic mediation. By the 15th century, chrysopoeia had developed an elaborate allegorical literature in which the operations were described in the language of marriage, death, resurrection, and kingship — the <i>Rosarium philosophorum</i> (1550) being the canonical example of this genre.</p>

<h2>Related Concepts</h2>
<p>Chrysopoeia is directly linked to the pursuit of the <a href="../concepts/lapis_philosophorum.html"><i>Lapis Philosophorum</i></a> — the Philosopher's Stone — conceived as the agent whose application to base metals produces the transmutation. The fundamental alchemical maxim <a href="../concepts/solve_et_coagula.html"><i>solve et coagula</i></a> describes the operative logic of chrysopoeia: the dissolution of the base metal's form and the coagulation of the purified substance into its gold form. The <i>tria prima</i> of <a href="../concepts/tria_prima.html">Paracelsus</a> — salt, sulfur, and mercury as the three principles of all matter — provided the theoretical basis for a reformed chrysopoeia in the 16th century. The broader alchemical cosmology presupposes the <a href="../concepts/macrocosm_microcosm.html">macrocosm-microcosm</a> correspondence: gold is the perfect metal because it corresponds to the sun, the most perfect celestial body, and the operations of chrysopoeia reproduce in the laboratory the perfective processes of nature.</p>

<h2>Literature</h2>
<p>Berthelot, Marcellin and Charles-Émile Ruelle. <i>Collection des anciens alchimistes grecs</i>. 3 vols. Paris: Steinheil, 1887–1888.</p>
<p>Principe, Lawrence M. <i>The Secrets of Alchemy</i>. Chicago: University of Chicago Press, 2013.</p>
<p>Newman, William R. and Lawrence M. Principe. <i>Alchemy Tried in the Fire: Starkey, Boyle, and the Fate of Helmontian Chymistry</i>. Chicago: University of Chicago Press, 2002.</p>
<p>Pereira, Michela. <i>The Alchemical Corpus Attributed to Raymond Lull</i>. London: Warburg Institute, 1989.</p>
<p>Jung, C. G. <i>Psychology and Alchemy</i>. Translated by R. F. C. Hull. London: Routledge, 1944.</p>
<p>Van Bladel, Kevin. <i>The Arabic Hermes: From Pagan Sage to Prophet of Science</i>. Oxford: Oxford University Press, 2009.</p>
<p>Martelli, Matteo (ed. and trans.). <i>The Four Books of Pseudo-Democritus</i>. Leeds: Maney Publishing, 2013.</p>
<p>Linden, Stanton J. (ed.). <i>The Alchemy Reader: From Hermes Trismegistus to Isaac Newton</i>. Cambridge: Cambridge University Press, 2003.</p>
<p>Moran, Bruce T. <i>Distilling Knowledge: Alchemy, Chemistry, and the Scientific Revolution</i>. Cambridge: Harvard University Press, 2005.</p>
<p>Rampling, Jennifer M. <i>The Experimental Fire: Inventing English Alchemy, 1300–1700</i>. Chicago: University of Chicago Press, 2020.</p>"""
}

# ---------------------------------------------------------------------------
# 3. SOLVE ET COAGULA
# ---------------------------------------------------------------------------
ENTRIES["solve_et_coagula"] = {
    "definition_short": (
        "Solve et coagula (Latin: 'dissolve and coagulate') is an Actor Term designating the fundamental "
        "paired operations of Western alchemy — the dissolution of a substance into its constituent "
        "principles and their subsequent reconsolidation in a purified, elevated form. The maxim "
        "encapsulates the cyclic logic of the Great Work: matter must be unmade before it can be "
        "perfected. Operating at once as a practical laboratory instruction and a cosmological-spiritual "
        "metaphor, solve et coagula appears across the Paracelsian and post-Paracelsian alchemical "
        "literature and continues to structure debate about the relationship between practical and "
        "spiritual dimensions of alchemy."
    ),
    "definition_long": """<p><i>Solve et coagula</i> (Latin: "dissolve and coagulate") is an Actor Term designating the foundational paired operation of Western alchemical practice — the alternating processes of dissolution (<i>solutio</i>) and solidification (<i>coagulatio</i>) that drive the alchemical transformation of matter toward its perfected state. As an Actor Term, it names a concept explicitly used by historical alchemical practitioners in their own writings rather than a category imposed retrospectively by modern scholars. The phrase crystallizes a fundamental insight of practical alchemy: the substance to be perfected must first be broken down — dissolved into its elemental or principial components — before those components can be recombined in a higher, purer configuration. In this sense, dissolution is not destruction but analysis, and coagulation is not mere solidification but synthesis at a higher level of refinement. The maxim operates simultaneously as a laboratory instruction governing actual chemical procedures (distillation, digestion, calcination, dissolution in acid, and precipitation) and as a cosmological principle governing the structure of natural processes and as a spiritual metaphor for the purification of the soul through the mortification and regeneration of the practitioner's selfhood.</p>

<h2>Historical Usage</h2>
<p>Although the phrase <i>solve et coagula</i> in this exact formulation becomes most prominent in the Paracelsian and post-Paracelsian alchemical literature of the 16th and 17th centuries, the underlying operational logic is ancient. In Zosimos of Panopolis (fl. c. 300 CE) — the earliest systematic theorist of Greek alchemy — the alchemical process is repeatedly described in terms of the "death" of the base metal (dissolution by fire and corrosive waters) and its "resurrection" as a spiritualized, luminous substance. Zosimos uses the vivid imagery of the "priest in the Book of the Key" who is boiled in a cauldron and thereby transformed — a visionary enactment of the solve/coagula polarity. The language is mythological rather than formular, but the operational structure is identical.</p>

<p>The Arabic alchemical tradition, mediated primarily through the vast corpus attributed to Jabir ibn Hayyan (8th–9th century CE), develops the pairing in explicitly theoretical terms within the sulfur-mercury theory: the dissolution of the metal's form releases its sulfurous (active, hot, dry) and mercurial (passive, cold, moist) principles, which can then be recombined in the correct proportion to yield the target metal. The theoretical articulation here is precise: <i>solve</i> is the analysis of the compound into its principles, <i>coagula</i> is the controlled synthesis of a new compound from those principles. This theoretical precision was transmitted to the Latin West through the pseudo-Geberian corpus, above all the <i>Summa perfectionis magisterii</i> of pseudo-Geber (c. 1300), which is the most rigorous Latin statement of a sulfur-mercury theory governing both dissolution and coagulation.</p>

<p>Paracelsus (1493–1541) transformed the inherited vocabulary by replacing the binary sulfur-mercury framework with a ternary one — the <i>tria prima</i> of salt, sulfur, and mercury — but the <i>solve et coagula</i> polarity remained fundamental. In Paracelsian iatrochemistry, the physician-alchemist must dissolve a medicinal substance (solve) to isolate its active principle (<i>archeus</i>) and then reconstitute it in a form suitable for administration (coagula). The 17th-century adept Johann Rudolf Glauber, whose <i>De natura salium</i> (1659) is one of the most practically oriented post-Paracelsian texts, uses solve et coagula as the organizing principle of a systematic practical chemistry. By the time of Robert Boyle and Isaac Newton, the phrase had become almost proverbial in alchemical discourse, appearing in Newton's alchemical notebooks (now housed at the Keynes Collection, King's College Cambridge) as a shorthand for the fundamental alternating rhythm of the Work.</p>

<p>The spiritual and cosmological valence of the phrase intensifies in the Rosicrucian literature of the early 17th century (the <i>Fama Fraternitatis</i>, 1614; the <i>Confessio Fraternitatis</i>, 1615) and in the theosophical alchemy of Jacob Böhme (1575–1624), where the dissolution-coagulation rhythm becomes a cosmic principle governing God's own self-revelation in creation. For Böhme, God "dissolves" his own hiddenness in the act of creation (a cosmic <i>solve</i>) and "coagulates" the multiplicity of creation into unity in redemption (a cosmic <i>coagula</i>).</p>

<h2>Scholarly Significance</h2>
<p>The modern historiography of <i>solve et coagula</i> has been significantly shaped by the tension between the Jungian "spiritual alchemy" interpretation and the revisionist practical-chemical reading. Carl Gustav Jung's <i>Psychology and Alchemy</i> (1944) treated <i>solve et coagula</i> as the alchemical symbol for the psychological process of individuation: dissolution corresponds to the ego's confrontation with the unconscious (the <i>nigredo</i>), while coagulation corresponds to the integration of unconscious contents into a differentiated, mature selfhood (the <i>albedo</i> and <i>rubedo</i>). This reading was enormously influential in non-specialist reception and continues to shape popular engagement with alchemy.</p>

<p>Lawrence Principe and William R. Newman's revisionist program, advanced in <i>Alchemy Tried in the Fire</i> (2002) and elaborated in Principe's <i>The Secrets of Alchemy</i> (2013), insists that <i>solve et coagula</i> must first be understood as a practical laboratory instruction before it can be assessed as a symbol. Their laboratory reconstructions of specific 17th-century alchemical recipes demonstrate that the operations of dissolution and coagulation described in texts like George Starkey's laboratory notebooks produced real, identifiable chemical products. Barbara Obrist's meticulous work on the iconographic and textual transmission of alchemical process-diagrams in <i>La cosmologie médiévale</i> (2004) and related studies has traced how the visual representation of the alternating solve-coagula cycle shaped both the practice and the self-understanding of medieval alchemists. The tension between "practical" and "spiritual" readings of the phrase is not, Principe argues, a modern imposition but was already present and contested within the alchemical tradition itself — different practitioners made different claims about the priority of laboratory fact or philosophical meaning.</p>

<h2>Transmission and Variant Forms</h2>
<p>The Latin formulation <i>solve et coagula</i> is characteristic of the medieval and early modern Western alchemical tradition. Variant forms include the Greek <i>lysis kai pēxis</i> (loosing and fixing) in the Zosimean tradition, and the Arabic <i>hall wa 'aqd</i> (dissolution and binding) in the Jabirian corpus. The alchemical phrase entered popular discourse through emblem books and philosophical poetry — notably in Michael Maier's <i>Atalanta Fugiens</i> (1617), where the alternating operations of the alchemical process are depicted in fifty emblems accompanied by musical canons. The phrase has subsequently been adopted far beyond its alchemical context into spiritual, psychological, and even organizational discourse, largely stripped of its technical grounding — a decontextualization that Principe and Newman's revisionist scholarship has sought to correct by insisting on the phrase's original practical precision.</p>

<h2>Related Concepts</h2>
<p>The operative logic of <i>solve et coagula</i> is inseparable from the pursuit of the <a href="../concepts/lapis_philosophorum.html"><i>Lapis Philosophorum</i></a>, whose production requires precisely these alternating operations applied to the prima materia through the phases of the Great Work. The Paracelsian reformulation of the maxim draws on the system of the <a href="../concepts/tria_prima.html"><i>tria prima</i></a> — salt, sulfur, mercury — whose interplay constitutes the substance acted upon by the operations of dissolution and coagulation. The cosmological dimension of the maxim relates it to the <a href="../concepts/macrocosm_microcosm.html">macrocosm-microcosm</a> correspondence: as the heavens cycle through conjunctions and oppositions, as the seasons dissolve and reconstitute life, so the alchemical vessel mirrors the universe's own processual rhythm. The spiritual valence of the maxim connects it to the concept of <a href="../concepts/palingenesia.html"><i>palingenesia</i></a> — regeneration through death and rebirth — that is central to both Hermetic philosophical religion and the alchemical Great Work.</p>

<h2>Literature</h2>
<p>Principe, Lawrence M. <i>The Secrets of Alchemy</i>. Chicago: University of Chicago Press, 2013.</p>
<p>Newman, William R. and Lawrence M. Principe. <i>Alchemy Tried in the Fire: Starkey, Boyle, and the Fate of Helmontian Chymistry</i>. Chicago: University of Chicago Press, 2002.</p>
<p>Jung, C. G. <i>Psychology and Alchemy</i>. Translated by R. F. C. Hull. London: Routledge, 1944.</p>
<p>Obrist, Barbara. <i>La cosmologie médiévale: Textes et images</i>. Florence: SISMEL Edizioni del Galluzzo, 2004.</p>
<p>Linden, Stanton J. (ed.). <i>The Alchemy Reader: From Hermes Trismegistus to Isaac Newton</i>. Cambridge: Cambridge University Press, 2003.</p>
<p>Berthelot, Marcellin and Charles-Émile Ruelle. <i>Collection des anciens alchimistes grecs</i>. 3 vols. Paris: Steinheil, 1887–1888.</p>
<p>Moran, Bruce T. <i>Distilling Knowledge: Alchemy, Chemistry, and the Scientific Revolution</i>. Cambridge: Harvard University Press, 2005.</p>
<p>Maier, Michael. <i>Atalanta Fugiens, hoc est, Emblemata nova de secretis naturae chymica</i>. Oppenheim: De Bry, 1617.</p>
<p>Hanegraaff, Wouter J. (ed.). <i>Dictionary of Gnosis and Western Esotericism</i>. 2 vols. Leiden: Brill, 2006.</p>
<p>Rampling, Jennifer M. <i>The Experimental Fire: Inventing English Alchemy, 1300–1700</i>. Chicago: University of Chicago Press, 2020.</p>"""
}

# ---------------------------------------------------------------------------
# 4. LAPIS PHILOSOPHORUM
# ---------------------------------------------------------------------------
ENTRIES["lapis_philosophorum"] = {
    "definition_short": (
        "The Lapis Philosophorum (Latin: 'Philosopher's Stone') is an Actor Term for the supreme agent "
        "of the alchemical Great Work — a substance, variously described as a powder, tincture, or stone, "
        "capable of transmuting base metals into gold and silver and of perfecting human bodies through "
        "medicinal action. Attested in Latin alchemical literature from the 12th century onward, it derives "
        "from the Arabic al-iksir (elixir). Its nature — whether primarily practical, spiritual, or both — "
        "has been the central debate of both historical alchemy and its modern historiography, from Jung's "
        "symbolic reading to Principe's laboratory reconstructions."
    ),
    "definition_long": """<p>The <i>Lapis Philosophorum</i> (Latin: "Philosopher's Stone") is an Actor Term designating the ultimate product and primary agent of the Western alchemical Great Work (<i>magnum opus</i>) — a hypothetical substance of supreme transformative power capable of transmuting base metals into gold, conferring longevity or immortality when prepared as a medicine (<i>elixir vitae</i>), and serving as the embodiment of perfected matter. As an Actor Term, the <i>Lapis</i> names a concept used by historical alchemists themselves to denote their supreme goal rather than a retrospective scholarly category. Latin alchemical literature attests the term from the 12th century onward, though its conceptual genealogy reaches back through the Arabic <i>al-iksir</i> (elixir) and the Greek <i>xerion</i> (dry powder) to the Hellenistic alchemical tradition of Egypt. The <i>Lapis</i> is simultaneously the goal of the Work and the instrument of its completion: once made, the Stone amplifies its own power through projection onto base metals, converting them in a cascade. No substance fitting this description has been isolated in the chemical sense, and the history of the <i>Lapis</i> is in large part a history of the creative failure that drove alchemical inquiry forward across fifteen centuries of sustained practice.</p>

<h2>Historical Usage</h2>
<p>The concept of a supreme transmuting agent appears in the earliest strata of the Greek alchemical tradition. Pseudo-Democritus (<i>Physika kai Mystika</i>, c. 1st century CE) speaks of a "divine water" capable of fixing volatile substances and of a "tincture" that transmutes metals. Zosimos of Panopolis (fl. c. 300 CE) describes the transforming agent variously as a "divine water," a "stone that is no stone," and an "iosis" (purple tincture) — a characteristic of Hermetic and alchemical discourse is the deliberate obscuration of the Stone's nature through paradoxical or multiply valenced epithets. The Arabic alchemical tradition, particularly the Jabirian corpus (8th–9th century CE attributed to Jabir ibn Hayyan), develops the theoretical account of the Stone within the sulfur-mercury framework: the <i>al-iksir</i> is a substance of perfect sulfur-mercury balance that, when introduced to an imperfect metal in small quantities, corrects the metal's imbalance and converts it to gold. The mechanism is analogous to the action of a leaven or a ferment — a small quantity of the perfect substance transforms a much larger quantity of the imperfect.</p>

<p>The Latin alchemical tradition received the concept primarily through the Toledo translations of the 12th century. Robert of Chester's 1144 translation of the <i>Liber de compositione alchemiae</i> introduced Latin readers to the Arabic alchemical system including the transmuting elixir. The pseudo-Geberian <i>Summa perfectionis magisterii</i> (c. 1300) provides the most rigorous Latin theoretical account of the Stone within a modified sulfur-mercury framework, insisting on the material reality of the transmutation and the repeatability of the projection. The 13th and 14th centuries produced an enormous literature of recipes claiming to describe the preparation of the Stone — the Lullian alchemical corpus (largely post-Lullian as Michela Pereira has established), the works of John of Rupescissa (fl. c. 1340–1365) who adapted the Stone into a medical context as the <i>quintessence</i>, and the anonymous <i>Rosarium philosophorum</i> (first printed 1550 but compiled earlier) which gives the fullest emblematic account of the Stone's generation through the <i>hieros gamos</i> (sacred marriage) of Sol and Luna.</p>

<p>The Paracelsian revolution of the 16th century partially displaced the metallic-transmutation emphasis of the <i>Lapis</i> in favor of its medicinal power as the <i>quinta essentia</i> or <i>Arcanum maximum</i> — the supreme medical agent capable of curing all diseases. But chrysopoietic interest persisted: George Starkey (writing as Eirenaeus Philalethes) and his pupil Robert Boyle continued the search for the metallic Stone into the 17th century, as William R. Newman and Lawrence M. Principe demonstrated through archival research. Isaac Newton's extensive unpublished alchemical notebooks (King's College, Cambridge, Keynes Collection) reveal sustained practical engagement with the problem of the Stone throughout his career as natural philosopher.</p>

<h2>Scholarly Significance</h2>
<p>The modern historiography of the <i>Lapis Philosophorum</i> has been dominated by three interpretive traditions. The first, associated with Carl Gustav Jung's <i>Psychology and Alchemy</i> (1944) and <i>Mysterium Coniunctionis</i> (1956), reads the Stone as a projection of the Self — the individuation archetype — onto the chemical process. For Jung, the alchemist who sought the Stone was unconsciously engaged in a process of psychological integration, and the stone's paradoxical qualities ("incombustible yet it makes all things burn," "it is more precious than gold yet cheaper than common salt") reflect the paradoxical nature of the Self as the reconciling symbol of conscious and unconscious. This reading had vast cultural influence and continues to shape popular reception of alchemy.</p>

<p>The revisionist tradition of Lawrence Principe and William R. Newman has offered a sustained critique of the Jungian approach, insisting that it reads modern psychological categories back into pre-modern alchemical texts and obscures the genuine practical and theoretical content of the tradition. Principe's <i>The Secrets of Alchemy</i> (2013) — the most accessible statement of this position — argues that the <i>Lapis</i> was genuinely sought as a physical substance by serious practical chemists and that many alchemical processes describing its preparation can be reconstructed in modern laboratory conditions, yielding identifiable chemical products. This does not mean that the <i>Lapis</i> was produced (no transmutation has been reproduced), but it means that the search for it generated real chemistry and real knowledge.</p>

<p>A third tradition, associated with Antoine Faivre and Wouter Hanegraaff's broader approach to Western esotericism, situates the <i>Lapis</i> within the broader symbolic economy of the Western esoteric tradition, acknowledging both the practical and the spiritual dimensions without reducing either to the other. Hanegraaff's account in the <i>Dictionary of Gnosis and Western Esotericism</i> (2006) and in subsequent work emphasizes that the question of whether the <i>Lapis</i> is a "material" or "spiritual" substance is itself a retrospective imposition: many historical alchemists operated within a framework in which matter and spirit were not sharply separated, and the <i>Lapis</i> could be simultaneously a chemical substance and a pneumatic or spiritual reality without contradiction.</p>

<h2>Transmission and Variant Forms</h2>
<p>The <i>Lapis Philosophorum</i> has been designated by a remarkable proliferation of synonymous and partially synonymous terms across the alchemical tradition, reflecting both the deliberate obscurantism of the genre and the genuine polyvalence of the concept. In Greek: <i>lithos</i> (stone), <i>xerion</i>, <i>iosis</i>. In Arabic: <i>al-iksir</i> (elixir), <i>al-hajar al-mukarram</i> (honored stone), <i>kimiya</i> in some usages. In Latin: <i>lapis</i>, <i>elixir</i>, <i>medicina</i>, <i>tinctura</i>, <i>quinta essentia</i>, <i>aurum potabile</i> (drinkable gold), <i>Arcanum maximum</i>, <i>Rebis</i> (the double thing), and dozens of allegorical designations including the Red King, the White Queen, the Philosopher's Egg, the Green Lion, and the Pelican. The Paracelsian tradition emphasizes the medicinal dimension under the term <i>Arcanum</i>. The Rosicrucian literature of the early 17th century — <i>Fama Fraternitatis</i> (1614), <i>Chymische Hochzeit Christiani Rosencreutz</i> (1616) — integrates the Stone into a narrative of Christian spiritual redemption. In the 19th and 20th century occult revival, the Stone becomes a symbol of spiritual perfection detached from any laboratory context — a usage that Principe's revisionist scholarship has made visible as a historical distortion.</p>

<h2>Related Concepts</h2>
<p>The <i>Lapis Philosophorum</i> is the terminal goal of the practical pursuit of <a href="../concepts/chrysopoeia.html">chrysopoeia</a> — gold-making — and its preparation requires the repeated application of the operations designated by <a href="../concepts/solve_et_coagula.html"><i>solve et coagula</i></a>. The Paracelsian version of the Stone as supreme medical agent draws on the concept of the <a href="../concepts/quintessence.html">quintessence</a> — the fifth element extracted from matter through distillation — and the <a href="../concepts/tria_prima.html"><i>tria prima</i></a> framework. The cosmological presupposition of the Stone's efficacy is the <a href="../concepts/macrocosm_microcosm.html">macrocosm-microcosm</a> correspondence: gold is the perfect metal because it corresponds to the sun, and the Stone achieves perfection because it embodies the solar principle in pure form. The alchemical regeneration effected by the Stone in metals parallels the spiritual <a href="../concepts/palingenesia.html"><i>palingenesia</i></a> — rebirth — of the practitioner who undergoes the Great Work.</p>

<h2>Literature</h2>
<p>Principe, Lawrence M. <i>The Secrets of Alchemy</i>. Chicago: University of Chicago Press, 2013.</p>
<p>Newman, William R. and Lawrence M. Principe. <i>Alchemy Tried in the Fire: Starkey, Boyle, and the Fate of Helmontian Chymistry</i>. Chicago: University of Chicago Press, 2002.</p>
<p>Jung, C. G. <i>Psychology and Alchemy</i>. Translated by R. F. C. Hull. London: Routledge, 1944.</p>
<p>Jung, C. G. <i>Mysterium Coniunctionis: An Inquiry into the Separation and Synthesis of Psychic Opposites in Alchemy</i>. Translated by R. F. C. Hull. London: Routledge, 1963.</p>
<p>Pereira, Michela. <i>The Alchemical Corpus Attributed to Raymond Lull</i>. London: Warburg Institute, 1989.</p>
<p>Hanegraaff, Wouter J. (ed.). <i>Dictionary of Gnosis and Western Esotericism</i>. 2 vols. Leiden: Brill, 2006.</p>
<p>Linden, Stanton J. (ed.). <i>The Alchemy Reader: From Hermes Trismegistus to Isaac Newton</i>. Cambridge: Cambridge University Press, 2003.</p>
<p>Moran, Bruce T. <i>Distilling Knowledge: Alchemy, Chemistry, and the Scientific Revolution</i>. Cambridge: Harvard University Press, 2005.</p>
<p>Rampling, Jennifer M. <i>The Experimental Fire: Inventing English Alchemy, 1300–1700</i>. Chicago: University of Chicago Press, 2020.</p>
<p>Obrist, Barbara. <i>La cosmologie médiévale: Textes et images</i>. Florence: SISMEL Edizioni del Galluzzo, 2004.</p>"""
}


def main():
    conn = sqlite3.connect(DB_PATH)
    cur = conn.cursor()
    for slug, data in ENTRIES.items():
        cur.execute("SELECT slug FROM concepts WHERE slug = ?", (slug,))
        if not cur.fetchone():
            print(f"WARNING: slug not found in DB: {slug}")
            continue
        cur.execute(
            "UPDATE concepts SET definition_short = ?, definition_long = ? WHERE slug = ?",
            (data["definition_short"], data["definition_long"], slug)
        )
        dl_words = len(data["definition_long"].split())
        ds_words = len(data["definition_short"].split())
        print(f"Updated {slug}: def_short={ds_words} words, def_long={dl_words} words")
    conn.commit()
    conn.close()
    print("Batch 1 complete.")


if __name__ == "__main__":
    main()
