"""
write_concepts_batch3.py — Decans, Astral Magic, Christian Kabbalah, Symphorien Champier
Idempotent: writes full definition_long and definition_short for:
  - decans
  - astral_magic
  - christian_kabbalah
  - symphorien_champier
"""
import sqlite3

DB_PATH = r"C:\Dev\EmeraldTablet\db\emerald_tablet.db"

ENTRIES = {}

# ---------------------------------------------------------------------------
# 1. DECANS
# ---------------------------------------------------------------------------
ENTRIES["decans"] = {
    "definition_short": (
        "The Decans are an Actor Term designating the thirty-six Egyptian stellar deities — each governing "
        "ten degrees of the zodiacal circle, one third of each zodiacal sign — that were central to "
        "Egyptian astral religion, time-keeping, and Hermetic cosmological theology. Attested in Middle "
        "Kingdom diagonal star clocks (c. 2100 BCE), they were integrated into the Hermetic tradition "
        "through the Liber Hermetis and the Asclepius, where each decan governs a portion of the human "
        "body and can be invoked through talismanic images. David Pingree and Liana Saif have traced "
        "their transmission from Egypt through Byzantium and the Arabic world to the Latin West."
    ),
    "definition_long": """<p>The Decans (<i>dekanoi</i> in Greek; derived from the Greek <i>deka</i>, "ten") are an Actor Term designating the thirty-six stellar deities of Egyptian religion, each governing a ten-degree arc of the zodiacal circle and one third of a zodiacal sign — and, by extension, governing a ten-day period of the Egyptian civil year, a segment of the human body (<i>melothesia</i>), and a range of practical operations in the sphere of medicine, talismanic magic, and fate. As an Actor Term, the Decans name a concept genuinely operative within Egyptian astral religion and subsequently within the Hermetic, Neoplatonic, and Arabic magical traditions, rather than a retrospective scholarly category. The history of the Decans is a history of progressive re-contextualization: what began in Middle Kingdom Egypt as a time-keeping device marking the heliacal risings of thirty-six groups of stars to indicate the ten-day divisions of the civil year was successively reinterpreted as a system of astral deities, as a cosmological framework for human fate, as a set of magical images with practical efficacy, and ultimately as a system of talismanic iconography transmitted from Egyptian temple culture through Greek astrology, Arabic <i>ilm al-nujum</i>, and into the Latin West of the 12th century and beyond. Their presence in the <i>Hermetic</i> corpus — above all in the <i>Liber Hermetis</i> (a Latin compilation of Hellenistic-era material attributed to Hermes Trismegistus) — makes them central to understanding the Egyptian religious background of the Hermetic tradition.</p>

<h2>Historical Usage</h2>
<p>The earliest attestations of the Decans are in the Egyptian Middle Kingdom diagonal star tables painted on the interior lids of coffins (c. 2100–1800 BCE), which track the heliacal risings of thirty-six star groups — each associated with a ten-day "week" — to divide the night into twelve hours. These coffin texts are the foundational documentation of the Decan system in its original Egyptian function: the Decans here are stars, not deities in the developed sense, though they are already personified and their risings mark important transitions in the religious calendar. By the New Kingdom period (c. 1550–1070 BCE), the Decans had acquired a more explicitly divine character and were systematically depicted in astronomical ceiling paintings, above all in the tomb of Seti I (c. 1279 BCE) at Thebes and in the Ramesseum, where they appear as gods with associated iconography. Alexandra von Lieven's meticulous studies of Egyptian astronomical texts provide the foundational scholarly account of this early material.</p>

<p>The integration of the Decans into the developed system of Hellenistic astrology — with its twelve zodiacal signs, seven planetary rulers, and elaborate system of correspondence — is attested from at least the 2nd century BCE in Egyptian-Greek magical and astrological texts. Firmicus Maternus, writing in Latin c. 335 CE in his <i>Mathesis</i>, provides one of the fullest surviving accounts of the Decan iconography and attributes, describing the image of each Decan — the specific divine form in which it was depicted on talismanic objects — as capable of producing specific effects when properly invoked. The <i>Liber Hermetis</i> (Latin title; the Greek original is lost but can be partially reconstructed), a Hellenistic-era astrological compilation attributed to Hermes Trismegistus and preserved in a late Latin translation, treats the Decans as cosmic governors of human fate: each Decan rules a portion of the human body, and diseases of that body-part are to be treated through the appropriate Decan's talismanic image. Wilhelm Gundel and Hans Georg Gundel's monumental <i>Dekane und Dekansternbilder</i> (1936) remains the most comprehensive study of the Decan iconographic tradition.</p>

<p>The <i>Asclepius</i> — the Latin translation of the Greek <i>Perfect Discourse</i>, available throughout the medieval period in the corpus of Apuleius — contains an important Hermetic cosmological treatment of the Decans. In <i>Asclepius</i> 19–20, Hermes describes the Decans as the highest governors of cosmic fate, superior in power to the seven planetary gods and governing all events in the sublunary world through the influx of their qualities. Garth Fowden's analysis of this passage in <i>The Egyptian Hermes</i> (1986) emphasizes its significance for understanding the specifically Egyptian astral theology embedded in the Hermetic tradition: the Decans here are not merely astrological "lots" but cosmic powers whose governance of human affairs reflects the Egyptian conception of the stellar gods as active agents in the maintenance of cosmic order (<i>maat</i>). Christian H. Bull's recent work extends this reading by situating the Hermetic Decan theology within the broader context of Egyptian priestly cosmology.</p>

<p>Abu Ma'shar (Albumasar, 787–886 CE) is the key figure in the Arabic transmission of the Decan tradition. His <i>Kitab al-Mudkhal al-Kabir</i> (Great Introduction to Astrology) and the related <i>Kitab al-Qiranat</i> systematically integrated the Decan lore into the Arabic astrological synthesis, drawing on Persian, Greek, and Indian sources alongside the Egyptian tradition. David Pingree's extensive work on the transmission of Decan iconography — tracing three distinct iconographic "families" (Egyptian, Persian-Indian, and Greek) in the manuscript tradition — maps the complex routes by which the Decan images reached the Latin West through Arabic intermediaries.</p>

<h2>Scholarly Significance</h2>
<p>The scholarly significance of the Decans within the history of Hermeticism has two principal dimensions. The first concerns their value as evidence for the Egyptian religious background of the Hermetic textual tradition. Fowden's argument in <i>The Egyptian Hermes</i> that the philosophical Hermetica were produced in a specifically Egyptian religious milieu — and not merely in a generically "Greek" or "Hellenistic" context — draws in part on the Decan cosmology of the <i>Asclepius</i> and the <i>Liber Hermetis</i> as markers of authentic Egyptian theological content. Bull's more recent thesis in <i>The Tradition of Hermes Trismegistus</i> (2018) sharpens this argument: if the Decans in the Hermetic texts reflect knowledge of Egyptian temple cult that would have been available only to practising Egyptian priests (or to their immediate intellectual heirs), then the Hermetic texts were composed in an environment with direct access to that priestly tradition.</p>

<p>The second dimension concerns the Decan's role in the transmission of Egyptian astral magic to the Latin West. Liana Saif's <i>The Arabic Influences on Early Modern Occult Philosophy</i> (2015) and her subsequent work on the Arabic occult sciences have demonstrated that the Decan lore preserved in Arabic astrological and magical texts was a primary channel through which Egyptian astral-theological content reached Renaissance Europe. The identification of specific Decan images in Warburg's famous analysis of the Schifanoia Palace frescoes in Ferrara (1912) — where Aby Warburg traced the iconographic tradition from Abu Ma'shar to the Italian court through the <i>Picatrix</i> — is the classic demonstration of this transmission. Warburg's analysis remains a landmark in art history and in the historiography of the magical tradition.</p>

<h2>Transmission and Variant Forms</h2>
<p>The Decan system was transmitted through at least three distinct iconographic families, as Pingree established: the Egyptian family (attested in the coffin texts and the <i>Liber Hermetis</i>), the Persian-Indian family (transmitted through Abu Ma'shar from Persian and Indian sources), and the Greek family (attested in Firmicus Maternus and related texts). The <i>Picatrix</i> (<i>Ghayat al-Hakim</i>, c. 1000 CE; Latin translation c. 1256) preserves a synthetic account of the Decan images drawing primarily on the Persian-Indian family, and it was through the <i>Picatrix</i> that the Decan iconography entered Renaissance talismanic practice. The three Renaissance texts that most directly preserve Decan lore are: Cornelius Agrippa's <i>De occulta philosophia</i> (1531, Book II), Ficino's <i>De vita coelitus comparanda</i> (1489), and the commentary tradition on Manilius's <i>Astronomica</i>. The identification of the thirty-six Decan images with specific talismanic objects — rings, seals, images engraved in gemstones — is attested across all three families and represents the practical application of Decan theology to everyday magical practice.</p>

<h2>Related Concepts</h2>
<p>The Decans belong to the broader framework of <a href="../concepts/astral_magic.html">Astral Magic</a> — the practice of drawing down celestial influences through ritual objects and procedures timed to planetary and stellar conjunctions — of which the Decanic talismanic tradition is a specific and ancient branch. Their cosmological function presupposes the <a href="../concepts/macrocosm_microcosm.html">macrocosm-microcosm</a> correspondence: the Decans govern portions of the human body because the small world of the human being mirrors the great world of the cosmos. The <i>Liber Hermetis</i> Decan lore is closely connected to the broader Hermetic astral theology of the <a href="../concepts/corpus_hermeticum.html"><i>Corpus Hermeticum</i></a>, particularly the <i>Asclepius</i>, where the Decans appear as cosmic governors alongside the seven planetary powers. The Hermetic context of the Decans makes them relevant to the <a href="../concepts/the_way_of_hermes.html">Way of Hermes</a>: the soul's ascent through the planetary spheres and beyond, as described in CH I, must pass through the Decan-governed regions of the cosmos.</p>

<h2>Literature</h2>
<p>Gundel, Wilhelm and Hans Georg Gundel. <i>Dekane und Dekansternbilder: Ein Beitrag zur Geschichte der Sternbilder der Kulturvölker</i>. Glückstadt: Augustin, 1936.</p>
<p>Fowden, Garth. <i>The Egyptian Hermes: A Historical Approach to the Late Pagan Mind</i>. Cambridge: Cambridge University Press, 1986.</p>
<p>Bull, Christian H. <i>The Tradition of Hermes Trismegistus: The Egyptian Priestly Figure as a Teacher of Hellenized Wisdom</i>. Leiden: Brill, 2018.</p>
<p>Saif, Liana. <i>The Arabic Influences on Early Modern Occult Philosophy</i>. Basingstoke: Palgrave Macmillan, 2015.</p>
<p>Pingree, David. "Some of the Sources of the Ghayat al-Hakim." <i>Journal of the Warburg and Courtauld Institutes</i> 43 (1980): 1–15.</p>
<p>Abu Ma'shar. <i>The Abbreviation of the Introduction to Astrology</i>. Edited and translated by Charles Burnett, Keiji Yamamoto, and Michio Yano. Leiden: Brill, 1994.</p>
<p>Copenhaver, Brian P. (trans.). <i>Hermetica: The Greek Corpus Hermeticum and the Latin Asclepius</i>. Cambridge: Cambridge University Press, 1992.</p>
<p>Hanegraaff, Wouter J. (ed.). <i>Dictionary of Gnosis and Western Esotericism</i>. 2 vols. Leiden: Brill, 2006.</p>
<p>Warburg, Aby. "Italienische Kunst und internationale Astrologie im Palazzo Schifanoia zu Ferrara." In <i>Gesammelte Schriften</i>. Vol. 2. Leipzig: Teubner, 1932. 459–481.</p>"""
}

# ---------------------------------------------------------------------------
# 2. ASTRAL MAGIC
# ---------------------------------------------------------------------------
ENTRIES["astral_magic"] = {
    "definition_short": (
        "Astral Magic is an Actor Term designating the practice of drawing down and directing the "
        "influences of stars, planets, and decans through talismans, ritual procedures, prayers, and "
        "suffumigations timed to auspicious celestial configurations, in order to achieve practical "
        "effects in the sublunary world. The Picatrix (Ghayat al-Hakim, c. 1000 CE) is its canonical "
        "Arabic textbook; al-Kindi's De radiis provides its theoretical foundation; and Ficino's "
        "De vita coelitus comparanda (1489) is its definitive Renaissance formulation. D. P. Walker "
        "and Frances Yates established its historiographical centrality; Hanegraaff and Copenhaver have "
        "subsequently refined its relationship to the Hermetic tradition."
    ),
    "definition_long": """<p>Astral Magic is an Actor Term designating the practice — attested across Late Antique, Arabic, and Renaissance sources — of systematically drawing down, directing, and concentrating the influences of celestial bodies (stars, planets, and the thirty-six <a href="../concepts/decans.html">Decans</a>) through the manufacture and consecration of talismans, the performance of ritual invocations and suffumigations, and the timing of operations to auspicious planetary conjunctions, in order to achieve specific practical effects in the sublunary world: curing disease, enhancing intellectual capacity, attracting love, protecting against enemies, or securing the favour of princes. As an Actor Term, it names a practice and conceptual framework employed by historical practitioners themselves — astrologers, physicians, court advisors, philosophers — who understood themselves to be operating within a coherent natural-philosophical account of how celestial influences act on terrestrial matter, not as sorcerers trafficking with demons. The canonical Arabic textbook of astral magic is the <i>Picatrix</i> (<i>Ghayat al-Hakim</i>, Arabic c. 1000 CE; Latin translation c. 1256), attributed to Maslama al-Majriti but probably the work of an anonymous Andalusian scholar. The theoretical foundation is al-Kindi's <i>De radiis stellarum</i> (c. 850 CE), which provides a systematic account of how all celestial and terrestrial things influence one another through the emanation of "rays." The definitive Renaissance formulation is Marsilio Ficino's <i>De vita coelitus comparanda</i> (1489, Book III of <i>De vita libri tres</i>), which remains the most philosophically sophisticated defence of astral magic in any period.</p>

<h2>Historical Usage</h2>
<p>The theoretical foundations of astral magic were laid in the Hellenistic period, in the confluence of Babylonian celestial observation, Egyptian Decan theology, Greek Platonic and Stoic cosmology, and the practical tradition of the Greek magical papyri (PGM). The key theoretical premise is the doctrine of cosmic sympathy (<i>sympatheia tou holou</i>) — the claim, associated with Stoic cosmology and developed by Neoplatonic philosophers including Plotinus and Iamblichus, that all parts of the cosmos are linked by bonds of mutual influence so that operations on one part affect corresponding parts throughout the whole. On this doctrine, the manufacture of a talisman engraved with the image of Mars under a Mars-ruled planetary hour and suffumigated with appropriate materials is not a superstitious act but a rational application of natural law: the talisman, constituted of materials that "belong" to Mars by their natural properties, attracts and concentrates the Martian influence and directs it toward the intended purpose.</p>

<p>Al-Kindi's <i>De radiis stellarum</i> (Latin title of the Arabic original, c. 850 CE) is the most rigorous theoretical treatment of this mechanism in the Arabic tradition: al-Kindi argues that all things emit "rays" that act on other things throughout the cosmos, that human speech, ritual actions, and specially prepared objects can shape and direct these rays, and that there is therefore a philosophically defensible account of why magic works. The <i>Picatrix</i> is the comprehensive practical manual: its four books describe the philosophical foundations of astral magic (Book I), the properties of the planets and decans (Book II), detailed procedures for the manufacture of talismans and the timing of operations (Book III), and further materials including planetary suffumigations, divine names, and magical images (Book IV). David Pingree's critical edition and study of the Latin <i>Picatrix</i> (1986, with Hellmut Ritter's edition of the Arabic) and Beatriz Rubio and Jose Martos Montiel's Spanish edition of the Arabic have provided the scholarly foundation for modern study of the text. Liana Saif's work has substantially illuminated the intellectual context of the <i>Picatrix</i> within the Arabic occult sciences.</p>

<p>In the Latin West, astral magic was received through the Toledo translations of the 12th century — Gerard of Cremona's translation of al-Kindi's <i>De radiis</i> and the partial Latin <i>Picatrix</i> — and was further developed in the astral-magical tradition of the 13th century represented by Michael Scot, William of Auvergne, and the pseudo-Albertine <i>Speculum astronomiae</i>. The <i>Speculum astronomiae</i> (attributed to Albertus Magnus) is particularly important as an attempt to distinguish licit from illicit forms of astral magic within a Christian theological framework: the author defends the use of astronomical images (<i>imagines astronomicae</i>) as natural science while condemning images that invoke demons. Marsilio Ficino's <i>De vita coelitus comparanda</i> (1489) is the Renaissance masterpiece of the genre. Ficino draws on Plotinus, Iamblichus, and the <i>Picatrix</i> (without naming the latter) to develop a philosophical account of how the physician-philosopher can draw solar and Jovian influences to counteract the Saturnine melancholy to which scholars are prone. The genius of Ficino's treatment lies in his integration of astral-magical practice into a framework of Neoplatonic natural philosophy and Galenic medicine, presenting the practices as a form of natural therapy rather than supernatural intervention.</p>

<h2>Scholarly Significance</h2>
<p>The historiography of astral magic has been defined above all by Frances Yates's <i>Giordano Bruno and the Hermetic Tradition</i> (1964), which identified astral magic as a central component of Renaissance Hermeticism and argued that it contributed to the development of the Scientific Revolution by promoting an "activist" attitude toward nature that privileged practical manipulation over passive observation. The Yates Paradigm gave astral magic a central place in the narrative of intellectual modernity and generated enormous scholarly attention to Ficino, Pico, Bruno, and Agrippa as representatives of a "Hermetic-Magian" tradition.</p>

<p>D. P. Walker's <i>Spiritual and Demonic Magic from Ficino to Campanella</i> (1958) remains the most detailed scholarly study of the actual content of Renaissance astral magic, tracing the debate between advocates of natural-magical practice and critics who insisted on the demonic character of any effective magic. Walker's analysis of Ficino's attempts to distinguish "spiritual" (purely natural) from "demonic" magic is essential for understanding the theological context in which astral magic was practiced and theorized. Brian P. Copenhaver's critical engagement with the Yates Paradigm — articulated in his introduction to the Cambridge <i>Hermetica</i> (1992) and in subsequent articles — has demonstrated that Yates substantially overestimated the specifically Hermetic dimension of Renaissance magic: the connections between the <i>Corpus Hermeticum</i> and the practical magical tradition are looser and more mediated than Yates suggested, and the astral-magical tradition draws as heavily on Arabic, Platonic, and Aristotelian sources as on strictly Hermetic ones. Hanegraaff's methodological work has further clarified the Actor/Analyst dimensions of the problem: "astral magic" is a historical practice, but the category "Hermetic magic" that Yates constructed is partly an Analyst-term construct that may not accurately reflect how historical practitioners categorized their own activities.</p>

<h2>Transmission and Variant Forms</h2>
<p>The transmission of astral magic from its Late Antique and Arabic origins to the Latin Renaissance followed several channels. The most important single text is the <i>Picatrix</i>, translated into Latin at the court of Alfonso X of Castile c. 1256 and subsequently widely copied. The pseudo-Ptolemaic <i>Centiloquium</i> (100 aphorisms attributed to Ptolemy) provided a more philosophically respectable vehicle for astral-magical doctrine. Cornelius Agrippa's <i>De occulta philosophia</i> (three books, 1531 — a vastly expanded version of the 1510 draft) synthesized the entire tradition into the most comprehensive Renaissance account of astral magic, integrating <i>Picatrix</i> material with Neoplatonic metaphysics, Kabbalistic theosophy, and Paracelsian chemistry. The subsequent transmission into the early modern period ran through John Dee (whose <i>Monas Hieroglyphica</i> of 1564 is a radically condensed astral-magical symbolism), Giordano Bruno, Robert Fludd, and the Rosicrucian movement of the early 17th century, before being progressively displaced by the mechanistic natural philosophy of the late 17th century — though, as Betty Jo Teeter Dobbs demonstrated, it persisted in Newton's alchemical notebooks.</p>

<h2>Related Concepts</h2>
<p>Astral Magic is organically related to the tradition of <a href="../concepts/decans.html">Decan</a> theology that provides its Egyptian astral-religious substrate. Its theoretical mechanism — cosmic sympathy channeled through appropriately constituted material objects — presupposes the <a href="../concepts/macrocosm_microcosm.html">macrocosm-microcosm</a> correspondence as its cosmological foundation. The concept of <a href="../concepts/magia_naturalis.html"><i>Magia Naturalis</i></a> — natural magic as a legitimate form of applied natural philosophy — is the broader Renaissance category within which Ficino's astral magic is situated. The Hermetic philosophical context for astral magic is provided by the <a href="../concepts/anima_mundi_divine.html"><i>Anima Mundi</i></a> doctrine: if the World Soul pervades and animates all things, then ritual actions that resonate with its animating principle can direct its influence toward specific ends.</p>

<h2>Literature</h2>
<p>Walker, D. P. <i>Spiritual and Demonic Magic from Ficino to Campanella</i>. London: Warburg Institute, 1958.</p>
<p>Yates, Frances A. <i>Giordano Bruno and the Hermetic Tradition</i>. London: Routledge and Kegan Paul, 1964.</p>
<p>Saif, Liana. <i>The Arabic Influences on Early Modern Occult Philosophy</i>. Basingstoke: Palgrave Macmillan, 2015.</p>
<p>Pingree, David. "Some of the Sources of the Ghayat al-Hakim." <i>Journal of the Warburg and Courtauld Institutes</i> 43 (1980): 1–15.</p>
<p>Copenhaver, Brian P. "Hermes Trismegistus, Proclus, and the Question of a Philosophy of Magic in the Renaissance." In <i>Hermeticism and the Renaissance</i>, edited by Ingrid Merkel and Allen G. Debus. Washington: Folger Shakespeare Library, 1988. 79–110.</p>
<p>Hanegraaff, Wouter J. (ed.). <i>Dictionary of Gnosis and Western Esotericism</i>. 2 vols. Leiden: Brill, 2006.</p>
<p>Ficino, Marsilio. <i>Three Books on Life</i>. Edited and translated by Carol V. Kaske and John R. Clark. Binghamton: Medieval and Renaissance Texts and Studies, 1989.</p>
<p>Fowden, Garth. <i>The Egyptian Hermes: A Historical Approach to the Late Pagan Mind</i>. Cambridge: Cambridge University Press, 1986.</p>
<p>Bull, Christian H. <i>The Tradition of Hermes Trismegistus</i>. Leiden: Brill, 2018.</p>"""
}

# ---------------------------------------------------------------------------
# 3. CHRISTIAN KABBALAH
# ---------------------------------------------------------------------------
ENTRIES["christian_kabbalah"] = {
    "definition_short": (
        "Christian Kabbalah is an Analyst Term — a retrospective scholarly category — designating the "
        "15th- through 17th-century movement in which Christian humanists, theologians, and philosophers "
        "appropriated Jewish Kabbalistic texts, concepts, and methods — particularly the Sefirot, "
        "divine Names, and Gematria — as supposed proofs of Christian theological doctrines and as "
        "tools of contemplative philosophy. Giovanni Pico della Mirandola's Conclusiones (1486) is the "
        "founding document; Johannes Reuchlin's De arte cabalistica (1517) its canonical textbook. "
        "Moshe Idel and Chaim Wirszubski have provided the most rigorous modern critical assessments "
        "of what was actually transmitted and from whom."
    ),
    "definition_long": """<p>Christian Kabbalah is an Analyst Term — a retrospective scholarly category — designating the intellectual movement that emerged in late 15th-century Italy and spread across Europe through the 16th and into the 17th century, in which Christian humanists, theologians, philosophers, and occult practitioners appropriated texts, concepts, and methods from the Jewish Kabbalistic tradition — above all the <i>Sefer ha-Zohar</i> (the Book of Splendour), the system of the ten <i>Sefirot</i> (divine emanations), the use of divine Names and letter-combinations, and the interpretive methods of Gematria (numerological equivalence), Notarikon (acronym interpretation), and Temurah (letter permutation) — and deployed them within a specifically Christian theological framework, arguing that the Kabbalistic tradition provided independent and ancient confirmation of the truth of Christian doctrines (the Trinity, the incarnation, the messiahship of Jesus) and offered a superior path of contemplative ascent to those available within the Scholastic tradition. As an Analyst Term, Christian Kabbalah names a phenomenon that historians have identified and categorized; it was not the term used by the practitioners themselves, who typically described their enterprise as "the Kabbalah" or "the true Kabbalah" without a "Christian" qualifier. The foundational scholarly account is François Secret's <i>Les Kabbalistes chrétiens de la Renaissance</i> (Paris, 1964), and the most rigorous critical assessment of what was actually appropriated from Jewish sources is Chaim Wirszubski's <i>Pico della Mirandola's Encounter with Jewish Mysticism</i> (1989).</p>

<h2>Historical Usage</h2>
<p>The originating moment of Christian Kabbalah is conventionally located in Giovanni Pico della Mirandola's <i>Conclusiones nongentae</i> (Rome, 1486) — 900 philosophical theses for a proposed public disputation in Rome, of which 47 are explicitly "Kabbalistic conclusions." Pico had access to Jewish Kabbalistic texts through a remarkable intermediary: Flavius Mithridates (Guglielmo Raimondo Moncada), a converted Sicilian Jew who translated for Pico large portions of the Kabbalistic literature, including substantial sections of the <i>Zohar</i>, the writings of the Spanish Kabbalist Menahem Recanati, and related texts. Wirszubski's analysis of the Mithridates-Pico relationship in <i>Pico della Mirandola's Encounter with Jewish Mysticism</i> (1989) — based on meticulous comparison of the Latin translations with the Hebrew originals — remains the definitive account of this transmission. Pico's <i>Conclusiones</i> include such claims as "No science can better assure us of the divinity of Christ than magic and Kabbalah" — a formula that captures both the apologetic strategy and the scandal that the text provoked: Pope Innocent VIII condemned 13 of the theses and suspended the planned disputation.</p>

<p>Johannes Reuchlin (1455–1522) of Pforzheim, the leading Hebraist of Germany, produced the two canonical textbooks of Christian Kabbalah in Latin. <i>De verbo mirifico</i> (On the Wonder-Working Word, 1494) uses the Kabbalistic doctrine of the divine Name to argue that the name "Jesus" (IHSVH), formed by inserting the Hebrew letter Shin into the Tetragrammaton (YHVH), is the most powerful of all divine Names. <i>De arte cabalistica</i> (On the Art of Kabbalah, 1517) is a more systematic philosophical dialogue that presents the Kabbalistic cosmological system — the <i>Sefirot</i>, the angelic hierarchies, the doctrines of the soul — as a philosophical supplement to Christian theology. Reuchlin's engagement with the Kabbalah should be understood in the context of his broader defence of Jewish books against Johann Pfefferkorn's campaign to have them destroyed — a defense in which his argument that the Talmud and Kabbalah contained valuable Christian-compatible philosophical resources played a direct role.</p>

<p>Francesco Giorgi (Franciscus Georgius) of Venice, a Franciscan friar, produced in <i>De harmonia mundi totius cantica tria</i> (Venice, 1525) what is arguably the most ambitious synthesis of Kabbalistic, Platonic, and Christian cosmological doctrine in the Renaissance. Giorgi drew on Pico, Reuchlin, and his own knowledge of Kabbalistic sources to argue for a universal harmony underlying all traditions of wisdom — a version of the <i>prisca theologia</i> synthesis applied to Kabbalah. Henry Cornelius Agrippa's <i>De occulta philosophia</i> (1531) integrates Kabbalistic elements — the three worlds of Kabbalistic cosmology, the use of Hebrew Names in angelic invocations — into a comprehensive account of natural, celestial, and ceremonial magic. The mid-16th to early-17th century saw the consolidation of Christian Kabbalah in works by Guillaume Postel, Francesco Patrizi, and above all the Jesuit Athanasius Kircher, whose <i>Oedipus Aegyptiacus</i> (1652–1654) provides the most baroque synthesis of Kabbalah, Hermeticism, and universal symbolism in the tradition.</p>

<h2>Scholarly Significance</h2>
<p>The scholarly account of Christian Kabbalah has been substantially revised over the past generation, primarily through the interventions of Moshe Idel and the philological precision of Wirszubski. Secret's foundational survey, while invaluable as a first mapping of the terrain, tended to treat Christian Kabbalah as a relatively coherent and unified tradition and to take the Christian kabbalists at their word about the nature and depth of their Kabbalistic knowledge. Idel — whose <i>Kabbalah: New Perspectives</i> (1988) fundamentally reoriented the study of Jewish Kabbalah by emphasizing its ecstatic and practical dimensions alongside the theosophical — has consistently pressed for greater specificity about which strands of the Kabbalistic tradition were actually received in Christian contexts and how much was simply misunderstood or strategically redeployed. In a series of critical studies, Idel has shown that Christian kabbalists typically had access to a relatively small and not particularly representative sample of Kabbalistic literature, mediated through translators who were themselves working under significant time and resource constraints, and that the resulting "Christian Kabbalah" was in many respects a new construction rather than an accurate transmission of the Jewish original.</p>

<p>Wirszubski's meticulous philological work on Pico's Kabbalistic sources demonstrated both the remarkable depth of what Mithridates transmitted and the significant distance between what Pico understood himself to be saying and what the original Hebrew texts actually contained. The result is a more nuanced picture: Christian Kabbalah was neither a simple appropriation nor a total distortion but a creative transformation of selected Kabbalistic materials within a specifically Christian Neoplatonic framework. Hanegraaff's methodological framework — the insistence on maintaining the Actor/Analyst distinction — has clarified the analytical situation: "Christian Kabbalah" as a unified "movement" is partly an Analyst-term construct, and the specific Christian kabbalists were in many respects working from quite different sources and toward quite different ends than the category implies.</p>

<p>The relationship of Christian Kabbalah to the Hermetic tradition is a much-debated question. Frances Yates's account in <i>Giordano Bruno and the Hermetic Tradition</i> (1964) posited a close alliance between Hermeticism and Kabbalah in the Renaissance as two complementary streams of "ancient wisdom" that mutually reinforced each other. Copenhaver and Hanegraaff have been critical of this synthesis, arguing that Yates overestimated both the degree of integration and the degree of Hermetic influence specifically on the kabbalistic synthesis. The two traditions were certainly combined — Pico's combination of Hermetic and Kabbalistic material is well documented — but they remained distinguishable, and treating them as a unified "Hermetic-Cabalist tradition" obscures their distinct genealogies and internal logics.</p>

<h2>Transmission and Variant Forms</h2>
<p>Christian Kabbalah spread from its Italian origins through several routes. In Germany, Reuchlin's works were widely read and influenced the Reformers — Luther engaged with Kabbalistic etymology — and the early Paracelsians. In France, Guillaume Postel (1510–1581) developed one of the most eccentric and radical Christian Kabbalistic syntheses, combining it with apocalyptic universalism and a distinctive doctrine of feminine redemption. In Spain and Portugal, the converso (Jewish convert) communities provided channels through which Kabbalistic knowledge continued to flow into Christian culture after the expulsions of 1492. In England, the 17th-century reception of Kabbalah was shaped primarily by Knorr von Rosenroth's monumental <i>Kabbala Denudata</i> (2 vols., 1677–1684), which provided Latin translations of major Kabbalistic texts and was read by Leibniz, Newton, and later by the Cambridge Platonists. The subsequent influence of Kabbalistic concepts on modern Western esotericism — Freemasonry, Rosicrucianism, Theosophy, the Hermetic Order of the Golden Dawn — runs primarily through this 17th-century channel rather than directly from the Renaissance sources.</p>

<h2>Related Concepts</h2>
<p>Christian Kabbalah belongs to the broader Renaissance project of <a href="../concepts/prisca_theologia.html"><i>prisca theologia</i></a> — the belief in a single primordial divine wisdom underlying all ancient philosophical and religious traditions — of which it represents the application to Jewish textual sources. Its integration with Hermetic sources in figures like Pico and Agrippa reflects the synthetic ambition of this project. The concept of <a href="../concepts/magia_naturalis.html"><i>Magia Naturalis</i></a> — natural magic as a legitimate philosophical enterprise — is closely related, since Christian Kabbalah provided both the theoretical framework (the divine Names and their power) and the practical techniques (the use of Hebrew letter-combinations in ritual) for a form of angelic or "spiritual" magic that sought to distinguish itself from the demonological tradition. The broader Hermetic theological framework of <a href="../concepts/theosophy.html">Christian Theosophy</a> in the 17th century — Böhme, Knorr, the Cambridge Platonists — represents the subsequent development of the Christian Kabbalistic synthesis in a Protestant and mystical-theological direction.</p>

<h2>Literature</h2>
<p>Secret, François. <i>Les Kabbalistes chrétiens de la Renaissance</i>. Paris: Dunod, 1964.</p>
<p>Wirszubski, Chaim. <i>Pico della Mirandola's Encounter with Jewish Mysticism</i>. Cambridge: Harvard University Press, 1989.</p>
<p>Idel, Moshe. <i>Kabbalah: New Perspectives</i>. New Haven: Yale University Press, 1988.</p>
<p>Dan, Joseph (ed.). <i>The Christian Kabbalah: Jewish Mystical Books and Their Christian Interpreters</i>. Cambridge: Harvard University Press, 1997.</p>
<p>Hanegraaff, Wouter J. (ed.). <i>Dictionary of Gnosis and Western Esotericism</i>. 2 vols. Leiden: Brill, 2006.</p>
<p>Yates, Frances A. <i>Giordano Bruno and the Hermetic Tradition</i>. London: Routledge and Kegan Paul, 1964.</p>
<p>Copenhaver, Brian P. <i>Hermetica: The Greek Corpus Hermeticum and the Latin Asclepius</i>. Cambridge: Cambridge University Press, 1992.</p>
<p>Reuchlin, Johannes. <i>De arte cabalistica</i>. Hagenau: Thomas Anshelm, 1517. English trans. Martin and Sarah Goodman. New York: Abaris Books, 1983.</p>
<p>Scholem, Gershom. <i>Major Trends in Jewish Mysticism</i>. New York: Schocken Books, 1941.</p>
<p>Knorr von Rosenroth, Christian. <i>Kabbala Denudata</i>. 2 vols. Sulzbach and Frankfurt: 1677–1684.</p>"""
}

# ---------------------------------------------------------------------------
# 4. SYMPHORIEN CHAMPIER
# ---------------------------------------------------------------------------
ENTRIES["symphorien_champier"] = {
    "definition_short": (
        "Symphorien Champier (c. 1472–c. 1539) was a French Renaissance physician, humanist, and prolific "
        "author based in Lyon who served as physician to Antoine, Duke of Lorraine. One of the earliest "
        "French enthusiasts of Ficino's Latin translations of the Corpus Hermeticum, Champier sought to "
        "synthesize Hermetic cosmology with Galenic medicine and Ficinian Neoplatonism in works including "
        "the Liber de quadruplici vita (1507). He is a significant figure in the transmission of Ficinian "
        "Hermeticism from Florence to French humanist circles in the early 16th century."
    ),
    "definition_long": """<p>Symphorien Champier (c. 1472–c. 1539) was a French Renaissance physician, humanist, and prolific author whose career was centered on Lyon — one of the great publishing and intellectual centers of early 16th-century France — and who served successively in the military campaigns of Louis XII and as personal physician to Antoine, Duke of Lorraine. Among the first French intellectuals to engage seriously with Marsilio Ficino's Latin translations of the <i>Corpus Hermeticum</i> (the <i>Pimander</i>, first published Florence, 1471), Champier produced a remarkable body of work attempting to synthesize Ficinian Neoplatonism, Hermetic cosmological theology, Galenic medicine, and Christian moral philosophy into a unified French humanist vision. While he does not rank among the first-order Renaissance philosophers — the synthetic ambition of his work often outpaced its philosophical rigor — his significance for the history of Hermeticism lies in his role as a cultural transmitter: it was substantially through Champier's writings that the Ficinian Hermetic synthesis became known to French humanist and medical circles before mid-century. Brian P. Copenhaver's work on Renaissance medical Hermeticism and Michael J. Heath's studies of French Renaissance humanism have provided the most useful modern assessments of his intellectual profile.</p>

<h2>Works and Intellectual Context</h2>
<p>Champier's most significant contribution to the Hermetic tradition is his <i>Liber de quadruplici vita</i> (Lyon: Claude Davost, 1507) — a composite work in four parts treating the active life (civic and military virtue), the contemplative life (philosophical meditation), the spiritual life (Christian devotion), and the "Hermetic life" modeled on the ideal of the sage-physician described in the philosophical Hermetica. The fourth book draws directly on Ficino's <i>De vita libri tres</i> (1489) and on the Hermetic tractates to construct an ideal of the physician as sage — a figure who combines medical knowledge, natural-philosophical understanding, astrological awareness, and spiritual contemplation in a unified life of service and wisdom. Champier's vision of the "Hermetic life" is not the isolated contemplative of the philosophical Hermetica but a socially engaged, practically effective physician-sage who participates in the world while remaining oriented toward divine wisdom.</p>

<p>His <i>Symphonia Platonis cum Aristotele et Galeni cum Hippocrate</i> (Paris: Josse Bade, 1516) represents his most ambitious philosophical project: an attempt to harmonize Platonism with Aristotelianism and Galenic medicine with Hippocratic empiricism, demonstrating the underlying unity of the Western philosophical and medical traditions. The Hermetic texts function in this project as a kind of metaframework — a primordial wisdom tradition that antedates both Plato and Aristotle and whose authority can adjudicate between their competing claims. This is a version of the <i>prisca theologia</i> synthesis in a specifically medical-philosophical key. Champier's knowledge of the <i>Corpus Hermeticum</i> was mediated entirely through Ficino's Latin translations and Ficino's extensive argumenta (prefatory essays) — he did not read Greek — which means that his Hermeticism is substantially Ficino's Hermeticism, filtered through a French medical-humanist sensibility.</p>

<p>Among his other works relevant to the Hermetic tradition: <i>Janua logicae et physicae</i> (1498), which includes early references to Hermetic natural philosophy; <i>Le myrouel des appothicaires et pharmacopoles</i> (1532), a French-language vernacular pharmacopoeia that incorporates Paracelsian elements; and the <i>Rosa gallica omnibus sanitatem affectantibus utilis et necessaria</i> (Paris, 1514), a medical encyclopedia that integrates astrological medicine — including Decan-based melothesia — into Galenic pharmacology. Champier also wrote historical works on the city of Lyon and on the antiquity of French civilization, applying his humanist historiographical skills to regional identity. His prolific output across genres — over fifty works, many of them compilations and anthologies — reflects both the frantic pace of early printing-press culture and the characteristically humanist ambition to synthesize and transmit across disciplinary boundaries.</p>

<h2>Hermetic Significance</h2>
<p>Champier's Hermetic significance is primarily that of a transmitter and popularizer rather than an original thinker. He stands at the intersection of several important cultural dynamics in the early 16th century: the northward diffusion of Italian Renaissance Neoplatonism (especially through the Lyon book trade and through his personal contacts with Italian humanists); the emergence of a specifically French Renaissance humanist culture that sought to integrate the new Italian learning with French civic and moral values; and the growing importance of the physician-humanist as a social type who combined intellectual ambition with practical professional identity. Champier's deployment of Hermetic materials — particularly the ideal of the sage-physician and the Hermetic cosmological framework — served his professional and cultural agenda: it elevated the status of medicine from a craft to a liberal art grounded in the highest philosophical and theological wisdom.</p>

<p>His reception of the <i>Asclepius</i> is particularly revealing. Where Ficino read the <i>Asclepius</i> primarily through its Neoplatonic theological framework — as a document of the Platonic tradition's knowledge of the divine — Champier reads it through a medical lens, emphasizing the Hermetic teachings on the sympathy between the human body (<i>microcosm</i>) and the celestial world (<i>macrocosm</i>), and applying them to the astrological medicine that governed diagnosis, prognosis, and treatment in learned 16th-century medical practice. This medical Hermeticism — the application of Hermetic cosmological doctrine to the reform of Galenic medicine — is one of the intellectual currents that eventually flows into the Paracelsian revolution, though Champier himself was not a Paracelsian and his framework remained fundamentally Galenic.</p>

<h2>Transmission and Reception</h2>
<p>Champier's works were read primarily within the Lyon and French humanist milieu of the first three decades of the 16th century. His influence on subsequent French Renaissance thought is difficult to measure precisely because he operated more as a catalyst than as a founder of a school: his synthetic compilations introduced French readers to materials — the Ficinian Hermetica, the Neoplatonic medical tradition, the astrological medicine of the Arabic sources — that they then pursued independently and in more sophisticated forms. He was in contact with Erasmus and with the Italian humanist milieu through his extensive correspondence and travels. His vernacular works contributed to the development of French as a language of scientific and philosophical discourse, anticipating the later efforts of Rabelais and the Pléiade. The subsequent history of French Renaissance Hermeticism — in figures such as Jacques Lefèvre d'Étaples, who also engaged with the Ficinian tradition, and in the medical-philosophical milieu that produced the Paracelsian reception in France — owes something to Champier's pioneering work of cultural transmission.</p>

<h2>Scholarly Debates</h2>
<p>The main scholarly questions about Champier concern the depth and originality of his engagement with Hermetic and Neoplatonic sources, and his relationship to the subsequent development of French Renaissance occult philosophy. Copenhaver's work on Renaissance medical Hermeticism places Champier within a tradition of physicians who used Ficinian materials to argue for the philosophical dignity of medicine — a tradition that also includes the Italian Giovanni Battista della Porta and the German Heinrich Cornelius Agrippa in different ways. The question of Champier's relationship to proto-Paracelsianism has been raised by historians of medicine: his incorporation of chemical and astrological elements into Galenic medical practice anticipates some features of the Paracelsian synthesis without sharing Paracelsus's radical anti-Galenism. Paul Oskar Kristeller's broader framework for understanding Renaissance Neoplatonism and its diffusion provides the essential context for Champier's role as a transmitter.</p>

<h2>Literature</h2>
<p>Copenhaver, Brian P. <i>Hermetica: The Greek Corpus Hermeticum and the Latin Asclepius</i>. Cambridge: Cambridge University Press, 1992.</p>
<p>Kristeller, Paul Oskar. <i>The Philosophy of Marsilio Ficino</i>. Translated by Virginia Conant. New York: Columbia University Press, 1943.</p>
<p>Hanegraaff, Wouter J. (ed.). <i>Dictionary of Gnosis and Western Esotericism</i>. 2 vols. Leiden: Brill, 2006.</p>
<p>Fowden, Garth. <i>The Egyptian Hermes: A Historical Approach to the Late Pagan Mind</i>. Cambridge: Cambridge University Press, 1986.</p>
<p>Walker, D. P. <i>Spiritual and Demonic Magic from Ficino to Campanella</i>. London: Warburg Institute, 1958.</p>
<p>Nauert, Charles G. <i>Agrippa and the Crisis of Renaissance Thought</i>. Urbana: University of Illinois Press, 1965.</p>
<p>Ficino, Marsilio. <i>Three Books on Life</i>. Edited and translated by Carol V. Kaske and John R. Clark. Binghamton: Medieval and Renaissance Texts and Studies, 1989.</p>
<p>Moran, Bruce T. <i>Distilling Knowledge: Alchemy, Chemistry, and the Scientific Revolution</i>. Cambridge: Harvard University Press, 2005.</p>"""
}


def main():
    conn = sqlite3.connect(DB_PATH)
    cur = conn.cursor()
    for slug, data in ENTRIES.items():
        cur.execute("SELECT slug FROM concepts WHERE slug = ?", (slug,))
        if not cur.fetchone():
            print(f"WARNING: slug not found in DB: {slug}")
            continue
        cur.execute(
            "UPDATE concepts SET definition_short = ?, definition_long = ? WHERE slug = ?",
            (data["definition_short"], data["definition_long"], slug)
        )
        dl_words = len(data["definition_long"].split())
        ds_words = len(data["definition_short"].split())
        print(f"Updated {slug}: def_short={ds_words} words, def_long={dl_words} words")
    conn.commit()
    conn.close()
    print("Batch 3 complete.")


if __name__ == "__main__":
    main()
