"""
Full encyclopedia biographies for modern scholars with short bio_html.
Idempotent: safe to re-run.
"""
import sqlite3
from pathlib import Path

DB = Path(r"c:\Dev\EmeraldTablet\db\emerald_tablet.db")
conn = sqlite3.connect(DB)

entries = {}

# ── Carl Jung ─────────────────────────────────────────────────────────────────
entries["carl_jung"] = """<p>Carl Gustav Jung (1875–1961), Swiss psychiatrist and founder of analytical psychology, produced the most influential psychological interpretation of Western alchemy and Gnosticism in the twentieth century. Born in Kesswil on Lake Constance, the son of a Protestant clergyman, Jung studied medicine at Basel and worked initially under Eugen Bleuler at the Burghölzli psychiatric clinic in Zurich. His early collaboration with Sigmund Freud — and his decisive break with Freud in 1912 over the nature of the libido — set the intellectual conditions for his life's work: a depth-psychological account of the human psyche in which the symbolism of mythology, religion, alchemy, and Gnosticism served as primary evidence. Jung's engagement with alchemical literature began in earnest in the early 1930s and occupied him until his death. His conclusion, stated most fully in <i>Psychology and Alchemy</i> (1944), was that alchemical symbolism represents the unconscious process of <i>individuation</i> — the drive of the psyche toward wholeness through the integration of conscious and unconscious contents. The transmutation of base metal into gold became, in his reading, a projection of the psyche's own transformative process, and the <i>lapis philosophorum</i> a symbol of the integrated self.</p>

<h2>Central Argument</h2>
<p>Jung's central thesis is that the symbolic language of <a href="../concepts/alchemy.html"><i>alchemy</i></a> — the <i>prima materia</i>, the <i>nigredo</i>, the <i>albedo</i>, the <i>rubedo</i>, the <i>coniunctio oppositorum</i> — maps directly onto the stages of psychological individuation. The alchemist, confronting the unconscious projections embedded in material substances, was unknowingly working through the integration of the shadow, the <i>anima</i> or <i>animus</i>, and ultimately the Self. This argument rests on his theory of archetypes: universal, inherited patterns of psychic organisation that appear across cultures and historical periods in mythology, religion, and in the dreams and fantasies of his clinical patients. Jung claimed to find the same imagery spontaneously in patients' dreams that he found in medieval alchemical manuscripts, and this cross-cultural resonance was for him the strongest evidence of the archetypes' reality. <i>Mysterium Coniunctionis</i> (1955–56), his last major work, takes the alchemical theme of the <i>coniunctio</i> — the union of sun and moon, sulphur and mercury, king and queen — as the emblem of the highest form of psychic integration. He drew most heavily on the work of <a href="../persons/ibn_umayl.html">Ibn Umayl</a> (Senior Zadith), whose <i>Tabula Chemica</i> he read as a sustained allegory of the psyche's encounter with its own unconscious depths. He also devoted sustained attention to <a href="../persons/zosimos_of_panopolis.html">Zosimos of Panopolis</a>'s dream visions, reading them as spontaneous products of the unconscious individuation process operating within a Late Antique alchemical practitioner. His engagement with Gnostic material — including the Pistis Sophia and the Valentinian systems — shaped his understanding of the archetype of the Self as a divine light hidden within matter and awaiting liberation, a motif he traced from Gnosticism through alchemy into the modern psyche.</p>

<h2>Key Works</h2>
<p><i>Psychology and Alchemy</i> (1944; Collected Works, vol. 12) is the central statement of Jung's alchemical interpretation, analysing a series of dreams alongside alchemical woodcuts from the Rosarium Philosophorum (1550). <i>Alchemical Studies</i> (Collected Works, vol. 13) collects his essays on Paracelsus, Zosimos's vision texts, and the spirit Mercurius, treated as a personification of the trickster archetype — the ambiguous, transformative figure who guides the soul through dissolution and reconstitution. <i>Mysterium Coniunctionis</i> (1955–56; Collected Works, vol. 14) is his most ambitious synthesis, tracing the <i>coniunctio</i> theme across the full range of alchemical literature in exhaustive detail. <i>Aion</i> (1951; Collected Works, vol. 9ii) addresses the symbolism of the Christ figure and the self through Gnostic and astrological material. <i>The Red Book</i> (Liber Novus), not published in full until 2009, records his own visionary experiences of 1913–30, revealing the personal imaginative substrate from which his theoretical interpretations grew and situating him as a practitioner as well as a theorist of the unconscious symbolic process he analysed in historical materials.</p>

<h2>Scholarly Lineage and Disputes</h2>
<p>Jung's most influential follower in the alchemy field was Marie-Louise von Franz, whose commentaries on alchemical texts extended his method across a wider range of primary sources. The methodological dispute with Wouter Hanegraaff is decisive: Hanegraaff argues in <i>New Age Religion and Western Culture</i> (1996) and <i>Esotericism and the Academy</i> (2012) that Jung's psychological reading systematically misrepresents the historical intention of alchemical authors, who meant their procedures religio-cosmologically or practically rather than as depth-psychological allegory. Lawrence Principe and William Newman, in <i>Alchemy Tried in the Fire</i> (Chicago, 2002), demonstrate through laboratory reconstruction that most alchemical language is sophisticated shorthand for actual chemical operations, making Jung's allegorising doubly inappropriate as a guide to historical meaning. Nevertheless, Jung's influence on twentieth-century reception of alchemy and <a href="../concepts/gnosis.html"><i>gnosis</i></a> has been immense: his framework shapes how millions of non-specialist readers encounter these traditions, and his interpretation cannot be ignored in any honest account of the modern history of ideas about Western esotericism.</p>

<h2>Literature</h2>
<p>Jung, Carl Gustav. <i>Psychology and Alchemy</i>. Translated by R.F.C. Hull. Collected Works, vol. 12. London: Routledge, 1953.<br>
Jung, Carl Gustav. <i>Mysterium Coniunctionis</i>. Translated by R.F.C. Hull. Collected Works, vol. 14. London: Routledge, 1963.<br>
Jung, Carl Gustav. <i>Alchemical Studies</i>. Translated by R.F.C. Hull. Collected Works, vol. 13. London: Routledge, 1967.<br>
Hanegraaff, Wouter J. <i>New Age Religion and Western Culture: Esotericism in the Mirror of Secular Thought</i>. Leiden: Brill, 1996.<br>
Principe, Lawrence M., and William R. Newman. <i>Alchemy Tried in the Fire</i>. Chicago: University of Chicago Press, 2002.<br>
Von Franz, Marie-Louise. <i>Alchemy: An Introduction to the Symbolism and the Psychology</i>. Toronto: Inner City Books, 1980.<br>
Shamdasani, Sonu. <i>Jung and the Making of Modern Psychology</i>. Cambridge: Cambridge University Press, 2003.</p>"""

# ── Moshe Idel ────────────────────────────────────────────────────────────────
entries["moshe_idel"] = """<p>Moshe Idel (born 1947 in Târgu Neamț, Romania), Israeli scholar of Jewish mysticism at the Hebrew University of Jerusalem, is the most important revisionist of Gershom Scholem's foundational history of Kabbalah and one of the central figures in scholarship on the intersection of Jewish mysticism with Renaissance Christian Hermetism. His first major work, <i>Kabbalah: New Perspectives</i> (1988), challenged Scholem's synthesis at its methodological foundations, arguing that Scholem's history had overemphasised the literary and Gnostic dimensions of the tradition at the expense of its ecstatic, theurgical, and performative dimensions. The figure of Abraham Abulafia (1240–c.1291), the Spanish Kabbalist who developed an elaborate system of letter-permutation and breath-control meditation aimed at prophetic experience, became Idel's paradigm case for a strand of Kabbalah that Scholem had marginalised. Idel's scholarship has subsequently reshaped the study of Jewish mysticism, Hermetism, and the Renaissance encounter between Jewish and Christian intellectual cultures.</p>

<h2>Central Argument</h2>
<p>Idel's revisionism proceeds on two fronts. Against Scholem's emphasis on Kabbalah's Gnostic content and its textual transmission, Idel insists on the primacy of practice: Kabbalah is not primarily a body of esoteric doctrine but a set of techniques — linguistic, contemplative, and theurgical — aimed at transforming the practitioner's relation to the divine. Where Scholem saw a single grand narrative moving from Gnostic origins through the Zohar to the Safed school of Luria, Idel sees multiple, relatively autonomous traditions pursuing different experiential and theological goals. His second major argument concerns the interaction between <a href="../concepts/kabbalah.html">Kabbalah</a> and Renaissance Christian thought. Where earlier scholarship had treated Christian Kabbalah as a superficial adoption of Jewish materials for Christian theological purposes, Idel argues for genuine intellectual exchange in which Kabbalistic ideas about language, <i>sefirot</i>, and divine names shaped the philosophical frameworks of Renaissance Christian thinkers in substantive ways. His work on <a href="../persons/giovanni_pico.html">Giovanni Pico della Mirandola</a> in <i>Kabbalah in Italy</i> (2011) demonstrates that Pico's engagement with Kabbalistic sources was more technically informed than previously acknowledged. This research has major implications for understanding the synthesis of Hermetism and Kabbalah in the Florentine Neoplatonic circle where Ficino and Pico collaborated, since it establishes that the Kabbalistic strand of that synthesis was not merely ornamental but carried genuine philosophical weight.</p>

<h2>Key Works</h2>
<p><i>Kabbalah: New Perspectives</i> (New Haven: Yale University Press, 1988) is the programmatic statement of Idel's revisionist methodology, introducing the categories of "theosophic-theurgical" and "ecstatic" Kabbalah as two major currents Scholem had illegitimately conflated. <i>The Mystical Experience in Abraham Abulafia</i> (Albany: SUNY Press, 1988) provides the detailed case study through Abulafia's techniques of letter-combination and linguistic meditation. <i>Golem: Jewish Magical and Mystical Traditions on the Artificial Anthropoid</i> (Albany: SUNY Press, 1990) traces the golem motif through Kabbalistic, magical, and philosophical literature. <i>Absorbing Perfections: Kabbalah and Interpretation</i> (New Haven: Yale University Press, 2002) addresses the hermeneutical theory underpinning Kabbalistic reading practices. <i>Kabbalah in Italy, 1280–1510</i> (New Haven: Yale University Press, 2011) provides the most detailed account of the Italian-Jewish context for Pico's Kabbalah.</p>

<h2>Scholarly Lineage and Disputes</h2>
<p>Idel's most sustained dispute is with Scholem's legacy as maintained by scholars such as Yehuda Liebes and Elliot Wolfson, who defend the primacy of the theosophical-mythological dimension of the Zohar against Idel's ecstatic alternative. His engagement with Christian Kabbalah places him in dialogue with Brian Copenhaver on Pico and with Wouter Hanegraaff on the broader history of Western esotericism. His methodological debts are to Scholem himself — he is a genuine heir who revises from within — but also to historians of religion such as Mircea Eliade and to the phenomenology of religious experience.</p>

<h2>Literature</h2>
<p>Idel, Moshe. <i>Kabbalah: New Perspectives</i>. New Haven: Yale University Press, 1988.<br>
Idel, Moshe. <i>The Mystical Experience in Abraham Abulafia</i>. Albany: State University of New York Press, 1988.<br>
Idel, Moshe. <i>Golem: Jewish Magical and Mystical Traditions on the Artificial Anthropoid</i>. Albany: SUNY Press, 1990.<br>
Idel, Moshe. <i>Kabbalah in Italy, 1280–1510</i>. New Haven: Yale University Press, 2011.<br>
Scholem, Gershom. <i>Major Trends in Jewish Mysticism</i>. New York: Schocken Books, 1941.<br>
Copenhaver, Brian P. "The Secret of Pico's Oration." <i>Midwest Studies in Philosophy</i> 26 (2002): 56–81.<br>
Hanegraaff, Wouter J. <i>Esotericism and the Academy</i>. Cambridge: Cambridge University Press, 2012.</p>"""

# ── Peter Forshaw ─────────────────────────────────────────────────────────────
entries["peter_forshaw"] = """<p>Peter J. Forshaw (born 1967), British scholar of Western esotericism at the University of Amsterdam, is among the most important specialists in Renaissance and early modern alchemical philosophy, Paracelsianism, and the visual culture of the occult sciences. Formed within the Amsterdam school of esotericism studies under <a href="../persons/wouter_hanegraaff.html">Wouter Hanegraaff</a>, Forshaw has concentrated his research on the intersection of alchemy, magic, Kabbalah, and Lutheran mysticism in the late sixteenth and early seventeenth centuries. His most distinctive contribution is the sustained scholarly rehabilitation of <a href="../persons/heinrich_khunrath.html">Heinrich Khunrath</a> (1560–1605), whose <i>Amphitheatrum Sapientiae Aeternae</i> (1595, expanded 1609) is among the most visually spectacular and philosophically ambitious texts of the Hermetic-alchemical tradition. Before Forshaw's work, Khunrath occupied a peculiar historiographical position: universally cited and frequently reproduced for its extraordinary engraved plates, but rarely subjected to sustained scholarly analysis of its philosophical argument. Forshaw's detailed reading established Khunrath as a coherent thinker — a physician, Paracelsian, and Lutheran mystic who fused practical alchemy with Kabbalistic speculation in a synthesis that is philosophically deliberate rather than merely eclectic.</p>

<h2>Central Argument</h2>
<p>Forshaw's central scholarly contribution is twofold. First, he argues that the visual culture of esotericism — its emblems, diagrams, and illustrated manuscripts — carries philosophical and theological arguments that cannot be adequately reconstructed from the verbal text alone. Khunrath's <i>Amphitheatrum</i> famously includes the "Alchemist's Laboratory-Oratory," in which a kneeling figure prays at one end of a room while retorts bubble at the other: for Forshaw, this image is not a pious embellishment but the central thesis of the work, stating that alchemical practice is simultaneously natural-philosophical investigation and spiritual devotion inseparable from each other. Second, Forshaw has placed Khunrath within the context of Paracelsian medicine and Lutheran theosophy, showing how his synthesis of the currents that prefigured <a href="../persons/jacob_boehme.html">Jakob Böhme</a> — Valentin Weigel, Sebastian Franck, German spiritualism — with Paracelsian alchemical medicine produced a distinctive form of Protestant Hermetism that could not have arisen in Catholic contexts. This framing challenges the traditional identification of Hermetism with Italian Renaissance Neoplatonism and insists on the importance of the German Reformation for the development of early modern occult philosophy.</p>

<h2>Key Works</h2>
<p>Forshaw's foundational article "Alchemical Drama" (<i>Ambix</i> 53, 2006) established the interpretive framework for reading the <i>Amphitheatrum Sapientiae Aeternae</i> as a unified philosophical performance. His contributions to Hanegraaff's <i>Dictionary of Gnosis and Western Esotericism</i> (Brill, 2006) synthesise current scholarship on Khunrath, Paracelsus, and alchemical imagery for a broader audience. His edited volume <i>Lux in Tenebris: The Visual and the Symbolic in Western Esotericism</i> (Brill, 2017) makes the case for visual culture as a primary object of esotericism research. He has also contributed to scholarly debates on <a href="../persons/john_dee.html">John Dee</a>'s mathematical and angelic philosophy and on the Paracelsian reform of medicine and natural philosophy, establishing his range across the full territory of early modern occult learning.</p>

<h2>Scholarly Lineage and Disputes</h2>
<p>Forshaw's methodological formation within the Amsterdam school means he shares Hanegraaff's commitment to the empirical-historical study of esotericism. His work on Khunrath is in dialogue with — and a correction of — the earlier historiography that treated the <i>Amphitheatrum</i> primarily as a document of the Rosicrucian imagination (the framework established by Frances Yates). Forshaw insists on Khunrath's pre-Rosicrucian context and on the specificity of his Lutheran-Paracelsian synthesis, which differs importantly from the later synthesis of <a href="../persons/michael_maier.html">Michael Maier</a> or Robert Fludd. His engagement with the visual dimension of <a href="../concepts/alchemy.html"><i>alchemy</i></a> has placed him in dialogue with art historians working on early modern emblematic culture.</p>

<h2>Literature</h2>
<p>Forshaw, Peter J. "Alchemical Drama: The Amphitheatre of Heinrich Khunrath." <i>Ambix</i> 53 (2006): 1–40.<br>
Forshaw, Peter J. (ed.). <i>Lux in Tenebris: The Visual and the Symbolic in Western Esotericism</i>. Leiden: Brill, 2017.<br>
Khunrath, Heinrich. <i>Amphitheatrum Sapientiae Aeternae</i>. Hamburg, 1595; expanded 1609. Facsimile: Stuttgart, 1992.<br>
Hanegraaff, Wouter J. (ed.). <i>Dictionary of Gnosis and Western Esotericism</i>. 2 vols. Leiden: Brill, 2006.<br>
Weeks, Andrew. <i>Paracelsus: Speculative Theory and the Crisis of the Early Reformation</i>. Albany: SUNY Press, 1997.<br>
Yates, Frances A. <i>The Rosicrucian Enlightenment</i>. London: Routledge, 1972.</p>"""

# ── Didier Kahn ───────────────────────────────────────────────────────────────
entries["didier_kahn"] = """<p>Didier Kahn (born 1965), French historian of alchemy and esotericism at the Centre national de la recherche scientifique (CNRS) in Paris, is the foremost authority on the history of alchemy in Renaissance France and on the reception of Paracelsian medicine in the French context. Working within the tradition of meticulous French archival historiography, Kahn has made French alchemy between approximately 1567 and 1625 — a period encompassing the Wars of Religion, the Edict of Nantes, and the early Bourbon monarchy — into a fully documented historical phenomenon. His scholarship demonstrates that alchemical practice, patronage, and publication were deeply embedded in the political, religious, and institutional conflicts of the French late Renaissance: alchemical projectors sought royal patronage at courts navigating Protestant–Catholic confessional politics, and alchemical texts circulated through the same networks as theological controversy and religious reform.</p>

<h2>Central Argument</h2>
<p>Kahn's central argument, stated most fully in <i>Alchimie et Paracelsisme en France à la fin de la Renaissance (1567–1625)</i> (Geneva: Droz, 2007), is that French <a href="../concepts/alchemy.html"><i>alchemy</i></a> in this period cannot be understood without reference to the specifically French configuration of confessional conflict, royal absolutism, and humanist culture. The arrival of Paracelsian medicine in France — championed by Joseph Du Chesne (Quercetanus) and attacked by <a href="../persons/andreas_libavius.html">Andreas Libavius</a> — was not a simple conflict between progressive chemistry and conservative Galenism, as earlier historiography had framed it, but a complex negotiation between different models of medical authority, religious conviction, and social legitimacy. Paracelsian practitioners frequently aligned themselves with Protestant reform or with Catholic mystical currents that found in <a href="../persons/paracelsus.html">Paracelsus</a>'s theosophical medicine an alternative to the scholastic medicine of the Paris Faculty. Kahn reconstructs this alignment through extensive archival research — patron records, letters, unpublished manuscripts, and printed ephemera — rather than canonical texts alone. His research on Paracelsus's French reception has substantially complicated the standard narrative in which Paracelsianism appears as a unified intellectual movement.</p>

<h2>Key Works</h2>
<p><i>Alchimie et Paracelsisme en France à la fin de la Renaissance (1567–1625)</i> (Geneva: Droz, 2007) is Kahn's masterwork: over seven hundred pages of documented history, arguing for alchemy's integration into the full social and institutional life of late Renaissance France. His co-edited collection with Sylvain Matton, <i>Alchimie: Art, histoire et mythes</i> (Paris: S.É.H.A., 1995), is a major reference collection. His numerous articles on individual alchemical figures — Joseph Du Chesne, Blaise de Vigenère, and others — have appeared in <i>Chrysopoeia</i> and in CNRS proceedings. His contributions to alchemy's historiography have engaged critically with Lawrence Principe and William Newman's laboratory-history approach, refining their framework by insisting on the French social context that their primarily English- and German-focused scholarship had not fully addressed.</p>

<h2>Scholarly Lineage and Disputes</h2>
<p>Kahn's methodological formation is in the French tradition of <i>histoire des mentalités</i> and the sociology of knowledge. He accepts the basic force of the Principe–Newman corrective against Jungian and spiritualising interpretations, but insists that the social and political dimensions of alchemical practice — patronage-seeking, confessional alignment, institutional competition — are as important as laboratory procedures and cannot be recovered from laboratory reconstruction alone. His work also engages with the question of what counts as "Paracelsianism," showing that in France the label was applied to a heterogeneous collection of practitioners whose only shared feature was opposition to the Galenic establishment, rather than genuine adherence to Paracelsus's complex theosophical system.</p>

<h2>Literature</h2>
<p>Kahn, Didier. <i>Alchimie et Paracelsisme en France à la fin de la Renaissance (1567–1625)</i>. Geneva: Droz, 2007.<br>
Kahn, Didier, and Sylvain Matton (eds.). <i>Alchimie: Art, histoire et mythes</i>. Paris: S.É.H.A., 1995.<br>
Principe, Lawrence M. <i>The Secrets of Alchemy</i>. Chicago: University of Chicago Press, 2012.<br>
Newman, William R., and Lawrence M. Principe. <i>Alchemy Tried in the Fire</i>. Chicago: University of Chicago Press, 2002.<br>
Debus, Allen G. <i>The French Paracelsians</i>. Cambridge: Cambridge University Press, 1991.<br>
Webster, Charles. <i>Paracelsus: Medicine, Magic and Mission at the End of Time</i>. New Haven: Yale University Press, 2008.</p>"""

# ── Florian Ebeling ───────────────────────────────────────────────────────────
entries["florian_ebeling"] = """<p>Florian Ebeling, German historian of religion and esotericism, is the author of <i>Das Geheimnis des Hermes Trismegistos: Geschichte des Hermetismus</i> (Munich: C.H. Beck, 2005), translated into English by David Lorton as <i>The Secret History of Hermes Trismegistus: Hermeticism from Ancient to Modern Times</i> (Ithaca: Cornell University Press, 2007). This volume represents the most concise and methodologically explicit synthetic account of the Hermetic tradition as a whole available in any language at the time of its publication. Working within the historiographical framework established by <a href="../persons/wouter_hanegraaff.html">Wouter Hanegraaff</a>, Ebeling organises the long history of Hermetism from its Egyptian antecedents through the <i>Corpus Hermeticum</i>'s Late Antique composition, the Arabic and medieval Latin transmission, the Renaissance rediscovery, and the modern period of Theosophy and New Age reception. The book is distinctive for its consistent methodological self-consciousness: it does not treat <a href="../concepts/hermeticism.html">Hermeticism</a> as an essence persisting unchanged from ancient Egypt to the present day, but traces the shifting cultural and intellectual functions that the name and texts of Hermes Trismegistus have been made to serve across radically different historical contexts.</p>

<h2>Central Argument</h2>
<p>Ebeling's central argument is that the figure of Hermes Trismegistus is not primarily a theological or philosophical claim but a cultural function: across its many different historical contexts, the name "Hermes Trismegistus" has served to authorise claims to ancient wisdom that are in fact products of their own period. This begins with the Late Antique Egyptian priestly milieu in which the philosophical Hermetica were actually composed — texts presenting themselves as ancient Egyptian wisdom while in fact articulating a synthesis of Middle Platonism, Stoic cosmology, and Egyptian religious tradition. It continues through Isaac Casaubon's famous 1614 philological demonstration that the <i>Corpus Hermeticum</i> postdated early Christianity — which destroyed the Hermetic texts' claim to <i>prisca theologia</i> authority while doing nothing to diminish their actual influence on European thought. And it extends into the modern period, where Theosophical and New Age movements have continued to invoke Hermes as a figure of perennial wisdom independently of the philological and historical scholarship that has reconstructed the actual history of the texts. Ebeling insists throughout that understanding the gap between the claimed and actual history of the Hermetic tradition is not debunking but a prerequisite for taking the tradition seriously as a historical phenomenon.</p>

<h2>Methodological Approach and Key Works</h2>
<p><i>The Secret History of Hermes Trismegistus</i> (2007) follows the chronological transmission of the Hermetic corpus from the Egyptian priestly context reconstructed by <a href="../persons/garth_fowden.html">Garth Fowden</a>'s <i>The Egyptian Hermes</i> (1986), through the Renaissance rediscovery focused on Marsilio Ficino's 1463 Latin translation and its consequences for Florentine Neoplatonism, through the Casaubon refutation and its complex aftermath, to the 20th-century reception in Jungian psychology, Theosophy, and New Age spirituality. Ebeling's methodological approach is historicist throughout: he situates each phase of the tradition's reception in its specific intellectual and social context, refusing both the Perennialist view that Hermetism transmits a timeless wisdom and the dismissive Enlightenment view that it is simply error. The book's brevity — under two hundred pages — makes it an ideal entry point for students approaching the Hermetic tradition, while its footnotes direct specialists to primary literature and to the most important recent scholarship.</p>

<h2>Scholarly Lineage and Disputes</h2>
<p>Ebeling's work is best understood as a synthesis and popularisation of the Amsterdam school's historiographical framework rather than as an independent research programme. His primary debts are to Hanegraaff's methodological writings, to Fowden's <i>The Egyptian Hermes</i>, and to Brian Copenhaver's scholarship on the Renaissance <i>Hermetica</i>. The book does not advance new archival findings; its contribution is to make the current state of scholarly understanding accessible to a broad audience without sacrificing methodological rigour. In the German academic context, it represents the first systematic application of the Amsterdam school's framework to a German-language audience, playing a similar pedagogical role to that of Hanegraaff's <i>Western Esotericism: A Guide for the Perplexed</i> (2012) in English.</p>

<h2>Literature</h2>
<p>Ebeling, Florian. <i>The Secret History of Hermes Trismegistus</i>. Translated by David Lorton. Ithaca: Cornell University Press, 2007.<br>
Hanegraaff, Wouter J. <i>Western Esotericism: A Guide for the Perplexed</i>. London: Bloomsbury, 2012.<br>
Fowden, Garth. <i>The Egyptian Hermes</i>. Cambridge: Cambridge University Press, 1986.<br>
Copenhaver, Brian P. (trans.). <i>Hermetica</i>. Cambridge: Cambridge University Press, 1992.<br>
Hanegraaff, Wouter J. <i>Esotericism and the Academy</i>. Cambridge: Cambridge University Press, 2012.<br>
Yates, Frances A. <i>Giordano Bruno and the Hermetic Tradition</i>. London: Routledge, 1964.</p>"""

# ── Hereward Tilton ───────────────────────────────────────────────────────────
entries["hereward_tilton"] = """<p>Hereward Tilton, British-Australian historian of alchemy and esotericism, is the author of <i>The Quest for the Phoenix: Spiritual Alchemy and Rosicrucianism in the Work of Count Michael Maier (1569–1622)</i> (Berlin: De Gruyter, 2003), the most detailed scholarly treatment of <a href="../persons/michael_maier.html">Michael Maier</a> available in English. Maier — physician, imperial count, court alchemist to Rudolf II, and author of the <i>Atalanta Fugiens</i> (1617) and <i>Symbola Aureae Mensae</i> (1617) — occupies a peculiar position in historiography: universally cited as one of the most important figures of early modern Hermetic-alchemical culture, but relatively neglected in detailed scholarly study. Tilton's monograph rectifies this neglect by reconstructing Maier's philosophical programme in its full complexity — drawing on his Latin texts, his correspondence, and the visual programme of his emblem books — and situating it within Rudolphine court culture, early Rosicrucianism, and the Paracelsian reform of natural philosophy.</p>

<h2>Central Argument</h2>
<p>Tilton's central argument is that Maier's alchemical philosophy is a coherent Hermetic-Neoplatonic synthesis rather than emblematic mystification or cryptic laboratory instruction. The <i>Atalanta Fugiens</i> — which combines fifty musical canons (the first alchemical musical compositions), fifty emblematic engravings, and fifty prose epigrams — is not primarily a work of esoteric entertainment but a sustained philosophical argument: that the alchemical process of transmutation is a recapitulation of the Neoplatonic process of emanation and return, and that the <i>lapis philosophorum</i> represents the soul's restoration to its divine origin. This reading is grounded in Tilton's detailed analysis of Maier's sources — particularly his use of <a href="../persons/marsilio_ficino.html">Marsilio Ficino</a>'s translations of the <i>Corpus Hermeticum</i> and his engagement with Paracelsus's concept of the <i>archeus</i> — and situates Maier's work as a deliberate attempt to answer the Rosicrucian challenge with a philosophically rigorous Hermetic programme. Tilton also demonstrates, through archival research, that Maier's relationship to the actual <a href="../concepts/rosicrucianism.html">Rosicrucian</a> movement was complex and ambivalent: he promoted Rosicrucianism in his <i>Silentium post Clamores</i> (1617) while simultaneously developing his own independent alchemical philosophy.</p>

<h2>Key Works and Methodological Approach</h2>
<p><i>The Quest for the Phoenix</i> (2003) combines intellectual history, textual analysis, and archival biography. Tilton reads Maier's Latin texts with philological precision while also attending to the social and patronage contexts — Rudolf II's Prague court, the English Hermetic circles of Robert Fludd and the Rosicrucian sympathisers — that shaped Maier's rhetorical strategies. His analysis of the <i>Atalanta Fugiens</i>'s musical canons — showing how the canonic structure (one melody pursuing another while a third sings a different tune) enacts the philosophical theme of soul pursuing perfection while guided by nature — is a particularly original contribution drawing on musicology as well as intellectual history. Tilton situates Maier within the broader tradition of Rudolphine court <a href="../concepts/alchemy.html"><i>alchemy</i></a> alongside figures such as Oswald Croll, Martin Ruland, and the English alchemist Edward Kelley.</p>

<h2>Scholarly Lineage and Disputes</h2>
<p>Tilton's work builds on pioneering studies of Maier by Joachim Telle and on the general framework for studying Rosicrucianism established by Frances Yates's <i>The Rosicrucian Enlightenment</i> (1972). He engages critically with Yates's tendency to read Rosicrucianism through the lens of intellectual history and symbolism, insisting on the importance of archival reconstruction of the actual social networks through which Rosicrucian ideas circulated. His methodological approach is closest to the Amsterdam school of esotericism studies — empirical, historicist, attentive to the actor/analyst distinction — and his work has been cited extensively by Peter Forshaw, Wouter Hanegraaff, and other Amsterdam-associated scholars.</p>

<h2>Literature</h2>
<p>Tilton, Hereward. <i>The Quest for the Phoenix: Spiritual Alchemy and Rosicrucianism in the Work of Count Michael Maier (1569–1622)</i>. Berlin: De Gruyter, 2003.<br>
Maier, Michael. <i>Atalanta Fugiens</i>. Oppenheim: Hieronymus Galler, 1617. Facsimile with translation by H.M.E. de Jong: Leiden: Brill, 1969.<br>
Yates, Frances A. <i>The Rosicrucian Enlightenment</i>. London: Routledge, 1972.<br>
Hanegraaff, Wouter J. (ed.). <i>Dictionary of Gnosis and Western Esotericism</i>. Leiden: Brill, 2006.<br>
Forshaw, Peter J. "Alchemical Drama." <i>Ambix</i> 53 (2006): 1–40.<br>
Telle, Joachim. <i>Sol und Luna</i>. Hürtgenwald: Pressler, 1980.</p>"""

# ── Marco Pasi ────────────────────────────────────────────────────────────────
entries["marco_pasi"] = """<p>Marco Pasi (born 1971 in Milan), Italian scholar of Western esotericism at the University of Amsterdam, is among the central figures of the Amsterdam school and has contributed both empirical research and theoretical reflection to the field. His empirical work focuses on the history of Thelema — the magical-philosophical system developed by Aleister Crowley — and on the relationship between esotericism and political ideology in the twentieth century. His theoretical contributions address the definitional problem of "esotericism" as a scholarly category: what does it mean to say that a text, practice, or movement belongs to the Western esoteric tradition, and what epistemic and ethical implications follow from such a classification? Trained at the European University Institute in Florence and formed intellectually within the Amsterdam school under <a href="../persons/wouter_hanegraaff.html">Wouter Hanegraaff</a>, Pasi represents a second generation of esotericism scholars who have consolidated and extended the Amsterdam methodological framework while also pushing it toward new empirical domains — particularly the history of modern occultism — that the school's first generation had left relatively underexplored.</p>

<h2>Central Argument</h2>
<p>Pasi's most distinctive theoretical contribution is his argument that "esotericism" can function as a valid comparative category if it is understood as a family-resemblance concept rather than an essential property. Against positions that would define esotericism by a fixed set of necessary and sufficient conditions (the approach of Antoine Faivre's typology) or dissolve it entirely as a mere scholarly projection (the most radical constructivist position), Pasi argues for a middle path: esotericism names a loosely connected family of practices, texts, and institutions sharing overlapping but not identical features, and the boundaries of this family are themselves objects of historical investigation rather than methodological stipulations. This approach allows him to study Aleister Crowley's Thelema — combining elements from the Hermetic Qabalah, Neoplatonism, Eastern religious traditions, and Crowley's own mythology — as genuinely esoteric without having to decide whether it is "really" continuous with earlier Hermetic traditions or represents a radical break. The question of continuity and rupture in esoteric history is, for Pasi, itself a historical question to be answered through empirical research rather than definitional stipulation.</p>

<h2>Key Works</h2>
<p><i>Aleister Crowley and the Temptation of Politics</i> (Acumen, 2014; Italian original, Mondadori, 1999) examines the intersections between Crowley's magical system and the political ideologies — fascism, nationalism, anarchism, libertarianism — he encountered across his long career. Pasi argues that Crowley's relationship to politics was not simply opportunism or provocation but reflects genuine tensions within Thelemic thought itself — particularly between its individualism (the Law of Thelema: "Do what thou wilt shall be the whole of the Law") and its rhetoric of hierarchy and mastery. This work opens a broader research programme on the relationship between modern <a href="../concepts/western_esotericism.html">Western esotericism</a> and political ideology. His theoretical articles in <i>Aries: Journal for the Study of Western Esotericism</i> address definitional questions about esotericism and the epistemological implications of studying contemporary esoteric movements alongside ancient and medieval traditions.</p>

<h2>Scholarly Lineage and Disputes</h2>
<p>Pasi's primary intellectual debts are to Hanegraaff's methodological writings — particularly the concept of "esotericism" as a modern scholarly construction that should be historicised rather than simply deployed — and to the broader tradition of the sociology of knowledge. He has engaged in productive dialogue with Kocku von Stuckrad on the question of whether esotericism is best understood as a "discourse" (von Stuckrad's term, drawing on Foucault) or as a set of practices and institutions (a more sociological framing). His engagement with Crowley places him in dialogue with <a href="../concepts/alchemy.html"><i>alchemy</i></a>'s modern historiographers and with cultural historians who have examined the relationship between esoteric movements and modernity more broadly, including Nicholas Goodrick-Clarke and Egil Asprem.</p>

<h2>Literature</h2>
<p>Pasi, Marco. <i>Aleister Crowley and the Temptation of Politics</i>. Durham: Acumen, 2014.<br>
Pasi, Marco. "The Neverendingly Told Story: Recent Biographies of Aleister Crowley." <i>Aries</i> 3 (2003): 224–245.<br>
Hanegraaff, Wouter J. <i>Esotericism and the Academy</i>. Cambridge: Cambridge University Press, 2012.<br>
Von Stuckrad, Kocku. <i>Western Esotericism: A Brief History of Secret Knowledge</i>. London: Equinox, 2005.<br>
Goodrick-Clarke, Nicholas. <i>The Occult Roots of Nazism</i>. London: I.B. Tauris, 1985.<br>
Asprem, Egil. <i>Arguing with Angels: Enochian Magic and Modern Occulture</i>. Albany: SUNY Press, 2012.</p>"""

# ── Write all to DB ───────────────────────────────────────────────────────────
for person_id, bio_html in entries.items():
    conn.execute(
        "UPDATE persons SET bio_html = ? WHERE person_id = ?",
        (bio_html.strip(), person_id)
    )
    chars = len(bio_html.strip())
    print(f"  Updated {person_id}: {chars:,} chars (~{chars // 6} words)")

conn.commit()
conn.close()
print("\nDone.")

