"""
write_bios_batch1.py — Five zero-bio persons
Idempotent: writes full bio_html for:
  - olympiodorus
  - suhrawardi
  - thomas_of_york
  - thierry_of_chartres
  - william_of_conches
"""
import sqlite3

DB_PATH = r"C:\Dev\EmeraldTablet\db\emerald_tablet.db"

BIOS = {}

# ---------------------------------------------------------------------------
# 1. OLYMPIODORUS
# ---------------------------------------------------------------------------
BIOS["olympiodorus"] = """<p>Olympiodorus the Younger (c. 495–570 CE) was a Neoplatonic philosopher and teacher who served as the head of the philosophical school at Alexandria during the 6th century, and whose name is associated with a significant body of alchemical writing preserved in the Byzantine Greek alchemical manuscript tradition. He is to be distinguished from several other figures who bore the same name in antiquity, including Olympiodorus the Elder (fl. c. 412 CE), an Athenian Neoplatonist, and Olympiodorus the historian of the Western Empire (fl. 5th century CE). Olympiodorus the Younger was among the last representatives of the Alexandrian Neoplatonic tradition before the school's decline following Justinian's restrictions on pagan philosophy (529 CE). His surviving philosophical works — commentaries on Plato's <i>Alcibiades I</i>, <i>Gorgias</i>, <i>Phaedo</i>, and on Aristotle's <i>Meteorologica</i> and <i>Categories</i> — establish him as a significant transmitter of Neoplatonic philosophical teaching in a Christian-dominated Late Antique context. His association with the alchemical tradition derives from the attribution of a treatise <i>On the Sacred Art</i> (<i>Peri tēs hierās technēs</i>) to "Olympiodorus the philosopher" in the Byzantine alchemical manuscript corpus.</p>

<h2>Works and Intellectual Context</h2>
<p>Olympiodorus the Younger worked in the tradition established by Ammonius of Alexandria (c. 435/445–517/526 CE), whose school had successfully navigated the transition from pagan to Christian intellectual culture by focusing on philosophical commentary — particularly on Aristotle — rather than on pagan cult or theology. Olympiodorus continued this accommodating approach, producing commentaries that engaged seriously with Platonic and Aristotelian philosophy while operating in a Christianized institutional environment. His commentary on the <i>Phaedo</i> is particularly important: it preserves significant material on Neoplatonic psychology, the soul's relationship to the body, and the philosophical dimensions of death and the afterlife — themes directly relevant to the alchemical tradition's concerns with purification and transformation.</p>

<p>The alchemical text attributed to "Olympiodorus the philosopher" — edited by Marcellin Berthelot and Charles-Émile Ruelle in their monumental <i>Collection des anciens alchimistes grecs</i> (3 vols., Paris, 1887–1888) — is a commentary on the alchemical writings of pseudo-Democritus (<i>Physika kai Mystika</i>) and Zosimos of Panopolis. The text engages with the allegorical dimensions of alchemical practice — the "divine water," the tinctures, the transformation of metals — in terms drawn from Neoplatonic metaphysics, treating the alchemical process as an analogue of the philosophical soul's purification and ascent. Whether the author of this alchemical treatise is identical with Olympiodorus the Younger the philosopher, or whether the attribution is a later pseudepigraphic assignment designed to lend philosophical authority to alchemical writing, is a question that modern scholarship has not definitively resolved. Michela Pereira, Lawrence M. Principe, and other scholars of the Hellenistic and Byzantine alchemical tradition have noted the difficulty: the alchemical <i>On the Sacred Art</i> shows familiarity with the Neoplatonic philosophical tradition consistent with an Alexandrian school context, but this familiarity could as well reflect the broad education of a 5th or 6th-century Alexandrian intellectual as the specific authorship of the historical Olympiodorus.</p>

<h2>Hermetic Significance</h2>
<p>The Olympiodoran alchemical text, whatever its authorship, represents an important moment in the integration of Neoplatonic philosophical categories into the interpretation of alchemical practice. The author — referred to here as "Olympiodorus" following manuscript tradition without prejudging the identification question — treats the operations of the sacred art as philosophically serious activities whose significance goes beyond mere technical metallurgy. The transformation of base metals is read as an analogue of the Neoplatonic soul's purification: just as the soul must be stripped of its material accretions through philosophical discipline before it can return to its divine source, so the base metal must be dissolved, purified, and reconstituted through the operations of the alchemical art before it can achieve its perfect form. This allegorical reading does not deny the material reality of the operations — the text contains specific procedural instructions — but frames them within a cosmological and psychological interpretation that connects practical alchemy to the broader Hermetic-Neoplatonic tradition of Late Antiquity.</p>

<p>The text preserves significant material on Zosimos of Panopolis and pseudo-Democritus, serving as a crucial witness for the state of the Greek alchemical tradition in the 6th century. Its discussion of the "divine water" (<i>theion hydōr</i>) — the universal solvent and transforming agent of Greek alchemy — connects to the broader Hermetic pneumatological tradition in which water, spirit, and light are the primary agents of cosmic transformation. The text also preserves important information about the social organization of the alchemical tradition: the reference to alchemical "adepts" (<i>philosophoi</i>) who guard the secrets of the art from the uninitiated echoes the initiatory language of the Hermetic philosophical texts and of the mystery traditions of Late Antiquity.</p>

<h2>Transmission and Reception</h2>
<p>The alchemical text attributed to Olympiodorus was preserved in the Byzantine Greek alchemical manuscript tradition, the same corpus that preserved the writings of Zosimos, Synesius, and the pseudo-Democritean texts. The primary manuscripts are collected in Berthelot and Ruelle's <i>Collection</i> — the foundational scholarly edition of the Greek alchemical corpus, now partially superseded by more recent critical work but still indispensable. The philosophical commentaries of Olympiodorus the Younger were transmitted through the Byzantine philosophical tradition and have been edited in the Commentaria in Aristotelem Graeca series and in individual critical editions. The dual transmission — philosophical and alchemical — under the same name contributed to the subsequent conflation of the two bodies of work in Renaissance and early modern alchemical anthologies, where "Olympiodorus" appears as an authority on both Platonic philosophy and alchemical practice.</p>

<h2>Scholarly Debates</h2>
<p>The principal scholarly debate concerns the identification of the alchemical "Olympiodorus the philosopher" with the historical Olympiodorus the Younger of Alexandria. The Berthelot-Ruelle edition assumed the identification as probable; subsequent scholarship has been more cautious. The alchemical text's Neoplatonic philosophical vocabulary is consistent with Alexandrian school culture of the 5th–6th century, but this is consistent with multiple possible authors. Matteo Martelli's work on the Byzantine transmission of Greek alchemy and Robert Halleux's studies of the alchemical manuscript tradition have clarified the textual situation without definitively resolving the authorship question. The broader question of the relationship between the Alexandrian Neoplatonic school and the alchemical tradition — how much mutual awareness and influence existed between professional philosophers and alchemical practitioners in Late Antique Alexandria — remains an active area of research.</p>

<h2>Literature</h2>
<p>Berthelot, Marcellin and Charles-Émile Ruelle. <i>Collection des anciens alchimistes grecs</i>. 3 vols. Paris: Steinheil, 1887–1888.</p>
<p>Westerink, L. G. (ed.). <i>Olympiodorus: In Platonis Gorgiam commentaria</i>. Leipzig: Teubner, 1970.</p>
<p>Westerink, L. G. (ed.). <i>The Greek Commentaries on Plato's Phaedo</i>. Vol. 1: Olympiodorus. Amsterdam: North-Holland Publishing, 1976.</p>
<p>Principe, Lawrence M. <i>The Secrets of Alchemy</i>. Chicago: University of Chicago Press, 2013.</p>
<p>Fowden, Garth. <i>The Egyptian Hermes: A Historical Approach to the Late Pagan Mind</i>. Cambridge: Cambridge University Press, 1986.</p>
<p>Halleux, Robert. <i>Les textes alchimiques</i>. Turnhout: Brepols, 1979.</p>
<p>Hanegraaff, Wouter J. (ed.). <i>Dictionary of Gnosis and Western Esotericism</i>. 2 vols. Leiden: Brill, 2006.</p>
<p>Blumenthal, H. J. "529 and Its Sequel: What Happened to the Academy?" <i>Byzantion</i> 48 (1978): 369–385.</p>"""

# ---------------------------------------------------------------------------
# 2. SUHRAWARDI
# ---------------------------------------------------------------------------
BIOS["suhrawardi"] = """<p>Shihab al-Din Yahya al-Suhrawardi (c. 1155–1191 CE), known as <i>Shaykh al-Ishraq</i> (Master of Illumination), was a Persian philosopher and mystic who founded the school of Illuminationist (<i>Ishraqi</i>) philosophy — one of the most significant intellectual traditions of medieval Islamic thought and one that explicitly incorporated the figure of Hermes Trismegistus into a prophetic chain of primordial wisdom. Born in Suhraward, in the northwestern Iranian province of Zanjan, he was educated in Maragha and Isfahan before traveling extensively through Anatolia and Syria. Executed in Aleppo under Saladin at approximately the age of 36 — the circumstances are disputed, probably involving both political and theological charges — he left a substantial body of philosophical and mystical writing that his students preserved and that formed the foundation of the Ishraqi tradition continued by figures including Mulla Sadra (1572–1640) and Qutb al-Din Shirazi (1236–1311). His importance for the history of Hermeticism lies in his explicit integration of Hermes Trismegistus — identified in the Islamic tradition with the Quranic prophet Idris — into a lineage of divine wisdom that runs from the primordial sages of Persia and Egypt through Greek philosophy to Islamic prophethood.</p>

<h2>Works and Intellectual Context</h2>
<p>Suhrawardi's philosophical corpus falls into two broad categories: the peripatetic (<i>mashayi</i>) treatises, written in a discursive Aristotelian style and dealing with logic, natural philosophy, and metaphysics; and the Illuminationist (<i>ishraqi</i>) works, written in a more mystical and symbolic register that draws on Platonic, Neoplatonic, and Iranian Zoroastrian sources. His masterpiece is <i>Hikmat al-Ishraq</i> (The Philosophy of Illumination, c. 1186 CE), a systematic philosophical work that begins with an Aristotelian critique of the theory of definition and proceeds to a complete metaphysical system grounded in the ontology of light. In Suhrawardi's system, existence is fundamentally luminous: God is the Light of Lights (<i>Nur al-Anwar</i>), and all beings are characterized by their degree of luminosity — their capacity to receive and transmit divine light. The system represents a deliberate synthesis of Platonic form theory, Neoplatonic emanationism, Zoroastrian light-cosmology, and Islamic Sufi mystical experience.</p>

<p>Related works include <i>Hayakil al-Nur</i> (The Temples of Light), a shorter philosophical meditation on the body as the temple of the luminous soul; <i>Al-Talwihat</i> (The Intimations), a systematic philosophical work in the peripatetic mode; and a series of mystical narratives (<i>qisas</i>) — including <i>The Red Intellect</i>, <i>The Rustling of Gabriel's Wing</i>, and <i>In the Land of Exile</i> — that use allegorical narrative and visionary imagery to convey the soul's journey toward illumination. These visionary narratives are particularly significant for the Hermetic tradition: they draw on the Iranian mythological geography of Hurqalya (the imaginal world intermediate between the material and the intelligible) and on the figure of the celestial guide who leads the soul upward — a figure that has deep structural affinities with the Hermetic guide-Poimandres of CH I.</p>

<h2>Hermetic Significance</h2>
<p>Suhrawardi's significance for the history of Hermeticism is multidimensional. Most directly, he explicitly incorporates Hermes Trismegistus — whom he identifies with Idris, the Quranic prophet of wisdom — into a chain of primordial sages (<i>hukama</i>) that stretches from the ancient Iranian sage-kings (Kayumarth, Faridun, Kay Khusraw) through Agathodaemon (identified with Seth or with the Greek hermetist), Asclepius, Pythagoras, Plato, and into the Islamic tradition. This wisdom chain (<i>silsila</i>) functions as the Illuminationist counterpart of the Hermetic <i>prisca theologia</i> — the claim of a primordial revelation transmitted through a chain of wise initiates. Kevin van Bladel's <i>The Arabic Hermes: From Pagan Sage to Prophet of Science</i> (2009) provides the definitive account of how Hermes came to be identified with Idris in the Islamic tradition, a development that makes Suhrawardi's synthesis possible.</p>

<p>John Walbridge's studies — particularly <i>The Leaven of the Ancients: Suhrawardi and the Heritage of the Greeks</i> (2000) and <i>The Wisdom of the Mystic East: Suhrawardi and Platonic Orientalism</i> (2001) — have provided the most sophisticated account of Suhrawardi's relationship to Greek philosophical sources, demonstrating that his engagement with Platonism and Neoplatonism was substantive and philosophically significant, not merely decorative. Suhrawardi's "Oriental philosophy" (<i>hikmat al-ishraq</i>) is not a simple appropriation of Western or Greek thought but a genuine synthesis in which Greek, Iranian, and Islamic elements are transformed into a new philosophical vision. The Hermetic element — via the Arabic Hermes tradition — is one constituent of this synthesis rather than its dominant component, but it is genuinely present and philosophically operative.</p>

<h2>Transmission and Reception</h2>
<p>Suhrawardi's Illuminationist philosophy had its most enduring impact in the Persian-speaking Islamic world, where it became one of the three main strands of Islamic philosophy alongside the Peripatetic (<i>mashayi</i>) tradition of Avicenna and the later speculative mysticism (<i>irfan</i>) of Ibn Arabi. Mulla Sadra (1572–1640), the greatest philosopher of the Safavid period, incorporated Ishraqi elements into his system of "Transcendent Wisdom" (<i>hikmat al-mutaaliya</i>) along with Avicennan philosophy and Ibn Arabian mysticism. In the Ottoman world, Suhrawardi's works were studied in the madrasa curriculum and were commented on by scholars including Mulla Lutfallah Khunaji. The reception of Suhrawardi in the modern West was shaped primarily by Henry Corbin (1903–1978), the French orientalist and philosopher whose four-volume <i>En Islam iranien</i> (1971–1972) and whose translations and editions of Suhrawardi's works gave the Ishraqi tradition its first sustained Western scholarly attention. Corbin's interpretation — deeply influenced by his own Heideggerian and phenomenological philosophical commitments — should be used critically, as Walbridge and others have noted, but it remains indispensable as an introduction to the tradition.</p>

<h2>Scholarly Debates</h2>
<p>The principal scholarly debates about Suhrawardi concern the sources and originality of his philosophical synthesis, and the appropriate interpretive framework for understanding his relationship to the Islamic mystical tradition. Corbin's reading emphasized the continuity between Suhrawardi and the Iranian mythological tradition, the angelology of Zoroastrianism, and the Shi'ite esotericism of the Imam — a reading that Walbridge has substantially qualified by insisting on the Greek philosophical dimensions of the Ishraqi system and by demonstrating that Suhrawardi's relationship to Zoroastrian sources is more selective and mediated than Corbin implied. Seyyed Hossein Nasr's presentations of Suhrawardi in <i>Three Muslim Sages</i> (1964) and related works offer an appreciative philosophical reading within the framework of perennial philosophy, which Hanegraaff's methodological framework would classify as an Analyst-level perspective that should be distinguished from strictly historical analysis. The political circumstances of Suhrawardi's execution remain incompletely understood: the charges likely involved accusations of heresy (for claiming to receive fresh prophetic revelation) combined with political intrigue in Saladin's court, but the relative weight of these factors is disputed.</p>

<h2>Literature</h2>
<p>Walbridge, John. <i>The Leaven of the Ancients: Suhrawardi and the Heritage of the Greeks</i>. Albany: SUNY Press, 2000.</p>
<p>Walbridge, John. <i>The Wisdom of the Mystic East: Suhrawardi and Platonic Orientalism</i>. Albany: SUNY Press, 2001.</p>
<p>Van Bladel, Kevin. <i>The Arabic Hermes: From Pagan Sage to Prophet of Science</i>. Oxford: Oxford University Press, 2009.</p>
<p>Corbin, Henry. <i>En Islam iranien: Aspects spirituels et philosophiques</i>. 4 vols. Paris: Gallimard, 1971–1972.</p>
<p>Nasr, Seyyed Hossein. <i>Three Muslim Sages: Avicenna, Suhrawardi, Ibn Arabi</i>. Cambridge: Harvard University Press, 1964.</p>
<p>Suhrawardi. <i>The Philosophy of Illumination</i>. Translated and edited by John Walbridge and Hossein Ziai. Provo: Brigham Young University Press, 1999.</p>
<p>Hanegraaff, Wouter J. (ed.). <i>Dictionary of Gnosis and Western Esotericism</i>. 2 vols. Leiden: Brill, 2006.</p>
<p>Ziai, Hossein. <i>Knowledge and Illumination: A Study of Suhrawardi's Hikmat al-Ishraq</i>. Atlanta: Scholars Press, 1990.</p>"""

# ---------------------------------------------------------------------------
# 3. THOMAS OF YORK
# ---------------------------------------------------------------------------
BIOS["thomas_of_york"] = """<p>Thomas of York (fl. c. 1250–1282) was an English Franciscan philosopher, theologian, and encyclopedist whose vast synthetic work <i>Sapientiale</i> (c. 1256–1260) represents one of the most ambitious attempts to harmonize Aristotelian natural philosophy with Christian theology and with the broader tradition of ancient wisdom — including texts attributed to Hermes Trismegistus — in 13th-century scholastic thought. A member of the Oxford Franciscan school, Thomas worked within the tradition established by Robert Grosseteste and developed by Roger Bacon, combining serious engagement with the newly available Aristotelian and Arabic philosophical texts with a concern to maintain the priority of Christian theological truth. David Porreca's meticulous research on the medieval scholastic reception of Hermetic texts has established Thomas of York as one of the most significant early scholastic philosophers to cite Hermes Trismegistus as a named philosophical authority — deploying Hermetic material alongside Aristotle, Avicenna, and the Church Fathers in systematic philosophical argument.</p>

<h2>Works and Intellectual Context</h2>
<p>The <i>Sapientiale</i> — Thomas's principal surviving work, edited in critical studies by George Bridges and others — is a massive encyclopedic work in seven books covering the whole of natural philosophy, metaphysics, and theology as understood in the mid-13th century. The work's title (roughly, "Book of Wisdom") signals its synthetic ambition: Thomas intended to demonstrate that all the wisdom of antiquity — Greek, Arabic, and Hermetic — converged upon and was perfected by Christian theology. This was a common strategy in the high scholastic period, visible also in Albertus Magnus's encyclopedic works and in the theological synthesis of Thomas Aquinas, but Thomas of York's version is notable for the prominence it gives to explicitly Hermetic sources.</p>

<p>Thomas drew upon the Hermetic texts available to him in Latin: the <i>Asclepius</i> (preserved in the corpus of Apuleius), the <i>Liber XXIV Philosophorum</i> (the collection of philosophical propositions attributed to Hermes), and various shorter Hermetic sententiae preserved in florilegia and encyclopedic collections. He also had access to the Arabic-Latin alchemical tradition, which preserved additional Hermetic material alongside the philosophical Hermetic texts. Porreca's analysis of the <i>Sapientiale</i> identifies specific passages in which Thomas cites "Hermes" or "Trismegistus" as an authority on theological and metaphysical questions — including questions about the nature of God, the structure of creation, and the relationship between intellect and matter — placing these citations alongside patristic and Aristotelian references in systematic arguments. This use of Hermetic authority is significant: it demonstrates that in the Oxford Franciscan milieu of the mid-13th century, Hermetic texts were regarded as serious philosophical sources worthy of citation in the highest-level theological argumentation.</p>

<h2>Hermetic Significance</h2>
<p>Thomas of York's significance for the history of Hermeticism lies precisely in his role as evidence for the circulation and intellectual status of Hermetic texts in the Latin scholastic tradition before the Renaissance recovery of the Greek <i>Corpus Hermeticum</i>. The standard historiographical narrative sometimes implies that Hermeticism was essentially absent from medieval European thought, awaiting the rediscovery of the Greek texts by Ficino in 1463. Porreca's research on the <i>Hermes Latinus</i> tradition — and Thomas of York's <i>Sapientiale</i> is a crucial piece of this evidence — demonstrates that this narrative is incorrect: Hermetic texts, particularly the <i>Asclepius</i> and the <i>Liber XXIV Philosophorum</i>, circulated widely in the medieval Latin tradition and were taken seriously as philosophical authorities by major scholastic thinkers.</p>

<p>Thomas's use of the <i>Liber XXIV Philosophorum</i> is particularly significant. The text's famous second proposition — "God is an infinite sphere whose center is everywhere and circumference nowhere" — appears in the <i>Sapientiale</i> as part of an argument about divine omnipresence and incomprehensibility. By deploying this Hermetic formula alongside patristic and Aristotelian arguments, Thomas integrates Hermetic theological language into the mainstream of Latin scholastic theology in a way that demonstrates both the availability and the prestige of the Hermetic sources in the Oxford Franciscan context. The formula subsequently appeared in Alan of Lille, Albertus Magnus, and many other scholastic writers — its transmission being precisely the kind of phenomenon that Porreca's <i>Hermes Latinus</i> research program has traced.</p>

<h2>Transmission and Reception</h2>
<p>Thomas of York's <i>Sapientiale</i> had a modest but real circulation in the later 13th and 14th centuries. Its influence was primarily local — within the English Franciscan tradition — and it did not achieve the pan-European reception of Albertus Magnus's works or the <i>Summa theologiae</i> of Thomas Aquinas. The work survives in a small number of manuscripts and was not printed in the early modern period. Its interest for modern scholarship is primarily as evidence for the intellectual culture of the Oxford Franciscan school and as a source for the history of the <i>Hermes Latinus</i> tradition — the cumulative body of Latin Hermetic material available in the medieval period. Porreca's research program has brought Thomas of York into visibility as a significant data point in the mapping of medieval Hermetic reception.</p>

<h2>Scholarly Debates</h2>
<p>The principal scholarly questions about Thomas of York concern the extent and depth of his engagement with Hermetic sources — how much he actually knew about the Hermetic tradition as opposed to citing isolated Hermetic sententiae lifted from florilegia — and his relationship to the broader 13th-century synthesis of Christian theology with non-Christian philosophical sources. Porreca's work is the starting point for any serious engagement with Thomas's use of Hermetic material. The broader context is provided by Charles Burnett's research on the 12th-century translation movement and by Paolo Lucentini's work on the medieval reception of the <i>Liber XXIV Philosophorum</i>. The question of how Thomas situates Hermetic authority in relation to Aristotelian, Augustinian, and Avicennan authority within his synthetic framework — whether Hermetic material is genuinely integrated or merely decorative — is a question that warrants further investigation.</p>

<h2>Literature</h2>
<p>Porreca, David. "Hermes Trismegistus in the Latin Middle Ages." PhD dissertation. University of Waterloo, 2001.</p>
<p>Lucentini, Paolo and Mark D. Delp. <i>Hermetis Trismegisti De sex rerum principiis</i>. Turnhout: Brepols, 2006.</p>
<p>Hanegraaff, Wouter J. (ed.). <i>Dictionary of Gnosis and Western Esotericism</i>. 2 vols. Leiden: Brill, 2006.</p>
<p>Burnett, Charles. "The Coherence of the Arabic-Latin Translation Program in Toledo in the Twelfth Century." <i>Science in Context</i> 14 (2001): 249–288.</p>
<p>Copenhaver, Brian P. <i>Hermetica: The Greek Corpus Hermeticum and the Latin Asclepius</i>. Cambridge: Cambridge University Press, 1992.</p>
<p>Dronke, Peter (ed.). <i>A History of Twelfth-Century Western Philosophy</i>. Cambridge: Cambridge University Press, 1988.</p>
<p>Baeumker, Clemens. <i>Das pseudo-hermetische Buch der vierundzwanzig Meister (Liber XXIV philosophorum)</i>. Münster: Aschendorff, 1913.</p>"""

# ---------------------------------------------------------------------------
# 4. THIERRY OF CHARTRES
# ---------------------------------------------------------------------------
BIOS["thierry_of_chartres"] = """<p>Thierry of Chartres (d. c. 1150–1155) was one of the most learned scholars of the 12th-century Latin West — Chancellor of the Cathedral School of Chartres from approximately 1141 and a leading figure in what Charles Homer Haskins called the "Renaissance of the Twelfth Century." A master in the tradition of Bernard of Chartres and a contemporary of William of Conches and Gilbert of Poitiers, Thierry combined an encyclopedic knowledge of the liberal arts (grammar, rhetoric, logic, arithmetic, geometry, music, and astronomy) with a bold application of Platonic and Hermetic cosmological categories to the interpretation of Christian scripture — an application that generated both admiration and controversy among his contemporaries. His importance for the history of Hermeticism lies in his direct and explicit use of the Latin <i>Asclepius</i> — the only complete Hermetic treatise available in the medieval Latin tradition — as a cosmological authority in his reading of Genesis, making him one of the clearest examples of Hermetic natural philosophy within mainstream Latin scholastic theology.</p>

<h2>Works and Intellectual Context</h2>
<p>Thierry's principal surviving works include his <i>Tractatus de sex dierum operibus</i> (Treatise on the Works of the Six Days, c. 1130s), a commentary on the first chapter of Genesis using Platonic and natural-philosophical categories; his commentary on Cicero's <i>De inventione</i>; his commentary on Boethius's <i>De trinitate</i>; and fragments and records of his lectures preserved by students including Herman of Carinthia and Clarenbaldus of Arras. His most significant project for the history of the liberal arts is the <i>Heptateuchon</i> — a massive anthology of the seven liberal arts that Thierry compiled as a comprehensive educational textbook, drawing on the full range of Latin literary and philosophical sources available to him. The <i>Heptateuchon</i> is evidence of the extraordinary breadth of Thierry's learning and of his ambition to create a systematic curriculum for philosophical education.</p>

<p>The <i>Tractatus de sex dierum operibus</i> is Thierry's most philosophically daring work and the text most directly relevant to the Hermetic tradition. In it, Thierry reads the six days of creation through a framework drawn from Plato's <i>Timaeus</i>, the Stoic doctrine of the <i>logos spermatikos</i> (seminal reason), and — crucially — the <i>Asclepius</i> of Hermes Trismegistus. Thierry identifies the <i>spiritus</i> ("spirit") of Genesis 1:2 — "the spirit of God moved upon the face of the waters" — with the Hermetic World Soul (<i>anima mundi</i>) described in the <i>Asclepius</i>: a divine principle that pervades and animates matter, endowing it with the capacity for rational self-organization. This identification was bold: it read the opening of the Hebrew Bible through a pagan philosophical lens, making Hermes Trismegistus an implicit authority for the interpretation of Christian scripture. Edouard Jeauneau, the leading modern editor and interpreter of Thierry's works, has provided the most detailed scholarly account of this move and its implications.</p>

<h2>Hermetic Significance</h2>
<p>Thierry of Chartres represents a remarkable moment in the medieval reception of Hermetic ideas: the explicit use of the <i>Asclepius</i> as a cosmological authority within the most prestigious genre of Christian intellectual life — the biblical commentary. His identification of the Genesis <i>spiritus</i> with the Hermetic World Soul demonstrates that the <i>Asclepius</i> was not merely quarantined as a pagan curiosity but was actively integrated into the central project of 12th-century Christian theology. Brian Stock's analysis in <i>Myth and Science in the Twelfth Century</i> (1972) situates Thierry within a broader 12th-century naturalist movement that used Hermetic and Platonic cosmology to develop a philosophy of nature grounded in secondary causation — the principle that God acts through the regular operations of nature rather than by miraculous intervention at each moment. This naturalism, which Thierry shares with William of Conches and Bernard Silvester, prepared the intellectual ground for the subsequent reception of Aristotelian natural philosophy in the 13th century.</p>

<p>Peter Dronke's contributions to <i>A History of Twelfth-Century Western Philosophy</i> (1988) and Winthrop Wetherbee's work on the literary and philosophical dimensions of the Chartrian tradition provide important context for Thierry's Hermetic synthesis. The concept of "immanence of ratio" — introduced by Mark Damien Delp to describe the 12th-century tendency to ground rational inquiry in Hermetic cosmological doctrine — applies directly to Thierry's project: his use of the <i>Asclepius</i>'s World Soul doctrine legitimates the rational investigation of nature by grounding it in a divine rational principle immanent in creation. This is Hermeticism in the service of natural-philosophical rationalism, not in the service of occult practice or ritual magic.</p>

<h2>Transmission and Reception</h2>
<p>Thierry's works circulated within the 12th-century schools and influenced a number of significant figures. Herman of Carinthia, one of the great translators of the Toledo translation movement, was a student of Thierry and carried elements of his Platonic-Hermetic cosmology into his translation project and into his own cosmological work <i>De essentiis</i> (c. 1143). Clarenbaldus of Arras, another student, wrote a commentary on Thierry's commentary on Boethius's <i>De trinitate</i> that helps reconstruct aspects of Thierry's theology. The influence of Thierry's cosmological synthesis on the 12th-century literary Neoplatonism of Bernard Silvester (<i>Cosmographia</i>, c. 1147) and Alan of Lille (<i>De planctu Naturae</i>, c. 1160–1170) is significant: both draw on the same confluence of Platonic, Hermetic, and Stoic sources that Thierry deployed in his Genesis commentary. The subsequent medieval tradition received Thierry's contribution primarily through these mediating figures rather than through his own works, which did not achieve wide manuscript circulation.</p>

<h2>Scholarly Debates</h2>
<p>The major scholarly debates about Thierry of Chartres concern the degree of his theological orthodoxy — whether his naturalistic reading of Genesis crossed the boundaries of acceptable Christian theological interpretation — and the institutional reality of the "School of Chartres" as a coherent philosophical tradition. Southern's skeptical reassessment in "The Schools of Paris and the School of Chartres" (1984) questioned whether there was a distinctive "Chartrian" philosophical tradition or whether the figures associated with Chartres were simply representative of a wider 12th-century intellectual culture. Subsequent scholarship, including the work of Jeauneau and Dronke, has argued for a more nuanced picture in which a genuine shared intellectual orientation among the Chartrian masters — including their common Platonic-Hermetic cosmological framework — can be identified without reifying it into a "school" with a fixed doctrine.</p>

<h2>Literature</h2>
<p>Jeauneau, Edouard. <i>Lectio philosophorum: Recherches sur l'École de Chartres</i>. Amsterdam: Hakkert, 1973.</p>
<p>Stock, Brian. <i>Myth and Science in the Twelfth Century: A Study of Bernard Silvester</i>. Princeton: Princeton University Press, 1972.</p>
<p>Dronke, Peter (ed.). <i>A History of Twelfth-Century Western Philosophy</i>. Cambridge: Cambridge University Press, 1988.</p>
<p>Lucentini, Paolo and Mark D. Delp. <i>Hermetis Trismegisti De sex rerum principiis</i>. Turnhout: Brepols, 2006.</p>
<p>Copenhaver, Brian P. <i>Hermetica: The Greek Corpus Hermeticum and the Latin Asclepius</i>. Cambridge: Cambridge University Press, 1992.</p>
<p>Porreca, David. "Hermes Trismegistus in the Latin Middle Ages." PhD dissertation. University of Waterloo, 2001.</p>
<p>Haskins, Charles Homer. <i>The Renaissance of the Twelfth Century</i>. Cambridge: Harvard University Press, 1927.</p>
<p>Hanegraaff, Wouter J. (ed.). <i>Dictionary of Gnosis and Western Esotericism</i>. 2 vols. Leiden: Brill, 2006.</p>
<p>Wetherbee, Winthrop. <i>Platonism and Poetry in the Twelfth Century: The Literary Influence of the School of Chartres</i>. Princeton: Princeton University Press, 1972.</p>"""

# ---------------------------------------------------------------------------
# 5. WILLIAM OF CONCHES
# ---------------------------------------------------------------------------
BIOS["william_of_conches"] = """<p>William of Conches (c. 1090–c. 1154) was one of the leading natural philosophers of the 12th-century Latin West, associated with the intellectual tradition of the Cathedral School of Chartres and with the broader movement of 12th-century rationalist naturalism that sought to explain the workings of the created world through the systematic analysis of natural causes. A student (possibly) of Bernard of Chartres — the "most copious spring of letters in Gaul" in the famous judgment of John of Salisbury — William produced several influential works in natural philosophy and grammar that synthesized Platonic cosmology, Arabic natural science, and Hermetic cosmological doctrine in the service of a naturalist Christian theology. His significance for the history of Hermeticism lies in his direct engagement with the <i>Asclepius</i>'s World Soul doctrine and with related Hermetic cosmological material as resources for his project of explaining creation through secondary causes — natural principles acting in accordance with divine reason — rather than through direct divine intervention.</p>

<h2>Works and Intellectual Context</h2>
<p>William's principal surviving works are: <i>Philosophia mundi</i> (Philosophy of the World, c. 1125) — a systematic account of cosmology, physics, and anthropology in four books that became one of the most widely read scientific texts of the 12th century; <i>Dragmaticon philosophiae</i> (c. 1144–1149) — a revised and expanded version of the <i>Philosophia mundi</i> in dialogue form, composed in response to criticism of the earlier work's theological boldness; and extensive commentaries on Plato's <i>Timaeus</i>, Boethius's <i>Consolation of Philosophy</i>, Macrobius's <i>Commentary on the Dream of Scipio</i>, and Priscian's <i>Institutiones grammaticae</i>. The relationship between the <i>Philosophia mundi</i> and the <i>Dragmaticon</i> is revealing: the later work modifies or qualifies some of the more daring positions of the earlier one — particularly on the World Soul and on the interpretation of the Trinity — apparently in response to criticism from William of Saint-Thierry (c. 1080–1148), the Cistercian theologian and friend of Bernard of Clairvaux who accused William of Conches of errors concerning the Holy Spirit and the soul.</p>

<p>The <i>Philosophia mundi</i> opens with a programmatic statement of the naturalist method: "The philosophers did not wish to investigate what God can do but what nature can do." This sentence encapsulates William's project: not to deny divine power but to insist that the proper object of natural philosophical inquiry is the regular operations of nature as instituted by God — the secondary causes through which divine reason acts in the world. For William, as for Thierry of Chartres, the Hermetic World Soul doctrine provides the key cosmological principle: the World Soul (<i>anima mundi</i>) — identified by William, following a complex tradition, with the Holy Spirit — is the rational-animating principle that pervades creation and makes it intelligible to philosophical inquiry. Winthrop Wetherbee and Edouard Jeauneau have provided the most detailed scholarly accounts of William's cosmology and its sources.</p>

<h2>Hermetic Significance</h2>
<p>William of Conches's engagement with Hermetic material is primarily cosmological rather than theological or ritual. He draws on the <i>Asclepius</i>'s account of the World Soul as the animating principle of the cosmos, on Hermetic pneumatology (the doctrine of the <i>spiritus</i> or vital spirit that mediates between soul and body), and on Hermetic teachings about the structure of the elements and the correspondence between celestial and terrestrial phenomena. These Hermetic elements are not cited as such — William does not typically signal that he is drawing on "Hermetic" texts, since in the 12th century the relevant texts (the <i>Asclepius</i>, the Hermetic sententiae in florilegia) circulated without the explicit authorial labeling that would become more prominent in later centuries — but their presence can be identified through careful textual analysis.</p>

<p>Brian Stock's analysis in <i>Myth and Science in the Twelfth Century</i> (1972) situated William within the broader 12th-century naturalist project that drew on Hermetic and Platonic cosmology to develop a coherent account of natural causation. The concept of the "immanence of ratio" — the Hermetic-philosophical principle that divine reason is immanent in creation and thus accessible to rational inquiry — describes William's intellectual posture precisely. His identification of the World Soul with the Holy Spirit — which generated the criticism from William of Saint-Thierry — was his most theologically daring application of Hermetic cosmological doctrine to Christian theology: by identifying the divine animating principle of the Hermetic <i>Asclepius</i> with the third person of the Trinity, William integrated Hermetic theology into the heart of Christian dogma. The identification was controversial, and the later <i>Dragmaticon</i> moderates it in favor of a more careful philosophical theology.</p>

<p>William's natural philosophy also demonstrates the integration of Arabic natural science — particularly as transmitted through the Constantinus Africanus translations from Arabic — with the Hermetic-Platonic cosmological framework. His account of the elements, the humors, the human body's relationship to the cosmos, and the role of celestial influences in human health draws simultaneously on Galenic medicine, Platonic cosmology, and the Arabic natural-philosophical tradition, creating a synthesis that anticipates the 13th-century integration of Aristotelian physics with Hermetic and Arabic occult science.</p>

<h2>Transmission and Reception</h2>
<p>The <i>Philosophia mundi</i> was one of the most widely circulated scientific texts of the 12th century, surviving in more than thirty manuscripts and being copied and excerpted throughout Europe. It was sufficiently well-known to be included in Peter Comestor's influential biblical encyclopedia <i>Historia scholastica</i> and to be quoted by commentators from England to Italy. The work of Edouard Jeauneau in editing and analyzing William's texts, and of Brian Stock and Winthrop Wetherbee in interpreting the literary and philosophical dimensions of the Chartrian tradition, has established William as a central figure in the intellectual history of the 12th century. The subsequent 13th-century reception of William's naturalism was partially absorbed into the Aristotelian synthesis, which provided a more rigorous philosophical vocabulary for many of the questions William had addressed through Platonic-Hermetic categories.</p>

<h2>Scholarly Debates</h2>
<p>The principal scholarly debates about William concern the institutional affiliation of his "school" (the same debate about the "School of Chartres" that applies to Thierry of Chartres), the degree of William's actual theological heterodoxy and whether the criticism from William of Saint-Thierry represented a genuine theological danger or an overreaction, and the precise sources of his natural-philosophical synthesis. The question of the relationship between the <i>Philosophia mundi</i> and the <i>Dragmaticon</i> — how much the later work represents genuine intellectual development versus strategic self-censorship in the face of criticism — has been debated by Jeauneau, Ronca, and others. The systematic edition and translation of William's works — particularly the <i>Philosophia mundi</i> and the <i>Dragmaticon</i> — by Italo Ronca and others in the Corpus Christianorum series provides the scholarly foundation for all current study of William's natural philosophy.</p>

<h2>Literature</h2>
<p>Ronca, Italo and Matthew Curr (trans.). <i>William of Conches: A Dialogue on Natural Philosophy (Dragmaticon Philosophiae)</i>. Notre Dame: University of Notre Dame Press, 1997.</p>
<p>Stock, Brian. <i>Myth and Science in the Twelfth Century: A Study of Bernard Silvester</i>. Princeton: Princeton University Press, 1972.</p>
<p>Dronke, Peter (ed.). <i>A History of Twelfth-Century Western Philosophy</i>. Cambridge: Cambridge University Press, 1988.</p>
<p>Jeauneau, Edouard. <i>Lectio philosophorum: Recherches sur l'École de Chartres</i>. Amsterdam: Hakkert, 1973.</p>
<p>Lucentini, Paolo and Mark D. Delp. <i>Hermetis Trismegisti De sex rerum principiis</i>. Turnhout: Brepols, 2006.</p>
<p>Copenhaver, Brian P. <i>Hermetica: The Greek Corpus Hermeticum and the Latin Asclepius</i>. Cambridge: Cambridge University Press, 1992.</p>
<p>Wetherbee, Winthrop. <i>Platonism and Poetry in the Twelfth Century: The Literary Influence of the School of Chartres</i>. Princeton: Princeton University Press, 1972.</p>
<p>Hanegraaff, Wouter J. (ed.). <i>Dictionary of Gnosis and Western Esotericism</i>. 2 vols. Leiden: Brill, 2006.</p>
<p>Porreca, David. "Hermes Trismegistus in the Latin Middle Ages." PhD dissertation. University of Waterloo, 2001.</p>"""


def main():
    conn = sqlite3.connect(DB_PATH)
    cur = conn.cursor()
    for person_id, bio in BIOS.items():
        cur.execute("SELECT person_id FROM persons WHERE person_id = ?", (person_id,))
        if not cur.fetchone():
            print(f"WARNING: person_id not found: {person_id}")
            continue
        cur.execute("UPDATE persons SET bio_html = ? WHERE person_id = ?", (bio, person_id))
        word_count = len(bio.split())
        print(f"Updated {person_id}: {word_count} words")
    conn.commit()
    conn.close()
    print("Bio batch 1 complete.")


if __name__ == "__main__":
    main()
