"""
write_concepts_batch2.py — Hanegraaff Analyst Terms + Ochema
Idempotent: writes full definition_long and definition_short for:
  - immanence_of_ratio
  - historical_imagination
  - altered_states_of_knowledge
  - ochema
"""
import sqlite3

DB_PATH = r"C:\Dev\EmeraldTablet\db\emerald_tablet.db"

ENTRIES = {}

# ---------------------------------------------------------------------------
# 1. IMMANENCE OF RATIO
# ---------------------------------------------------------------------------
ENTRIES["immanence_of_ratio"] = {
    "definition_short": (
        "Immanence of Ratio is an Analyst Term introduced by Mark Damien Delp, in collaboration with "
        "Paolo Lucentini, to describe the distinctive 12th-century intellectual tendency to ground the "
        "rational investigation of nature in Hermetic cosmological doctrine — especially as transmitted "
        "through the Liber XXIV Philosophorum and the Asclepius. The concept captures how medieval "
        "thinkers at Chartres and in related circles used the Hermetic claim that a divine rational "
        "principle pervades all creation as a philosophical warrant for natural inquiry, producing a "
        "Hermetic natural philosophy that preceded and enabled the full reception of Aristotle."
    ),
    "definition_long": """<p>Immanence of Ratio is an Analyst Term — a retrospective scholarly category — introduced by Mark Damien Delp, in his collaborative work with Paolo Lucentini on the medieval Latin Hermetic tradition, to describe a distinctive intellectual posture that characterizes a cluster of 12th-century thinkers associated with the cathedral school of Chartres and related centers. The concept names the philosophical tendency to ground the rational investigation of the natural world in the Hermetic cosmological claim that a divine rational principle — a <i>ratio</i> or <i>logos</i> — is immanent within creation, permeating matter and making it intelligible. In this framework, the study of nature is not merely permitted but mandated by theology: if God has infused the world with his own rationality, then the systematic analysis of that world — through natural philosophy, mathematics, and cosmology — becomes a form of theological inquiry. The concept appears in Lucentini and Delp's critical edition and study of the <i>De sex rerum principiis</i> (Brepols, 2006), a key text of the <i>Hermes Latinus</i> corpus, and has been developed in the context of broader scholarly attention to the Hermetic dimensions of 12th-century intellectual culture. Hanegraaff's <i>Dictionary of Gnosis and Western Esotericism</i> (2006) situates the concept within the longer history of the relationship between Hermeticism and natural philosophy.</p>

<h2>Historical Usage</h2>
<p>As an Analyst Term, the Immanence of Ratio does not name a phrase used by 12th-century thinkers themselves but rather describes a structural feature of their thought that modern scholars have identified. The relevant historical figures typically appeal to the Platonic concept of the World Soul (<i>anima mundi</i>), the Stoic <i>logos spermatikos</i> (seminal reason), and the Hermetic doctrine of the divine spirit pervading creation — all synthesized through the Latin translations of Hermetic texts available in the 12th century, above all the <i>Asclepius</i> and the fragments of the <i>Liber XXIV Philosophorum</i>.</p>

<p>Thierry of Chartres (d. c. 1150), in his <i>Tractatus de sex dierum operibus</i>, reads the opening of Genesis through a cosmological framework drawn explicitly from Plato's <i>Timaeus</i> and the <i>Asclepius</i>: the <i>spiritus</i> brooding over the waters in Genesis 1:2 is identified with the Hermetic World Soul and with the Stoic pneuma that vivifies and rationally structures the cosmos. William of Conches (c. 1090–1154), in his <i>Philosophia mundi</i> and <i>Dragmaticon philosophiae</i>, similarly uses Hermetic and Platonic cosmology to argue that God acts in creation through secondary causes — through the natural order — rather than by miraculous intervention at each moment. This naturalistic theology, grounded in the immanence of divine reason, provided the intellectual warrant for systematic natural philosophy as a legitimate Christian enterprise.</p>

<p>The <i>Liber XXIV Philosophorum</i> — a collection of twenty-four philosophical propositions about the nature of God attributed to "Hermes" in the medieval tradition — is particularly important for understanding the Immanence of Ratio. Its famous second proposition, "God is an infinite sphere whose centre is everywhere and circumference nowhere," provided a conceptual formula for the omnipresent divine rationality that many 12th-century thinkers found intellectually compelling. The text was edited and studied by Clemens Baeumker (1913) and has received renewed attention in Lucentini and Delp's critical edition (2006). David Porreca's work on the scholastic reception of Hermetic texts, documented in his studies of the <i>Hermes Latinus</i> tradition, demonstrates how this formula circulated across the full range of 12th and 13th-century scholastic writing, appearing in texts by Alan of Lille, Albertus Magnus, and Thomas Aquinas, among many others.</p>

<p>The <i>De sex rerum principiis</i> — a Hermetic-inflected Latin cosmological text of uncertain date, edited by Lucentini and Delp — provides a systematic account of how divine rational principles structure the six levels of creation. Whether this text was composed in the 12th century or is a later product is disputed, but its circulation in the 12th–13th century scholastic milieu is well documented. The text represents the Immanence of Ratio in its most explicit Hermetic form: the rational principles (<i>rationes</i>) of things are not merely abstract forms in a Platonic heaven but are actively immanent within created beings, intelligible to the philosopher who proceeds by careful natural inquiry.</p>

<h2>Scholarly Significance</h2>
<p>The concept of the Immanence of Ratio contributes to a significant revision in the historiography of medieval natural philosophy and its relationship to the Hermetic tradition. The dominant historiographical narrative of the 20th century — associated above all with Charles Homer Haskins's <i>The Renaissance of the Twelfth Century</i> (1927) and with the history of science tradition — emphasized the rediscovery of Aristotle's natural philosophy (via Arabic translations) as the primary driver of 12th-century intellectual transformation. On this account, the Hermetic material present in 12th-century texts was either unimportant or merely a transitional phenomenon that Aristotelianism would soon supersede.</p>

<p>Lucentini and Delp's work, along with that of Paolo Lucentini's broader research program on the <i>Hermes Latinus</i>, argues for a more complex picture in which Hermetic natural philosophy — precisely because of its doctrine of the immanent divine ratio — provided an independent philosophical warrant for natural inquiry that operated alongside, and sometimes in advance of, the Aristotelian synthesis. The Immanence of Ratio, on this account, is not a way-station to Aristotelianism but a philosophically serious and internally coherent position in its own right. Hanegraaff's placement of this concept within the larger history of Western esotericism emphasizes its significance as evidence that the Hermetic tradition contributed substantively to the development of natural philosophy, not merely to occult or esoteric speculation.</p>

<p>Brian Stock's <i>Myth and Science in the Twelfth Century</i> (1972) and Peter Dronke's contributions to <i>A History of Twelfth-Century Western Philosophy</i> (1988) provide important contextual frameworks for understanding how the Chartrian synthesis of Platonism, Hermeticism, and Christian theology produced a distinctive natural-philosophical tradition. More recently, scholars including Charles Burnett, Irene Caiazzo, and Stephen Gersh have mapped the specific textual channels through which Hermetic material reached 12th-century thinkers.</p>

<h2>Transmission and Variant Forms</h2>
<p>The Immanence of Ratio as a conceptual tendency was transmitted primarily through the Latin <i>Asclepius</i> (the only complete Hermetic text available in Latin throughout the medieval period), the <i>Liber XXIV Philosophorum</i>, and numerous shorter Hermetic sententiae embedded in florilegia and encyclopedic works. The Arabic Hermetic tradition transmitted a parallel doctrine through the <i>Picatrix</i> (<i>Ghayat al-Hakim</i>) and through the philosophical writings of al-Kindi and his school, which grounded the action of celestial bodies on terrestrial matter in a rational-causal framework analogous to the Hermetic Immanence of Ratio. The concept's later career in the Renaissance — particularly in the Florentine Neoplatonism of Ficino and Pico — represents a direct continuation of the medieval Hermetic natural-philosophical tradition, now enriched by the newly recovered Greek <i>Corpus Hermeticum</i>.</p>

<h2>Related Concepts</h2>
<p>The Immanence of Ratio is philosophically grounded in the Hermetic doctrine of the <a href="../concepts/anima_mundi_divine.html"><i>Anima Mundi</i></a> — the World Soul as the rational-animating principle immanent in creation — which provides its theological foundation. It relates directly to the broader epistemological claim of <a href="../concepts/gnosis.html"><i>gnosis</i></a>: if the divine ratio is immanent in matter, then the careful philosophical investigation of matter becomes a path to knowledge of the divine. The concept of the <a href="../concepts/macrocosm_microcosm.html">macrocosm-microcosm</a> correspondence is its cosmological expression: the same ratio that structures the great world (macrocosm) structures the small world of the human being (microcosm), making both equally available to rational inquiry. The <a href="../concepts/monad.html">Monad</a> as the Hermetic first principle from which all rational order emanates is the metaphysical ground of the Immanence of Ratio.</p>

<h2>Literature</h2>
<p>Lucentini, Paolo and Mark D. Delp. <i>Hermetis Trismegisti De sex rerum principiis</i>. Turnhout: Brepols, 2006.</p>
<p>Hanegraaff, Wouter J. (ed.). <i>Dictionary of Gnosis and Western Esotericism</i>. 2 vols. Leiden: Brill, 2006.</p>
<p>Stock, Brian. <i>Myth and Science in the Twelfth Century: A Study of Bernard Silvester</i>. Princeton: Princeton University Press, 1972.</p>
<p>Dronke, Peter (ed.). <i>A History of Twelfth-Century Western Philosophy</i>. Cambridge: Cambridge University Press, 1988.</p>
<p>Haskins, Charles Homer. <i>The Renaissance of the Twelfth Century</i>. Cambridge: Harvard University Press, 1927.</p>
<p>Porreca, David. "Hermes Trismegistus in the Latin Middle Ages." PhD dissertation. University of Waterloo, 2001.</p>
<p>Baeumker, Clemens. <i>Das pseudo-hermetische Buch der vierundzwanzig Meister (Liber XXIV philosophorum)</i>. Münster: Aschendorff, 1913.</p>
<p>Copenhaver, Brian P. <i>Hermetica: The Greek Corpus Hermeticum and the Latin Asclepius</i>. Cambridge: Cambridge University Press, 1992.</p>
<p>Burnett, Charles. "The Coherence of the Arabic-Latin Translation Program in Toledo in the Twelfth Century." <i>Science in Context</i> 14 (2001): 249–288.</p>"""
}

# ---------------------------------------------------------------------------
# 2. HISTORICAL IMAGINATION
# ---------------------------------------------------------------------------
ENTRIES["historical_imagination"] = {
    "definition_short": (
        "Historical Imagination is an Analyst Term introduced by Wouter J. Hanegraaff as the organizing "
        "framework of his Hermetic Spirituality and the Historical Imagination (2022). It designates the "
        "faculty — operative in both ancient Hermetic authors and modern scholars — by which narratives "
        "of the past are constructed, legitimated, and made persuasive. Hanegraaff argues that the "
        "Hermetic texts are themselves products of a historical imagination projecting primordial wisdom "
        "onto the mythical Hermes Trismegistus, and that modern historians of the tradition inevitably "
        "exercise a comparable imaginative faculty in their own reconstructions."
    ),
    "definition_long": """<p>Historical Imagination is an Analyst Term — a retrospective scholarly category — introduced by Wouter J. Hanegraaff as the governing conceptual framework of his major study <i>Hermetic Spirituality and the Historical Imagination</i> (Oxford University Press, 2022). As an Analyst Term in the Hanegraaffian sense, it does not name a concept used by historical Hermetic practitioners but rather a critical-analytical category designed to illuminate the relationship between historiography, narrative, and the construction of religious and philosophical traditions. The term designates the faculty by which human beings — both ancient and modern — construct compelling narratives of the past: selecting, shaping, and endowing with authority a version of history that serves present needs and reflects present assumptions. Hanegraaff's central argument is that both the ancient Hermetic authors and the modern scholars who study them exercise this faculty, and that a fully critical history of Hermeticism must be reflexively aware of its own imaginative operations. The concept draws on a lineage of historiographical theory from Hayden White's <i>Metahistory: The Historical Imagination in Nineteenth-Century Europe</i> (1973) and Paul Ricoeur's <i>Time and Narrative</i> (3 vols., 1983–1985) while applying it to the specific case of the Hermetic tradition.</p>

<h2>Historical Usage</h2>
<p>Since Historical Imagination is an Analyst Term coined by Hanegraaff in 2022, it has no historical usage in the sense that Actor Terms do — it was not employed by ancient Hermetic practitioners as a self-description. What Hanegraaff's concept illuminates, however, is a historical phenomenon that pervades the Hermetic textual tradition: the systematic construction of a narrative of primordial wisdom attributed to a mythical sage who never existed in the form the tradition claims. Hermes Trismegistus — "Thrice-Greatest Hermes" — is presented in the Hermetic texts themselves and in their subsequent reception as a historical figure of supreme antiquity who received divine revelation and transmitted it across the generations. The Late Antique Hermetic authors who composed the texts of the <i>Corpus Hermeticum</i> (2nd–3rd centuries CE) were not simply recording a preexisting tradition but actively constructing one — projecting wisdom that was genuinely their own (synthesized from Platonic, Stoic, Egyptian, and Jewish sources) onto the figure of a mythical Egyptian sage of immense antiquity.</p>

<p>This construction was enormously successful: Lactantius (c. 250–325 CE) cited Hermes Trismegistus as a pagan prophet of Christ; Augustine of Hippo (354–430 CE) engaged with the <i>Asclepius</i> seriously in <i>De civitate Dei</i>; the Renaissance humanists who received Marsilio Ficino's Latin <i>Pimander</i> (1463) believed they were reading the work of a sage as ancient as Moses. Isaac Casaubon's 1614 demonstration that the Greek <i>Corpus Hermeticum</i> was not ancient but Hellenistic-era in composition — a demonstration achieved through internal stylistic and linguistic analysis — was the decisive modern interruption of this historical imagination. But as Hanegraaff shows, the Casaubon critique did not end the imaginative construction: it merely forced it to relocate and reformulate. Subsequent esoteric appropriations of the Hermetic tradition have continued to exercise historical imagination — constructing narratives of perennial wisdom, of suppressed priestly knowledge, of ancient Egyptian mysticism — in ways that are recognizably continuous with the original Hermetic historical imagination even while departing from its specific claims.</p>

<h2>Scholarly Significance</h2>
<p>Hanegraaff's concept of Historical Imagination intervenes in the ongoing methodological debates within the academic study of Western esotericism over the relationship between historical scholarship and the traditions it studies. The debate has several dimensions. The first concerns what Antoine Faivre, in his foundational typological approach, called the "forms" of esotericism — a set of structural characteristics (living nature, correspondences, imagination, transmutation, concordance, transmission) that Faivre used to define Western esotericism as a coherent object of study. Hanegraaff has consistently criticized Faivre's approach for building perennialist and essentialist assumptions into the analytical framework, inadvertently reproducing the claims of the traditions under study rather than analyzing them critically.</p>

<p>The second dimension concerns the Yates Paradigm — Frances Yates's influential thesis in <i>Giordano Bruno and the Hermetic Tradition</i> (1964) that Renaissance Hermeticism was a driving force behind the Scientific Revolution. Hanegraaff's analysis shows that Yates herself exercised a powerful historical imagination in constructing a narrative of Hermetic influence that served her interpretive purposes (emphasizing continuity between ancient wisdom and modern science) while flattening the enormous complexity and internal tensions of the tradition. Copenhaver's and Hanegraaff's subsequent revisions of the Yates Paradigm have restored much of this complexity.</p>

<p>The third dimension is reflexive: Hanegraaff's concept of Historical Imagination applies not only to the object of study (the Hermetic tradition) but to the scholarly practice of studying it. Modern academic historians of esotericism — including Hanegraaff himself — exercise historical imagination in constructing their accounts of the tradition. The difference between critical historical scholarship and esoteric historiography, on this account, is not that one exercises imagination and the other does not, but that critical scholarship is reflexively aware of its imaginative operations and subjects them to methodological scrutiny, while esoteric historiography typically presents its imaginative constructions as historical fact. This reflexive dimension of the concept connects it to the broader tradition of historiographical theory from White and Ricoeur through to contemporary approaches in intellectual history.</p>

<h2>Transmission and Variant Forms</h2>
<p>The concept of Historical Imagination as developed by Hanegraaff synthesizes elements from several intellectual traditions. Hayden White's <i>Metahistory</i> (1973) demonstrated that historical writing employs literary tropes (irony, tragedy, comedy, romance) to organize events into intelligible narratives — a claim that applies directly to the Hermetic tradition's self-presentation as a narrative of primordial revelation transmitted across the ages. Paul Ricoeur's <i>Time and Narrative</i> (1983–1985) provided a phenomenological account of how narrative constitutes temporal experience and historical identity. Michel Foucault's genealogical approach — tracing the contingent historical conditions that make certain knowledge claims possible — is also relevant to Hanegraaff's analysis, though Hanegraaff maintains a more traditionally historicist framework. The concept has affinities with Jan Assmann's work on "cultural memory" (<i>Das kulturelle Gedächtnis</i>, 1992) and with the sociology of knowledge tradition from Karl Mannheim onward, but it is specifically adapted to the Hermetic case in Hanegraaff's application.</p>

<h2>Related Concepts</h2>
<p>The concept of Historical Imagination is directly related to Hanegraaff's other major Analyst Terms for the Hermetic tradition. The concept of <a href="../concepts/altered_states_of_knowledge.html">Altered States of Knowledge</a> provides its experiential counterpart: where Historical Imagination describes how Hermetic traditions construct and legitimate their claims about the past, Altered States of Knowledge describes the transformed cognitive state that the Hermetic path aims to produce in the practitioner. The <a href="../concepts/the_way_of_hermes.html">Way of Hermes</a> names the specific path whose historical legitimation is constructed through the historical imagination. The concept also relates to the broader framework of <a href="../concepts/gnosis.html"><i>gnosis</i></a> — the specific form of knowledge claimed by the Hermetic tradition — whose relationship to historical authority (the authority of the ancient sage Hermes Trismegistus) is precisely what the historical imagination constructs and the critical historian deconstructs.</p>

<h2>Literature</h2>
<p>Hanegraaff, Wouter J. <i>Hermetic Spirituality and the Historical Imagination</i>. Oxford: Oxford University Press, 2022.</p>
<p>Hanegraaff, Wouter J. (ed.). <i>Dictionary of Gnosis and Western Esotericism</i>. 2 vols. Leiden: Brill, 2006.</p>
<p>White, Hayden. <i>Metahistory: The Historical Imagination in Nineteenth-Century Europe</i>. Baltimore: Johns Hopkins University Press, 1973.</p>
<p>Ricoeur, Paul. <i>Time and Narrative</i>. 3 vols. Translated by Kathleen McLaughlin and David Pellauer. Chicago: University of Chicago Press, 1983–1985.</p>
<p>Yates, Frances A. <i>Giordano Bruno and the Hermetic Tradition</i>. London: Routledge and Kegan Paul, 1964.</p>
<p>Copenhaver, Brian P. <i>Hermetica: The Greek Corpus Hermeticum and the Latin Asclepius</i>. Cambridge: Cambridge University Press, 1992.</p>
<p>Fowden, Garth. <i>The Egyptian Hermes: A Historical Approach to the Late Pagan Mind</i>. Cambridge: Cambridge University Press, 1986.</p>
<p>Faivre, Antoine. <i>Access to Western Esotericism</i>. Albany: SUNY Press, 1994.</p>
<p>Assmann, Jan. <i>Das kulturelle Gedächtnis: Schrift, Erinnerung und politische Identität in frühen Hochkulturen</i>. Munich: Beck, 1992.</p>
<p>Bull, Christian H. <i>The Tradition of Hermes Trismegistus: The Egyptian Priestly Figure as a Teacher of Hellenized Wisdom</i>. Leiden: Brill, 2018.</p>"""
}

# ---------------------------------------------------------------------------
# 3. ALTERED STATES OF KNOWLEDGE
# ---------------------------------------------------------------------------
ENTRIES["altered_states_of_knowledge"] = {
    "definition_short": (
        "Altered States of Knowledge is an Analyst Term introduced by Wouter J. Hanegraaff in Hermetic "
        "Spirituality and the Historical Imagination (2022) to describe the epistemological dimension of "
        "Hermetic gnosis. The concept designates not a temporary change in consciousness but a permanent "
        "cognitive and existential transformation of the knowing subject — a shift from ordinary sensory "
        "and discursive cognition to a form of knowing grounded in the divine nous. Hanegraaff "
        "distinguishes it from both mystical union and from mere intellectual knowledge, emphasizing its "
        "cognitive content and its irreversible character as a transformation of the self."
    ),
    "definition_long": """<p>Altered States of Knowledge is an Analyst Term introduced by Wouter J. Hanegraaff in <i>Hermetic Spirituality and the Historical Imagination</i> (2022) to designate the epistemological dimension of the Hermetic path — the claim, central to the philosophical Hermetica, that genuine knowledge of the divine involves not merely the acquisition of new information but a radical transformation of the knowing subject itself. As an Analyst Term, the concept does not replicate the vocabulary of historical Hermetic practitioners (who spoke rather of <i>gnosis</i>, of "knowing God," of becoming <i>nous</i>) but rather provides a precise analytical characterization of what those practitioners were claiming. The term deliberately invokes, and then revises, the language of "altered states of consciousness" familiar from cognitive science of religion and from psychological accounts of religious experience: Hanegraaff argues that the Hermetic transformation is best understood not as a temporary alteration of consciousness — a visionary episode, a trance, a mystical experience that leaves the subject fundamentally unchanged — but as a permanent and irreversible alteration of the subject's cognitive and existential orientation, a shift in the very <i>mode</i> by which the person knows and is in the world. The Hermetic practitioner who has undergone this transformation does not merely know more; they know <i>differently</i> — from the perspective of the divine <i>nous</i> rather than from the perspective of the materially conditioned, sensorially bound, ego-identified ordinary self.</p>

<h2>Historical Usage</h2>
<p>As an Analyst Term, Altered States of Knowledge has no historical usage among Hermetic practitioners. The phenomena it designates, however, are pervasively documented in the philosophical Hermetica, above all in the key transformation narratives of the <i>Corpus Hermeticum</i>. The most explicit account is in CH XIII (<i>On Regeneration</i>), where the student Tat asks Hermes for instruction in the doctrine of regeneration (<i>palingenesia</i>). Hermes's response describes not a mystical experience but a structured cognitive transformation: the twelve "penalties" (<i>timoriai</i>) of material embodiment — ignorance, grief, intemperance, desire, injustice, deceit, envy, treachery, rage, rashness, malice, and the ultimate penalty — are progressively expelled and replaced by the ten divine powers of the Decad. The result is not simply a new belief but a new mode of cognition and existence: Tat exclaims, "I have been begotten again in mind" (<i>enennoêthên en noi</i>). This is not a metaphor for intellectual realization; it is a claim about the restructuring of cognitive reality.</p>

<p>CH I (<i>Poimandres</i>) narrates a comparable transformation through a visionary encounter with the divine Poimandres, who reveals to the narrator the structure of the cosmos and the soul's proper path. The encounter does not merely inform — it transforms: the narrator is charged to go out and teach others, to guide them toward the same transformation, and the text ends with a hymnic outpouring that itself enacts the altered state through its language and address. CH IV (<i>The Mixing Bowl</i>) presents the transformation through the image of a divine krater (<i>mixing bowl</i>) filled with <i>nous</i> and sent down to earth: those who heed the call and "immerse themselves in the bowl" undergo the transformation. Those who do not remain in their ordinary sensory condition. The choice is presented as genuinely momentous — not between different beliefs but between fundamentally different ways of being in the world.</p>

<p>CH X (<i>The Key</i>) develops the epistemological analysis most explicitly: the transformed practitioner gains the capacity to know all things simultaneously — past, present, and future — not through accumulated information but through the immediate cognitive grasp of the divine intellect in which all things are contained. This claim is not presented as a hyperbole but as a literal description of a cognitive capacity that differs categorically from ordinary sensory and discursive cognition. Copenhaver's standard English translation of the <i>Corpus Hermeticum</i> (1992) and Mahé's French philological edition of the related Nag Hammadi materials are indispensable resources for tracking these claims across the Hermetic corpus.</p>

<h2>Scholarly Significance</h2>
<p>Hanegraaff's concept of Altered States of Knowledge occupies a strategic position in the broader methodological debates of the academic study of Western esotericism. It intervenes in the long-standing tension between "experientialist" and "constructivist" approaches to mystical and religious experience. The experientialist tradition — associated with figures such as William James (<i>The Varieties of Religious Experience</i>, 1902) and Huston Smith — tends to treat certain types of religious experience as sui generis, as disclosing genuine transcendent realities that cannot be reduced to social or linguistic construction. The constructivist tradition — associated with Steven Katz, Wayne Proudfoot, and others — argues that all religious experience is shaped by prior cultural conditioning and that there is no unmediated "pure" experience beneath the culturally specific descriptions.</p>

<p>Hanegraaff's concept steers between these positions: he insists that the Hermetic transformation involves a genuine alteration of cognitive functioning — not merely a new belief or a new description of an unchanged experience — while also insisting that this alteration is culturally and textually mediated, shaped by the specific doctrines, practices, and social contexts of the Hermetic tradition. The comparison with cognitive science of religion is deliberate: Hanegraaff acknowledges the work of Harvey Whitehouse, Pascal Boyer, and other cognitive scientists of religion, but argues against purely naturalistic accounts that reduce the Hermetic cognitive transformation to neurological events. The transformation involves cognitive content — specific knowledge of cosmological structure, of the soul's destiny, of the divine nature — that cannot be specified in purely neurological terms.</p>

<p>The concept also engages with the broader question of the relationship between philosophy and religion in Late Antiquity. Hanegraaff argues that the Hermetic Altered States of Knowledge represent a form of philosophical religion that is genuinely different from both mainstream Greek philosophy (which sought knowledge through discursive argument) and from mystery religion (which promised salvation through ritual initiation without the intellectual transformation). The Hermetic path combines elements of both while being reducible to neither — a claim that bears directly on how the tradition is positioned within the wider history of Late Antique religion.</p>

<h2>Transmission and Variant Forms</h2>
<p>The transformative epistemology designated by Altered States of Knowledge was transmitted to subsequent traditions in various forms. In the Neoplatonic tradition — above all in Plotinus (<i>Enneads</i>, c. 253–270 CE) and Iamblichus (<i>De mysteriis</i>, c. 300 CE) — the concept of <i>henosis</i> (union with the One) shares the Hermetic insistence on a transformation of the knowing subject rather than merely the acquisition of new information. The theurgical tradition of Iamblichus introduces ritual practices as means of achieving this transformation, paralleling the Hermetic use of hymnic prayer and contemplative exercise. In Islamic Hermeticism, Suhrawardi's Illuminationist philosophy (<i>Hikmat al-Ishraq</i>, c. 1186 CE) develops a comparable epistemology in which the acquisition of genuine knowledge (<i>kashf</i>, unveiling) involves a transformation of the soul's cognitive orientation through illumination from the divine Light. In the Latin West, the concept was partially transmitted through the mediation of the <i>Asclepius</i> and through the Neoplatonic commentary tradition, though typically filtered through Christian categories of conversion and spiritual transformation.</p>

<h2>Related Concepts</h2>
<p>Altered States of Knowledge is the epistemological complement of the <a href="../concepts/the_way_of_hermes.html">Way of Hermes</a> — the path whose goal is precisely this transformation of the knowing subject. It is inseparable from the concept of <a href="../concepts/gnosis.html"><i>gnosis</i></a>, which names the specific form of knowledge that the transformation makes possible: not propositional knowledge about God but participatory knowledge that is simultaneously self-knowledge and divine knowledge. The transformation is mediated through the divine <a href="../concepts/nous.html"><i>nous</i></a> — the intellect that descends from the supreme God — whose reception or "immersion" in the soul constitutes the structural mechanism of the cognitive shift. The concept of <a href="../concepts/palingenesia.html"><i>palingenesia</i></a> — regeneration — is the experiential name for the same transformation viewed from the perspective of the practitioner's existential condition rather than from the perspective of their cognitive capacities. The concept of <a href="../concepts/historical_imagination.html">Historical Imagination</a> provides its methodological complement: where Altered States of Knowledge describes what the Hermetic path aims to produce, Historical Imagination describes how the tradition constructs the narrative authority that makes the path credible.</p>

<h2>Literature</h2>
<p>Hanegraaff, Wouter J. <i>Hermetic Spirituality and the Historical Imagination</i>. Oxford: Oxford University Press, 2022.</p>
<p>Hanegraaff, Wouter J. (ed.). <i>Dictionary of Gnosis and Western Esotericism</i>. 2 vols. Leiden: Brill, 2006.</p>
<p>Copenhaver, Brian P. (trans.). <i>Hermetica: The Greek Corpus Hermeticum and the Latin Asclepius</i>. Cambridge: Cambridge University Press, 1992.</p>
<p>Fowden, Garth. <i>The Egyptian Hermes: A Historical Approach to the Late Pagan Mind</i>. Cambridge: Cambridge University Press, 1986.</p>
<p>Van den Kerchove, Anna. <i>La voie d'Hermès: Pratiques rituelles et traités hermétiques</i>. Turnhout: Brepols, 2012.</p>
<p>Bull, Christian H. <i>The Tradition of Hermes Trismegistus: The Egyptian Priestly Figure as a Teacher of Hellenized Wisdom</i>. Leiden: Brill, 2018.</p>
<p>Litwa, M. David (trans.). <i>Hermetica II: The Excerpts of Stobaeus, Papyrus Fragments, and Ancient Testimonies</i>. Cambridge: Cambridge University Press, 2018.</p>
<p>James, William. <i>The Varieties of Religious Experience: A Study in Human Nature</i>. London: Longmans, Green, 1902.</p>
<p>Mahé, Jean-Pierre. <i>Hermès en Haute-Égypte</i>. 2 vols. Quebec: Presses de l'Université Laval, 1978–1982.</p>
<p>Plotinus. <i>The Enneads</i>. Translated by A. H. Armstrong. 7 vols. Cambridge: Harvard University Press, 1966–1988.</p>"""
}

# ---------------------------------------------------------------------------
# 4. OCHEMA
# ---------------------------------------------------------------------------
ENTRIES["ochema"] = {
    "definition_short": (
        "Ochema (Greek: ochema, 'vehicle' or 'chariot') is an Actor Term designating the pneumatic or "
        "luminous subtle body that serves as the vehicle of the rational soul in Neoplatonic and Hermetic "
        "philosophy — an intermediary substance between the immortal intellect and the gross material body "
        "through which the soul acts in the world and through which it ascends through the planetary spheres "
        "after death. Systematically theorized by Proclus in his Elements of Theology and developed by "
        "Iamblichus in his account of theurgy, the ochema is also attested in the Hermetic description of "
        "the soul's katabasis and anabasis across the planetary spheres."
    ),
    "definition_long": """<p><i>Ochema</i> (Greek: <i>ὄχημα</i>, "vehicle" or "chariot") is an Actor Term designating the luminous, subtle, or pneumatic body that functions as the vehicle of the rational soul in the Neoplatonic and Hermetic philosophical traditions of Late Antiquity — a mediating substance occupying the ontological space between the immortal intellective soul and the gross, corruptible material body. As an Actor Term, it designates a concept genuinely operative within the philosophical systems of late Neoplatonic and Hermetic thinkers rather than a retrospective scholarly category. The <i>ochema</i> is the instrument through which the soul perceives, acts, and is affected in the material world; it is the vehicle the soul inhabits during its descent through the planetary spheres at the moment of incarnation and the vehicle that it must progressively purify and eventually shed in its return ascent to the divine. The concept is attested in Plato's <i>Timaeus</i> (41e), where the Demiurge plants souls in the stars "as if in a vehicle" (<i>hōs eis ochēma</i>), and it receives its fullest systematic treatment in Proclus of Athens (c. 412–485 CE) and in the theurgical philosophy of Iamblichus of Chalcis (c. 245–325 CE). Its relevance to the Hermetic tradition specifically lies in the Hermetic account of the soul's descent through and ascent through the planetary spheres — narratives that presuppose a subtle vehicle through which the soul acquires and subsequently sheds the qualities of each planetary sphere.</p>

<h2>Historical Usage</h2>
<p>The earliest attestations of the concept are in Plato and in Stoic pneumatology. Plato's <i>Timaeus</i> (41e) introduces the image of the soul "planted in a vehicle" (<i>ochēma</i>) and drawn through the cosmos, providing the conceptual seed from which the later elaborate doctrine grew. The Stoic concept of the <i>pneuma</i> — a subtle, warm, breath-like substance that pervades and animates the cosmos and the individual body — provided the physical theory within which the soul-vehicle could be understood as a real, if subtle, material substance. The synthesis of Platonic soul-vehicle doctrine with Stoic pneumatology became the standard philosophical framework for the <i>ochema</i> in late Neoplatonic and Hermetic thought.</p>

<p>Iamblichus of Chalcis (c. 245–325 CE) is the pivotal figure in the development of the ochema doctrine within the theurgical tradition. His <i>De mysteriis</i> (Concerning the Mysteries) — a defense of traditional religion and theurgy against the more intellectualist approach of Porphyry — develops the concept of the pneumatic vehicle as the medium through which the gods communicate with the soul in ritual contexts. For Iamblichus, the theurgical rites that involve images, incantations, and material substances act precisely on the ochema — the subtle vehicle — thereby purifying it and making it an apt receptacle for divine illumination. This means that theurgy is not mere superstition but a philosophically grounded practice operating on a real, if subtle, dimension of the soul's constitution. Crystal Addey's study <i>Divination and Theurgy in Neoplatonism</i> (2014) provides a detailed account of this framework.</p>

<p>Proclus of Athens (c. 412–485 CE) provides the most systematic theoretical account of the ochema in his <i>Elements of Theology</i> (propositions 196–210) and in his <i>Commentary on the Timaeus</i>. For Proclus, the soul possesses three "vehicles": the highest, immortal, luminous vehicle (<i>ochema-astron</i>) in which the soul is planted by the Demiurge; an intermediate vehicle of a more condensed but still subtle substance (<i>pneumatikon ochema</i>) acquired during the soul's descent through the planetary spheres; and the gross material body. The doctrine of the planetary spheres is central: as the soul descends through each sphere on its way to incarnation, it acquires from each sphere a quality or "covering" (<i>chitōn</i>) that thickens its vehicle; as it ascends after death (having undergone sufficient purification), it progressively sheds these coverings, restoring the luminous vehicle to its original purity. John F. Finamore's study <i>Iamblichus and the Theory of the Vehicle of the Soul</i> (1985) remains the standard monograph on the Iamblichan dimension of the doctrine.</p>

<p>The Hermetic relevance is direct. The narrative in CH I (<i>Poimandres</i>) of the soul's descent through the seven planetary spheres — acquiring at each sphere the corresponding quality (from Saturn: contraction and deceit; from Jupiter: evil ambition; from Mars: reckless boldness; from the Sun: desire for mastery; from Venus: deceitful longing; from Mercury: evil cunningness; from the Moon: desire and deceit) — presupposes a subtle vehicle that accumulates these qualities layer by layer. The parallel account in CH XIII of the soul's regeneration, in which the twelve penalties of material life are expelled and replaced by divine powers, can be read as describing a purification of this accumulated vehicle. Synesius of Cyrene (c. 373–414 CE), a Neoplatonist and bishop whose <i>De insomniis</i> (On Dreams) provides the most developed treatment of the pneumatic vehicle in a Christian context, treated it as the organ of dreaming and visionary experience — a connection noted by Robert C. Kissling in his 1922 study in the <i>American Journal of Philology</i>.</p>

<h2>Scholarly Significance</h2>
<p>Modern scholarly engagement with the ochema doctrine has proceeded primarily within the study of Neoplatonism and theurgical philosophy rather than within Hermetic studies proper, though the Hermetic relevance has been noted by Fowden, Hanegraaff, and others. The foundational modern study is Dodds's commentary on Proclus's <i>Elements of Theology</i> (1933, 2nd ed. 1963), which provides a meticulous philological account of the ochema doctrine in the context of Proclean metaphysics. Finamore's monograph (1985) extended the analysis to Iamblichus. More recently, Addey's work and the broader revival of interest in late Neoplatonic theurgy (associated with scholars such as Polymnia Athanassiadi, Gregory Shaw, and John Dillon) has given the concept renewed scholarly attention.</p>

<p>The historiographical significance of the ochema doctrine lies partly in what it reveals about the relationship between philosophy and religion in Late Antiquity. The elaborate theoretical framework developed by Proclus and Iamblichus to account for the soul's vehicle demonstrates that the late Neoplatonic defense of ritual practice — theurgy, prayer, divination — was philosophically serious and internally consistent: it rested on a coherent metaphysical theory of the soul's constitution and not merely on credulity or tradition. The connection between the ochema and the Hermetic planetary-descent narratives demonstrates, moreover, that the Hermetic texts were composed within a shared philosophical milieu in which the soul-vehicle doctrine was a live theoretical option rather than a marginal speculation.</p>

<h2>Transmission and Variant Forms</h2>
<p>The Latin rendering of <i>ochema</i> is typically <i>vehiculum animae</i> (vehicle of the soul), which appears in Macrobius's <i>Commentary on the Dream of Scipio</i> (c. 400 CE) — a text that was enormously influential on medieval Latin cosmology. Through Macrobius, the doctrine of the planetary soul-vehicle was transmitted to the Latin medieval tradition, where it influenced both cosmological poetry (Bernardus Silvestris's <i>Cosmographia</i>, c. 1147) and natural philosophy. The concept is also rendered as <i>spiritus</i> in some Latin contexts, particularly in the medical and astrological tradition where the subtle spirit is the medium through which celestial influences act on the human body — a usage that creates important overlaps with the <a href="../concepts/pneuma.html"><i>pneuma</i></a> tradition. In Arabic, the subtle body is designated variously as <i>ruh</i> (spirit) and <i>jism latif</i> (subtle body), and the doctrine was transmitted through the Arabic Neoplatonic tradition (particularly the <i>Theology of Aristotle</i>, an Arabic adaptation of Plotinus) to Islamic philosophy. The Renaissance concept of the <i>spiritus phantasticus</i> or <i>spiritus imaginationis</i> — developed by Ficino in his <i>De vita</i> (1489) as the medium of celestial and magical action on the human organism — represents a direct continuation of the ochema tradition within a Renaissance Neoplatonic framework.</p>

<h2>Related Concepts</h2>
<p>The ochema is the ontological vehicle of <a href="../concepts/gnosis.html"><i>gnosis</i></a> in the sense that the soul's capacity for divine knowledge is mediated through its subtle vehicle: the purer the ochema, the more transparent it is to divine illumination. The doctrine of the planetary descent and ascent of the soul presupposes the account of the <a href="../concepts/anima_mundi_divine.html"><i>Anima Mundi</i></a> as the cosmic soul through whose sphere the individual soul passes in its katabasis and anabasis. The <a href="../concepts/theurgy.html">theurgical</a> tradition of Iamblichus treats the ochema as the direct target of ritual practice — it is the subtle body that is purified through theurgical rites and thereby rendered fit for divine presence. The concept connects closely to the <a href="../concepts/macrocosm_microcosm.html">macrocosm-microcosm</a> doctrine: the ochema's layered structure, accumulating planetary qualities in descent and shedding them in ascent, maps the structure of the cosmos onto the structure of the individual soul in its most intimate dimension.</p>

<h2>Literature</h2>
<p>Finamore, John F. <i>Iamblichus and the Theory of the Vehicle of the Soul</i>. Chico, CA: Scholars Press, 1985.</p>
<p>Proclus. <i>The Elements of Theology</i>. Translated and edited by E. R. Dodds. 2nd ed. Oxford: Clarendon Press, 1963.</p>
<p>Iamblichus. <i>De mysteriis</i>. Translated by Emma C. Clarke, John M. Dillon, and Jackson P. Hershbell. Atlanta: Society of Biblical Literature, 2003.</p>
<p>Addey, Crystal. <i>Divination and Theurgy in Neoplatonism: Oracles of the Gods</i>. Farnham: Ashgate, 2014.</p>
<p>Kissling, Robert C. "The ochema-pneuma of the Neo-Platonists and the De insomniis of Synesius of Cyrene." <i>American Journal of Philology</i> 43 (1922): 318–330.</p>
<p>Copenhaver, Brian P. (trans.). <i>Hermetica: The Greek Corpus Hermeticum and the Latin Asclepius</i>. Cambridge: Cambridge University Press, 1992.</p>
<p>Fowden, Garth. <i>The Egyptian Hermes: A Historical Approach to the Late Pagan Mind</i>. Cambridge: Cambridge University Press, 1986.</p>
<p>Hanegraaff, Wouter J. (ed.). <i>Dictionary of Gnosis and Western Esotericism</i>. 2 vols. Leiden: Brill, 2006.</p>
<p>Shaw, Gregory. <i>Theurgy and the Soul: The Neoplatonism of Iamblichus</i>. University Park: Pennsylvania State University Press, 1995.</p>
<p>Macrobius. <i>Commentary on the Dream of Scipio</i>. Translated by William Harris Stahl. New York: Columbia University Press, 1952.</p>"""
}


def main():
    conn = sqlite3.connect(DB_PATH)
    cur = conn.cursor()
    for slug, data in ENTRIES.items():
        cur.execute("SELECT slug FROM concepts WHERE slug = ?", (slug,))
        if not cur.fetchone():
            print(f"WARNING: slug not found in DB: {slug}")
            continue
        cur.execute(
            "UPDATE concepts SET definition_short = ?, definition_long = ? WHERE slug = ?",
            (data["definition_short"], data["definition_long"], slug)
        )
        dl_words = len(data["definition_long"].split())
        ds_words = len(data["definition_short"].split())
        print(f"Updated {slug}: def_short={ds_words} words, def_long={dl_words} words")
    conn.commit()
    conn.close()
    print("Batch 2 complete.")


if __name__ == "__main__":
    main()
